import {
	Button,
	CheckboxControl,
	ToggleControl,
	__experimentalVStack as VStack,
} from '@wordpress/components';
import { createInterpolateElement } from '@wordpress/element';
import { __, sprintf } from '@wordpress/i18n';
import { intlFormat } from 'date-fns';
import { SectionHeader } from '../../../../../components/section-header';
import { Text } from '../../../../../components/text';
import { BillingPurchaseInfoPopover } from '../../../dataviews';
import type { AtomicTransfer, Purchase } from '@automattic/api-core';

type Props = {
	atomicTransfer?: Pick< AtomicTransfer, 'created_at' >;
	purchase: Purchase | undefined;
	siteSlug: string;
	atomicRevertCheckOne: boolean;
	onClickCheckOne: ( isChecked: boolean ) => void;
	atomicRevertCheckTwo: boolean;
	onClickCheckTwo: ( isChecked: boolean ) => void;
	hasBackupsFeature: boolean;
	isRemovePlan?: boolean;
	isDowngradePlan?: boolean;
	enableLosslessRevert?: boolean;
	setEnableLosslessRevert?: ( isChecked: boolean ) => void;
};

export function AtomicRevertStep( props: Props ) {
	const {
		atomicTransfer,
		purchase,
		siteSlug,
		atomicRevertCheckOne,
		atomicRevertCheckTwo,
		enableLosslessRevert,
		setEnableLosslessRevert,
		hasBackupsFeature,
		onClickCheckOne,
		onClickCheckTwo,
		isRemovePlan,
		isDowngradePlan,
	} = props;

	if ( ! siteSlug || ! atomicTransfer || ! purchase || ! atomicTransfer.created_at ) {
		return null;
	}

	const atomicTransferDate = intlFormat( atomicTransfer.created_at, { dateStyle: 'medium' } );
	const purchaseRenewalDate =
		purchase?.expiry_date && intlFormat( purchase.expiry_date, { dateStyle: 'medium' } );
	const isPlanPurchase = purchase.is_plan;
	const createInfoPopover = (
		<BillingPurchaseInfoPopover>
			{ sprintf(
				/* translators: %(atomicTransferDate)s is a date */
				__(
					'On %(atomicTransferDate)s, we automatically moved your site to a platform that supports the usage of plugins, custom themes, and hosting features. If you deactivate your plan, we will move your site back to its original platform.'
				),
				{ atomicTransferDate }
			) }
		</BillingPurchaseInfoPopover>
	);

	let subHeaderText: string;
	let highlightWords: string[] = [];
	if ( isPlanPurchase ) {
		if ( isRemovePlan ) {
			subHeaderText = sprintf(
				/* translators: %(atomicTransferDate)s is a date */
				__(
					'If you deactivate your plan, we will set your site to private and revert it to the point when you installed your first plugin or custom theme, or activated hosting features on %(atomicTransferDate)s. All of your posts, pages, and media will be preserved, except for content generated by plugins or custom themes.'
				),
				{ atomicTransferDate }
			);
			highlightWords = [ atomicTransferDate ];
		} else if ( isDowngradePlan ) {
			subHeaderText = sprintf(
				/* translators: %(atomicTransferDate)s is a date */
				__(
					'If you downgrade your plan, we will immediately set your site to private and revert it to the point when you installed your first plugin or custom theme, or activated hosting features on %(atomicTransferDate)s.'
				),
				{
					atomicTransferDate,
				}
			);
			highlightWords = [ atomicTransferDate ];
		} else {
			subHeaderText = sprintf(
				/* translators: %(purchaseRenewalDate)s and %(atomicTransferDate)s are both dates */
				__(
					'If you cancel your plan, when your plan expires on %(purchaseRenewalDate)s, we will set your site to private and revert it to the point when you installed your first plugin or custom theme, or activated hosting features on %(atomicTransferDate)s. All of your posts, pages, and media will be preserved, except for content generated by plugins or custom themes.'
				),
				{
					purchaseRenewalDate,
					atomicTransferDate,
				}
			);
			highlightWords = purchaseRenewalDate
				? [ purchaseRenewalDate, atomicTransferDate ]
				: [ atomicTransferDate ];
		}
	} else {
		subHeaderText = sprintf(
			/* translators: %(atomicTransferDate)s is a date */
			__(
				'If you deactivate your product, we will set your site to private and revert it to the point when you installed your first plugin or custom theme, or activated hosting features on %(atomicTransferDate)s. All of your posts, pages, and media will be preserved, except for content generated by plugins or custom themes.'
			),
			{ atomicTransferDate }
		);
		highlightWords = [ atomicTransferDate ];
	}

	return (
		<VStack spacing={ 4 }>
			<SectionHeader level={ 3 } title={ __( 'Proceed with caution' ) } />
			<Text as="p">
				<Text as="span" highlightWords={ highlightWords }>
					{ subHeaderText }
				</Text>
				{ ! isDowngradePlan && createInfoPopover }
			</Text>
			<Text as="p">
				{ createInterpolateElement(
					__(
						'Please <strong>confirm and check</strong> the following items before you continue with plan deactivation:'
					),
					{ strong: <strong /> }
				) }
			</Text>
			<CheckboxControl
				label={
					isPlanPurchase && ! isRemovePlan && ! isDowngradePlan
						? sprintf(
								/* translators: %(purchaseRenewalDate)s is the date that the purchase renews */
								__(
									'Any themes/plugins you have installed on the site will be removed on %(purchaseRenewalDate)s, along with their data.'
								),
								{
									purchaseRenewalDate: intlFormat( purchase.expiry_date, { dateStyle: 'medium' } ),
								}
						  )
						: __(
								'Any themes/plugins you have installed on the site will be removed, along with their data.'
						  )
				}
				checked={ atomicRevertCheckOne }
				onChange={ onClickCheckOne }
			/>
			<CheckboxControl
				label={
					isPlanPurchase && ! isRemovePlan && ! isDowngradePlan
						? sprintf(
								/* translators: %(purchaseRenewalDate)s is the date that the purchase renews */
								__(
									'On %(purchaseRenewalDate)s, your site will return to its original settings and theme right before the first plugin or custom theme was installed.'
								),
								{
									purchaseRenewalDate: intlFormat( purchase.expiry_date, { dateStyle: 'medium' } ),
								}
						  )
						: __(
								'Your site will return to its original settings and theme right before the first plugin or custom theme was installed.'
						  )
				}
				checked={ atomicRevertCheckTwo }
				onChange={ onClickCheckTwo }
			/>
			{ hasBackupsFeature && (
				<>
					<Text weight="bold">{ __( 'Would you like to download the backup of your site?' ) }</Text>
					<Text as="p">
						{ createInterpolateElement(
							__(
								"To make sure you have everything after your plan is deactivated or if you'd like to migrate, you can <backupLink>download a backup</backupLink>."
							),
							{
								backupLink: (
									<Button variant="link" href={ `/backup/${ siteSlug }` }>
										{ __( 'download a backup' ) }
									</Button>
								),
							}
						) }
					</Text>
				</>
			) }
			{ isDowngradePlan && (
				<ToggleControl
					label={ __( 'Restore my posts, pages, and media.' ) }
					help={ __(
						'Your posts, pages, and media added after upgrading will be automatically imported to your downgraded site. This process may take up to 24 hours.'
					) }
					checked={ enableLosslessRevert }
					onChange={ setEnableLosslessRevert! }
				/>
			) }
		</VStack>
	);
}
