import {
	PRODUCT_JETPACK_BACKUP_T1_MONTHLY,
	JETPACK_BACKUP_PRODUCT_LANDING_PAGE_URL,
	JETPACK_ANTI_SPAM_PRODUCT_LANDING_PAGE_URL,
	JETPACK_SCAN_PRODUCT_LANDING_PAGE_URL,
	JETPACK_SEARCH_PRODUCT_LANDING_PAGE_URL,
	PRODUCT_JETPACK_ANTI_SPAM,
	PRODUCT_JETPACK_BOOST,
	PRODUCT_JETPACK_CRM,
	PRODUCT_JETPACK_SCAN,
	PRODUCT_JETPACK_SEARCH,
	PRODUCT_JETPACK_SOCIAL_ADVANCED,
	PRODUCT_JETPACK_VIDEOPRESS,
	JETPACK_BOOST_PRODUCT_LANDING_PAGE_URL,
	JETPACK_SOCIAL_PRODUCT_LANDING_PAGE_URL,
	JETPACK_VIDEOPRESS_PRODUCT_LANDING_PAGE_URL,
	JETPACK_CRM_PRODUCT_LANDING_PAGE_URL,
} from '@automattic/calypso-products';
import { localizeUrl } from '@automattic/i18n-utils';

const PRODUCT_URL_MAP: { [ key: string ]: string } = {
	[ PRODUCT_JETPACK_BACKUP_T1_MONTHLY ]: JETPACK_BACKUP_PRODUCT_LANDING_PAGE_URL,
	[ PRODUCT_JETPACK_BOOST ]: JETPACK_BOOST_PRODUCT_LANDING_PAGE_URL,
	[ PRODUCT_JETPACK_SCAN ]: JETPACK_SCAN_PRODUCT_LANDING_PAGE_URL,
	[ PRODUCT_JETPACK_SEARCH ]: JETPACK_SEARCH_PRODUCT_LANDING_PAGE_URL,
	[ PRODUCT_JETPACK_ANTI_SPAM ]: JETPACK_ANTI_SPAM_PRODUCT_LANDING_PAGE_URL,
	[ PRODUCT_JETPACK_SOCIAL_ADVANCED ]: JETPACK_SOCIAL_PRODUCT_LANDING_PAGE_URL,
	[ PRODUCT_JETPACK_VIDEOPRESS ]: JETPACK_VIDEOPRESS_PRODUCT_LANDING_PAGE_URL,
	[ PRODUCT_JETPACK_CRM ]: JETPACK_CRM_PRODUCT_LANDING_PAGE_URL,
};

export const getProductUrl = ( productSlug: string ) =>
	localizeUrl( PRODUCT_URL_MAP[ productSlug ] );
