#!/usr/bin/env bash
REPORTER=${REPORTER:-spec}
NODE_BIN=$(npm bin)
BASE_DIR=$NODE_BIN/../..
NODE_PATH=$BASE_DIR/test:$BASE_DIR/client
NODE_ENV=test NODE_PATH=$NODE_PATH $BASE_DIR/test/runner.js --reporter=$REPORTER $@
