/**
 * External dependencies
 */

const sections = [
	{
		name: 'sites',
		paths: [ '/sites' ],
		module: 'my-sites',
		group: 'sites',
		secondary: true,
		load: () => import( /* webpackChunkName: 'sites' */ 'my-sites' ),
	},
	{
		name: 'customize',
		paths: [ '/customize' ],
		module: 'my-sites/customize',
		group: 'sites',
		secondary: true,
		load: () => import( /* webpackChunkName: 'customize' */ 'my-sites/customize' ),
	},
	{
		name: 'me',
		paths: [ '/me' ],
		module: 'me',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'me' */ 'me' ),
	},
	{
		name: 'account',
		paths: [ '/me/account' ],
		module: 'me/account',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'account' */ 'me/account' ),
	},
	{
		name: 'account-close',
		paths: [ '/me/account/close' ],
		module: 'me/account-close',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'account-close' */ 'me/account-close' ),
	},
	{
		name: 'activity',
		paths: [ '/activity-log' ],
		module: 'my-sites/activity',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'activity' */ 'my-sites/activity' ),
	},
	{
		name: 'security',
		paths: [ '/me/security' ],
		module: 'me/security',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'security' */ 'me/security' ),
	},
	{
		name: 'privacy',
		paths: [ '/me/privacy' ],
		module: 'me/privacy',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'privacy' */ 'me/privacy' ),
	},
	{
		name: 'purchases',
		paths: [ '/me/purchases', '/purchases', '/me/billing', '/payment-methods/add-credit-card' ],
		module: 'me/purchases',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'purchases' */ 'me/purchases' ),
	},
	{
		name: 'notification-settings',
		paths: [ '/me/notifications' ],
		module: 'me/notification-settings',
		group: 'me',
		secondary: true,
		load: () =>
			import( /* webpackChunkName: 'notification-settings' */ 'me/notification-settings' ),
	},
	{
		name: 'site-blocks',
		paths: [ '/me/site-blocks' ],
		module: 'me/site-blocks',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'site-blocks' */ 'me/site-blocks' ),
	},
	{
		name: 'concierge',
		paths: [ '/me/concierge' ],
		module: 'me/concierge',
		group: 'me',
		secondary: false,
		load: () => import( /* webpackChunkName: 'concierge' */ 'me/concierge' ),
	},
	{
		name: 'media',
		paths: [ '/media' ],
		module: 'my-sites/media',
		group: 'sites',
		secondary: true,
		load: () => import( /* webpackChunkName: 'media' */ 'my-sites/media' ),
	},
	{
		name: 'people',
		paths: [ '/people' ],
		module: 'my-sites/people',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'people' */ 'my-sites/people' ),
	},
	{
		name: 'plugins',
		paths: [ '/plugins' ],
		module: 'my-sites/plugins',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'plugins' */ 'my-sites/plugins' ),
	},
	{
		name: 'posts-pages',
		paths: [ '/pages' ],
		module: 'my-sites/pages',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'posts-pages' */ 'my-sites/pages' ),
	},
	{
		name: 'posts-pages',
		paths: [ '/posts' ],
		module: 'my-sites/posts',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'posts-pages' */ 'my-sites/posts' ),
	},
	{
		name: 'settings-performance',
		paths: [ '/settings/performance' ],
		module: 'my-sites/site-settings/settings-performance',
		secondary: true,
		group: 'sites',
		load: () =>
			import(
				/* webpackChunkName: 'settings-performance' */ 'my-sites/site-settings/settings-performance'
			),
	},
	{
		name: 'settings-writing',
		paths: [ '/settings/writing', '/settings/taxonomies', '/settings/podcasting' ],
		module: 'my-sites/site-settings/settings-writing',
		secondary: true,
		group: 'sites',
		load: () =>
			import(
				/* webpackChunkName: 'settings-writing' */ 'my-sites/site-settings/settings-writing'
			),
	},
	{
		name: 'settings-discussion',
		paths: [ '/settings/discussion' ],
		module: 'my-sites/site-settings/settings-discussion',
		secondary: true,
		group: 'sites',
		load: () =>
			import(
				/* webpackChunkName: 'settings-discussion' */ 'my-sites/site-settings/settings-discussion'
			),
	},
	{
		name: 'settings-security',
		paths: [ '/settings/security' ],
		module: 'my-sites/site-settings/settings-security',
		secondary: true,
		group: 'sites',
		load: () =>
			import(
				/* webpackChunkName: 'settings-security' */ 'my-sites/site-settings/settings-security'
			),
	},
	{
		name: 'settings',
		paths: [ '/settings' ],
		module: 'my-sites/site-settings',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'settings' */ 'my-sites/site-settings' ),
	},
	{
		name: 'marketing',
		paths: [ '/marketing', '/sharing' ],
		module: 'my-sites/marketing',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'marketing' */ 'my-sites/marketing' ),
	},
	{
		name: 'jetpack-connect',
		paths: [ '/jetpack' ],
		module: 'jetpack-connect',
		secondary: false,
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'jetpack-connect' */ 'jetpack-connect' ),
	},
	{
		name: 'jetpack-onboarding',
		paths: [ '/jetpack/start' ],
		module: 'jetpack-onboarding',
		secondary: false,
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'jetpack-onboarding' */ 'jetpack-onboarding' ),
	},
	{
		name: 'signup',
		paths: [ '/start' ],
		module: 'signup',
		secondary: false,
		enableLoggedOut: true,
		isomorphic: true,
		load: () => import( /* webpackChunkName: 'signup' */ 'signup' ),
	},
	{
		name: 'stats',
		paths: [ '/stats' ],
		module: 'my-sites/stats',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'stats' */ 'my-sites/stats' ),
	},
	{
		name: 'checklist',
		paths: [ '/checklist' ],
		module: 'my-sites/checklist',
		secondary: true,
		group: 'checklist',
		load: () => import( /* webpackChunkName: 'checklist' */ 'my-sites/checklist' ),
	},
	{
		name: 'google-my-business',
		paths: [ '/google-my-business' ],
		module: 'my-sites/google-my-business',
		secondary: true,
		group: 'sites',
		load: () =>
			import( /* webpackChunkName: 'google-my-business' */ 'my-sites/google-my-business' ),
	},
	// Since we're using find() and startsWith() on paths, 'themes' needs to go before 'theme',
	// or it'll be falsely associated with the latter section.
	{
		name: 'themes',
		paths: [ '/themes', '/design' ],
		module: 'my-sites/themes',
		enableLoggedOut: true,
		secondary: true,
		group: 'sites',
		isomorphic: true,
		title: 'Themes',
		load: () => import( /* webpackChunkName: 'themes' */ 'my-sites/themes' ),
	},
	{
		name: 'theme',
		paths: [ '/theme' ],
		module: 'my-sites/theme',
		enableLoggedOut: true,
		secondary: false,
		group: 'sites',
		isomorphic: true,
		title: 'Themes',
		load: () => import( /* webpackChunkName: 'theme' */ 'my-sites/theme' ),
	},
	{
		name: 'domains',
		paths: [ '/domains' ],
		module: 'my-sites/domains',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'domains' */ 'my-sites/domains' ),
	},
	{
		name: 'email',
		paths: [ '/email' ],
		module: 'my-sites/email',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'email' */ 'my-sites/email' ),
	},
	{
		name: 'checkout',
		paths: [ '/checkout' ],
		module: 'my-sites/checkout',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'checkout' */ 'my-sites/checkout' ),
	},
	{
		name: 'plans',
		paths: [ '/plans' ],
		module: 'my-sites/plans',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'plans' */ 'my-sites/plans' ),
	},
	{
		name: 'accept-invite',
		paths: [ '/accept-invite' ],
		module: 'my-sites/invites',
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'accept-invite' */ 'my-sites/invites' ),
	},
	{
		name: 'earn',
		paths: [ '/earn', '/ads' ],
		module: 'my-sites/earn',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'earn' */ 'my-sites/earn' ),
	},
	{
		name: 'mailing-lists',
		paths: [ '/mailing-lists/unsubscribe' ],
		module: 'mailing-lists',
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'mailing-lists' */ 'mailing-lists' ),
	},
	{
		name: 'feature-upsell',
		paths: [ '/feature' ],
		module: 'my-sites/feature-upsell',
		group: 'sites',
		secondary: true,
		load: () => import( /* webpackChunkName: 'feature-upsell' */ 'my-sites/feature-upsell' ),
	},
	{
		name: 'post-editor',
		paths: [ '/post', '/page', '/edit' ],
		module: 'post-editor',
		group: 'editor',
		secondary: true,
		load: () => import( /* webpackChunkName: 'post-editor' */ 'post-editor' ),
	},
	{
		name: 'account-recovery',
		paths: [ '/account-recovery' ],
		module: 'account-recovery',
		secondary: false,
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'account-recovery' */ 'account-recovery' ),
	},
	// this MUST be the first section for /read paths so subsequent sections under /read can override settings
	{
		name: 'reader',
		paths: [ '/', '/read' ],
		module: 'reader',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader' ),
	},
	{
		name: 'reader',
		paths: [ '/read/feeds/[^\\/]+', '/read/blogs/[^\\/]+', '/read/a8c' ],
		module: 'reader',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader' ),
	},
	{
		name: 'reader',
		paths: [ '/read/feeds/[^\\/]+/posts/[^\\/]+', '/read/blogs/[^\\/]+/posts/[^\\/]+' ],
		module: 'reader/full-post',
		secondary: false,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/full-post' ),
	},
	{
		name: 'reader',
		paths: [ '/discover' ],
		module: 'reader/discover',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/discover' ),
	},
	{
		name: 'reader',
		paths: [ '/following' ],
		module: 'reader/following',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/following' ),
	},
	{
		name: 'reader',
		paths: [ '/tags', '/tag' ],
		module: 'reader/tag-stream',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/tag-stream' ),
	},
	{
		name: 'reader',
		paths: [ '/activities' ],
		module: 'reader/liked-stream',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/liked-stream' ),
	},
	{
		name: 'reader',
		paths: [ '/read/search', '/recommendations' ],
		module: 'reader/search',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/search' ),
	},
	{
		name: 'reader',
		paths: [ '/read/list' ],
		module: 'reader/list',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/list' ),
	},
	{
		name: 'reader',
		paths: [ '/read/conversations' ],
		module: 'reader/conversations',
		secondary: true,
		group: 'reader',
		load: () => import( /* webpackChunkName: 'reader' */ 'reader/conversations' ),
	},
	{
		name: 'help',
		paths: [ '/help' ],
		module: 'me/help',
		secondary: true,
		enableLoggedOut: true,
		group: 'me',
		load: () => import( /* webpackChunkName: 'help' */ 'me/help' ),
	},
	{
		name: 'login',
		paths: [ '/log-in' ],
		module: 'login',
		enableLoggedOut: true,
		secondary: false,
		isomorphic: true,
		load: () => import( /* webpackChunkName: 'login' */ 'login' ),
	},
	{
		name: 'auth',
		paths: [ '/oauth-login', '/authorize', '/api/oauth/token' ],
		module: 'auth',
		secondary: false,
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'auth' */ 'auth' ),
	},
	{
		name: 'posts-custom',
		paths: [ '/types' ],
		module: 'my-sites/types',
		secondary: true,
		group: 'sites',
		load: () => import( /* webpackChunkName: 'posts-custom' */ 'my-sites/types' ),
	},
	{
		name: 'happychat',
		paths: [ '/me/chat' ],
		module: 'me/happychat',
		group: 'me',
		secondary: true,
		load: () => import( /* webpackChunkName: 'happychat' */ 'me/happychat' ),
	},
	{
		name: 'comments',
		paths: [ '/comments', '/comment' ],
		module: 'my-sites/comments',
		group: 'sites',
		secondary: true,
		load: () => import( /* webpackChunkName: 'comments' */ 'my-sites/comments' ),
	},
	{
		name: 'preview',
		paths: [ '/view' ],
		module: 'my-sites/preview',
		group: 'sites',
		secondary: true,
		load: () => import( /* webpackChunkName: 'preview' */ 'my-sites/preview' ),
	},
	{
		name: 'domain-connect-authorize',
		paths: [ '/domain-connect' ],
		module: 'my-sites/domains/domain-management/domain-connect',
		secondary: false,
		load: () =>
			import(
				/* webpackChunkName: 'domain-connect-authorize' */ 'my-sites/domains/domain-management/domain-connect'
			),
	},
	{
		name: 'gutenberg-editor',
		paths: [ '/block-editor' ],
		module: 'gutenberg/editor',
		group: 'gutenberg',
		secondary: false,
		load: () => import( /* webpackChunkName: 'gutenberg-editor' */ 'gutenberg/editor' ),
	},
	{
		name: 'devdocs',
		paths: [ '/devdocs' ],
		module: 'devdocs',
		secondary: true,
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'devdocs' */ 'devdocs' ),
	},
	{
		name: 'devdocs',
		paths: [ '/devdocs/start' ],
		module: 'devdocs',
		secondary: false,
		enableLoggedOut: true,
		load: () => import( /* webpackChunkName: 'devdocs' */ 'devdocs' ),
	},
	// extensions
	{
		name: 'hello-dolly',
		paths: [ '/hello-dolly' ],
		module: 'hello-dolly',
		group: 'sites',
		secondary: true,
		enableLoggedOut: true,
		env_id: [ 'development', 'wpcalypso' ],
		load: () => import( /* webpackChunkName: 'hello-dolly' */ 'hello-dolly' ),
	},
	{
		name: 'sensei',
		paths: [ '/extensions/sensei' ],
		module: 'sensei',
		group: 'sites',
		secondary: true,
		env_id: [ 'development', 'wpcalypso' ],
		load: () => import( /* webpackChunkName: 'sensei' */ 'sensei' ),
	},
	{
		name: 'woocommerce',
		paths: [ '/store' ],
		module: 'woocommerce',
		group: 'sites',
		secondary: true,
		env_id: [ 'development', 'desktop', 'wpcalypso', 'stage', 'production' ],
		load: () => import( /* webpackChunkName: 'woocommerce' */ 'woocommerce' ),
	},
	{
		name: 'wp-super-cache',
		paths: [ '/extensions/wp-super-cache' ],
		settings_path: '/extensions/wp-super-cache',
		module: 'wp-super-cache',
		group: 'sites',
		secondary: true,
		env_id: [ 'development', 'wpcalypso', 'horizon', 'stage', 'production' ],
		load: () => import( /* webpackChunkName: 'wp-super-cache' */ 'wp-super-cache' ),
	},
	{
		name: 'zoninator',
		paths: [ '/extensions/zoninator' ],
		settings_path: '/extensions/zoninator',
		module: 'zoninator',
		group: 'sites',
		secondary: true,
		env_id: [ 'development', 'wpcalypso', 'stage', 'production' ],
		load: () => import( /* webpackChunkName: 'zoninator' */ 'zoninator' ),
	},
];

module.exports = sections;
