export const JETPACK_GET_AGENCIES_REQUEST = 'JETPACK_GET_AGENCIES_REQUEST';
export const JETPACK_GET_AGENCIES_SUCCESS = 'JETPACK_GET_AGENCIES_SUCCESS';
export const JETPACK_GET_AGENCIES_ERROR = 'JETPACK_GET_AGENCIES_ERROR';
export const JETPACK_CURRENT_AGENCY_UPDATE = 'JETPACK_CURRENT_AGENCY_UPDATE';
export const JETPACK_SET_AGENCY_CLIENT_USER = 'JETPACK_SET_AGENCY_CLIENT_USER';
