/**
 * /* Notices use different action constants
 *
 */

export const INSTALL_PLUGIN = 'INSTALL_PLUGIN';
export const REMOVE_PLUGIN = 'REMOVE_PLUGIN';
export const UPDATE_PLUGIN = 'UPDATE_PLUGIN';
export const ACTIVATE_PLUGIN = 'ACTIVATE_PLUGIN';
export const DEACTIVATE_PLUGIN = 'DEACTIVATE_PLUGIN';
export const ENABLE_AUTOUPDATE_PLUGIN = 'ENABLE_AUTOUPDATE_PLUGIN';
export const DISABLE_AUTOUPDATE_PLUGIN = 'DISABLE_AUTOUPDATE_PLUGIN';
