export const A4A_DASHBOARD_SECTION_DEFINITION = {
	name: 'dashboard-a4a',
	module: 'dashboard/app-a4a',
};

export const A4A_DASHBOARD_SECTION_PATHS = [
	'/',
	'/oauth/token',
	'/overview',
	'/sites',
	'/dev-tools',
	'/migrations',
	'/marketplace',
	'/hosting',
	'/products',
	'/purchases',
	'/exclusive-offers',
	'/library',
	'/partner-directory',
	'/partner-directory/expertise',
	'/partner-directory/details',
	'/tiers',
	'/referrals',
	'/woopayments',
	'/payout-settings',
	'/agency/team',
	'/agency/ai',
	'/agency/ai/read',
	'/agency/ai/write',
	'/agency/ai/prompts',
	'/agency/ai/connect',
	'/client',
	'/client/subscriptions',
];
