/** @format */
export const actionTypes = {
	FETCH_SETTINGS: 'NOTIFICATION_SETTINGS_FETCH',
	FETCH_SETTINGS_COMPLETE: 'NOTIFICATION_SETTINGS_FETCH_COMPLETE',
	FETCH_SETTINGS_FAILED: 'NOTIFICATION_SETTINGS_FETCH_FAILED',

	TOGGLE_SETTING: 'NOTIFICATION_SETTINGS_TOGGLE_SETTING',

	SAVE_SETTINGS: 'NOTIFICATION_SETTINGS_SAVE',
	SAVE_SETTINGS_COMPLETE: 'NOTIFICATION_SETTINGS_SAVE_COMPLETE',
	SAVE_SETTINGS_FAILED: 'NOTIFICATION_SETTINGS_SAVE_FAILED',
};
