export const WP_SUPER_CACHE_RECEIVE_SETTINGS = 'WP_SUPER_CACHE_RECEIVE_SETTINGS';
export const WP_SUPER_CACHE_REQUEST_SETTINGS = 'WP_SUPER_CACHE_REQUEST_SETTINGS';
export const WP_SUPER_CACHE_REQUEST_SETTINGS_FAILURE = 'WP_SUPER_CACHE_REQUEST_SETTINGS_FAILURE';
export const WP_SUPER_CACHE_REQUEST_SETTINGS_SUCCESS = 'WP_SUPER_CACHE_REQUEST_SETTINGS_SUCCESS';
export const WP_SUPER_CACHE_SAVE_SETTINGS = 'WP_SUPER_CACHE_SAVE_SETTINGS';
export const WP_SUPER_CACHE_SAVE_SETTINGS_FAILURE = 'WP_SUPER_CACHE_SAVE_SETTINGS_FAILURE';
export const WP_SUPER_CACHE_SAVE_SETTINGS_SUCCESS = 'WP_SUPER_CACHE_SAVE_SETTINGS_SUCCESS';
export const WP_SUPER_CACHE_UPDATE_SETTINGS = 'WP_SUPER_CACHE_UPDATE_SETTINGS';
