export const WP_SUPER_CACHE_RECEIVE_SETTINGS = 'WP_SUPER_CACHE_RECEIVE_SETTINGS';
export const WP_SUPER_CACHE_REQUEST_SETTINGS = 'WP_SUPER_CACHE_REQUEST_SETTINGS';
export const WP_SUPER_CACHE_REQUEST_SETTINGS_FAILURE = 'WP_SUPER_CACHE_REQUEST_SETTINGS_FAILURE';
export const WP_SUPER_CACHE_REQUEST_SETTINGS_SUCCESS = 'WP_SUPER_CACHE_REQUEST_SETTINGS_SUCCESS';

export const WP_SUPER_CACHE_SETTINGS_SAVE = 'WP_SUPER_CACHE_SETTINGS_SAVE';
export const WP_SUPER_CACHE_SETTINGS_SAVE_FAILURE = 'WP_SUPER_CACHE_SETTINGS_SAVE_FAILURE';
export const WP_SUPER_CACHE_SETTINGS_SAVE_SUCCESS = 'WP_SUPER_CACHE_SETTINGS_SAVE_SUCCESS';
export const WP_SUPER_CACHE_SETTINGS_UPDATE = 'WP_SUPER_CACHE_SETTINGS_UPDATE';
