import { localizeUrl } from '@automattic/i18n-utils';
import { Button } from '@wordpress/components';
import { useTranslate } from 'i18n-calypso';
import A4AModal from 'calypso/a8c-for-agencies/components/a4a-modal';

import './style.scss';

type Props = {
	show: boolean;
	onClose: () => void;
};

const TosModal = ( { show, onClose }: Props ) => {
	const translate = useTranslate();

	if ( ! show ) {
		return null;
	}

	return (
		<A4AModal
			className="a4a-tos-modal"
			onClose={ onClose }
			title={ translate( 'Automattic for Agencies Platform Agreement' ) }
			subtile=""
			showCloseButton={ false }
			extraActions={
				<Button variant="primary" onClick={ onClose }>
					{ translate( 'Close' ) }
				</Button>
			}
		>
			<div className="a4a-tos-modal-content">
				<div>
					This Automattic for Agencies Platform Agreement, (the “<strong>Agreement</strong>”) is a
					legally binding agreement between Automattic Inc. (“<strong>Automattic</strong>”) and you,
					effective as of the date you first access the Platform (the “Effective Date”). By
					registering for and participating in Automattic for Agencies (“<strong>A4A</strong>”), you
					acknowledge and agree that you have read and agree to be bound by the terms of this
					Agreement.&nbsp;
				</div>
				<ol className="a4a-tos-modal-list">
					<li>
						<strong>Automattic Services and Access</strong>
						<ol style={ { listStyleType: 'lower-alpha' } } className="a4a-tos-modal-list">
							<li>
								License. Subject to your compliance with the terms and conditions of this Agreement,
								our privacy policy at{ ' ' }
								<a href={ localizeUrl( 'https://automattic.com/privacy/' ) }>
									https://automattic.com/privacy/
								</a>{ ' ' }
								which you agree applies to your participation in A4A, and the applicable Terms of
								Service at:{ ' ' }
								<a href={ localizeUrl( 'https://wordpress.com/tos/' ) }>
									https://wordpress.com/tos/
								</a>
								,{ ' ' }
								<a href={ localizeUrl( 'https://pressable.com/legal/terms-of-service/' ) }>
									https://pressable.com/legal/terms-of-service/
								</a>
								,{ ' ' }
								<a
									href={ localizeUrl(
										'https://woocommerce.com/document/woopayments/our-policies/'
									) }
								>
									https://woocommerce.com/document/woopayments/our-policies/
								</a>
								,{ ' ' }
								<a
									href={ localizeUrl( 'https://automattic.com/for/agencies/community-guidelines' ) }
								>
									https://automattic.com/for/agencies/community-guidelines
								</a>
								, the Automattic API Guidelines at{ ' ' }
								<a href={ localizeUrl( 'https://developer.wordpress.com/guidelines/' ) }>
									https://developer.wordpress.com/guidelines/
								</a>{ ' ' }
								and any other terms provided to you by Automattic, Automattic grants you a license
								to access A4A solely for the purpose of procuring licenses to Automattic products
								and services made available to you in the A4A dashboard (the “
								<strong>Automattic Products</strong>”) to provide relevant services for your
								customers (“<strong>Customers</strong>”), and to receive applicable referral fees
								for products purchased by your Customers directly from Automattic. You shall not
								access or use A4A for any other purpose. You shall not publicly advertise or
								misrepresent prices of Automattic Products. Automattic Products and pricing or
								discounting therefore made available through A4A by Automattic may be added,
								removed, or changed at Automattic’s sole discretion, at any time. Automattic
								reserves the right, but not the obligation, to monitor any and all use of A4A and
								Automattic Products to ensure compliance with the terms and conditions of this
								Agreement. Automattic may, in its sole discretion, take any action it deems
								necessary to enforce this Agreement, including but not limited to, suspending or
								terminating your access to A4A, requiring remedial actions to correct
								non-compliance, or initiating legal proceedings. You may not participate in any
								other Automattic discount or incentive program, for example, the Automattic
								affiliate program, during the term of this Agreement.
							</li>

							<li>
								Account Access. In order to access A4A, you may be required to log in to Jetpack or
								other Automattic products with your applicable account. You shall not grant any
								third party access to A4A, and will maintain the confidentiality of any account
								login credentials provided by Automattic or generated by A4A. You shall ensure
								registration and other information you provide is complete, accurate, and
								up-to-date. You shall be responsible for the acts or omissions of any person who
								accesses A4A using these credentials. You agree to establish and use commercially
								reasonable procedures and controls to protect the privacy, security, and integrity
								of A4A. You will immediately notify Automattic of any actual or suspected threat or
								hazard to the security of A4A (“<strong>Security Breach</strong>”), and will assist
								Automattic in taking any actions Automattic deems necessary to remedy such Security
								Breach.&nbsp;
							</li>

							<li>
								Relationship. The obligations and relationship between you and your Customers are
								your sole responsibility. You hereby acknowledge and&nbsp;agree&nbsp;that Automattic
								will have no liability or obligation to your Customers.
							</li>

							<li>
								Customer Referrals.
								<ol style={ { listStyleType: 'lower-roman' } } className="a4a-tos-modal-list">
									<li>
										Should you receive any introductions from Automattic to provide your services to
										a user of an Automattic product or service, you shall:
										<ol className="a4a-tos-modal-list">
											<li>
												respond to Customer following the introduction in a prompt manner and no
												later than 48 hours after such introduction;
											</li>

											<li>
												ensure such response includes information outlining the services and pricing
												you offer; and
											</li>

											<li>
												accept requested calls with a Customer to progress the potential
												relationship.
											</li>
										</ol>
									</li>

									<li>
										Should the outcome of 1(d)(i) lead to a potential working engagement between you
										and Customer, you agree that Automattic may, at its discretion, review
										any&nbsp;proposal&nbsp;or quote prepared for Customer ahead of any communication
										of such proposal or quote to Customer
									</li>
								</ol>
							</li>
						</ol>
					</li>
				</ol>
				<ol start={ 2 } className="a4a-tos-modal-list">
					<li>
						<strong>Fees and Payment</strong>
						<ol style={ { listStyleType: 'lower-alpha' } } className="a4a-tos-modal-list">
							<li>
								Pricing. Unless otherwise specified by Automattic, you may license Automattic
								Products through A4A at rates provided by Automattic in the A4A dashboard (“
								<strong>Rates</strong>”), which are subject to change by Automattic from time to
								time during the Term. Automattic may change any rates, discounts, or referral fees
								upon written notice, or by updating the Rates, effective upon such notice or update.
								Unless otherwise required by Automattic, you are under no obligation to pass through
								any discount to your Customers.
							</li>

							<li>
								Promotions. During the Program, at its sole discretion, Automattic may offer
								promotions or incentives subject to certain conditions as stipulated by Automattic
								(“<strong>Promotion</strong>”). Should you receive any discount code, concession, or
								price reduction in relation to any applicable tier program, you shall adhere to any
								discount terms and conditions as provided to you by Automattic.&nbsp;
							</li>

							<li>
								Payment. Unless otherwise specified by Automattic, Automattic will provide a monthly
								invoice to you, and you shall pay all amounts invoiced within ten (10) days from
								receipt. Alternatively, Automattic may require you to include a payment method in
								A4A to enable automatic payments. For any amounts earned by you, for example through
								a referral program offered through A4A, Automattic will pay you for verified amounts
								earned.&nbsp;
							</li>

							<li>
								Monthly Reports. Upon Automattic’s request, you shall provide a monthly report
								showing data for Automattic Products licensed by you. If requested by Automattic,
								the report will detail for the prior month, at a minimum:
								<ol style={ { listStyleType: 'lower-roman' } } className="a4a-tos-modal-list">
									<li>The number of new Automattic Products licensed,</li>

									<li>the number of Automattic licenses terminated,</li>

									<li>the number of Automattic licenses transferred,</li>

									<li>
										the dates of activation, termination, and transfer of each of the foregoing,
									</li>

									<li>
										the number of your Customers using the Automattic Products, and the breakdown of
										Customers with each combination of license, and
									</li>

									<li>
										detail on number of Automattic Products purchased or upgraded, cumulatively and
										incrementally, compared to the prior month.
									</li>
								</ol>
							</li>

							<li>
								Automattic may request reasonable backup documentation to verify the numbers
								included in the monthly report. You will provide the report no later than ten (10)
								days after Automattic's request. Additionally, upon Automattic's request, you will
								provide Automattic with a list of your current Customers, or with access to Customer
								websites.
							</li>

							<li>
								Audit. Automattic shall have the right at its own expense to retain a qualified
								independent third party to audit any and all records related to this Agreement, not
								more than once per quarter per year. In the event that the audit shows an
								overpayment by Automattic or underpayment by Company, Company shall promptly pay the
								corrective amount to Automattic, provided that in the event the payment discrepancy
								is greater than five percent (5%), Company shall also pay the reasonable,
								documented, cost of such audit.
							</li>
						</ol>
					</li>

					<li>
						<strong>Ownership</strong>
						<ol style={ { listStyleType: 'lower-alpha' } } className="a4a-tos-modal-list">
							<li>
								As between the parties, Automattic owns all right, title, and interest in A4A, the
								Automattic Products, all Automattic intellectual property, and all registration data
								and other data collected by Automattic in connection with the use of Automattic
								Products.
							</li>

							<li>
								Except to the extent set forth herein, neither party grants the other any license,
								express or implied, to its intellectual property rights (including but not limited
								to patents, copyrights, trade secrets and trademarks), and you may not transfer or
								grant any licenses to the Automattic Products to any third party.&nbsp;
							</li>

							<li>
								You recognize and acknowledge that the use of any Automattic Trademarks or
								intellectual property (the “<strong>Automattic Trademarks</strong>”) shall not
								confer upon you any proprietary rights to the Automattic Trademarks and you: (i)
								shall not question, contest or challenge Automattic's ownership of any of
								Automattic's Trademarks nor shall you claim any right, title or interest in any of
								the Automattic Trademarks, except the right to use the same pursuant to the terms
								and conditions of this Agreement, (ii) shall not encourage or assist others directly
								or indirectly to do so, either during the term (as defined above) or after its
								expiration, and (iii) shall not utilize the Automattic Trademarks in any manner that
								would diminish the value of the Automattic Trademarks or harm the reputation of
								Automattic. You additionally agree not to compete with Automattic's own sales
								efforts, including, but not limited to, buying the Automattic Trademarks or other
								related keywords in SEM. Automattic must pre-approve any marketing materials or
								activities that use the Automattic Trademarks.
							</li>

							<li>
								Except as&nbsp;expressly permitted under this Agreement, or as otherwise permitted
								by Automattic in writing,&nbsp; you may not, without Automattic's prior written
								consent, publish any materials, make any announcements or publications containing or
								concerning Automattic or use the Automattic Trademarks. If approval is granted, you
								agree to abide by Automattic's published trademark guidelines at all times,
								available at{ ' ' }
								<a href={ localizeUrl( 'https://automattic.com/press/brand-materials/' ) }>
									https://automattic.com/press/brand-materials/
								</a>
								.
							</li>

							<li>
								You agree that Automattic may use your name and logo in any marketing materials,
								client listings and for the purpose of various Automattic agency directories, and
								shall provide assistance to Automattic as requested to participate in case studies,
								marketing materials, or other publications.
							</li>
						</ol>
					</li>

					<li>
						<strong>Term, Termination, Suspension</strong>
						<ol style={ { listStyleType: 'lower-alpha' } } className="a4a-tos-modal-list">
							<li>
								Term. This Agreement will commence as of the Eﬀective Date and will remain in eﬀect
								for a period of one year from the Effective Date (the “Term”). After the Term, this
								Agreement will automatically renew for consecutive one-year periods (each a “Renewal
								Term”), unless either party gives written notice to the other at least thirty (30)
								days before the expiration of the then-current term.
							</li>

							<li>
								Termination. Either party may terminate this Agreement: (a) at any time, if the
								other party breaches any material term of this Agreement and fails to cure such
								breach within 30 days after receiving notice from the non-breaching party; or (b)
								immediately if the other party becomes insolvent, ﬁles a petition in bankruptcy, or
								makes an assignment for the beneﬁt of creditors. Automattic may terminate this
								Agreement for any reason upon written notice to you. In the event of the termination
								or expiration of this Agreement, licenses to Automattic Products acquired hereunder
								shall terminate, and you must procure replacement licenses directly with Automattic,
								unless otherwise directed by Automattic. Further, you shall comply with any
								applicable wind-down processes or requirements provided to you by Automattic, which
								may include working with Automattic to communicate with users, continuing to provide
								services, or transferring applicable licenses to Automattic Products.&nbsp;
							</li>

							<li>
								Suspension Rights. Automattic may suspend access to or remove access to the
								Automattic Products for you or your Customers or affiliates in Automattic's sole
								discretion, if Automattic believes that you or a Customer of yours is engaged in:
								(a) any activity that may harm Automattic, its brand/reputation its systems or any
								third-party systems, (b) fraudulent or illegal activity or any other activity that
								could result in legal liability to Automattic or any third party; or (c) any other
								reason, subject to Automattic's reasonable discretion. Any such suspension may
								continue until the activity giving rise to the suspension has been cured and
								Automattic has received satisfactory assurances that it will not recur. Automattic
								reserves the right to work directly with your Customers and affiliates to resolve
								any issue related to or arising out of this Agreement. Additionally, if Automattic
								determines, at its sole discretion, that you are not distributing new Automattic
								Products to a sufficient number of customers, Automattic may, upon written notice to
								you, revoke your access to any discounted rates or revenue share until such time as
								Automattic has determined you are distributing a sufficient amount of new Automattic
								Products.
							</li>
						</ol>
					</li>

					<li>
						<strong>Confidentiality</strong> <br />
						The parties each acknowledge that they may be furnished with, receive or otherwise have
						access to information of or concerning the other party that such party considers to be
						confidential, a trade secret, or otherwise restricted. “Confidential Information” means
						all information, in any form, furnished or made available directly or indirectly by one
						party to the other that is marked confidential, restricted, or with a similar
						designation, or information which, under the circumstances of its disclosure, a
						reasonable party would deem to be confidential information. For clarity, Automattic
						Confidential Information shall include (but not be limited to) the Rates and any other
						information related to pricing, discounts, or the Automattic Products. Each party shall
						maintain as confidential and shall use at least the same degree of care as it employs to
						avoid unauthorized disclosure of its own Confidential Information, but in any event no
						less than commercially reasonable efforts. In addition to the confidentiality
						obligations set forth herein, the parties agree to comply with all applicable data
						protection laws concerning the processing of personal data. You shall implement and
						maintain a privacy policy in accordance with such laws, which shall include provisions
						relating to the collection, use, and sharing of personal data obtained in the course of
						performing this Agreement.
					</li>
				</ol>

				<ol start={ 6 } className="a4a-tos-modal-list">
					<li>
						<strong>Representations and Warranties</strong>
						<ol style={ { listStyleType: 'lower-alpha' } } className="a4a-tos-modal-list">
							<li>
								Each party represents and warrants to the other party that: (1) it is duly
								organized, validly existing and in good standing under the laws of the state under
								which it is organized; (2) it has the power and authority to enter into this
								Agreement and to perform fully its obligations hereunder; (3) it is under no
								contractual or other legal obligation that will in any way interfere with its full,
								prompt and complete performance hereunder; (4) the individual executing this
								Agreement on its behalf has the authority to do so; (5) it will comply with all
								applicable laws, rules, and regulations in its performance under this Agreement, and
								its performance hereunder shall not cause the other party to violate any of the
								foregoing; and (6) the obligations created by this Agreement, insofar as they
								purport to be binding on it, constitute legal, valid and binding obligations
								enforceable in accordance with their terms.
							</li>

							<li>
								You additionally represent and warrant to Automattic that: (1) you shall access and
								use A4A solely as contemplated under this Agreement to license Automattic Products
								for your use on behalf of your Customers; (2) you have all appropriate rights,
								licenses, and consents to incorporate the Automattic Products into your Customers'
								products and services, and to bind Customers to the applicable Automattic terms of
								service for each Automattic Product; (3) you shall not place excessive calls to
								Automattic's systems or otherwise overburden Automattic systems, as determined by
								Automattic; (4) you shall not use or allow the use of Automattic APIs to send or
								facilitate the sending of unsolicited communications or for any fraudulent purpose;
								(5) you shall not modify, decompile, reverse engineer or otherwise alter or seek to
								derive the trade secrets and other inherent intellectual property of any Automattic
								API or A4A; (6) you shall not use the any Automattic API or A4A (i) to create or
								enable any application, website, tool, or other mechanism that is, or enables, or
								operates in conjunction with, any malware, spyware, adware, other malicious programs
								or code, or (ii) in any manner that would violate any applicable law or governmental
								regulation; (7) you shall not violate or misappropriate the intellectual property
								rights of Automattic or any third party; (8) you have all necessary rights,
								licenses, and consents to provide any applicable data or information to Automattic;
								(9) you will perform your services in a professional, prompt, and competent manner;
								(10) you will not sublicense or subcontract any of the services you have agreed to
								perform for your client related to the Automattic Products without advance written
								permission from Automattic; and (11) you shall not engage in any activity that, in
								Automattic's sole discretion would harm the reputation or brand of Automattic.
							</li>

							<li>
								Any warranties for the Automattic Products shall run directly from Automattic to the
								Customer or prospect. In no event shall you make any representation, guarantee or
								warranty concerning the Automattic Products.
							</li>

							<li>
								EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT, AUTOMATTIC MAKES NO WARRANTY OF ANY
								KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, AND EACH PARTY SPECIFICALLY
								DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING ANY WARRANTIES OF MERCHANTABILITY,
								FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, TO THE MAXIMUM EXTENT
								PERMITTED BY APPLICABLE LAW.
							</li>
						</ol>
					</li>

					<li>
						<strong>Indemnification</strong>
					</li>
				</ol>
				<div>
					You will indemnify, defend and hold harmless Automattic, its affiliates, subsidiaries, and
					its directors, officers and employees against any liability, damage, loss or expense
					(including reasonable attorneys' fees and costs) incurred by Automattic in connection with
					any claim arising out of or relating to this Agreement or A4A.&nbsp;
				</div>
				<ol start={ 8 } className="a4a-tos-modal-list">
					<li>
						<strong>Limitation of Liability</strong>
					</li>
				</ol>
				<div>
					Except for your breach of confidentiality obligations in Section 5, your indemnification
					obligations in Section 7, or your gross negligence or willful misconduct, in no event will
					Automattic or you be liable for indirect, special, incidental, punitive or consequential
					damages arising out of or related to this Agreement, however caused, and under whatever
					cause of action of theory of liability even if a party has been advised of the possibility
					of such damages. To the maximum extent permitted by applicable law, Automattic's total
					aggregate liability will not exceed $1,000.&nbsp;
				</div>
				<ol start={ 9 } className="a4a-tos-modal-list">
					<li>
						<strong>Miscellaneous</strong>
						<ol style={ { listStyleType: 'lower-alpha' } } className="a4a-tos-modal-list">
							<li>
								Independent Contractors. The parties shall be independent contractors under this
								Agreement, and nothing herein shall constitute either party as the employer,
								employee, agent, or representative of the other party, or both parties as joint
								venturers or partners for any purpose.
							</li>

							<li>
								Assignment. This Agreement is not assignable or transferable by you except to any
								successor corporation or entity whether by purchase of all or substantially all of
								the assets relating to this Agreement, a sale of a controlling interest of the
								capital stock of the assigning party, by merger, consolidation or otherwise.
								&nbsp;This Agreement shall be binding upon and inure to the benefit of the parties
								hereto and their respective successors and permitted assigns.
							</li>

							<li>
								Notices. All notices must be in English, in writing and sent by email to the other
								party's email address as indicated below. Notice will be treated as given on
								receipt, as verified by electronic log. If to you: any email address used to
								register with A4A or one of your Automattic accounts. If to Automattic, with copies
								to <a href="mailto:partnerships@automattic.com">partnerships@automattic.com</a> and{ ' ' }
								<a href="mailto:contracts@automattic.com">contracts@automattic.com</a>
							</li>

							<li>
								Governing Law. This Agreement shall be governed by the laws of the State of
								California, without reference to conflict of law principles. For all disputes
								arising out of or related to this Agreement, the parties submit to the exclusive
								subject matter jurisdiction, personal jurisdiction and venue of the United States
								District Court for the Northern District of California.
							</li>

							<li>
								Amendment. We may modify this Agreement from time to time, for example, to reflect
								changes to A4A (e.g., adding new features or benefits, or retiring certain features)
								or for legal, regulatory, or security reasons. If we do this, we'll provide notice
								of the changes, such as by posting the amended Agreement and updating the “Last
								Modified” date or, if the changes, in our sole discretion, are material, we may
								notify you through our services or other communications. Any changes will apply on a
								going-forward basis, and, unless we say otherwise, the amended Agreement will be
								effective immediately. By continuing to use A4A, you agree to be bound by the
								updated Agreement. You have the right to object to any changes at any time by
								ceasing your use of A4A.
							</li>

							<li>
								No Waiver. The failure of either party to enforce its rights under this Agreement at
								any time for any period shall not be construed as a waiver of such rights.&nbsp;
							</li>

							<li>
								Entire Agreement. This Agreement, inclusive of all referenced terms herein, is the
								complete and exclusive statement of the mutual understanding of the parties and
								supersedes and cancels all previous written and oral agreements and communications
								relating to the subject matter hereof. Any pre-printed or standard terms of any
								purchase order, confirmation, or similar form, even if signed by the parties after
								the effectiveness hereof, shall have no force or effect.
							</li>

							<li>
								Severability. If any provision of this Agreement shall be adjudged by any court of
								competent jurisdiction to be unenforceable or invalid, that provision shall be
								limited or eliminated to the minimum extent necessary so that this arrangement shall
								otherwise remain in full force and effect and enforceable.
							</li>

							<li>
								No Third party Beneficiaries. The provisions hereof are for the benefit of the
								parties only and not for any other person or entity.
							</li>

							<li>
								Survival. Any provisions which by their nature should survive termination or
								expiration of this Agreement will survive.
							</li>
						</ol>
					</li>
				</ol>
				<p>
					<em>Last updated: May 1, 2024</em>
				</p>
			</div>
		</A4AModal>
	);
};

export default TosModal;
