# Stale https://probot.github.io/apps/stale/
# A way to keep our repo a bit cleaner by prompting for an update
# when an issue gets old, and closing that issue if it is not updated.
#
#
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 270
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - "[Pri] High"
  - "[Pri] BLOCKER"
  - "[Status] Keep Open"
  - "OSS Citizen"
# Set to true to ignore issues in a project
exemptProjects: true
# Set to true to ignore issues in a milestone
exemptMilestones: true
# Label to use when marking an issue as stale
staleLabel: "[Status] Stale"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been marked as stale because it hasn't been updated in a while. It will be closed in a week. If you would like it to remain open, can you please comment below and see what you can do to get things moving with this issue? Thanks! 🙏
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
