# Stale https://probot.github.io/apps/stale/
# A way to keep our repo a bit cleaner by prompting for an update
# when an issue gets old, and closing that issue if it is not updated.
#
#
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
# Set to false to disable auto-close.
daysUntilClose: false
# Issues with these labels will never be considered stale
exemptLabels:
  - "[Pri] High"
  - "[Pri] BLOCKER"
  - "[Status] Keep Open"
# Set to true to ignore issues in a project
exemptProjects: true
# Set to true to ignore issues in a milestone
exemptMilestones: true
# Label to use when marking an issue as stale
staleLabel: "[Status] Stale"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  <p>This issue has been marked as stale. 
  This happened because:</p>
  
  <ul>
    <li>It has been inactive in the past 6 months.</li>
    <li>It isn't a project or a milestone, and hasn’t been labeled with one of `[Pri] Blocker`, 
  `[Pri] High`, or `[Status] Keep Open`.</li>
  </ul>
  
  <p>You can keep the issue open by adding a comment. If you do, please 
  provide additional context and explain why you’d like it to remain open. 
  You can also close the issue yourself — if you do, please add a brief 
  explanation and apply one of relevant issue close labels.</p>
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
