import { category, page, postList, video } from '@wordpress/icons';
import type {
	Audience,
	ContentType,
	PreviewType,
	Product,
	PrototypeResource,
	Stage,
} from './browse-resources-types';

export const PRODUCTS: Product[] = [
	'WordPress VIP',
	'Pressable',
	'Program',
	'WooCommerce',
	'WordPress.com',
	'Jetpack',
];

export const STAGES: Stage[] = [ 'Learn', 'Sell', 'Manage', 'Grow' ];

export const CONTENT_TYPES: ContentType[] = [
	'One-pager',
	'Battle card',
	'Talk track',
	'Reference guide',
	'Slide deck',
	'Webinar',
	'Blog',
	'Case study',
	'Checklist',
	'Guide',
];

export const AUDIENCES: Audience[] = [ 'All', 'Developer', 'Business', 'Client' ];

export const AUDIENCE_LABELS: Record< Audience, string > = {
	All: 'All audiences',
	Developer: 'Developer',
	Business: 'Business',
	Client: 'Client',
};

// Maps the placeholder preview type to an existing @wordpress/icons glyph used
// for the card thumbnail and the modal preview header.
export const PREVIEW_ICON = {
	pdf: page,
	doc: postList,
	slides: category,
	video,
} as const satisfies Record< PreviewType, unknown >;

/**
 * Local mock dataset for the Milestone 1 browse prototype. This is intentionally
 * static — there is no backend or API wiring here. Items are spread across every
 * product, stage, content type, and audience so filtering, search, and the
 * preview modal are all demonstrable.
 */
export const RESOURCES: PrototypeResource[] = [
	{
		id: 'r1',
		product: 'WordPress VIP',
		stage: 'Sell',
		contentType: 'Battle card',
		audience: 'Business',
		title: 'WordPress VIP vs. traditional enterprise CMS',
		description:
			'Side-by-side positioning to win enterprise conversations, covering security, scale, and governance.',
		previewType: 'pdf',
	},
	{
		id: 'r2',
		product: 'WordPress VIP',
		stage: 'Learn',
		contentType: 'One-pager',
		audience: 'All',
		title: 'What is WordPress VIP?',
		description:
			'A quick overview of the enterprise platform and where it fits in your agency’s offering.',
		previewType: 'pdf',
		topResource: true,
	},
	{
		id: 'r3',
		product: 'WordPress VIP',
		stage: 'Grow',
		contentType: 'Case study',
		audience: 'Client',
		title: 'How an agency scaled a Fortune 500 site on VIP',
		description:
			'A client-ready story showing measurable performance and uptime gains after migration.',
		previewType: 'pdf',
	},
	{
		id: 'r4',
		product: 'Pressable',
		stage: 'Manage',
		contentType: 'Reference guide',
		audience: 'Developer',
		title: 'Pressable site management reference',
		description: 'SSH, staging, backups, and cache controls for day-to-day site operations.',
		previewType: 'pdf',
		topResource: true,
	},
	{
		id: 'r5',
		product: 'Pressable',
		stage: 'Learn',
		contentType: 'Guide',
		audience: 'Business',
		title: 'Getting started with Pressable for agencies',
		description: 'Set up your account, add sites, and understand plan tiers and billing.',
		previewType: 'doc',
	},
	{
		id: 'r6',
		product: 'Pressable',
		stage: 'Sell',
		contentType: 'Talk track',
		audience: 'Business',
		title: 'Positioning Pressable hosting',
		description: 'A talk track for recommending managed hosting without sounding salesy.',
		previewType: 'doc',
	},
	{
		id: 'r7',
		product: 'Pressable',
		stage: 'Grow',
		contentType: 'Webinar',
		audience: 'All',
		title: 'Scaling your hosting business with Pressable',
		description:
			'A recorded session on migrations, bulk site management, and protecting your margins.',
		previewType: 'video',
	},
	{
		id: 'r8',
		product: 'Program',
		stage: 'Learn',
		contentType: 'One-pager',
		audience: 'Business',
		title: 'The Automattic for Agencies program at a glance',
		description: 'Benefits, tiers, and how commissions and referrals work.',
		previewType: 'pdf',
	},
	{
		id: 'r9',
		product: 'Program',
		stage: 'Grow',
		contentType: 'Checklist',
		audience: 'Business',
		title: 'Agency growth checklist',
		description: 'Twelve steps to unlock higher tiers and recurring revenue.',
		previewType: 'pdf',
	},
	{
		id: 'r10',
		product: 'Program',
		stage: 'Sell',
		contentType: 'Slide deck',
		audience: 'Client',
		title: 'Client pitch deck: why work with our agency',
		description: 'An editable deck to present your Automattic-backed capabilities to prospects.',
		previewType: 'slides',
	},
	{
		id: 'r11',
		product: 'WooCommerce',
		stage: 'Sell',
		contentType: 'Battle card',
		audience: 'Business',
		title: 'WooCommerce vs. hosted commerce platforms',
		description:
			'Objection handling for merchants weighing open-source flexibility against lock-in.',
		previewType: 'pdf',
		topResource: true,
	},
	{
		id: 'r12',
		product: 'WooCommerce',
		stage: 'Manage',
		contentType: 'Reference guide',
		audience: 'Developer',
		title: 'WooCommerce extensions reference',
		description: 'The essential extensions for subscriptions, bookings, and payments.',
		previewType: 'pdf',
	},
	{
		id: 'r13',
		product: 'WooCommerce',
		stage: 'Grow',
		contentType: 'Case study',
		audience: 'Client',
		title: 'Growing a store’s revenue with WooPayments',
		description: 'A client-facing case study on conversion lifts and recurring commissions.',
		previewType: 'pdf',
	},
	{
		id: 'r14',
		product: 'WooCommerce',
		stage: 'Learn',
		contentType: 'Blog',
		audience: 'Developer',
		title: 'Building performant Woo stores',
		description: 'Patterns for caching, queries, and checkout speed on high-traffic stores.',
		previewType: 'doc',
	},
	{
		id: 'r15',
		product: 'WordPress.com',
		stage: 'Learn',
		contentType: 'Guide',
		audience: 'Developer',
		title: 'WordPress.com developer tools guide',
		description: 'Staging, GitHub deployments, WP-CLI, and SSH for agency workflows.',
		previewType: 'doc',
	},
	{
		id: 'r16',
		product: 'WordPress.com',
		stage: 'Sell',
		contentType: 'One-pager',
		audience: 'Business',
		title: 'Why host clients on WordPress.com',
		description: 'Performance, security, and support benefits in one page.',
		previewType: 'pdf',
	},
	{
		id: 'r17',
		product: 'WordPress.com',
		stage: 'Manage',
		contentType: 'Checklist',
		audience: 'Developer',
		title: 'Site launch checklist',
		description: 'Pre-flight checks for performance, SEO, and security before go-live.',
		previewType: 'pdf',
	},
	{
		id: 'r18',
		product: 'WordPress.com',
		stage: 'Grow',
		contentType: 'Talk track',
		audience: 'Client',
		title: 'Upsell conversations that build trust',
		description: 'How to recommend upgrades that genuinely help your client’s site.',
		previewType: 'doc',
	},
	{
		id: 'r19',
		product: 'Jetpack',
		stage: 'Manage',
		contentType: 'Reference guide',
		audience: 'Developer',
		title: 'Jetpack security & backups reference',
		description: 'Configure real-time backups, malware scanning, and downtime alerts.',
		previewType: 'pdf',
	},
	{
		id: 'r20',
		product: 'Jetpack',
		stage: 'Learn',
		contentType: 'One-pager',
		audience: 'All',
		title: 'Jetpack for agencies',
		description: 'The security, performance, and growth toolkit included with your sites.',
		previewType: 'pdf',
	},
	{
		id: 'r21',
		product: 'Jetpack',
		stage: 'Sell',
		contentType: 'Slide deck',
		audience: 'Business',
		title: 'Selling Jetpack bundles',
		description: 'A deck that frames security and performance as client peace of mind.',
		previewType: 'slides',
	},
	{
		id: 'r22',
		product: 'Jetpack',
		stage: 'Grow',
		contentType: 'Webinar',
		audience: 'All',
		title: 'Recurring revenue with Jetpack',
		description: 'A recorded walkthrough of bundling and reselling Jetpack plans.',
		previewType: 'video',
	},
	{
		id: 'r23',
		product: 'Program',
		stage: 'Manage',
		contentType: 'Reference guide',
		audience: 'Business',
		title: 'Managing your agency dashboard',
		description: 'Team roles, billing, and client site organization in one place.',
		previewType: 'pdf',
	},
	{
		id: 'r24',
		product: 'WordPress VIP',
		stage: 'Manage',
		contentType: 'Webinar',
		audience: 'Developer',
		title: 'Operating enterprise sites on VIP',
		description: 'A technical session on CI/CD, code review, and observability at scale.',
		previewType: 'video',
	},
];
