// Local design fixtures. Titles and media are illustrative, not published enablement materials.
export const sampleResources = [
	{
		id: 'sample-01',
		title: 'Introducing WordPress VIP',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'WordPress VIP',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-02',
		title: 'Managed hosting for growing agencies',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'Pressable',
		stage: 'Grow',
		audience: 'Business',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-03',
		title: 'Your first WooCommerce discovery call',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'WooCommerce',
		stage: 'Sell',
		audience: 'Business',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-04',
		title: 'WordPress.com for agency projects',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'WordPress.com',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-05',
		title: 'An introduction to Jetpack for agencies',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'Jetpack',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-06',
		title: 'Your agency program starter kit',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-07',
		title: 'Pricing projects with confidence',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'Automattic for Agencies',
		stage: 'Sell',
		audience: 'Business',
		format: 'Talk track',
		url: '',
	},
	{
		id: 'sample-08',
		title: 'Setting expectations before kickoff',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'Client',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-09',
		title: 'Making the case for enterprise WordPress',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'WordPress VIP',
		stage: 'Sell',
		audience: 'Business',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-10',
		title: 'Moving your first client to Pressable',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'Pressable',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-11',
		title: 'Planning a store launch',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'WooCommerce',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-12',
		title: 'A client-ready hosting overview',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'WordPress.com',
		stage: 'Learn',
		audience: 'Client',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-13',
		title: 'Building a website security package',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'Jetpack',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-14',
		title: 'Understanding tiers and benefits',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Talk track',
		url: '',
	},
	{
		id: 'sample-15',
		title: 'Running a discovery workshop',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'Automattic for Agencies',
		stage: 'Sell',
		audience: 'Business',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-16',
		title: 'A better website handoff',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'Automattic for Agencies',
		stage: 'Manage',
		audience: 'Client',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-17',
		title: 'Planning an enterprise migration',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'WordPress VIP',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-18',
		title: 'A practical guide to staging sites',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'Pressable',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-19',
		title: 'Choosing extensions with confidence',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'WooCommerce',
		stage: 'Learn',
		audience: 'Developer',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-20',
		title: 'Deploying with GitHub',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'WordPress.com',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-21',
		title: 'Real-time backups explained',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'Jetpack',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Talk track',
		url: '',
	},
	{
		id: 'sample-22',
		title: 'Your guide to referrals and commissions',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-23',
		title: 'Writing a proposal that gets read',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'Automattic for Agencies',
		stage: 'Sell',
		audience: 'Business',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-24',
		title: 'Explaining performance without jargon',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'Automattic for Agencies',
		stage: 'Sell',
		audience: 'Developer',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-25',
		title: 'Security questions your clients will ask',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'WordPress VIP',
		stage: 'Sell',
		audience: 'Developer',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-26',
		title: 'Explaining hosting value to your clients',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'Pressable',
		stage: 'Sell',
		audience: 'Client',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-27',
		title: 'Improving the checkout experience',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'WooCommerce',
		stage: 'Learn',
		audience: 'Developer',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-28',
		title: 'Working with staging environments',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'WordPress.com',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Talk track',
		url: '',
	},
	{
		id: 'sample-29',
		title: 'Responding to a security incident',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'Jetpack',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-30',
		title: 'Inviting your team to the dashboard',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'Automattic for Agencies',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-31',
		title: 'Building a repeatable sales process',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-32',
		title: 'Helping clients plan their content',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-33',
		title: 'A better workflow for editorial teams',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'WordPress VIP',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-34',
		title: 'Managing a portfolio of client sites',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'Pressable',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-35',
		title: 'Subscriptions and recurring payments',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'WooCommerce',
		stage: 'Grow',
		audience: 'Business',
		format: 'Talk track',
		url: '',
	},
	{
		id: 'sample-36',
		title: 'Moving an existing site to WordPress.com',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'WordPress.com',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-37',
		title: 'Improving performance with Jetpack Boost',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'Jetpack',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-38',
		title: 'Preparing your partner directory profile',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-39',
		title: 'Moving from projects to retainers',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'Automattic for Agencies',
		stage: 'Grow',
		audience: 'Business',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-40',
		title: 'Running an effective quarterly review',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'Automattic for Agencies',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-41',
		title: 'Measuring performance at scale',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'WordPress VIP',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-42',
		title: 'Backups and recovery, step by step',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'Pressable',
		stage: 'Manage',
		audience: 'Developer',
		format: 'Talk track',
		url: '',
	},
	{
		id: 'sample-43',
		title: 'Keeping a busy store running smoothly',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'WooCommerce',
		stage: 'Manage',
		audience: 'All audiences',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-44',
		title: 'A practical site handoff checklist',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'WordPress.com',
		stage: 'Manage',
		audience: 'Client',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-45',
		title: 'Protecting your clients from spam',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'Jetpack',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-46',
		title: 'Finding the right product for a client',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-47',
		title: 'Creating a client onboarding playbook',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'Client',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-48',
		title: 'Turning client feedback into next steps',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-49',
		title: 'Preparing for a VIP discovery call',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'WordPress VIP',
		stage: 'Sell',
		audience: 'Business',
		format: 'Talk track',
		url: '',
	},
	{
		id: 'sample-50',
		title: 'Choosing the right hosting plan',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'Pressable',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-51',
		title: 'A client guide to WooCommerce',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'WooCommerce',
		stage: 'Learn',
		audience: 'Client',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-52',
		title: 'Developer tools in action',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'WordPress.com',
		stage: 'Learn',
		audience: 'Developer',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-53',
		title: 'Presenting a maintenance proposal',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'Jetpack',
		stage: 'Sell',
		audience: 'Business',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-54',
		title: 'Making the most of your agency partnership',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'Automattic for Agencies',
		stage: 'Grow',
		audience: 'Business',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-55',
		title: 'Having better renewal conversations',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'Automattic for Agencies',
		stage: 'Grow',
		audience: 'Business',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-56',
		title: 'Talking about accessibility with clients',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'Client',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-57',
		title: 'Building a long-term enterprise partnership',
		description:
			'A sample agency story exploring the approach, lessons learned, and opportunities.',
		product: 'WordPress VIP',
		stage: 'Grow',
		audience: 'Business',
		format: 'Case study',
		url: '',
	},
	{
		id: 'sample-58',
		title: 'Turning hosting into recurring revenue',
		description: 'A practical introduction with the essentials your team needs to get started.',
		product: 'Pressable',
		stage: 'Grow',
		audience: 'Business',
		format: 'Guide',
		url: '',
	},
	{
		id: 'sample-59',
		title: 'Growing beyond the first sale',
		description: 'Watch a walkthrough of the key decisions, common questions, and next steps.',
		product: 'WooCommerce',
		stage: 'Grow',
		audience: 'Business',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-60',
		title: 'Choosing a plan for your next project',
		description: 'A reusable checklist to help your team prepare, deliver, and follow through.',
		product: 'WordPress.com',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Checklist',
		url: '',
	},
	{
		id: 'sample-61',
		title: 'Selling peace of mind with ongoing care',
		description: 'A presentation to support your next client conversation or team workshop.',
		product: 'Jetpack',
		stage: 'Sell',
		audience: 'Business',
		format: 'Slide deck',
		url: '',
	},
	{
		id: 'sample-62',
		title: 'Your first 90 days in the program',
		description: 'A concise overview you can share with a client or keep close for reference.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'One-pager',
		url: '',
	},
	{
		id: 'sample-63',
		title: 'Building a healthier project pipeline',
		description: 'A recorded session exploring practical workflows and everyday agency challenges.',
		product: 'Automattic for Agencies',
		stage: 'Grow',
		audience: 'Business',
		format: 'Video',
		url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
	},
	{
		id: 'sample-64',
		title: 'Telling the story of a successful project',
		description: 'Conversation prompts and talking points to help you explain the value clearly.',
		product: 'Automattic for Agencies',
		stage: 'Learn',
		audience: 'All audiences',
		format: 'Talk track',
		url: '',
	},
];
