/**
 * Web pay processor (Apple Pay and Google Pay) for Dashboard checkout.
 *
 * Handles transactions coming from Stripe's Payment Request API, which powers
 * both Apple Pay and Google Pay with a single code path.
 */
import { confirmStripePaymentIntent } from '@automattic/calypso-stripe';
import {
	makeSuccessResponse,
	makeErrorResponse,
	type PaymentProcessorResponse,
} from '@automattic/composite-checkout';
import { createTransactionCart, createTransactionRequest } from '../transaction-utils';
import type { TransactionRequest, TransactionResponse } from '@automattic/api-core';
import type { StripeConfiguration } from '@automattic/calypso-stripe';
import type { DomainContactDetails, ResponseCart } from '@automattic/shopping-cart';
import type { Stripe } from '@stripe/stripe-js';

export interface WebPayProcessorSubmitData {
	stripe: Stripe;
	stripeConfiguration: StripeConfiguration;
	paymentMethodToken: string;
	name: string | undefined;
}

export interface WebPayProcessorOptions {
	siteId: number;
	responseCart: ResponseCart;
	countryCode?: string;
	postalCode?: string;
	domainDetails?: DomainContactDetails | null;
}

function doesResponseRequire3DS( response: unknown ): response is TransactionResponse & {
	message: { requires_action: true; payment_intent_client_secret: string };
} {
	if ( ! response || typeof response !== 'object' ) {
		return false;
	}
	const r = response as TransactionResponse;
	return !! ( r.message?.requires_action && r.message?.payment_intent_client_secret );
}

/**
 * Process an Apple Pay or Google Pay transaction.
 *
 * The paymentMethodToken is the Stripe payment method ID generated by the
 * Stripe Payment Request API after the user authenticates in their wallet.
 */
export async function webPayProcessor(
	submitData: WebPayProcessorSubmitData,
	submitTransaction: ( request: TransactionRequest ) => Promise< unknown >,
	options: WebPayProcessorOptions
): Promise< PaymentProcessorResponse > {
	const { siteId, responseCart, countryCode, postalCode, domainDetails } = options;

	const cart = createTransactionCart( { siteId, responseCart } );
	const transactionRequest = createTransactionRequest( {
		cart,
		payment: {
			payment_method: 'WPCOM_Billing_Stripe_Payment_Method',
			payment_key: submitData.paymentMethodToken,
			payment_partner: submitData.stripeConfiguration.processor_id,
			name: submitData.name || '',
			country: countryCode,
			country_code: countryCode,
			postal_code: postalCode,
			zip: postalCode,
		},
		domainDetails: domainDetails ?? null,
	} );

	let response: unknown;
	try {
		response = await submitTransaction( transactionRequest );
	} catch ( error ) {
		return makeErrorResponse( ( error as Error ).message );
	}

	if ( doesResponseRequire3DS( response ) ) {
		try {
			await confirmStripePaymentIntent(
				submitData.stripe,
				response.message.payment_intent_client_secret
			);
		} catch ( error ) {
			return makeErrorResponse( ( error as Error ).message );
		}
	}

	return makeSuccessResponse( response );
}
