compressionLevel: 0

enableGlobalCache: true

preferAggregateCacheInfo: true

logFilters:
  - pattern: 'fsevents@*/* The * architecture is incompatible with this module, link skipped.'
    level: discard

  # Depends on newspack-components: https://github.com/Automattic/newspack-plugin/pull/1135
  - pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react (pa4cd8) with version 17.0.2, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"
    level: discard
  - pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react-dom (pe0d22) with version 17.0.2, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"
    level: discard

  # Depends on
  #   airbnb-prop-types: https://github.com/airbnb/prop-types/issues/73
  #   react-autosize-textarea: https://github.com/buildo/react-autosize-textarea/issues/149
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "calypso@workspace:client provides react (pe6f5d) with version 17.0.2, which doesn't satisfy what @automattic/isolated-block-editor and some of its descendants request"
    level: discard

  # Depends on
  #   react-simple-code-editor: https://github.com/satya164/react-simple-code-editor/issues/75
  - pattern: "calypso@workspace:client provides react (p44ec6) with version 17.0.2, which doesn't satisfy what react-live and some of its descendants request"
    level: discard
  - pattern: "calypso@workspace:client provides react-dom (p2ead7) with version 17.0.2, which doesn't satisfy what react-live and some of its descendants request"
    level: discard

  # Depends on
  #   react-autosize-textarea: https://github.com/buildo/react-autosize-textarea/issues/149
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "calypso@workspace:client provides react-dom (pb67b8) with version 17.0.2, which doesn't satisfy what @automattic/isolated-block-editor and some of its descendants request"
    level: discard

  # Depends on
  #   react-autosize-textarea: https://github.com/buildo/react-autosize-textarea/issues/149
  - pattern: "wp-calypso@workspace:. provides react (pc4e63) with version 17.0.2, which doesn't satisfy what @types/wordpress__block-editor and some of its descendants request"
    level: discard
  - pattern: "wp-calypso@workspace:. provides react-dom (p05bbc) with version 17.0.2, which doesn't satisfy what @types/wordpress__block-editor and some of its descendants request"
    level: discard

  # Depends on
  #   airbnb-prop-types: https://github.com/airbnb/prop-types/issues/73
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "wp-calypso@workspace:. provides react (p06525) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard

  # Depends on
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "wp-calypso@workspace:. provides react-dom (p45deb) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard

  # Depends on
  #   @react/router: https://github.com/reach/router/issues/429
  #   create-react-context: https://github.com/jamiebuilds/create-react-context/pull/33
  - pattern: "calypso@workspace:client provides react (pf0c51) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard
  - pattern: "wp-calypso@workspace:. provides react (p08767) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard

  # Depends on
  #   @react/router: https://github.com/reach/router/issues/429
  - pattern: "calypso@workspace:client provides react-dom (p69c5d) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard
  - pattern: "wp-calypso@workspace:. provides react-dom (pff688) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard

  # `postinstall` script fails (https://github.com/pmndrs/react-spring/issues/1668)
  # Fixed in https://github.com/yarnpkg/berry/pull/3661, we need for a new yarn release.
  # Work around it by disabling scripts for this package (see `dependenciesMeta` in `package.json`). The workaround can be removed
  # once we have a Yarn version with the fix.
  - pattern: '@react-spring/core@npm:9.3.0 [3ac30] lists build scripts, but its build has been explicitly disabled through configuration.'
    level: discard

nodeLinker: node-modules

packageExtensions:
  '@emotion/native@10.0.27':
    peerDependencies:
      '@emotion/core': '*'
      react: '*'
  '@storybook/csf-tools@6.3.12':
    peerDependencies:
      webpack: '*'
      '@babel/core': '*'
  '@storybook/core-server@6.3.12':
    peerDependencies:
      '@babel/core': '*'
  '@storybook/core@6.3.12':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@types/wordpress__block-editor@6.0.4':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@types/wordpress__blocks@6.4.12':
    peerDependencies:
      react: '*'
  '@types/wordpress__components@14.0.4':
    peerDependencies:
      react: '*'
  '@types/wordpress__editor@10.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@types/wordpress__media-utils@0.2.4':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@types/wordpress__plugins@3.0.0':
    peerDependencies:
      react: '*'
  '@wordpress/annotations@2.2.6':
    peerDependencies:
      redux: '*'
      react: '*'
  '@wordpress/block-editor@7.0.4':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/block-editor@8.0.5':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/block-library@6.0.9':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/blocks@11.1.4':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/components@12.0.8': # TODO: Remove when newspack-components updates.
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
  '@wordpress/components@18.0.0':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
  '@wordpress/components@19.0.5':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
  '@wordpress/compose@3.25.3':
    peerDependencies:
      react: '*'
  '@wordpress/compose@5.0.6':
    peerDependencies:
      react: '*'
  '@wordpress/core-data@4.0.7':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/data-controls@2.2.7':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/data@4.27.3':
    peerDependencies:
      react: '*'
  '@wordpress/data@6.1.4':
    peerDependencies:
      react: '*'
  '@wordpress/edit-post@5.0.11':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/edit-site@3.0.11':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/editor@12.0.8':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/eslint-plugin@9.3.0':
    peerDependencies:
      '@babel/core': '*'
  '@wordpress/format-library@3.0.11':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/interface@4.1.7':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/jest-preset-default@7.1.3':
    peerDependencies:
      '@babel/core': '*'
      react: '*'
      react-dom: '*'
  '@wordpress/keyboard-shortcuts@3.0.6':
    peerDependencies:
      redux: '*'
      react: '*'
  '@wordpress/list-reusable-blocks@3.0.5':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/notices@3.2.7':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/nux@5.0.9':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/plugins@4.0.6':
    peerDependencies:
      react: '*'
  '@wordpress/postcss-plugins-preset@3.2.5':
    peerDependencies:
      postcss: '*'
  '@wordpress/reusable-blocks@3.0.11':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/rich-text@3.25.3':
    peerDependencies:
      react: '*'
  '@wordpress/rich-text@5.0.6':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/scripts@19.2.2':
    peerDependencies:
      '@babel/core': '*'
      react: '*'
      react-dom: '*'
  '@wordpress/server-side-render@3.0.9':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/viewport@4.0.6':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wp-g2/components@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/context@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/styles@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  fake-indexeddb@3.1.3:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  file-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  '@automattic/isolated-block-editor@2.6.0':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
    dependencies:
      # Note: isolated block editor already declares this as a dev dep, but since
      # an eslint plugin is a proper dependency, it doesn't think the dev dep exists.
      # Can be removed once https://github.com/Automattic/isolated-block-editor/pull/88
      # is merged and released.
      eslint: '*'
  jest-enzyme@7.1.2:
    peerDependencies:
      react: '*'
  '@automattic/newspack-blocks@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
  newspack-components@1.6.1:
    dependencies:
      react-native: '*' # TODO: Remove when newspack-components updates.
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
  react-native-codegen@0.0.7: # TODO: Remove when newspack-components updates.
    # This package is unused by our repo. We only install react-native in newspack-components
    # to fulfill a basically useless (and removed in newer versions) peer dependency.
    # This brings along this secondary peer dep warning which only exists in
    # transitive dependencies. To avoid having to write these dependencies all
    # over the place, I'm just installing them directly here to stop the problem.
    dependencies:
      '@babel/preset-env': '*'
      '@babel/core': '*'
  react-dev-utils@11.0.4:
    peerDependencies:
      typescript: '*'
      webpack: '*'
  react-with-styles@3.2.3:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.4.0:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.5.5:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.6.2:
    peerDependencies:
      react-dom: '*'
  realistic-structured-clone@2.0.2:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.0.cjs
