compressionLevel: 0

enableGlobalCache: true

preferAggregateCacheInfo: true

logFilters:
  - pattern: 'fsevents@*/* The platform * is incompatible with this module, link skipped.'
    level: discard

nodeLinker: node-modules

packageExtensions:
  '@emotion/native@10.0.27':
    peerDependencies:
      '@emotion/core': '*'
      react: '*'
  '@storybook/csf-tools@6.3.8':
    peerDependencies:
      webpack: '*'
      '@babel/core': '*'
  '@storybook/core-server@6.3.8':
    peerDependencies:
      '@babel/core': '*'
  '@storybook/core@6.3.8':
    peerDependencies:
      '@babel/core': '*'
      'webpack': '*'
  '@types/wordpress__block-editor@6.0.4':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@types/wordpress__blocks@6.4.12':
    peerDependencies:
      react: '*'
  '@types/wordpress__components@14.0.3':
    peerDependencies:
      react: '*'
  '@types/wordpress__data-controls@1.0.5':
    peerDependencies:
      react-native: '*'
  '@types/wordpress__editor@10.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
  '@types/wordpress__media-utils@0.2.4':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
  '@types/wordpress__plugins@2.3.7':
    peerDependencies:
      react: '*'
  '@wordpress/annotations@2.2.3':
    peerDependencies:
      redux: '*'
      react: '*'
  '@wordpress/api-fetch@3.23.1':
    peerDependencies:
      react-native: '*'
  '@wordpress/api-fetch@4.0.0':
    peerDependencies:
      react-native: '*'
  '@wordpress/api-fetch@5.2.2':
    peerDependencies:
      react-native: '*'
  '@wordpress/block-editor@5.3.3':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
  '@wordpress/block-editor@7.0.2':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/block-library@2.29.3':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/block-library@5.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/blocks@8.0.3':
    peerDependencies:
      react: '*'
  '@wordpress/blocks@11.1.0':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/components@12.0.8':
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
  '@wordpress/components@13.0.3':
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
  '@wordpress/components@16.0.0':
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      redux: '*'
  '@wordpress/components@17.0.0':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
  '@wordpress/compose@3.25.3':
    peerDependencies:
      react: '*'
  '@wordpress/compose@5.0.2':
    peerDependencies:
      react: '*'
  '@wordpress/core-data@2.26.3':
    peerDependencies:
      react: '*'
      react-native: '*'
  '@wordpress/core-data@4.0.1':
    peerDependencies:
      react: '*'
      react-native: '*'
      redux: '*'
  '@wordpress/data-controls@1.21.3':
    peerDependencies:
      react: '*'
      react-native: '*'
  '@wordpress/data-controls@2.2.3':
    peerDependencies:
      react: '*'
      react-native: '*'
      redux: '*'
  '@wordpress/data@4.27.3':
    peerDependencies:
      react: '*'
  '@wordpress/data@6.1.0':
    peerDependencies:
      react: '*'
  '@wordpress/edit-post@5.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/edit-site@3.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/editor@9.26.3':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/editor@11.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/format-library@1.27.3':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
  '@wordpress/format-library@3.0.2':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      redux: '*'
      react-native: '*'
  '@wordpress/interface@2.0.2':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
  '@wordpress/interface@4.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/jest-preset-default@7.1.0':
    peerDependencies:
      '@babel/core': '*'
      react: '*'
      react-dom: '*'
  '@wordpress/keyboard-shortcuts@1.14.3':
    peerDependencies:
      react: '*'
  '@wordpress/keyboard-shortcuts@3.0.2':
    peerDependencies:
      redux: '*'
      react: '*'
  '@wordpress/list-reusable-blocks@3.0.2':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      react-native: '*'
      redux: '*'
  '@wordpress/media-utils@1.20.3':
    peerDependencies:
      react-native: '*'
  '@wordpress/media-utils@3.0.0':
    peerDependencies:
      react-native: '*'
  '@wordpress/notices@2.13.3':
    peerDependencies:
      react: '*'
  '@wordpress/notices@3.2.3':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/nux@5.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/plugins@2.25.3':
    peerDependencies:
      react: '*'
  '@wordpress/plugins@4.0.1':
    peerDependencies:
      react: '*'
  '@wordpress/postcss-plugins-preset@3.2.0':
    peerDependencies:
      postcss: '*'
  '@wordpress/reusable-blocks@1.2.3':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
  '@wordpress/reusable-blocks@3.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/rich-text@3.25.3':
    peerDependencies:
      react: '*'
  '@wordpress/rich-text@5.0.2':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wordpress/scripts@18.0.0':
    peerDependencies:
      '@babel/core': '*'
      react: '*'
      react-dom: '*'
  '@wordpress/server-side-render@1.21.3':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/server-side-render@3.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/url@2.22.2':
    peerDependencies:
      react-native: '*'
  '@wordpress/url@3.2.2':
    peerDependencies:
      react-native: '*'
  '@wordpress/viewport@2.26.3':
    peerDependencies:
      react: '*'
  '@wordpress/viewport@4.0.1':
    peerDependencies:
      react: '*'
      redux: '*'
  '@wp-g2/components@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/components@0.0.160':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/context@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/context@0.0.160':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/styles@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/styles@0.0.160':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  fake-indexeddb@3.1.3:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  file-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  '@automattic/isolated-block-editor@2.4.1':
    peerDependencies:
      '@wp-g2/create-styles': '*'
      react: '*'
      react-dom: '*'
      redux: '*'
      react-native: '*'
  jest-enzyme@7.1.2:
    peerDependencies:
      react: '*'
  '@automattic/newspack-blocks@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
      react-native: '*'
      reakit-utils: '*'
  newspack-components@*:
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
  react-dev-utils@11.0.4:
    peerDependencies:
      typescript: '*'
      webpack: '*'
  react-live@2.4.0:
    peerDependencies:
      react: '*'
      react-dom: '*'
  react-with-styles@3.2.3:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.4.0:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.5.5:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.6.2:
    peerDependencies:
      react-dom: '*'
  realistic-structured-clone@2.0.2:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  xunit-viewer@5.2.0:
    peerDependencies:
      '@babel/core': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.0.0.cjs
