compressionLevel: 0

enableGlobalCache: true

logFilters:
  - level: discard
    pattern: "+(react|react-dom) is listed by your project with version 18.3.1, which doesn't satisfy what +(@wordpress/*|@types/wordpress__*) and other dependencies request*"

nodeLinker: node-modules

packageExtensions:
  "@automattic/newspack-blocks@*":
    peerDependencies:
      moment: "*"
      react: "*"
      react-dom: "*"
  "@signal-noise/stylelint-scales@2.0.3":
    peerDependencies:
      postcss: "*"
  "@wordpress/stylelint-config@22.2.0":
    peerDependencies:
      postcss: "*"
  fake-indexeddb@3.1.7:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  newspack-components@2.1.0:
    peerDependencies:
      moment: "*"
      react: "*"
      react-dom: "*"
  realistic-structured-clone@2.0.2:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  stylelint-config-recommended-scss@5.0.2:
    peerDependencies:
      postcss: "*"
  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
