compressionLevel: 0

enableGlobalCache: true

preferAggregateCacheInfo: true

logFilters:
  - pattern: 'fsevents@*/* The * architecture is incompatible with this module, link skipped.'
    level: discard

  # Depends on newspack-components: https://github.com/Automattic/newspack-plugin/pull/1135
  - pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react (pa4cd8) with version 17.0.2, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"
    level: discard
  - pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react-dom (pe0d22) with version 17.0.2, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"
    level: discard

  # Depends on
  #   airbnb-prop-types: https://github.com/airbnb/prop-types/issues/73
  #   react-autosize-textarea: https://github.com/buildo/react-autosize-textarea/issues/149
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "calypso@workspace:client provides react (pbf525) with version 17.0.2, which doesn't satisfy what @automattic/isolated-block-editor and some of its descendants request"
    level: discard

  # Depends on
  #   react-autosize-textarea: https://github.com/buildo/react-autosize-textarea/issues/149
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "calypso@workspace:client provides react-dom (p79552) with version 17.0.2, which doesn't satisfy what @automattic/isolated-block-editor and some of its descendants request"
    level: discard

  # Depends on
  #   react-simple-code-editor: https://github.com/satya164/react-simple-code-editor/issues/75
  - pattern: "calypso@workspace:client provides react (p44ec6) with version 17.0.2, which doesn't satisfy what react-live and some of its descendants request"
    level: discard
  - pattern: "calypso@workspace:client provides react-dom (p2ead7) with version 17.0.2, which doesn't satisfy what react-live and some of its descendants request"
    level: discard

  # Depends on
  #   react-autosize-textarea: https://github.com/buildo/react-autosize-textarea/issues/149
  - pattern: "wp-calypso@workspace:. provides react (p79163) with version 17.0.2, which doesn't satisfy what @types/wordpress__block-editor and some of its descendants request"
    level: discard
  - pattern: "wp-calypso@workspace:. provides react-dom (pf5aa8) with version 17.0.2, which doesn't satisfy what @types/wordpress__block-editor and some of its descendants request"
    level: discard

  # Depends on
  #   airbnb-prop-types: https://github.com/airbnb/prop-types/issues/73
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "wp-calypso@workspace:. provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "calypso@workspace:client provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/launch@workspace:packages/launch *provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/o2-blocks@workspace:apps/o2-blocks provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/search@workspace:packages/search *provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/wpcom-block-editor@workspace:apps/wpcom-block-editor provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard

  # Depends on
  #   react-dates: https://github.com/airbnb/react-dates/issues/2105
  #   react-with-direction: https://github.com/airbnb/react-with-direction/issues/20
  - pattern: "wp-calypso@workspace:. provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "calypso@workspace:client provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/domain-picker@workspace:packages/domain-picker *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/launch@workspace:packages/launch *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/o2-blocks@workspace:apps/o2-blocks provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/onboarding@workspace:packages/onboarding *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/page-pattern-modal@workspace:packages/page-pattern-modal *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/search@workspace:packages/search *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/social-previews@workspace:packages/social-previews *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/wpcom-block-editor@workspace:apps/wpcom-block-editor provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard
  - pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
    level: discard

  # Depends on
  #   @react/router: https://github.com/reach/router/issues/429
  #   create-react-context: https://github.com/jamiebuilds/create-react-context/pull/33
  - pattern: "calypso@workspace:client provides react (pf0c51) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard
  - pattern: "wp-calypso@workspace:. provides react (p08767) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard

  # Depends on
  #   @react/router: https://github.com/reach/router/issues/429
  - pattern: "calypso@workspace:client provides react-dom (p69c5d) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard
  - pattern: "wp-calypso@workspace:. provides react-dom (pff688) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
    level: discard

  # Depends on
  #  @wordpress/eslint-plugin: https://github.com/WordPress/gutenberg/issues/35576
  - pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides eslint (pcb2ba) with version 8.6.0, which doesn't satisfy what @wordpress/eslint-plugin and some of its descendants request"
    level: discard
  - pattern: "wp-calypso@workspace:. provides eslint (p3918c) with version 8.6.0, which doesn't satisfy what @wordpress/eslint-plugin and some of its descendants request"
    level: discard

  # `postinstall` script fails (https://github.com/pmndrs/react-spring/issues/1668)
  # Fixed in https://github.com/yarnpkg/berry/pull/3661, we need for a new yarn release.
  # Work around it by disabling scripts for this package (see `dependenciesMeta` in `package.json`). The workaround can be removed
  # once we have a Yarn version with the fix.
  - pattern: '@react-spring/core@npm:9.3.0 * lists build scripts, but its build has been explicitly disabled through configuration.'
    level: discard

nodeLinker: node-modules

packageExtensions:
  '@emotion/native@10.0.27':
    peerDependencies:
      '@emotion/core': '*'
      react: '*'
  '@signal-noise/stylelint-scales@2.0.3':
    peerDependencies:
      postcss: '*'
  '@types/wordpress__block-editor@6.0.5':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@types/wordpress__blocks@6.4.12':
    peerDependencies:
      react: '*'
  '@types/wordpress__components@14.0.10':
    peerDependencies:
      react: '*'
  '@types/wordpress__editor@10.0.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@types/wordpress__media-utils@0.2.4':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@types/wordpress__plugins@3.0.0':
    peerDependencies:
      react: '*'
  '@wordpress/annotations@2.2.7':
    peerDependencies:
      redux: '*'
      react: '*'
  '@wordpress/block-library@6.0.18':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/components@12.0.8': # TODO: Remove when newspack-components updates.
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
      react-native: '*'
  '@wordpress/compose@3.25.3':
    peerDependencies:
      react: '*'
  '@wordpress/data@4.27.3':
    peerDependencies:
      react: '*'
  '@wordpress/edit-post@5.0.20':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
      reakit-utils: '*'
  '@wordpress/jest-preset-default@7.1.3':
    peerDependencies:
      '@babel/core': '*'
      react: '*'
      react-dom: '*'
  '@wordpress/list-reusable-blocks@3.0.13':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
      redux: '*'
  '@wordpress/rich-text@3.25.3':
    peerDependencies:
      react: '*'
  '@wordpress/stylelint-config@20.0.3':
    peerDependencies:
      postcss: '*'
  '@wp-g2/components@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/context@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  '@wp-g2/styles@0.0.140':
    peerDependencies:
      '@wordpress/data': '*'
      '@wordpress/is-shallow-equal': '*'
  fake-indexeddb@3.1.7:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  file-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  '@automattic/isolated-block-editor@2.8.1':
    peerDependencies:
      react: '*'
      react-dom: '*'
      redux: '*'
  jest-enzyme@7.1.2:
    peerDependencies:
      react: '*'
  '@automattic/newspack-blocks@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
      reakit-utils: '*'
  newspack-components@1.6.1:
    dependencies:
      react-native: '*' # TODO: Remove when newspack-components updates.
    peerDependencies:
      '@wordpress/data': '*'
      react: '*'
      react-dom: '*'
  react-native-codegen@0.0.7: # TODO: Remove when newspack-components updates.
    # This package is unused by our repo. We only install react-native in newspack-components
    # to fulfill a basically useless (and removed in newer versions) peer dependency.
    # This brings along this secondary peer dep warning which only exists in
    # transitive dependencies. To avoid having to write these dependencies all
    # over the place, I'm just installing them directly here to stop the problem.
    dependencies:
      '@babel/preset-env': '*'
      '@babel/core': '*'
  react-with-styles@3.2.3:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.4.0:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.5.5:
    peerDependencies:
      react-dom: '*'
  reakit-warning@0.6.2:
    peerDependencies:
      react-dom: '*'
  realistic-structured-clone@2.0.2:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  stylelint-config-recommended-scss@5.0.2:
    peerDependencies:
      postcss: '*'
  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
