### Basic Yarn settings. ###
compressionLevel: 0
nodeLinker: node-modules
enableGlobalCache: true
preferAggregateCacheInfo: true
yarnPath: .yarn/releases/yarn-3.2.3.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

### Log filters to discard irrelevant warnings. ###
logFilters:
# The fsevents warning is useless, so discard it:
  - level: discard
    pattern: "fsevents@*/* The * architecture is incompatible with this module, link skipped."

# Newspack blocks has many transitive dependencies without React 18 explicitly supported, so we need to ignore those.
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"

# WordPress packages often have transitive dependencies with incorrect react-related peer dependencies.
# This matcher discards those log messages, while allowing non-react or non-wordpress related violations
# to be handled separately. (For example, npm packages can be handled via packageExtensions.)
#
# WordPress will need to update/change the following packages to versions which include React 18 support,
# and then we'll need to update to those WordPress package versions before we can remove this.
# - react-autosize-textarea@npm:7.1.0
# - reakit-system@npm:0.15.2
# - reakit-utils@npm:0.15.2
# - reakit-warning@npm:0.6.2
# - reakit@npm:1.3.11
#
# The matcher works like so:
# 1. Match any workspace package, such as @automattic/global-styles@workspace, calypso@workspace, happy-blocks@workspace
# 2. Match any path within the workspace, such as @workspace:packages/page-pattern-modal [cd6b3], @workspace::apps/editing-toolkit, @workspace:client, or @workspace:.
# 3. Match a react or react-dom on the current version which a workspace package provides.
# 4. Match only violations coming from within @wordpress packages.
  - level: discard
    pattern: "**@workspace:+(client|*/*|.) provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what +(@wordpress/*|@types/wordpress__*) and some of its descendants request"

# TODO: Remove this once Reakit can be removed (or once Reakit includes React 18 as a peer dependency.)
  - level: discard
    pattern: "calypso@workspace:client provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what reakit and some of its descendants request"
  
# TODO: Remove this once the react-autosize-textarea transitive dependency has been fixed/updated to a version with React 18 support.
  - level: discard
    pattern: "calypso@workspace:client provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what @automattic/block-renderer and some of its descendants request"

# React day picker version 7 does not include explicit react 18 support, but we can't update to v8 just yet.
# TODO: Remove after updating to react-day-picker version 8.
  - level: discard
    pattern: "calypso@workspace:client provides react (*) with version 18.2.0, which doesn't satisfy what react-day-picker requests"

# TODO: Remove after the `preact` dependency version has beem bumped in `@wordpress/interactivity.
  - level: discard
    pattern: "@wordpress/interactivity@npm:2.4.0 provides preact (*) with version 10.15.1, which doesn't satisfy what deepsignal requests"

### Package extensions to provide missing peer dependencies. ###
packageExtensions:
  "@automattic/newspack-blocks@*":
    peerDependencies:
      moment: "*"
      react: "*"
      react-dom: "*"
  "@signal-noise/stylelint-scales@2.0.3":
    peerDependencies:
      postcss: "*"
  "@wordpress/stylelint-config@21.26.0":
    peerDependencies:
      postcss: "*"
  fake-indexeddb@3.1.7:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  newspack-components@2.1.0:
    peerDependencies:
      moment: "*"
      react: "*"
      react-dom: "*"
  reakit-warning@0.6.2:
    peerDependencies:
      react-dom: "*"
  realistic-structured-clone@2.0.2:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  stylelint-config-recommended-scss@5.0.2:
    peerDependencies:
      postcss: "*"
  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
