compressionLevel: 0

enableGlobalCache: true

logFilters:
  - level: discard
    pattern: "fsevents@*/* The * architecture is incompatible with this module, link skipped."
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react (pc86c0) with version 17.0.2, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react-dom (p9837d) with version 17.0.2, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react (p44ec6) with version 17.0.2, which doesn't satisfy what react-live and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react-dom (p2ead7) with version 17.0.2, which doesn't satisfy what react-live and some of its descendants request"
  - level: discard
    pattern: "wp-calypso@workspace:. provides react (*) with version 17.0.2, which doesn't satisfy what @types/wordpress__block-editor and some of its descendants request"
  - level: discard
    pattern: "wp-calypso@workspace:. provides react-dom (*) with version 17.0.2, which doesn't satisfy what @types/wordpress__block-editor and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react (*) with version 17.0.2, which doesn't satisfy what @automattic/design-preview and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react-dom (*) with version 17.0.2, which doesn't satisfy what @automattic/design-preview and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/o2-blocks@workspace:apps/o2-blocks provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/o2-blocks@workspace:apps/o2-blocks provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-block-editor@workspace:apps/wpcom-block-editor provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-block-editor@workspace:apps/wpcom-block-editor provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "wp-calypso@workspace:. provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/launch@workspace:packages/launch *provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/o2-blocks@workspace:apps/o2-blocks provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/search@workspace:packages/search *provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "happy-blocks@workspace:apps/happy-blocks provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "happy-blocks@workspace:apps/happy-blocks provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "happy-blocks@workspace:apps/happy-blocks provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "happy-blocks@workspace:apps/happy-blocks provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-block-editor@workspace:apps/wpcom-block-editor provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/tour-kit@workspace:packages/tour-kit *provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "wp-calypso@workspace:. provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/domain-picker@workspace:packages/domain-picker *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/launch@workspace:packages/launch *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/o2-blocks@workspace:apps/o2-blocks provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/onboarding@workspace:packages/onboarding *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/page-pattern-modal@workspace:packages/page-pattern-modal *provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/page-pattern-modal@workspace:packages/page-pattern-modal *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/page-pattern-modal@workspace:packages/page-pattern-modal *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/search@workspace:packages/search *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/social-previews@workspace:packages/social-previews *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-block-editor@workspace:apps/wpcom-block-editor provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/tour-kit@workspace:packages/tour-kit *provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react (pf0c51) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
  - level: discard
    pattern: "wp-calypso@workspace:. provides react (p08767) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react-dom (p69c5d) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
  - level: discard
    pattern: "wp-calypso@workspace:. provides react-dom (pff688) with version 17.0.2, which doesn't satisfy what @automattic/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides eslint (pcb2ba) with version 8.6.0, which doesn't satisfy what @wordpress/eslint-plugin and some of its descendants request"
  - level: discard
    pattern: "wp-calypso@workspace:. provides eslint (p3918c) with version 8.6.0, which doesn't satisfy what @wordpress/eslint-plugin and some of its descendants request"
  - level: discard
    pattern: "@react-spring/core@npm:9.3.0 * lists build scripts, but its build has been explicitly disabled through configuration."
  - level: discard
    pattern: "@automattic/global-styles@workspace:packages/global-styles provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/global-styles@workspace:packages/global-styles provides react (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"
  - level: discard
    pattern: "@automattic/global-styles@workspace:packages/global-styles provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/block-editor and some of its descendants request"
  - level: discard
    pattern: "@automattic/global-styles@workspace:packages/global-styles provides react-dom (*) with version 17.0.2, which doesn't satisfy what @wordpress/components and some of its descendants request"

nodeLinker: node-modules

packageExtensions:
  "@automattic/newspack-blocks@*":
    peerDependencies:
      moment: "*"
      react: "*"
      react-dom: "*"
  "@signal-noise/stylelint-scales@2.0.3":
    peerDependencies:
      postcss: "*"
  "@types/wordpress__block-editor@6.0.5":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@types/wordpress__blocks@6.4.12":
    peerDependencies:
      react: "*"
  "@types/wordpress__components@14.0.10":
    peerDependencies:
      react: "*"
  "@types/wordpress__editor@10.0.1":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@types/wordpress__media-utils@0.2.4":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@types/wordpress__plugins@3.0.0":
    peerDependencies:
      react: "*"
  "@wordpress/data-controls@2.26.1":
    peerDependencies:
      react: "*"
  "@wordpress/notices@3.26.1":
    peerDependencies:
      react: "*"
  "@wordpress/stylelint-config@21.9.1":
    peerDependencies:
      postcss: "*"
  fake-indexeddb@3.1.7:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  file-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  newspack-components@2.1.0:
    peerDependencies:
      moment: "*"
      react: "*"
      react-dom: "*"
  react-with-styles@3.2.3:
    peerDependencies:
      react-dom: "*"
  reakit-warning@0.6.2:
    peerDependencies:
      react-dom: "*"
  realistic-structured-clone@2.0.2:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  stylelint-config-recommended-scss@5.0.2:
    peerDependencies:
      postcss: "*"
  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
