export default {
	ID: 95327318,
	URL: 'https://restapiusertests.wordpress.com',
	canUpdateFiles: true,
	capabilities: {},
	description: 'Just another WordPress site',
	domain: 'restapiusertests.wordpress.com',
	hasJetpackProtect: true,
	icon: {},
	is_following: false,
	is_private: false,
	jetpack: true,
	lang: 'en',
	logo: {},
	meta: {},
	name: 'Site 1',
	options: {},
	plan: 1,
	plugins: [],
	post_count: 13,
	single_user_site: true,
	slug: 'restapiusertests.wordpress.com',
	subscribers_count: 0,
	title: 'Site 1',
	update: {},
	jp_version: '3.6',
	user_can_manage: true,
	visible: true,
	wpcom_url: 'restapiusertests.wordpress.com',
};
