export const itemsSchema = {
	type: 'array',
	items: {
		type: 'object',
		required: [ 'product_id' ],
		properties: {
			android_sku: { type: 'string' },
			apple_sku: { type: 'string' },
			available: { type: 'string' },
			bill_period: { type: 'number' },
			bill_period_label: { type: 'string' },
			bundle_product_ids: { type: 'array' },
			cost: { type: 'number' },
			capability: { type: 'string' },
			description: { type: 'string' },
			feature_1: { type: 'string' },
			feature_2: { type: 'string' },
			feature_3: { type: 'string' },
			feature_4: { type: 'string' },
			feature_5: { type: 'string' },
			features_highlight: { type: [ 'null', 'array' ] },
			formatted_price: { type: 'string' },
			formatted_original_price: { type: 'string' },
			height: { type: 'number' },
			icon: { type: 'string' },
			icon_active: { type: 'string' },
			multi: { type: 'number' },
			original: { type: 'number' },
			price: { type: 'string' },
			prices: { type: 'object' },
			product_id: { type: 'number' },
			product_name: { type: 'string' },
			product_name_en: { type: 'string' },
			product_name_short: { type: 'string' },
			product_slug: { type: 'string' },
			product_type: { type: 'string' },
			raw_price: { type: 'number' },
			saving: { type: 'number' },
			shortdesc: { type: 'string' },
			store: { type: [ 'number', 'null' ] },
			support_document: { type: 'string' },
			tagline: { type: 'string' },
			width: { type: 'number' }
		}
	}
};
