/**
 * Please keep this list alphabetized!
 */
export const READER_CONVERSATION_FOLLOW = 'READER_CONVERSATION_FOLLOW';
export const READER_CONVERSATION_MUTE = 'READER_CONVERSATION_MUTE';
export const READER_CONVERSATION_UPDATE_FOLLOW_STATUS = 'READER_CONVERSATION_UPDATE_FOLLOW_STATUS';
export const READER_EXPAND_COMMENTS = 'READER_EXPAND_COMMENTS';
export const READER_FOLLOW = 'READER_FOLLOW';
export const READER_FOLLOW_COMPLETE = 'READER_FOLLOW_COMPLETE';
export const READER_FOLLOW_ERROR = 'READER_FOLLOW_ERROR';
export const READER_FOLLOWS_MARK_AS_STALE = 'READER_FOLLOWS_MARK_AS_STALE';
export const READER_FOLLOWS_RECEIVE = 'READER_FOLLOWS_RECEIVE';
export const READER_FOLLOWS_SYNC_COMPLETE = 'READER_FOLLOWS_SYNC_COMPLETE';
export const READER_FOLLOWS_SYNC_PAGE = 'READER_FOLLOWS_SYNC_PAGE';
export const READER_FOLLOWS_SYNC_START = 'READER_FOLLOWS_SYNC_START';
export const READER_SAVED_POST_MARK_READ = 'READER_SAVED_POST_MARK_READ';
export const READER_SAVED_POST_MARK_UNREAD = 'READER_SAVED_POST_MARK_UNREAD';
export const READER_SAVED_POST_SAVE = 'READER_SAVED_POST_SAVE';
export const READER_SAVED_POST_UNSAVE = 'READER_SAVED_POST_UNSAVE';
export const READER_SAVED_POSTS_RECEIVE = 'READER_SAVED_POSTS_RECEIVE';
export const READER_SAVED_POSTS_REORDER = 'READER_SAVED_POSTS_REORDER';
export const READER_SAVED_POSTS_REQUEST = 'READER_SAVED_POSTS_REQUEST';
export const READER_SAVED_POSTS_REQUEST_FAILURE = 'READER_SAVED_POSTS_REQUEST_FAILURE';
export const READER_SEEN_MARK_ALL_AS_SEEN_RECEIVE = 'READER_SEEN_MARK_ALL_AS_SEEN_RECEIVE';
export const READER_SEEN_MARK_ALL_AS_SEEN_REQUEST = 'READER_SEEN_MARK_ALL_AS_SEEN_REQUEST';
export const READER_SEEN_MARK_AS_SEEN_BLOG_REQUEST = 'READER_SEEN_MARK_AS_SEEN_BLOG_REQUEST';
export const READER_SEEN_MARK_AS_SEEN_RECEIVE = 'READER_SEEN_MARK_AS_SEEN_RECEIVE';
export const READER_SEEN_MARK_AS_SEEN_REQUEST = 'READER_SEEN_MARK_AS_SEEN_REQUEST';
export const READER_SEEN_MARK_AS_UNSEEN_BLOG_REQUEST = 'READER_SEEN_MARK_AS_UNSEEN_BLOG_REQUEST';
export const READER_SEEN_MARK_AS_UNSEEN_RECEIVE = 'READER_SEEN_MARK_AS_UNSEEN_RECEIVE';
export const READER_SEEN_MARK_AS_UNSEEN_REQUEST = 'READER_SEEN_MARK_AS_UNSEEN_REQUEST';
export const READER_SITE_BLOCK = 'READER_SITE_BLOCK';
export const READER_SITE_BLOCKS_RECEIVE = 'READER_SITE_BLOCKS_RECEIVE';
export const READER_SITE_BLOCKS_REQUEST = 'READER_SITE_BLOCKS_REQUEST';
export const READER_SITE_RECEIVE = 'READER_SITE_RECEIVE';
export const READER_SITE_UNBLOCK = 'READER_SITE_UNBLOCK';
export const READER_SUBSCRIBE_TO_NEW_COMMENT_EMAIL = 'READER_SUBSCRIBE_TO_NEW_COMMENT_EMAIL';
export const READER_SUBSCRIBE_TO_NEW_POST_EMAIL = 'READER_SUBSCRIBE_TO_NEW_POST_EMAIL';
export const READER_SUBSCRIBE_TO_NEW_POST_NOTIFICATIONS =
	'READER_SUBSCRIBE_TO_NEW_POST_NOTIFICATIONS';
export const READER_UNFOLLOW = 'READER_UNFOLLOW';
export const READER_UNSUBSCRIBE_TO_NEW_COMMENT_EMAIL = 'READER_UNSUBSCRIBE_TO_NEW_COMMENT_EMAIL';
export const READER_UNSUBSCRIBE_TO_NEW_POST_EMAIL = 'READER_UNSUBSCRIBE_TO_NEW_POST_EMAIL';
export const READER_UNSUBSCRIBE_TO_NEW_POST_NOTIFICATIONS =
	'READER_UNSUBSCRIBE_TO_NEW_POST_NOTIFICATIONS';
export const READER_UPDATE_NEW_POST_EMAIL_SUBSCRIPTION =
	'READER_UPDATE_NEW_POST_EMAIL_SUBSCRIPTION';
export const READER_VIEWING_FULL_POST_SET = 'READER_VIEWING_FULL_POST_SET';
export const READER_VIEWING_FULL_POST_UNSET = 'READER_VIEWING_FULL_POST_UNSET';
