/**
 * Please keep this list alphabetized!
 */
export const READER_CONVERSATION_FOLLOW = 'READER_CONVERSATION_FOLLOW';
export const READER_CONVERSATION_MUTE = 'READER_CONVERSATION_MUTE';
export const READER_CONVERSATION_UPDATE_FOLLOW_STATUS = 'READER_CONVERSATION_UPDATE_FOLLOW_STATUS';
export const READER_EXPAND_COMMENTS = 'READER_EXPAND_COMMENTS';
export const READER_SAVED_POST_MARK_READ = 'READER_SAVED_POST_MARK_READ';
export const READER_SAVED_POST_MARK_UNREAD = 'READER_SAVED_POST_MARK_UNREAD';
export const READER_SAVED_POST_SAVE = 'READER_SAVED_POST_SAVE';
export const READER_SAVED_POST_UNSAVE = 'READER_SAVED_POST_UNSAVE';
export const READER_SAVED_POSTS_RECEIVE = 'READER_SAVED_POSTS_RECEIVE';
export const READER_SAVED_POSTS_REORDER = 'READER_SAVED_POSTS_REORDER';
export const READER_SAVED_POSTS_REQUEST = 'READER_SAVED_POSTS_REQUEST';
export const READER_SAVED_POSTS_REQUEST_FAILURE = 'READER_SAVED_POSTS_REQUEST_FAILURE';
export const READER_SITE_BLOCK = 'READER_SITE_BLOCK';
export const READER_SITE_BLOCKS_RECEIVE = 'READER_SITE_BLOCKS_RECEIVE';
export const READER_SITE_BLOCKS_REQUEST = 'READER_SITE_BLOCKS_REQUEST';
export const READER_SITE_RECEIVE = 'READER_SITE_RECEIVE';
export const READER_SITE_UNBLOCK = 'READER_SITE_UNBLOCK';
export const READER_VIEWING_FULL_POST_SET = 'READER_VIEWING_FULL_POST_SET';
export const READER_VIEWING_FULL_POST_UNSET = 'READER_VIEWING_FULL_POST_UNSET';
