/* eslint-disable no-restricted-imports */
/* eslint-disable wpcalypso/jsx-classname-namespace */
import { LoadingPlaceholder } from '@automattic/components';
import { HelpCenterSelect, useJetpackSearchAIQuery } from '@automattic/data-stores';
import styled from '@emotion/styled';
import { useSelect } from '@wordpress/data';
import { external, Icon, page } from '@wordpress/icons';
import { useI18n } from '@wordpress/react-i18n';
import { Fragment } from 'react';
import stripTags from 'striptags';
export const SITE_STORE = 'automattic/site' as const;
import './help-center-article-content.scss';
import { HELP_CENTER_STORE } from '../stores';

const GPTResponsePlaceholder = styled( LoadingPlaceholder )< { width?: string } >`
	:not( :last-child ) {
		margin-block-end: 0.5rem;
	}
	width: ${ ( { width = '100%' } ) => width };
`;

const GPTResponseDisclaimer = styled.div`
	color: var( --studio-gray-50 );
	font-size: 11px;
	text-align: right;

	@media ( min-width: 600px ) {
		padding: 5px 0;
	}
`;

const Placeholders = () => (
	<Fragment>
		<GPTResponsePlaceholder width="18%" />
		<GPTResponsePlaceholder width="80%" />
		<GPTResponsePlaceholder width="80%" />
		<GPTResponsePlaceholder width="55%" />
	</Fragment>
);

export function HelpCenterGPT() {
	const { __ } = useI18n();

	// Report loading state up.
	const { message } = useSelect(
		( select ) => ( {
			message: ( select( HELP_CENTER_STORE ) as HelpCenterSelect ).getMessage(),
		} ),
		[]
	);

	const { data } = useJetpackSearchAIQuery( '9619154', message ?? '', 'response' );

	return (
		<div className="help-center-sibyl-articles__container">
			<h3 id="help-center--contextual_help" className="help-center__section-title">
				{ __( 'Quick response', __i18n_text_domain__ ) }
			</h3>
			<div className="help-center-gpt-response">
				{ ! data?.response && <Placeholders /> }
				{ data?.response && (
					<span
						// eslint-disable-next-line react/no-danger
						dangerouslySetInnerHTML={ {
							__html: stripTags( data.response, [
								'a',
								'p',
								'ol',
								'ul',
								'li',
								'br',
								'b',
								'strong',
								'i',
								'em',
							] ),
						} }
					/>
				) }
				<GPTResponseDisclaimer>
					{ __( "Generated by WordPress.com's Support AI", __i18n_text_domain__ ) }
				</GPTResponseDisclaimer>
			</div>
			<h3 id="help-center--contextual_help" className="help-center__section-title">
				{ __( 'Relevant resources', __i18n_text_domain__ ) }
			</h3>
			<ul
				className="help-center-sibyl-articles__list"
				aria-labelledby="help-center--contextual_help"
			>
				{ data?.urls?.map( ( article ) => {
					return (
						<li key={ article.url }>
							<a href={ article.url } target="_blank" rel="noreferrer noopener">
								<Icon icon={ page } />
								<span>{ article.title }</span>
								<Icon icon={ external } size={ 20 } />
							</a>
						</li>
					);
				} ) }
			</ul>
		</div>
	);
}
