window.configData = {
	env_id: 'production',
	i18n_default_locale_slug: 'en',
	zendesk_support_chat_key: 'cec07bc9-4da6-4dd2-afa7-c7e01ae73584',
	client_slug: 'browser',
	twemoji_cdn_url: 'https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/',
	site_filter: [],
	sections: {},
	enable_all_sections: false,
	livechat_support_locales: [ 'en', 'en-gb' ],
	upwork_support_locales: [
		'de',
		'de-at',
		'de-li',
		'de-lu',
		'de-ch',
		'es',
		'es-cl',
		'es-mx',
		'fr',
		'fr-ca',
		'fr-be',
		'fr-ch',
		'it',
		'it-ch',
		'ja',
		'nl',
		'nl-be',
		'nl-nl',
		'pt',
		'pt-pt',
		'pt-br',
		'sv',
		'sv-fi',
		'sv-se',
	],
	jetpack_support_blog: 'jetpackme.wordpress.com',
	wpcom_support_blog: 'en.support.wordpress.com',
	is_running_in_jetpack_site: false,
	gutenboarding_url: '/new',
	features: {
		'help/gpt-response': true,
	},
	signup_url: '/',
	wapuu: false,
	wpcom_signup_id: '39911',
	wpcom_signup_key: 'cOaYKdrkgXz8xY7aysv4fU6wL6sK5J8a6ojReEIAPwggsznj4Cb6mW0nffTxtYT8',
};
window.process = {
	env: {
		NODE_DEBUG: 'dev',
	},
};
