export const WP_JOB_MANAGER_DISPLAY_SETTINGS = 'WP_JOB_MANAGER_DISPLAY_SETTINGS';
export const WP_JOB_MANAGER_ENABLE_SETTINGS = 'WP_JOB_MANAGER_ENABLE_SETTINGS';
export const WP_JOB_MANAGER_FETCH_SETTINGS = 'WP_JOB_MANAGER_FETCH_SETTINGS';
