export const WP_JOB_MANAGER_FETCH_ERROR = 'WP_JOB_MANAGER_FETCH_ERROR';
export const WP_JOB_MANAGER_FETCH_SETTINGS = 'WP_JOB_MANAGER_FETCH_SETTINGS';
export const WP_JOB_MANAGER_UPDATE_SETTINGS = 'WP_JOB_MANAGER_UPDATE_SETTINGS';
