/**
 * List of window events and reason codes sent to the WP Desktop renderer.
 *
 * Reason codes should be prefixed with `REASON_`.
 *
 * Please keep this list alphabetized!
 *
 */

export const NOTIFY_DESKTOP_CANNOT_USE_EDITOR = 'DESKTOP_CANNOT_USE_EDITOR';
export const NOTIFY_DESKTOP_DID_ACTIVATE_JETPACK_MODULE = 'DESKTOP_DID_ACTIVATE_JETPACK_MODULE';
export const NOTIFY_DESKTOP_DID_REQUEST_SITE = 'NOTIFY_DESKTOP_DID_REQUEST_SITE';
export const NOTIFY_DESKTOP_SEND_TO_PRINTER = 'NOTIFY_DESKTOP_SEND_TO_PRINTER';
export const NOTIFY_DESKTOP_NOTIFICATIONS_UNSEEN_COUNT_SET =
	'NOTIFY_DESKTOP_NOTIFICATIONS_UNSEEN_COUNT_SET';
export const NOTIFY_DESKTOP_VIEW_POST_CLICKED = 'NOTIFY_DESKTOP_VIEW_POST_CLICKED';
export const REASON_BLOCK_EDITOR_JETPACK_REQUIRES_SSO = 'REASON_BLOCK_EDITOR_JETPACK_REQUIRES_SSO';
export const REASON_BLOCK_EDITOR_UNKOWN_IFRAME_LOAD_FAILURE =
	'REASON_BLOCK_EDITOR_UNKOWN_IFRAME_LOAD_FAILURE';
