// flow-typed signature: f85bac13d59fee6f20760af7fcda8413
// flow-typed version: <<STUB>>/babel-plugin-transform-react-display-name_v6.8.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-display-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-display-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-display-name/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-display-name/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-display-name/lib/index'>;
}
