// flow-typed signature: 36ec4f65f13fb001ad9269d865d99808
// flow-typed version: <<STUB>>/blob_v0.0.4/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blob/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blob/index' {
  declare module.exports: $Exports<'blob'>;
}
declare module 'blob/index.js' {
  declare module.exports: $Exports<'blob'>;
}
declare module 'blob/test/index.js' {
  declare module.exports: $Exports<'blob/test/index'>;
}
