// flow-typed signature: 2128c9d5660245f1574d217b931577fb
// flow-typed version: <<STUB>>/bounding-client-rect_v1.0.5/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bounding-client-rect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bounding-client-rect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bounding-client-rect/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bounding-client-rect/index' {
  declare module.exports: $Exports<'bounding-client-rect'>;
}
declare module 'bounding-client-rect/index.js' {
  declare module.exports: $Exports<'bounding-client-rect'>;
}
declare module 'bounding-client-rect/test/test.js' {
  declare module.exports: $Exports<'bounding-client-rect/test/test'>;
}
