// flow-typed signature: f6177ed7effd80b6ff0712d860380a2c
// flow-typed version: <<STUB>>/browser-filesaver_v1.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-filesaver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-filesaver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-filesaver/demo/demo' {
  declare module.exports: any;
}

declare module 'browser-filesaver/demo/demo.min' {
  declare module.exports: any;
}

declare module 'browser-filesaver/FileSaver' {
  declare module.exports: any;
}

declare module 'browser-filesaver/FileSaver.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-filesaver/demo/demo.js' {
  declare module.exports: $Exports<'browser-filesaver/demo/demo'>;
}
declare module 'browser-filesaver/demo/demo.min.js' {
  declare module.exports: $Exports<'browser-filesaver/demo/demo.min'>;
}
declare module 'browser-filesaver/FileSaver.js' {
  declare module.exports: $Exports<'browser-filesaver/FileSaver'>;
}
declare module 'browser-filesaver/FileSaver.min.js' {
  declare module.exports: $Exports<'browser-filesaver/FileSaver.min'>;
}
