// flow-typed signature: cf505845c12be65ba8c8e9d81ee56ffe
// flow-typed version: <<STUB>>/click-outside_v2.0.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'click-outside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'click-outside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'click-outside/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'click-outside/build/index.js' {
  declare module.exports: $Exports<'click-outside/build/index'>;
}
declare module 'click-outside/index' {
  declare module.exports: $Exports<'click-outside'>;
}
declare module 'click-outside/index.js' {
  declare module.exports: $Exports<'click-outside'>;
}
