// flow-typed signature: f907a3d2d085da203b2a5266b283ee3f
// flow-typed version: <<STUB>>/emoji-text_v0.2.6/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-text/Gruntfile' {
  declare module.exports: any;
}

declare module 'emoji-text/test/emoji-text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-text/Gruntfile.js' {
  declare module.exports: $Exports<'emoji-text/Gruntfile'>;
}
declare module 'emoji-text/index' {
  declare module.exports: $Exports<'emoji-text'>;
}
declare module 'emoji-text/index.js' {
  declare module.exports: $Exports<'emoji-text'>;
}
declare module 'emoji-text/test/emoji-text.js' {
  declare module.exports: $Exports<'emoji-text/test/emoji-text'>;
}
