// flow-typed signature: 012f16b0f55cb8d018cdad8328d2a176
// flow-typed version: <<STUB>>/esformatter-collapse-objects-a8c_v0.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-collapse-objects-a8c'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-collapse-objects-a8c' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-collapse-objects-a8c/test/compare.spec' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/input-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/input-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/input-linelength' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/output-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/output-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/output-linelength' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/objects/input-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/objects/input-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/objects/input-linelength' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/objects/output-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/objects/output-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects-a8c/test/compare/objects/output-linelength' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-collapse-objects-a8c/index' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c'>;
}
declare module 'esformatter-collapse-objects-a8c/index.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare.spec.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare.spec'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/input-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/arrays/input-depth'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/input-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/arrays/input-keycount'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/input-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/arrays/input-linelength'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/output-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/arrays/output-depth'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/output-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/arrays/output-keycount'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/arrays/output-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/arrays/output-linelength'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/objects/input-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/objects/input-depth'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/objects/input-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/objects/input-keycount'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/objects/input-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/objects/input-linelength'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/objects/output-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/objects/output-depth'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/objects/output-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/objects/output-keycount'>;
}
declare module 'esformatter-collapse-objects-a8c/test/compare/objects/output-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects-a8c/test/compare/objects/output-linelength'>;
}
