// flow-typed signature: cc056eecbb532b1bf76fbef08dc8b6b1
// flow-typed version: <<STUB>>/esformatter-dot-notation_v1.3.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-dot-notation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-dot-notation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'esformatter-dot-notation/index' {
  declare module.exports: $Exports<'esformatter-dot-notation'>;
}
declare module 'esformatter-dot-notation/index.js' {
  declare module.exports: $Exports<'esformatter-dot-notation'>;
}
