// flow-typed signature: 9b3af6262936fe9f111a48ad60b09fa9
// flow-typed version: <<STUB>>/esformatter_v0.7.3/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter/lib/cli' {
  declare module.exports: any;
}

declare module 'esformatter/lib/diff' {
  declare module.exports: any;
}

declare module 'esformatter/lib/esformatter' {
  declare module.exports: any;
}

declare module 'esformatter/lib/format' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ArrayExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ArrayPattern' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ArrowFunctionExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/AssignmentExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/BinaryExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/CallExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/CatchClause' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ClassDeclaration' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ConditionalExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/DoWhileStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ExportAllDeclaration' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ExportDefaultDeclaration' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ExportNamedDeclaration' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ExportSpecifier' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/expressionParentheses' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ForInStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ForStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/FunctionDeclaration' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/FunctionExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/IfStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ImportDeclaration' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ImportSpecifier' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/LogicalExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/MemberExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/MethodDefinition' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ObjectExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ObjectPattern' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/Params' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ReturnStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/SequenceExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/SwitchCase' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/SwitchStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/ThrowStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/TryStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/UnaryExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/UpdateExpression' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/VariableDeclaration' {
  declare module.exports: any;
}

declare module 'esformatter/lib/hooks/WhileStatement' {
  declare module.exports: any;
}

declare module 'esformatter/lib/indent' {
  declare module.exports: any;
}

declare module 'esformatter/lib/limit' {
  declare module.exports: any;
}

declare module 'esformatter/lib/lineBreakAroundNode' {
  declare module.exports: any;
}

declare module 'esformatter/lib/options' {
  declare module.exports: any;
}

declare module 'esformatter/lib/plugins' {
  declare module.exports: any;
}

declare module 'esformatter/lib/transform' {
  declare module.exports: any;
}

declare module 'esformatter/test/api.spec' {
  declare module.exports: any;
}

declare module 'esformatter/test/bin/node_modules/esformatter/lib/cli' {
  declare module.exports: any;
}

declare module 'esformatter/test/bin/node_modules/esformatter/lib/fake' {
  declare module.exports: any;
}

declare module 'esformatter/test/cli.spec' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/align_comments-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/align_comments-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/argumentlist-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/argumentlist-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/array_bug-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/array_bug-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/array_expression-2-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/array_expression-2-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/array_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/array_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/assignment_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/assignment_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/basic_function_indent_2-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/basic_function_indent_2-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/basic_function_indent-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/basic_function_indent-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/binary_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/binary_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/call_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/call_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/comment_group-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/comment_group-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/commented_config-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/commented_config-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/conditional_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/conditional_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/expression_parentheses-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/expression_parentheses-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/for_in_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/for_in_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/for_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/for_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/function-expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/function-expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/if_statement_spacy-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/if_statement_spacy-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/if_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/if_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/iife-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/iife-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/linebreak-before-eof-2-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/linebreak-before-eof-2-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/linebreak-before-eof-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/linebreak-before-eof-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/member_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/member_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/module-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/module-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/multi-indent-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/multi-indent-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/negative_indent-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/negative_indent-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_expression-2-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_expression-2-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_expression-3-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_expression-3-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_pattern-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/object_pattern-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/one-line-var-declaration-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/one-line-var-declaration-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/switch_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/switch_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/top-level-indent-exception-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/top-level-indent-exception-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/try_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/try_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/variable_declaration-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/custom/variable_declaration-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/array_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/array_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/array_pattern-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/array_pattern-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/arrow_function_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/arrow_function_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/assignment_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/assignment_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/binary_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/binary_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/call_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/call_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/class_declaration-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/class_declaration-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/comma_operator-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/comma_operator-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/comments-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/comments-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/conditional_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/conditional_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/do_while_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/do_while_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/empty_file-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/empty_file-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/for_in_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/for_in_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/for_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/for_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/function_declaration-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/function_declaration-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/function_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/function_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/if_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/if_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/iife-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/iife-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/inplace-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/inplace-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/jsx-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/jsx-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/logical_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/logical_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/member_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/member_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/module-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/module-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/new_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/new_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/obj_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/obj_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/object_pattern-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/object_pattern-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/switch_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/switch_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/throw_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/throw_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/try_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/try_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/unary_expression-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/unary_expression-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/var-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/var-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/while_statement-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/default/while_statement-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/error/invalid-1' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/error/invalid-2' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/jquery/spacing-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/jquery/spacing-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/nested/nested-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/nested/nested-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/package/nested/pkg_nested-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/package/nested/pkg_nested-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/package/package-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/package/package-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/package/rc/nested-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/package/rc/nested-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/top-in' {
  declare module.exports: any;
}

declare module 'esformatter/test/compare/rc/top-out' {
  declare module.exports: any;
}

declare module 'esformatter/test/diff.spec' {
  declare module.exports: any;
}

declare module 'esformatter/test/format.spec' {
  declare module.exports: any;
}

declare module 'esformatter/test/helpers' {
  declare module.exports: any;
}

declare module 'esformatter/test/pipe.spec' {
  declare module.exports: any;
}

declare module 'esformatter/test/plugin/index' {
  declare module.exports: any;
}

declare module 'esformatter/test/plugins.spec' {
  declare module.exports: any;
}

declare module 'esformatter/test/runner' {
  declare module.exports: any;
}

declare module 'esformatter/test/transform.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter/lib/cli.js' {
  declare module.exports: $Exports<'esformatter/lib/cli'>;
}
declare module 'esformatter/lib/diff.js' {
  declare module.exports: $Exports<'esformatter/lib/diff'>;
}
declare module 'esformatter/lib/esformatter.js' {
  declare module.exports: $Exports<'esformatter/lib/esformatter'>;
}
declare module 'esformatter/lib/format.js' {
  declare module.exports: $Exports<'esformatter/lib/format'>;
}
declare module 'esformatter/lib/hooks.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks'>;
}
declare module 'esformatter/lib/hooks/ArrayExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ArrayExpression'>;
}
declare module 'esformatter/lib/hooks/ArrayPattern.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ArrayPattern'>;
}
declare module 'esformatter/lib/hooks/ArrowFunctionExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ArrowFunctionExpression'>;
}
declare module 'esformatter/lib/hooks/AssignmentExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/AssignmentExpression'>;
}
declare module 'esformatter/lib/hooks/BinaryExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/BinaryExpression'>;
}
declare module 'esformatter/lib/hooks/CallExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/CallExpression'>;
}
declare module 'esformatter/lib/hooks/CatchClause.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/CatchClause'>;
}
declare module 'esformatter/lib/hooks/ClassDeclaration.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ClassDeclaration'>;
}
declare module 'esformatter/lib/hooks/ConditionalExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ConditionalExpression'>;
}
declare module 'esformatter/lib/hooks/DoWhileStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/DoWhileStatement'>;
}
declare module 'esformatter/lib/hooks/ExportAllDeclaration.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ExportAllDeclaration'>;
}
declare module 'esformatter/lib/hooks/ExportDefaultDeclaration.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ExportDefaultDeclaration'>;
}
declare module 'esformatter/lib/hooks/ExportNamedDeclaration.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ExportNamedDeclaration'>;
}
declare module 'esformatter/lib/hooks/ExportSpecifier.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ExportSpecifier'>;
}
declare module 'esformatter/lib/hooks/expressionParentheses.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/expressionParentheses'>;
}
declare module 'esformatter/lib/hooks/ForInStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ForInStatement'>;
}
declare module 'esformatter/lib/hooks/ForStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ForStatement'>;
}
declare module 'esformatter/lib/hooks/FunctionDeclaration.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/FunctionDeclaration'>;
}
declare module 'esformatter/lib/hooks/FunctionExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/FunctionExpression'>;
}
declare module 'esformatter/lib/hooks/IfStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/IfStatement'>;
}
declare module 'esformatter/lib/hooks/ImportDeclaration.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ImportDeclaration'>;
}
declare module 'esformatter/lib/hooks/ImportSpecifier.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ImportSpecifier'>;
}
declare module 'esformatter/lib/hooks/LogicalExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/LogicalExpression'>;
}
declare module 'esformatter/lib/hooks/MemberExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/MemberExpression'>;
}
declare module 'esformatter/lib/hooks/MethodDefinition.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/MethodDefinition'>;
}
declare module 'esformatter/lib/hooks/ObjectExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ObjectExpression'>;
}
declare module 'esformatter/lib/hooks/ObjectPattern.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ObjectPattern'>;
}
declare module 'esformatter/lib/hooks/Params.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/Params'>;
}
declare module 'esformatter/lib/hooks/ReturnStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ReturnStatement'>;
}
declare module 'esformatter/lib/hooks/SequenceExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/SequenceExpression'>;
}
declare module 'esformatter/lib/hooks/SwitchCase.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/SwitchCase'>;
}
declare module 'esformatter/lib/hooks/SwitchStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/SwitchStatement'>;
}
declare module 'esformatter/lib/hooks/ThrowStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/ThrowStatement'>;
}
declare module 'esformatter/lib/hooks/TryStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/TryStatement'>;
}
declare module 'esformatter/lib/hooks/UnaryExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/UnaryExpression'>;
}
declare module 'esformatter/lib/hooks/UpdateExpression.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/UpdateExpression'>;
}
declare module 'esformatter/lib/hooks/VariableDeclaration.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/VariableDeclaration'>;
}
declare module 'esformatter/lib/hooks/WhileStatement.js' {
  declare module.exports: $Exports<'esformatter/lib/hooks/WhileStatement'>;
}
declare module 'esformatter/lib/indent.js' {
  declare module.exports: $Exports<'esformatter/lib/indent'>;
}
declare module 'esformatter/lib/limit.js' {
  declare module.exports: $Exports<'esformatter/lib/limit'>;
}
declare module 'esformatter/lib/lineBreakAroundNode.js' {
  declare module.exports: $Exports<'esformatter/lib/lineBreakAroundNode'>;
}
declare module 'esformatter/lib/options.js' {
  declare module.exports: $Exports<'esformatter/lib/options'>;
}
declare module 'esformatter/lib/plugins.js' {
  declare module.exports: $Exports<'esformatter/lib/plugins'>;
}
declare module 'esformatter/lib/transform.js' {
  declare module.exports: $Exports<'esformatter/lib/transform'>;
}
declare module 'esformatter/test/api.spec.js' {
  declare module.exports: $Exports<'esformatter/test/api.spec'>;
}
declare module 'esformatter/test/bin/node_modules/esformatter/lib/cli.js' {
  declare module.exports: $Exports<'esformatter/test/bin/node_modules/esformatter/lib/cli'>;
}
declare module 'esformatter/test/bin/node_modules/esformatter/lib/fake.js' {
  declare module.exports: $Exports<'esformatter/test/bin/node_modules/esformatter/lib/fake'>;
}
declare module 'esformatter/test/cli.spec.js' {
  declare module.exports: $Exports<'esformatter/test/cli.spec'>;
}
declare module 'esformatter/test/compare/custom/align_comments-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/align_comments-in'>;
}
declare module 'esformatter/test/compare/custom/align_comments-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/align_comments-out'>;
}
declare module 'esformatter/test/compare/custom/argumentlist-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/argumentlist-in'>;
}
declare module 'esformatter/test/compare/custom/argumentlist-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/argumentlist-out'>;
}
declare module 'esformatter/test/compare/custom/array_bug-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/array_bug-in'>;
}
declare module 'esformatter/test/compare/custom/array_bug-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/array_bug-out'>;
}
declare module 'esformatter/test/compare/custom/array_expression-2-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/array_expression-2-in'>;
}
declare module 'esformatter/test/compare/custom/array_expression-2-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/array_expression-2-out'>;
}
declare module 'esformatter/test/compare/custom/array_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/array_expression-in'>;
}
declare module 'esformatter/test/compare/custom/array_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/array_expression-out'>;
}
declare module 'esformatter/test/compare/custom/assignment_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/assignment_expression-in'>;
}
declare module 'esformatter/test/compare/custom/assignment_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/assignment_expression-out'>;
}
declare module 'esformatter/test/compare/custom/basic_function_indent_2-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/basic_function_indent_2-in'>;
}
declare module 'esformatter/test/compare/custom/basic_function_indent_2-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/basic_function_indent_2-out'>;
}
declare module 'esformatter/test/compare/custom/basic_function_indent-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/basic_function_indent-in'>;
}
declare module 'esformatter/test/compare/custom/basic_function_indent-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/basic_function_indent-out'>;
}
declare module 'esformatter/test/compare/custom/binary_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/binary_expression-in'>;
}
declare module 'esformatter/test/compare/custom/binary_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/binary_expression-out'>;
}
declare module 'esformatter/test/compare/custom/call_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/call_expression-in'>;
}
declare module 'esformatter/test/compare/custom/call_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/call_expression-out'>;
}
declare module 'esformatter/test/compare/custom/comment_group-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/comment_group-in'>;
}
declare module 'esformatter/test/compare/custom/comment_group-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/comment_group-out'>;
}
declare module 'esformatter/test/compare/custom/commented_config-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/commented_config-in'>;
}
declare module 'esformatter/test/compare/custom/commented_config-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/commented_config-out'>;
}
declare module 'esformatter/test/compare/custom/conditional_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/conditional_expression-in'>;
}
declare module 'esformatter/test/compare/custom/conditional_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/conditional_expression-out'>;
}
declare module 'esformatter/test/compare/custom/expression_parentheses-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/expression_parentheses-in'>;
}
declare module 'esformatter/test/compare/custom/expression_parentheses-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/expression_parentheses-out'>;
}
declare module 'esformatter/test/compare/custom/for_in_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/for_in_statement-in'>;
}
declare module 'esformatter/test/compare/custom/for_in_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/for_in_statement-out'>;
}
declare module 'esformatter/test/compare/custom/for_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/for_statement-in'>;
}
declare module 'esformatter/test/compare/custom/for_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/for_statement-out'>;
}
declare module 'esformatter/test/compare/custom/function-expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/function-expression-in'>;
}
declare module 'esformatter/test/compare/custom/function-expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/function-expression-out'>;
}
declare module 'esformatter/test/compare/custom/if_statement_spacy-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/if_statement_spacy-in'>;
}
declare module 'esformatter/test/compare/custom/if_statement_spacy-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/if_statement_spacy-out'>;
}
declare module 'esformatter/test/compare/custom/if_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/if_statement-in'>;
}
declare module 'esformatter/test/compare/custom/if_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/if_statement-out'>;
}
declare module 'esformatter/test/compare/custom/iife-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/iife-in'>;
}
declare module 'esformatter/test/compare/custom/iife-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/iife-out'>;
}
declare module 'esformatter/test/compare/custom/linebreak-before-eof-2-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/linebreak-before-eof-2-in'>;
}
declare module 'esformatter/test/compare/custom/linebreak-before-eof-2-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/linebreak-before-eof-2-out'>;
}
declare module 'esformatter/test/compare/custom/linebreak-before-eof-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/linebreak-before-eof-in'>;
}
declare module 'esformatter/test/compare/custom/linebreak-before-eof-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/linebreak-before-eof-out'>;
}
declare module 'esformatter/test/compare/custom/member_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/member_expression-in'>;
}
declare module 'esformatter/test/compare/custom/member_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/member_expression-out'>;
}
declare module 'esformatter/test/compare/custom/module-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/module-in'>;
}
declare module 'esformatter/test/compare/custom/module-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/module-out'>;
}
declare module 'esformatter/test/compare/custom/multi-indent-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/multi-indent-in'>;
}
declare module 'esformatter/test/compare/custom/multi-indent-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/multi-indent-out'>;
}
declare module 'esformatter/test/compare/custom/negative_indent-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/negative_indent-in'>;
}
declare module 'esformatter/test/compare/custom/negative_indent-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/negative_indent-out'>;
}
declare module 'esformatter/test/compare/custom/object_expression-2-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_expression-2-in'>;
}
declare module 'esformatter/test/compare/custom/object_expression-2-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_expression-2-out'>;
}
declare module 'esformatter/test/compare/custom/object_expression-3-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_expression-3-in'>;
}
declare module 'esformatter/test/compare/custom/object_expression-3-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_expression-3-out'>;
}
declare module 'esformatter/test/compare/custom/object_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_expression-in'>;
}
declare module 'esformatter/test/compare/custom/object_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_expression-out'>;
}
declare module 'esformatter/test/compare/custom/object_pattern-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_pattern-in'>;
}
declare module 'esformatter/test/compare/custom/object_pattern-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/object_pattern-out'>;
}
declare module 'esformatter/test/compare/custom/one-line-var-declaration-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/one-line-var-declaration-in'>;
}
declare module 'esformatter/test/compare/custom/one-line-var-declaration-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/one-line-var-declaration-out'>;
}
declare module 'esformatter/test/compare/custom/switch_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/switch_statement-in'>;
}
declare module 'esformatter/test/compare/custom/switch_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/switch_statement-out'>;
}
declare module 'esformatter/test/compare/custom/top-level-indent-exception-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/top-level-indent-exception-in'>;
}
declare module 'esformatter/test/compare/custom/top-level-indent-exception-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/top-level-indent-exception-out'>;
}
declare module 'esformatter/test/compare/custom/try_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/try_statement-in'>;
}
declare module 'esformatter/test/compare/custom/try_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/try_statement-out'>;
}
declare module 'esformatter/test/compare/custom/variable_declaration-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/variable_declaration-in'>;
}
declare module 'esformatter/test/compare/custom/variable_declaration-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/custom/variable_declaration-out'>;
}
declare module 'esformatter/test/compare/default/array_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/array_expression-in'>;
}
declare module 'esformatter/test/compare/default/array_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/array_expression-out'>;
}
declare module 'esformatter/test/compare/default/array_pattern-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/array_pattern-in'>;
}
declare module 'esformatter/test/compare/default/array_pattern-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/array_pattern-out'>;
}
declare module 'esformatter/test/compare/default/arrow_function_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/arrow_function_expression-in'>;
}
declare module 'esformatter/test/compare/default/arrow_function_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/arrow_function_expression-out'>;
}
declare module 'esformatter/test/compare/default/assignment_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/assignment_expression-in'>;
}
declare module 'esformatter/test/compare/default/assignment_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/assignment_expression-out'>;
}
declare module 'esformatter/test/compare/default/binary_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/binary_expression-in'>;
}
declare module 'esformatter/test/compare/default/binary_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/binary_expression-out'>;
}
declare module 'esformatter/test/compare/default/call_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/call_expression-in'>;
}
declare module 'esformatter/test/compare/default/call_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/call_expression-out'>;
}
declare module 'esformatter/test/compare/default/class_declaration-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/class_declaration-in'>;
}
declare module 'esformatter/test/compare/default/class_declaration-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/class_declaration-out'>;
}
declare module 'esformatter/test/compare/default/comma_operator-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/comma_operator-in'>;
}
declare module 'esformatter/test/compare/default/comma_operator-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/comma_operator-out'>;
}
declare module 'esformatter/test/compare/default/comments-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/comments-in'>;
}
declare module 'esformatter/test/compare/default/comments-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/comments-out'>;
}
declare module 'esformatter/test/compare/default/conditional_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/conditional_expression-in'>;
}
declare module 'esformatter/test/compare/default/conditional_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/conditional_expression-out'>;
}
declare module 'esformatter/test/compare/default/do_while_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/do_while_statement-in'>;
}
declare module 'esformatter/test/compare/default/do_while_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/do_while_statement-out'>;
}
declare module 'esformatter/test/compare/default/empty_file-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/empty_file-in'>;
}
declare module 'esformatter/test/compare/default/empty_file-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/empty_file-out'>;
}
declare module 'esformatter/test/compare/default/for_in_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/for_in_statement-in'>;
}
declare module 'esformatter/test/compare/default/for_in_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/for_in_statement-out'>;
}
declare module 'esformatter/test/compare/default/for_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/for_statement-in'>;
}
declare module 'esformatter/test/compare/default/for_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/for_statement-out'>;
}
declare module 'esformatter/test/compare/default/function_declaration-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/function_declaration-in'>;
}
declare module 'esformatter/test/compare/default/function_declaration-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/function_declaration-out'>;
}
declare module 'esformatter/test/compare/default/function_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/function_expression-in'>;
}
declare module 'esformatter/test/compare/default/function_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/function_expression-out'>;
}
declare module 'esformatter/test/compare/default/if_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/if_statement-in'>;
}
declare module 'esformatter/test/compare/default/if_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/if_statement-out'>;
}
declare module 'esformatter/test/compare/default/iife-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/iife-in'>;
}
declare module 'esformatter/test/compare/default/iife-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/iife-out'>;
}
declare module 'esformatter/test/compare/default/inplace-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/inplace-in'>;
}
declare module 'esformatter/test/compare/default/inplace-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/inplace-out'>;
}
declare module 'esformatter/test/compare/default/jsx-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/jsx-in'>;
}
declare module 'esformatter/test/compare/default/jsx-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/jsx-out'>;
}
declare module 'esformatter/test/compare/default/logical_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/logical_expression-in'>;
}
declare module 'esformatter/test/compare/default/logical_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/logical_expression-out'>;
}
declare module 'esformatter/test/compare/default/member_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/member_expression-in'>;
}
declare module 'esformatter/test/compare/default/member_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/member_expression-out'>;
}
declare module 'esformatter/test/compare/default/module-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/module-in'>;
}
declare module 'esformatter/test/compare/default/module-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/module-out'>;
}
declare module 'esformatter/test/compare/default/new_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/new_expression-in'>;
}
declare module 'esformatter/test/compare/default/new_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/new_expression-out'>;
}
declare module 'esformatter/test/compare/default/obj_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/obj_expression-in'>;
}
declare module 'esformatter/test/compare/default/obj_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/obj_expression-out'>;
}
declare module 'esformatter/test/compare/default/object_pattern-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/object_pattern-in'>;
}
declare module 'esformatter/test/compare/default/object_pattern-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/object_pattern-out'>;
}
declare module 'esformatter/test/compare/default/switch_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/switch_statement-in'>;
}
declare module 'esformatter/test/compare/default/switch_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/switch_statement-out'>;
}
declare module 'esformatter/test/compare/default/throw_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/throw_statement-in'>;
}
declare module 'esformatter/test/compare/default/throw_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/throw_statement-out'>;
}
declare module 'esformatter/test/compare/default/try_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/try_statement-in'>;
}
declare module 'esformatter/test/compare/default/try_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/try_statement-out'>;
}
declare module 'esformatter/test/compare/default/unary_expression-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/unary_expression-in'>;
}
declare module 'esformatter/test/compare/default/unary_expression-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/unary_expression-out'>;
}
declare module 'esformatter/test/compare/default/var-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/var-in'>;
}
declare module 'esformatter/test/compare/default/var-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/var-out'>;
}
declare module 'esformatter/test/compare/default/while_statement-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/while_statement-in'>;
}
declare module 'esformatter/test/compare/default/while_statement-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/default/while_statement-out'>;
}
declare module 'esformatter/test/compare/error/invalid-1.js' {
  declare module.exports: $Exports<'esformatter/test/compare/error/invalid-1'>;
}
declare module 'esformatter/test/compare/error/invalid-2.js' {
  declare module.exports: $Exports<'esformatter/test/compare/error/invalid-2'>;
}
declare module 'esformatter/test/compare/jquery/spacing-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/jquery/spacing-in'>;
}
declare module 'esformatter/test/compare/jquery/spacing-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/jquery/spacing-out'>;
}
declare module 'esformatter/test/compare/rc/nested/nested-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/nested/nested-in'>;
}
declare module 'esformatter/test/compare/rc/nested/nested-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/nested/nested-out'>;
}
declare module 'esformatter/test/compare/rc/package/nested/pkg_nested-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/package/nested/pkg_nested-in'>;
}
declare module 'esformatter/test/compare/rc/package/nested/pkg_nested-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/package/nested/pkg_nested-out'>;
}
declare module 'esformatter/test/compare/rc/package/package-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/package/package-in'>;
}
declare module 'esformatter/test/compare/rc/package/package-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/package/package-out'>;
}
declare module 'esformatter/test/compare/rc/package/rc/nested-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/package/rc/nested-in'>;
}
declare module 'esformatter/test/compare/rc/package/rc/nested-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/package/rc/nested-out'>;
}
declare module 'esformatter/test/compare/rc/top-in.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/top-in'>;
}
declare module 'esformatter/test/compare/rc/top-out.js' {
  declare module.exports: $Exports<'esformatter/test/compare/rc/top-out'>;
}
declare module 'esformatter/test/diff.spec.js' {
  declare module.exports: $Exports<'esformatter/test/diff.spec'>;
}
declare module 'esformatter/test/format.spec.js' {
  declare module.exports: $Exports<'esformatter/test/format.spec'>;
}
declare module 'esformatter/test/helpers.js' {
  declare module.exports: $Exports<'esformatter/test/helpers'>;
}
declare module 'esformatter/test/pipe.spec.js' {
  declare module.exports: $Exports<'esformatter/test/pipe.spec'>;
}
declare module 'esformatter/test/plugin/index.js' {
  declare module.exports: $Exports<'esformatter/test/plugin/index'>;
}
declare module 'esformatter/test/plugins.spec.js' {
  declare module.exports: $Exports<'esformatter/test/plugins.spec'>;
}
declare module 'esformatter/test/runner.js' {
  declare module.exports: $Exports<'esformatter/test/runner'>;
}
declare module 'esformatter/test/transform.spec.js' {
  declare module.exports: $Exports<'esformatter/test/transform.spec'>;
}
