// flow-typed signature: 77aceccbe754a20e44266a6c5def0ca6
// flow-typed version: <<STUB>>/esformatter-semicolons_v1.1.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-semicolons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-semicolons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-semicolons/test/compare-test' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/break-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/continue-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/empty-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/expression-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/module-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/return-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/simple-object-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/input/variable-declaration' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/break-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/continue-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/empty-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/expression-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/module-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/return-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/simple-object-statement' {
  declare module.exports: any;
}

declare module 'esformatter-semicolons/test/fixtures/output/variable-declaration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-semicolons/index' {
  declare module.exports: $Exports<'esformatter-semicolons'>;
}
declare module 'esformatter-semicolons/index.js' {
  declare module.exports: $Exports<'esformatter-semicolons'>;
}
declare module 'esformatter-semicolons/test/compare-test.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/compare-test'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/break-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/break-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/continue-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/continue-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/empty-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/empty-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/expression-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/expression-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/module-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/module-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/return-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/return-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/simple-object-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/simple-object-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/input/variable-declaration.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/input/variable-declaration'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/break-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/break-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/continue-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/continue-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/empty-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/empty-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/expression-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/expression-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/module-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/module-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/return-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/return-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/simple-object-statement.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/simple-object-statement'>;
}
declare module 'esformatter-semicolons/test/fixtures/output/variable-declaration.js' {
  declare module.exports: $Exports<'esformatter-semicolons/test/fixtures/output/variable-declaration'>;
}
