// flow-typed signature: 7f4378cec9a701ccae743efa7ae16461
// flow-typed version: <<STUB>>/filesize_v3.2.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'filesize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'filesize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'filesize/lib/filesize.es6' {
  declare module.exports: any;
}

declare module 'filesize/lib/filesize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'filesize/lib/filesize.es6.js' {
  declare module.exports: $Exports<'filesize/lib/filesize.es6'>;
}
declare module 'filesize/lib/filesize.js' {
  declare module.exports: $Exports<'filesize/lib/filesize'>;
}
