// flow-typed signature: b72e60f7ea5311ad6be67af3b3d6f5c3
// flow-typed version: <<STUB>>/get-video-id_v2.1.4/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-video-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-video-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'get-video-id/index' {
  declare module.exports: $Exports<'get-video-id'>;
}
declare module 'get-video-id/index.js' {
  declare module.exports: $Exports<'get-video-id'>;
}
