// flow-typed signature: 2230cbcc5e83b3b3dd35091bf754063f
// flow-typed version: <<STUB>>/he_v0.5.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'he'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'he' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'he/he' {
  declare module.exports: any;
}

// Filename aliases
declare module 'he/he.js' {
  declare module.exports: $Exports<'he/he'>;
}
