// flow-typed signature: 4e7fc4958999f0c7df4fb28639ff952f
// flow-typed version: <<STUB>>/is-my-json-valid_v2.13.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-my-json-valid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-my-json-valid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-my-json-valid/example' {
  declare module.exports: any;
}

declare module 'is-my-json-valid/formats' {
  declare module.exports: any;
}

declare module 'is-my-json-valid/require' {
  declare module.exports: any;
}

declare module 'is-my-json-valid/test/fixtures/cosmic' {
  declare module.exports: any;
}

declare module 'is-my-json-valid/test/json-schema' {
  declare module.exports: any;
}

declare module 'is-my-json-valid/test/misc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-my-json-valid/example.js' {
  declare module.exports: $Exports<'is-my-json-valid/example'>;
}
declare module 'is-my-json-valid/formats.js' {
  declare module.exports: $Exports<'is-my-json-valid/formats'>;
}
declare module 'is-my-json-valid/index' {
  declare module.exports: $Exports<'is-my-json-valid'>;
}
declare module 'is-my-json-valid/index.js' {
  declare module.exports: $Exports<'is-my-json-valid'>;
}
declare module 'is-my-json-valid/require.js' {
  declare module.exports: $Exports<'is-my-json-valid/require'>;
}
declare module 'is-my-json-valid/test/fixtures/cosmic.js' {
  declare module.exports: $Exports<'is-my-json-valid/test/fixtures/cosmic'>;
}
declare module 'is-my-json-valid/test/json-schema.js' {
  declare module.exports: $Exports<'is-my-json-valid/test/json-schema'>;
}
declare module 'is-my-json-valid/test/misc.js' {
  declare module.exports: $Exports<'is-my-json-valid/test/misc'>;
}
