// flow-typed signature: efa97acb340079094a0b8c9508022787
// flow-typed version: <<STUB>>/jade_vpugjs/jade#29784fd/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jade/bin/jade' {
  declare module.exports: any;
}

declare module 'jade/development' {
  declare module.exports: any;
}

declare module 'jade/lib/index' {
  declare module.exports: any;
}

declare module 'jade/register' {
  declare module.exports: any;
}

declare module 'jade/release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jade/bin/jade.js' {
  declare module.exports: $Exports<'jade/bin/jade'>;
}
declare module 'jade/development.js' {
  declare module.exports: $Exports<'jade/development'>;
}
declare module 'jade/lib/index.js' {
  declare module.exports: $Exports<'jade/lib/index'>;
}
declare module 'jade/register.js' {
  declare module.exports: $Exports<'jade/register'>;
}
declare module 'jade/release.js' {
  declare module.exports: $Exports<'jade/release'>;
}
