// flow-typed signature: 1144975aa88702c735b4bd4e1811c46c
// flow-typed version: <<STUB>>/jquery_v1.11.3/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery/dist/jquery' {
  declare module.exports: any;
}

declare module 'jquery/dist/jquery.min' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/jsonp' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/load' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/parseJSON' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/parseXML' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/script' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/var/nonce' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/var/rquery' {
  declare module.exports: any;
}

declare module 'jquery/src/ajax/xhr' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/attr' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/classes' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/prop' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/support' {
  declare module.exports: any;
}

declare module 'jquery/src/attributes/val' {
  declare module.exports: any;
}

declare module 'jquery/src/callbacks' {
  declare module.exports: any;
}

declare module 'jquery/src/core' {
  declare module.exports: any;
}

declare module 'jquery/src/core/access' {
  declare module.exports: any;
}

declare module 'jquery/src/core/init' {
  declare module.exports: any;
}

declare module 'jquery/src/core/parseHTML' {
  declare module.exports: any;
}

declare module 'jquery/src/core/ready' {
  declare module.exports: any;
}

declare module 'jquery/src/core/var/rsingleTag' {
  declare module.exports: any;
}

declare module 'jquery/src/css' {
  declare module.exports: any;
}

declare module 'jquery/src/css/addGetHookIf' {
  declare module.exports: any;
}

declare module 'jquery/src/css/curCSS' {
  declare module.exports: any;
}

declare module 'jquery/src/css/defaultDisplay' {
  declare module.exports: any;
}

declare module 'jquery/src/css/hiddenVisibleSelectors' {
  declare module.exports: any;
}

declare module 'jquery/src/css/support' {
  declare module.exports: any;
}

declare module 'jquery/src/css/swap' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/cssExpand' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/isHidden' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/rmargin' {
  declare module.exports: any;
}

declare module 'jquery/src/css/var/rnumnonpx' {
  declare module.exports: any;
}

declare module 'jquery/src/data' {
  declare module.exports: any;
}

declare module 'jquery/src/data/accepts' {
  declare module.exports: any;
}

declare module 'jquery/src/data/support' {
  declare module.exports: any;
}

declare module 'jquery/src/deferred' {
  declare module.exports: any;
}

declare module 'jquery/src/deprecated' {
  declare module.exports: any;
}

declare module 'jquery/src/dimensions' {
  declare module.exports: any;
}

declare module 'jquery/src/effects' {
  declare module.exports: any;
}

declare module 'jquery/src/effects/animatedSelector' {
  declare module.exports: any;
}

declare module 'jquery/src/effects/support' {
  declare module.exports: any;
}

declare module 'jquery/src/effects/Tween' {
  declare module.exports: any;
}

declare module 'jquery/src/event' {
  declare module.exports: any;
}

declare module 'jquery/src/event/ajax' {
  declare module.exports: any;
}

declare module 'jquery/src/event/alias' {
  declare module.exports: any;
}

declare module 'jquery/src/event/support' {
  declare module.exports: any;
}

declare module 'jquery/src/exports/amd' {
  declare module.exports: any;
}

declare module 'jquery/src/exports/global' {
  declare module.exports: any;
}

declare module 'jquery/src/intro' {
  declare module.exports: any;
}

declare module 'jquery/src/jquery' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/_evalUrl' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/support' {
  declare module.exports: any;
}

declare module 'jquery/src/manipulation/var/rcheckableType' {
  declare module.exports: any;
}

declare module 'jquery/src/offset' {
  declare module.exports: any;
}

declare module 'jquery/src/outro' {
  declare module.exports: any;
}

declare module 'jquery/src/queue' {
  declare module.exports: any;
}

declare module 'jquery/src/queue/delay' {
  declare module.exports: any;
}

declare module 'jquery/src/selector-sizzle' {
  declare module.exports: any;
}

declare module 'jquery/src/selector' {
  declare module.exports: any;
}

declare module 'jquery/src/serialize' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/dist/sizzle' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/dist/sizzle.min' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/test/data/empty' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/test/data/testinit' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/test/jquery' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/test/unit/extending' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/test/unit/selector' {
  declare module.exports: any;
}

declare module 'jquery/src/sizzle/test/unit/utilities' {
  declare module.exports: any;
}

declare module 'jquery/src/support' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing/findFilter' {
  declare module.exports: any;
}

declare module 'jquery/src/traversing/var/rneedsContext' {
  declare module.exports: any;
}

declare module 'jquery/src/var/class2type' {
  declare module.exports: any;
}

declare module 'jquery/src/var/concat' {
  declare module.exports: any;
}

declare module 'jquery/src/var/deletedIds' {
  declare module.exports: any;
}

declare module 'jquery/src/var/hasOwn' {
  declare module.exports: any;
}

declare module 'jquery/src/var/indexOf' {
  declare module.exports: any;
}

declare module 'jquery/src/var/pnum' {
  declare module.exports: any;
}

declare module 'jquery/src/var/push' {
  declare module.exports: any;
}

declare module 'jquery/src/var/rnotwhite' {
  declare module.exports: any;
}

declare module 'jquery/src/var/slice' {
  declare module.exports: any;
}

declare module 'jquery/src/var/strundefined' {
  declare module.exports: any;
}

declare module 'jquery/src/var/support' {
  declare module.exports: any;
}

declare module 'jquery/src/var/toString' {
  declare module.exports: any;
}

declare module 'jquery/src/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery/dist/jquery.js' {
  declare module.exports: $Exports<'jquery/dist/jquery'>;
}
declare module 'jquery/dist/jquery.min.js' {
  declare module.exports: $Exports<'jquery/dist/jquery.min'>;
}
declare module 'jquery/src/ajax.js' {
  declare module.exports: $Exports<'jquery/src/ajax'>;
}
declare module 'jquery/src/ajax/jsonp.js' {
  declare module.exports: $Exports<'jquery/src/ajax/jsonp'>;
}
declare module 'jquery/src/ajax/load.js' {
  declare module.exports: $Exports<'jquery/src/ajax/load'>;
}
declare module 'jquery/src/ajax/parseJSON.js' {
  declare module.exports: $Exports<'jquery/src/ajax/parseJSON'>;
}
declare module 'jquery/src/ajax/parseXML.js' {
  declare module.exports: $Exports<'jquery/src/ajax/parseXML'>;
}
declare module 'jquery/src/ajax/script.js' {
  declare module.exports: $Exports<'jquery/src/ajax/script'>;
}
declare module 'jquery/src/ajax/var/nonce.js' {
  declare module.exports: $Exports<'jquery/src/ajax/var/nonce'>;
}
declare module 'jquery/src/ajax/var/rquery.js' {
  declare module.exports: $Exports<'jquery/src/ajax/var/rquery'>;
}
declare module 'jquery/src/ajax/xhr.js' {
  declare module.exports: $Exports<'jquery/src/ajax/xhr'>;
}
declare module 'jquery/src/attributes.js' {
  declare module.exports: $Exports<'jquery/src/attributes'>;
}
declare module 'jquery/src/attributes/attr.js' {
  declare module.exports: $Exports<'jquery/src/attributes/attr'>;
}
declare module 'jquery/src/attributes/classes.js' {
  declare module.exports: $Exports<'jquery/src/attributes/classes'>;
}
declare module 'jquery/src/attributes/prop.js' {
  declare module.exports: $Exports<'jquery/src/attributes/prop'>;
}
declare module 'jquery/src/attributes/support.js' {
  declare module.exports: $Exports<'jquery/src/attributes/support'>;
}
declare module 'jquery/src/attributes/val.js' {
  declare module.exports: $Exports<'jquery/src/attributes/val'>;
}
declare module 'jquery/src/callbacks.js' {
  declare module.exports: $Exports<'jquery/src/callbacks'>;
}
declare module 'jquery/src/core.js' {
  declare module.exports: $Exports<'jquery/src/core'>;
}
declare module 'jquery/src/core/access.js' {
  declare module.exports: $Exports<'jquery/src/core/access'>;
}
declare module 'jquery/src/core/init.js' {
  declare module.exports: $Exports<'jquery/src/core/init'>;
}
declare module 'jquery/src/core/parseHTML.js' {
  declare module.exports: $Exports<'jquery/src/core/parseHTML'>;
}
declare module 'jquery/src/core/ready.js' {
  declare module.exports: $Exports<'jquery/src/core/ready'>;
}
declare module 'jquery/src/core/var/rsingleTag.js' {
  declare module.exports: $Exports<'jquery/src/core/var/rsingleTag'>;
}
declare module 'jquery/src/css.js' {
  declare module.exports: $Exports<'jquery/src/css'>;
}
declare module 'jquery/src/css/addGetHookIf.js' {
  declare module.exports: $Exports<'jquery/src/css/addGetHookIf'>;
}
declare module 'jquery/src/css/curCSS.js' {
  declare module.exports: $Exports<'jquery/src/css/curCSS'>;
}
declare module 'jquery/src/css/defaultDisplay.js' {
  declare module.exports: $Exports<'jquery/src/css/defaultDisplay'>;
}
declare module 'jquery/src/css/hiddenVisibleSelectors.js' {
  declare module.exports: $Exports<'jquery/src/css/hiddenVisibleSelectors'>;
}
declare module 'jquery/src/css/support.js' {
  declare module.exports: $Exports<'jquery/src/css/support'>;
}
declare module 'jquery/src/css/swap.js' {
  declare module.exports: $Exports<'jquery/src/css/swap'>;
}
declare module 'jquery/src/css/var/cssExpand.js' {
  declare module.exports: $Exports<'jquery/src/css/var/cssExpand'>;
}
declare module 'jquery/src/css/var/isHidden.js' {
  declare module.exports: $Exports<'jquery/src/css/var/isHidden'>;
}
declare module 'jquery/src/css/var/rmargin.js' {
  declare module.exports: $Exports<'jquery/src/css/var/rmargin'>;
}
declare module 'jquery/src/css/var/rnumnonpx.js' {
  declare module.exports: $Exports<'jquery/src/css/var/rnumnonpx'>;
}
declare module 'jquery/src/data.js' {
  declare module.exports: $Exports<'jquery/src/data'>;
}
declare module 'jquery/src/data/accepts.js' {
  declare module.exports: $Exports<'jquery/src/data/accepts'>;
}
declare module 'jquery/src/data/support.js' {
  declare module.exports: $Exports<'jquery/src/data/support'>;
}
declare module 'jquery/src/deferred.js' {
  declare module.exports: $Exports<'jquery/src/deferred'>;
}
declare module 'jquery/src/deprecated.js' {
  declare module.exports: $Exports<'jquery/src/deprecated'>;
}
declare module 'jquery/src/dimensions.js' {
  declare module.exports: $Exports<'jquery/src/dimensions'>;
}
declare module 'jquery/src/effects.js' {
  declare module.exports: $Exports<'jquery/src/effects'>;
}
declare module 'jquery/src/effects/animatedSelector.js' {
  declare module.exports: $Exports<'jquery/src/effects/animatedSelector'>;
}
declare module 'jquery/src/effects/support.js' {
  declare module.exports: $Exports<'jquery/src/effects/support'>;
}
declare module 'jquery/src/effects/Tween.js' {
  declare module.exports: $Exports<'jquery/src/effects/Tween'>;
}
declare module 'jquery/src/event.js' {
  declare module.exports: $Exports<'jquery/src/event'>;
}
declare module 'jquery/src/event/ajax.js' {
  declare module.exports: $Exports<'jquery/src/event/ajax'>;
}
declare module 'jquery/src/event/alias.js' {
  declare module.exports: $Exports<'jquery/src/event/alias'>;
}
declare module 'jquery/src/event/support.js' {
  declare module.exports: $Exports<'jquery/src/event/support'>;
}
declare module 'jquery/src/exports/amd.js' {
  declare module.exports: $Exports<'jquery/src/exports/amd'>;
}
declare module 'jquery/src/exports/global.js' {
  declare module.exports: $Exports<'jquery/src/exports/global'>;
}
declare module 'jquery/src/intro.js' {
  declare module.exports: $Exports<'jquery/src/intro'>;
}
declare module 'jquery/src/jquery.js' {
  declare module.exports: $Exports<'jquery/src/jquery'>;
}
declare module 'jquery/src/manipulation.js' {
  declare module.exports: $Exports<'jquery/src/manipulation'>;
}
declare module 'jquery/src/manipulation/_evalUrl.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/_evalUrl'>;
}
declare module 'jquery/src/manipulation/support.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/support'>;
}
declare module 'jquery/src/manipulation/var/rcheckableType.js' {
  declare module.exports: $Exports<'jquery/src/manipulation/var/rcheckableType'>;
}
declare module 'jquery/src/offset.js' {
  declare module.exports: $Exports<'jquery/src/offset'>;
}
declare module 'jquery/src/outro.js' {
  declare module.exports: $Exports<'jquery/src/outro'>;
}
declare module 'jquery/src/queue.js' {
  declare module.exports: $Exports<'jquery/src/queue'>;
}
declare module 'jquery/src/queue/delay.js' {
  declare module.exports: $Exports<'jquery/src/queue/delay'>;
}
declare module 'jquery/src/selector-sizzle.js' {
  declare module.exports: $Exports<'jquery/src/selector-sizzle'>;
}
declare module 'jquery/src/selector.js' {
  declare module.exports: $Exports<'jquery/src/selector'>;
}
declare module 'jquery/src/serialize.js' {
  declare module.exports: $Exports<'jquery/src/serialize'>;
}
declare module 'jquery/src/sizzle/dist/sizzle.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/dist/sizzle'>;
}
declare module 'jquery/src/sizzle/dist/sizzle.min.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/dist/sizzle.min'>;
}
declare module 'jquery/src/sizzle/test/data/empty.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/test/data/empty'>;
}
declare module 'jquery/src/sizzle/test/data/testinit.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/test/data/testinit'>;
}
declare module 'jquery/src/sizzle/test/jquery.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/test/jquery'>;
}
declare module 'jquery/src/sizzle/test/unit/extending.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/test/unit/extending'>;
}
declare module 'jquery/src/sizzle/test/unit/selector.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/test/unit/selector'>;
}
declare module 'jquery/src/sizzle/test/unit/utilities.js' {
  declare module.exports: $Exports<'jquery/src/sizzle/test/unit/utilities'>;
}
declare module 'jquery/src/support.js' {
  declare module.exports: $Exports<'jquery/src/support'>;
}
declare module 'jquery/src/traversing.js' {
  declare module.exports: $Exports<'jquery/src/traversing'>;
}
declare module 'jquery/src/traversing/findFilter.js' {
  declare module.exports: $Exports<'jquery/src/traversing/findFilter'>;
}
declare module 'jquery/src/traversing/var/rneedsContext.js' {
  declare module.exports: $Exports<'jquery/src/traversing/var/rneedsContext'>;
}
declare module 'jquery/src/var/class2type.js' {
  declare module.exports: $Exports<'jquery/src/var/class2type'>;
}
declare module 'jquery/src/var/concat.js' {
  declare module.exports: $Exports<'jquery/src/var/concat'>;
}
declare module 'jquery/src/var/deletedIds.js' {
  declare module.exports: $Exports<'jquery/src/var/deletedIds'>;
}
declare module 'jquery/src/var/hasOwn.js' {
  declare module.exports: $Exports<'jquery/src/var/hasOwn'>;
}
declare module 'jquery/src/var/indexOf.js' {
  declare module.exports: $Exports<'jquery/src/var/indexOf'>;
}
declare module 'jquery/src/var/pnum.js' {
  declare module.exports: $Exports<'jquery/src/var/pnum'>;
}
declare module 'jquery/src/var/push.js' {
  declare module.exports: $Exports<'jquery/src/var/push'>;
}
declare module 'jquery/src/var/rnotwhite.js' {
  declare module.exports: $Exports<'jquery/src/var/rnotwhite'>;
}
declare module 'jquery/src/var/slice.js' {
  declare module.exports: $Exports<'jquery/src/var/slice'>;
}
declare module 'jquery/src/var/strundefined.js' {
  declare module.exports: $Exports<'jquery/src/var/strundefined'>;
}
declare module 'jquery/src/var/support.js' {
  declare module.exports: $Exports<'jquery/src/var/support'>;
}
declare module 'jquery/src/var/toString.js' {
  declare module.exports: $Exports<'jquery/src/var/toString'>;
}
declare module 'jquery/src/wrap.js' {
  declare module.exports: $Exports<'jquery/src/wrap'>;
}
