// flow-typed signature: abad4ea7b47f1050f54a5973809cd696
// flow-typed version: <<STUB>>/keymaster_v1.6.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keymaster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keymaster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keymaster/keymaster' {
  declare module.exports: any;
}

declare module 'keymaster/test/evidence' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keymaster/keymaster.js' {
  declare module.exports: $Exports<'keymaster/keymaster'>;
}
declare module 'keymaster/test/evidence.js' {
  declare module.exports: $Exports<'keymaster/test/evidence'>;
}
