// flow-typed signature: d550bce878008c146550ac6b5e5c1f94
// flow-typed version: <<STUB>>/lru_v3.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lru'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lru' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lru/example/usage' {
  declare module.exports: any;
}

declare module 'lru/test/lru-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lru/example/usage.js' {
  declare module.exports: $Exports<'lru/example/usage'>;
}
declare module 'lru/index' {
  declare module.exports: $Exports<'lru'>;
}
declare module 'lru/index.js' {
  declare module.exports: $Exports<'lru'>;
}
declare module 'lru/test/lru-test.js' {
  declare module.exports: $Exports<'lru/test/lru-test'>;
}
