// flow-typed signature: cc3e318de1094482500e83f9b968ec73
// flow-typed version: <<STUB>>/mixedindentlint_v1.1.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mixedindentlint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mixedindentlint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mixedindentlint/bin/mixedindentlint' {
  declare module.exports: any;
}

declare module 'mixedindentlint/lib/indent-checker' {
  declare module.exports: any;
}

declare module 'mixedindentlint/test/indent-checker-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mixedindentlint/bin/mixedindentlint.js' {
  declare module.exports: $Exports<'mixedindentlint/bin/mixedindentlint'>;
}
declare module 'mixedindentlint/lib/indent-checker.js' {
  declare module.exports: $Exports<'mixedindentlint/lib/indent-checker'>;
}
declare module 'mixedindentlint/test/indent-checker-test.js' {
  declare module.exports: $Exports<'mixedindentlint/test/indent-checker-test'>;
}
