// flow-typed signature: 4510c13c662b8ead537ad1e561876bc1
// flow-typed version: <<STUB>>/mocha-junit-reporter_v1.12.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-junit-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-junit-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-junit-reporter/test/helpers/mock-runner' {
  declare module.exports: any;
}

declare module 'mocha-junit-reporter/test/helpers/mock-test' {
  declare module.exports: any;
}

declare module 'mocha-junit-reporter/test/mocha-junit-reporter-spec' {
  declare module.exports: any;
}

declare module 'mocha-junit-reporter/test/mock-results' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-junit-reporter/index' {
  declare module.exports: $Exports<'mocha-junit-reporter'>;
}
declare module 'mocha-junit-reporter/index.js' {
  declare module.exports: $Exports<'mocha-junit-reporter'>;
}
declare module 'mocha-junit-reporter/test/helpers/mock-runner.js' {
  declare module.exports: $Exports<'mocha-junit-reporter/test/helpers/mock-runner'>;
}
declare module 'mocha-junit-reporter/test/helpers/mock-test.js' {
  declare module.exports: $Exports<'mocha-junit-reporter/test/helpers/mock-test'>;
}
declare module 'mocha-junit-reporter/test/mocha-junit-reporter-spec.js' {
  declare module.exports: $Exports<'mocha-junit-reporter/test/mocha-junit-reporter-spec'>;
}
declare module 'mocha-junit-reporter/test/mock-results.js' {
  declare module.exports: $Exports<'mocha-junit-reporter/test/mock-results'>;
}
