// flow-typed signature: 58938aed37671b5540c5b1f9b53dd981
// flow-typed version: <<STUB>>/percentage-regex_v3.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'percentage-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'percentage-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'percentage-regex/index' {
  declare module.exports: $Exports<'percentage-regex'>;
}
declare module 'percentage-regex/index.js' {
  declare module.exports: $Exports<'percentage-regex'>;
}
