// flow-typed signature: 543a1dc6add015b9bef611d7fe260632
// flow-typed version: <<STUB>>/photon_v2.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'photon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'photon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'photon/dist/photon' {
  declare module.exports: any;
}

declare module 'photon/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'photon/dist/photon.js' {
  declare module.exports: $Exports<'photon/dist/photon'>;
}
declare module 'photon/index' {
  declare module.exports: $Exports<'photon'>;
}
declare module 'photon/index.js' {
  declare module.exports: $Exports<'photon'>;
}
declare module 'photon/test/test.js' {
  declare module.exports: $Exports<'photon/test/test'>;
}
