// flow-typed signature: 358dc248182deac1fd985d7a56452c0a
// flow-typed version: <<STUB>>/q_v1.0.1/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'q'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'q' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'q/benchmark/compare-with-callbacks' {
  declare module.exports: any;
}

declare module 'q/benchmark/scenarios' {
  declare module.exports: any;
}

declare module 'q/q' {
  declare module.exports: any;
}

declare module 'q/queue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'q/benchmark/compare-with-callbacks.js' {
  declare module.exports: $Exports<'q/benchmark/compare-with-callbacks'>;
}
declare module 'q/benchmark/scenarios.js' {
  declare module.exports: $Exports<'q/benchmark/scenarios'>;
}
declare module 'q/q.js' {
  declare module.exports: $Exports<'q/q'>;
}
declare module 'q/queue.js' {
  declare module.exports: $Exports<'q/queue'>;
}
