// flow-typed signature: 31d5b17f8558dd9d0ed9f0c81f7b867d
// flow-typed version: <<STUB>>/qs_v4.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qs/lib/index' {
  declare module.exports: any;
}

declare module 'qs/lib/parse' {
  declare module.exports: any;
}

declare module 'qs/lib/stringify' {
  declare module.exports: any;
}

declare module 'qs/lib/utils' {
  declare module.exports: any;
}

declare module 'qs/test/parse' {
  declare module.exports: any;
}

declare module 'qs/test/stringify' {
  declare module.exports: any;
}

declare module 'qs/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qs/lib/index.js' {
  declare module.exports: $Exports<'qs/lib/index'>;
}
declare module 'qs/lib/parse.js' {
  declare module.exports: $Exports<'qs/lib/parse'>;
}
declare module 'qs/lib/stringify.js' {
  declare module.exports: $Exports<'qs/lib/stringify'>;
}
declare module 'qs/lib/utils.js' {
  declare module.exports: $Exports<'qs/lib/utils'>;
}
declare module 'qs/test/parse.js' {
  declare module.exports: $Exports<'qs/test/parse'>;
}
declare module 'qs/test/stringify.js' {
  declare module.exports: $Exports<'qs/test/stringify'>;
}
declare module 'qs/test/utils.js' {
  declare module.exports: $Exports<'qs/test/utils'>;
}
