// flow-typed signature: 38e9edd359c87f1611a45b1cdedc4785
// flow-typed version: <<STUB>>/react-pure-render_v1.0.2/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pure-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pure-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pure-render/component' {
  declare module.exports: any;
}

declare module 'react-pure-render/function' {
  declare module.exports: any;
}

declare module 'react-pure-render/mixin' {
  declare module.exports: any;
}

declare module 'react-pure-render/shallowEqual' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pure-render/component.js' {
  declare module.exports: $Exports<'react-pure-render/component'>;
}
declare module 'react-pure-render/function.js' {
  declare module.exports: $Exports<'react-pure-render/function'>;
}
declare module 'react-pure-render/index' {
  declare module.exports: $Exports<'react-pure-render'>;
}
declare module 'react-pure-render/index.js' {
  declare module.exports: $Exports<'react-pure-render'>;
}
declare module 'react-pure-render/mixin.js' {
  declare module.exports: $Exports<'react-pure-render/mixin'>;
}
declare module 'react-pure-render/shallowEqual.js' {
  declare module.exports: $Exports<'react-pure-render/shallowEqual'>;
}
