// flow-typed signature: b743c2eca8f4ffdb38da3cb1218ea49f
// flow-typed version: <<STUB>>/react-hot-loader_v1.3.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hot-loader/getRootInstancesFromReactMount' {
  declare module.exports: any;
}

declare module 'react-hot-loader/Injection' {
  declare module.exports: any;
}

declare module 'react-hot-loader/isReactClassish' {
  declare module.exports: any;
}

declare module 'react-hot-loader/isReactElementish' {
  declare module.exports: any;
}

declare module 'react-hot-loader/makeExportsHot' {
  declare module.exports: any;
}

declare module 'react-hot-loader/makeIdentitySourceMap' {
  declare module.exports: any;
}

declare module 'react-hot-loader/RootInstanceProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hot-loader/getRootInstancesFromReactMount.js' {
  declare module.exports: $Exports<'react-hot-loader/getRootInstancesFromReactMount'>;
}
declare module 'react-hot-loader/index' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/index.js' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/Injection.js' {
  declare module.exports: $Exports<'react-hot-loader/Injection'>;
}
declare module 'react-hot-loader/isReactClassish.js' {
  declare module.exports: $Exports<'react-hot-loader/isReactClassish'>;
}
declare module 'react-hot-loader/isReactElementish.js' {
  declare module.exports: $Exports<'react-hot-loader/isReactElementish'>;
}
declare module 'react-hot-loader/makeExportsHot.js' {
  declare module.exports: $Exports<'react-hot-loader/makeExportsHot'>;
}
declare module 'react-hot-loader/makeIdentitySourceMap.js' {
  declare module.exports: $Exports<'react-hot-loader/makeIdentitySourceMap'>;
}
declare module 'react-hot-loader/RootInstanceProvider.js' {
  declare module.exports: $Exports<'react-hot-loader/RootInstanceProvider'>;
}
