// flow-typed signature: 01d02b7809b2288e6475734dcb7178b0
// flow-typed version: <<STUB>>/to-title-case_v0.1.5/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-title-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-title-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-title-case/test/mocha' {
  declare module.exports: any;
}

declare module 'to-title-case/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-title-case/index' {
  declare module.exports: $Exports<'to-title-case'>;
}
declare module 'to-title-case/index.js' {
  declare module.exports: $Exports<'to-title-case'>;
}
declare module 'to-title-case/test/mocha.js' {
  declare module.exports: $Exports<'to-title-case/test/mocha'>;
}
declare module 'to-title-case/test/tests.js' {
  declare module.exports: $Exports<'to-title-case/test/tests'>;
}
