// flow-typed signature: f0f55ae64eff4cd879ac1a16d18e710e
// flow-typed version: <<STUB>>/tracekit_v0.4.3/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tracekit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tracekit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tracekit/Gruntfile' {
  declare module.exports: any;
}

declare module 'tracekit/karma.conf' {
  declare module.exports: any;
}

declare module 'tracekit/spec/fixtures/captured-errors' {
  declare module.exports: any;
}

declare module 'tracekit/spec/tracekit-computestacktrace-spec' {
  declare module.exports: any;
}

declare module 'tracekit/spec/tracekit-handler-spec' {
  declare module.exports: any;
}

declare module 'tracekit/spec/tracekit-parser-spec' {
  declare module.exports: any;
}

declare module 'tracekit/tracekit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tracekit/Gruntfile.js' {
  declare module.exports: $Exports<'tracekit/Gruntfile'>;
}
declare module 'tracekit/karma.conf.js' {
  declare module.exports: $Exports<'tracekit/karma.conf'>;
}
declare module 'tracekit/spec/fixtures/captured-errors.js' {
  declare module.exports: $Exports<'tracekit/spec/fixtures/captured-errors'>;
}
declare module 'tracekit/spec/tracekit-computestacktrace-spec.js' {
  declare module.exports: $Exports<'tracekit/spec/tracekit-computestacktrace-spec'>;
}
declare module 'tracekit/spec/tracekit-handler-spec.js' {
  declare module.exports: $Exports<'tracekit/spec/tracekit-handler-spec'>;
}
declare module 'tracekit/spec/tracekit-parser-spec.js' {
  declare module.exports: $Exports<'tracekit/spec/tracekit-parser-spec'>;
}
declare module 'tracekit/tracekit.js' {
  declare module.exports: $Exports<'tracekit/tracekit'>;
}
