// flow-typed signature: 4359573edb7188bc4eaa9bcb4fe8f588
// flow-typed version: <<STUB>>/wpcom_v5.3.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wpcom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wpcom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wpcom/build/index' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/batch' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/domain.dns' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/domain.email' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/domain' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/domains' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/marketing' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/marketing.survey' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.connected-application' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.keyring-connection' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.publicize-connection' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.settings' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.settings.password' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.settings.profile-links' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.two-step' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/me.two-step.sms' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/plans' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/runtime/site.get' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/runtime/site.post.get' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.category' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.comment' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.comment.like' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.credit-vouchers' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.domain' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.follow' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.media' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.plugin' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.post-type' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.post' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.post.like' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.post.reblog' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.post.subscriber' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.settings' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.tag' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.taxonomy' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.taxonomy.term' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.wordads.earnings' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.wordads' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.wordads.settings' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.wordads.tos' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/site.wpcom-plugin' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/users' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/util/pinghub' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/util/request' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/util/runtime-builder' {
  declare module.exports: any;
}

declare module 'wpcom/build/lib/util/send-request' {
  declare module.exports: any;
}

declare module 'wpcom/build/wpcom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wpcom/build/index.js' {
  declare module.exports: $Exports<'wpcom/build/index'>;
}
declare module 'wpcom/build/lib/batch.js' {
  declare module.exports: $Exports<'wpcom/build/lib/batch'>;
}
declare module 'wpcom/build/lib/domain.dns.js' {
  declare module.exports: $Exports<'wpcom/build/lib/domain.dns'>;
}
declare module 'wpcom/build/lib/domain.email.js' {
  declare module.exports: $Exports<'wpcom/build/lib/domain.email'>;
}
declare module 'wpcom/build/lib/domain.js' {
  declare module.exports: $Exports<'wpcom/build/lib/domain'>;
}
declare module 'wpcom/build/lib/domains.js' {
  declare module.exports: $Exports<'wpcom/build/lib/domains'>;
}
declare module 'wpcom/build/lib/marketing.js' {
  declare module.exports: $Exports<'wpcom/build/lib/marketing'>;
}
declare module 'wpcom/build/lib/marketing.survey.js' {
  declare module.exports: $Exports<'wpcom/build/lib/marketing.survey'>;
}
declare module 'wpcom/build/lib/me.connected-application.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.connected-application'>;
}
declare module 'wpcom/build/lib/me.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me'>;
}
declare module 'wpcom/build/lib/me.keyring-connection.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.keyring-connection'>;
}
declare module 'wpcom/build/lib/me.publicize-connection.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.publicize-connection'>;
}
declare module 'wpcom/build/lib/me.settings.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.settings'>;
}
declare module 'wpcom/build/lib/me.settings.password.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.settings.password'>;
}
declare module 'wpcom/build/lib/me.settings.profile-links.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.settings.profile-links'>;
}
declare module 'wpcom/build/lib/me.two-step.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.two-step'>;
}
declare module 'wpcom/build/lib/me.two-step.sms.js' {
  declare module.exports: $Exports<'wpcom/build/lib/me.two-step.sms'>;
}
declare module 'wpcom/build/lib/plans.js' {
  declare module.exports: $Exports<'wpcom/build/lib/plans'>;
}
declare module 'wpcom/build/lib/runtime/site.get.js' {
  declare module.exports: $Exports<'wpcom/build/lib/runtime/site.get'>;
}
declare module 'wpcom/build/lib/runtime/site.post.get.js' {
  declare module.exports: $Exports<'wpcom/build/lib/runtime/site.post.get'>;
}
declare module 'wpcom/build/lib/site.category.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.category'>;
}
declare module 'wpcom/build/lib/site.comment.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.comment'>;
}
declare module 'wpcom/build/lib/site.comment.like.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.comment.like'>;
}
declare module 'wpcom/build/lib/site.credit-vouchers.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.credit-vouchers'>;
}
declare module 'wpcom/build/lib/site.domain.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.domain'>;
}
declare module 'wpcom/build/lib/site.follow.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.follow'>;
}
declare module 'wpcom/build/lib/site.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site'>;
}
declare module 'wpcom/build/lib/site.media.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.media'>;
}
declare module 'wpcom/build/lib/site.plugin.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.plugin'>;
}
declare module 'wpcom/build/lib/site.post-type.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.post-type'>;
}
declare module 'wpcom/build/lib/site.post.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.post'>;
}
declare module 'wpcom/build/lib/site.post.like.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.post.like'>;
}
declare module 'wpcom/build/lib/site.post.reblog.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.post.reblog'>;
}
declare module 'wpcom/build/lib/site.post.subscriber.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.post.subscriber'>;
}
declare module 'wpcom/build/lib/site.settings.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.settings'>;
}
declare module 'wpcom/build/lib/site.tag.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.tag'>;
}
declare module 'wpcom/build/lib/site.taxonomy.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.taxonomy'>;
}
declare module 'wpcom/build/lib/site.taxonomy.term.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.taxonomy.term'>;
}
declare module 'wpcom/build/lib/site.wordads.earnings.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.wordads.earnings'>;
}
declare module 'wpcom/build/lib/site.wordads.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.wordads'>;
}
declare module 'wpcom/build/lib/site.wordads.settings.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.wordads.settings'>;
}
declare module 'wpcom/build/lib/site.wordads.tos.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.wordads.tos'>;
}
declare module 'wpcom/build/lib/site.wpcom-plugin.js' {
  declare module.exports: $Exports<'wpcom/build/lib/site.wpcom-plugin'>;
}
declare module 'wpcom/build/lib/users.js' {
  declare module.exports: $Exports<'wpcom/build/lib/users'>;
}
declare module 'wpcom/build/lib/util/pinghub.js' {
  declare module.exports: $Exports<'wpcom/build/lib/util/pinghub'>;
}
declare module 'wpcom/build/lib/util/request.js' {
  declare module.exports: $Exports<'wpcom/build/lib/util/request'>;
}
declare module 'wpcom/build/lib/util/runtime-builder.js' {
  declare module.exports: $Exports<'wpcom/build/lib/util/runtime-builder'>;
}
declare module 'wpcom/build/lib/util/send-request.js' {
  declare module.exports: $Exports<'wpcom/build/lib/util/send-request'>;
}
declare module 'wpcom/build/wpcom.js' {
  declare module.exports: $Exports<'wpcom/build/wpcom'>;
}
