// flow-typed signature: be4ebb3d01ba37c93423d8f730b22b95
// flow-typed version: <<STUB>>/wpcom-proxy-request_v3.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wpcom-proxy-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wpcom-proxy-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wpcom-proxy-request/build/index' {
  declare module.exports: any;
}

declare module 'wpcom-proxy-request/build/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wpcom-proxy-request/build/index.js' {
  declare module.exports: $Exports<'wpcom-proxy-request/build/index'>;
}
declare module 'wpcom-proxy-request/build/test/index.js' {
  declare module.exports: $Exports<'wpcom-proxy-request/build/test/index'>;
}
