import {
	Button,
	Card,
	CardBody,
	CardMedia,
	Spinner,
	__experimentalHStack as HStack,
	__experimentalText as Text,
	__experimentalVStack as VStack,
} from '@wordpress/components';
import { dateI18n } from '@wordpress/date';
import { __, _n, sprintf } from '@wordpress/i18n';
import { Icon, warning } from '@wordpress/icons';
import { useEffect, useRef, useState } from 'react';
import useUpdateAgentStudioOutput from '../../data/use-update-agent-studio-output';
import { getAgentStudioOutputPath } from '../../lib/paths';
import { ELA_PAGE_HEIGHT, ELA_PAGE_WIDTH } from '../../one-pager/engine/types';
import { getOnePagerServices } from '../../one-pager/services';
import DeleteDeliverableDialog from './delete-deliverable-dialog';
import type { AgentStudioOutput } from '../../types';

import './style.scss';

interface Props {
	output: AgentStudioOutput;
}

export default function DeliverableCard( { output }: Props ) {
	const [ isDeleteDialogOpen, setIsDeleteDialogOpen ] = useState( false );

	return (
		<Card size="small" className="a4a-agent-studio-deliverable-card">
			<CardMedia className="a4a-agent-studio-deliverable-card__media">
				<DeliverablePreview output={ output } />
			</CardMedia>
			<CardBody className="a4a-agent-studio-deliverable-card__body">
				<VStack spacing={ 1 } className="a4a-agent-studio-deliverable-card__info">
					<Text size={ 15 } weight={ 600 } className="a4a-agent-studio-deliverable-card__title">
						{ output.title }
					</Text>
					<Text variant="muted">{ dateI18n( 'F j, Y', output.createdAt ) }</Text>
					<Text variant="muted">{ getMetaLabel( output ) }</Text>
				</VStack>
				<HStack justify="flex-end" spacing={ 2 }>
					{ output.kind === 'one-pager' && output.status === 'ready' && (
						<Button variant="primary" href={ getAgentStudioOutputPath( output.id ) }>
							{ __( 'Open' ) }
						</Button>
					) }
					<Button variant="secondary" isDestructive onClick={ () => setIsDeleteDialogOpen( true ) }>
						{ __( 'Delete' ) }
					</Button>
				</HStack>
			</CardBody>
			{ isDeleteDialogOpen && (
				<DeleteDeliverableDialog
					output={ output }
					onClose={ () => setIsDeleteDialogOpen( false ) }
					onDeleted={ () => setIsDeleteDialogOpen( false ) }
				/>
			) }
		</Card>
	);
}

function DeliverablePreview( { output }: Props ) {
	useOnePagerCoverBackfill( output );

	if ( output.status === 'generating' ) {
		return (
			<div className="a4a-agent-studio-deliverable-card__state">
				<Spinner />
				<Text>{ __( 'Generating…' ) }</Text>
			</div>
		);
	}

	if ( output.status === 'failed' ) {
		return (
			<div className="a4a-agent-studio-deliverable-card__state">
				<Icon icon={ warning } size={ 24 } />
				<Text>{ __( 'Generation failed' ) }</Text>
			</div>
		);
	}

	// One-pager cards lead with a single cover snapshot rendered to PNG once,
	// post-generation, so the list never live-renders HTML on scroll.
	if ( output.kind === 'one-pager' && output.previewUrls?.[ 0 ] ) {
		return (
			<img
				className="a4a-agent-studio-deliverable-card__cover"
				src={ output.previewUrls[ 0 ] }
				alt=""
			/>
		);
	}

	if ( output.kind === 'one-pager' ) {
		// Cover snapshot is still being generated by the backfill effect.
		return (
			<div className="a4a-agent-studio-deliverable-card__state">
				<Spinner />
			</div>
		);
	}

	return (
		<div className="a4a-agent-studio-deliverable-card__strip">
			{ output.previewUrls?.map( ( url ) => <img key={ url } src={ url } alt="" /> ) }
		</div>
	);
}

/**
 * Generates a cover thumbnail for a finished one-pager that doesn't have one
 * yet and persists it back on the output. Covers outputs created before the
 * thumbnail snapshot was added to the generation flow, and any that lost
 * their thumb to an IDB reset.
 */
function useOnePagerCoverBackfill( output: AgentStudioOutput ): void {
	const updateOutput = useUpdateAgentStudioOutput();
	const inFlightRef = useRef( false );

	useEffect( () => {
		if ( output.kind !== 'one-pager' ) {
			return;
		}
		if ( output.status !== 'ready' ) {
			return;
		}
		if ( output.previewUrls && output.previewUrls.length > 0 ) {
			return;
		}
		const cover = output.onePagerData?.covers[ output.onePagerData.selectedCoverIdx ?? 0 ];
		if ( ! cover ) {
			return;
		}
		if ( inFlightRef.current ) {
			return;
		}
		inFlightRef.current = true;
		let cancelled = false;
		( async () => {
			try {
				const dataUrl = await getOnePagerServices().thumbnail.renderPagePng( {
					html: cover.html,
					width: ELA_PAGE_WIDTH,
					height: ELA_PAGE_HEIGHT,
				} );
				if ( cancelled || ! dataUrl ) {
					return;
				}
				updateOutput.mutate( {
					outputId: output.id,
					updates: { previewUrls: [ dataUrl ] },
				} );
			} catch ( error ) {
				// eslint-disable-next-line no-console
				console.warn( '[one-pager card] cover backfill failed:', error );
			} finally {
				inFlightRef.current = false;
			}
		} )();
		return () => {
			cancelled = true;
		};
	}, [
		output.id,
		output.kind,
		output.status,
		output.previewUrls,
		output.onePagerData,
		updateOutput,
	] );
}

function getMetaLabel( output: AgentStudioOutput ) {
	if ( output.status === 'generating' ) {
		return __( 'Generating…' );
	}

	if ( output.status === 'failed' ) {
		return __( 'Generation failed' );
	}

	const count = output.assetCount ?? output.previewUrls?.length ?? 0;
	return sprintf(
		/* translators: %d is the number of generated assets. */
		_n( '%d asset', '%d assets', count ),
		count
	);
}
