/* Follow Source Constants */
export const IN_STREAM_RECOMMENDATION = 'in-stream-recommendation';
export const SEARCH_RESULTS_SITES = 'search-results-sites';
export const READER_POST_OPTIONS_MENU = 'reader-post-options-menu';
export const READER_SUGGESTED_FOLLOWS_DIALOG = 'reader-suggested-follows-dialog';
export const READER_SEARCH_POPULAR_SITES = 'reader-search-popular-sites';
export const READER_DISCOVER = 'reader-discover';
export const READER_FOLLOW_SITES_SEARCH = 'reader-follow-sites-search';
export const READER_FOLLOW_SITES_PACK = 'reader-follow-sites-pack';
export const READER_FOLLOW_SITES_POPULAR = 'reader-follow-sites-popular';
