/* Follow Source Constants */
export const IN_STREAM_RECOMMENDATION = 'in-stream-recommendation';
export const EMPTY_SEARCH_RECOMMENDATIONS = 'empty-search-rec';
export const SEARCH_RESULTS = 'search-results';
export const SEARCH_RESULTS_SITES = 'search-results-sites';
export const SEARCH_RESULTS_URL_INPUT = 'search-results-url-input';
export const READER_SUBSCRIPTIONS = 'reader-subscriptions';
export const READER_FEED_SEARCH = 'reader-feed-search-result';
export const READER_FOLLOWING_MANAGE_URL_INPUT = 'reader-following-manage-url-input';
export const READER_FOLLOWING_MANAGE_SEARCH_RESULT = 'reader-following-manage-search-result';
export const READER_FOLLOWING_MANAGE_RECOMMENDATION = 'reader-following-manage-recommendation';
export const READER_FULL_POST = 'reader-full-post';
export const READER_POST_OPTIONS_MENU = 'reader-post-options-menu';
export const TAG_PAGE = 'reader-tag-page';
export const DISCOVER_POST = 'reader-discover-post';
