/**
 * Internal dependencies
 *
 * @format
 */

import {
	addDomainToCart,
	addGoogleAppsRegistrationData,
	addItem,
	addItems,
	addPrivacyToAllDomains,
	applyCoupon,
	closeCartPopup,
	disableCart,
	openCartPopup,
	removeDomainFromCart,
	removeItem,
	removePrivacyFromAllDomains,
	showCartOnMobile,
} from './cart';
import {
	resetTransaction,
	setDomainDetails,
	setNewCreditCardDetails,
	setPayment,
	submitTransaction,
} from './checkout';
import { startFreeTrial } from './free-trials';
import {
	acceptTransfer,
	addDns,
	addEmailForwarding,
	applyDnsTemplate,
	cancelTransferRequest,
	closeSiteRedirectNotice,
	declineTransfer,
	deleteDns,
	deleteEmailForwarding,
	enablePrivacyProtection,
	fetchDns,
	fetchDomains,
	fetchEmailForwarding,
	fetchNameservers,
	fetchSiteRedirect,
	fetchWapiDomainInfo,
	fetchWhois,
	requestTransferCode,
	resendIcannVerification,
	resendVerificationEmailForwarding,
	setPrimaryDomain,
	updateNameservers,
	updateSiteRedirect,
	updateWhois,
} from './domain-management';
import { goToDomainCheckout } from './domain-search';
import { cancelAndRefundPurchase, cancelPurchase, submitSurvey } from './purchases';

export {
	addDomainToCart,
	addGoogleAppsRegistrationData,
	addItem,
	addItems,
	addPrivacyToAllDomains,
	applyCoupon,
	closeCartPopup,
	disableCart,
	openCartPopup,
	removeDomainFromCart,
	removeItem,
	removePrivacyFromAllDomains,
	showCartOnMobile,
	resetTransaction,
	setDomainDetails,
	setNewCreditCardDetails,
	setPayment,
	submitTransaction,
	startFreeTrial,
	acceptTransfer,
	addDns,
	addEmailForwarding,
	applyDnsTemplate,
	cancelTransferRequest,
	closeSiteRedirectNotice,
	declineTransfer,
	deleteDns,
	deleteEmailForwarding,
	enablePrivacyProtection,
	fetchDns,
	fetchDomains,
	fetchEmailForwarding,
	fetchNameservers,
	fetchSiteRedirect,
	fetchWapiDomainInfo,
	fetchWhois,
	requestTransferCode,
	resendIcannVerification,
	resendVerificationEmailForwarding,
	setPrimaryDomain,
	updateNameservers,
	updateSiteRedirect,
	updateWhois,
	goToDomainCheckout,
	cancelAndRefundPurchase,
	cancelPurchase,
	submitSurvey,
};

export default {
	addDomainToCart,
	addGoogleAppsRegistrationData,
	addItem,
	addItems,
	addPrivacyToAllDomains,
	applyCoupon,
	closeCartPopup,
	disableCart,
	openCartPopup,
	removeDomainFromCart,
	removeItem,
	removePrivacyFromAllDomains,
	showCartOnMobile,
	resetTransaction,
	setDomainDetails,
	setNewCreditCardDetails,
	setPayment,
	submitTransaction,
	startFreeTrial,
	acceptTransfer,
	addDns,
	addEmailForwarding,
	applyDnsTemplate,
	cancelTransferRequest,
	closeSiteRedirectNotice,
	declineTransfer,
	deleteDns,
	deleteEmailForwarding,
	enablePrivacyProtection,
	fetchDns,
	fetchDomains,
	fetchEmailForwarding,
	fetchNameservers,
	fetchSiteRedirect,
	fetchWapiDomainInfo,
	fetchWhois,
	requestTransferCode,
	resendIcannVerification,
	resendVerificationEmailForwarding,
	setPrimaryDomain,
	updateNameservers,
	updateSiteRedirect,
	updateWhois,
	goToDomainCheckout,
	cancelAndRefundPurchase,
	cancelPurchase,
	submitSurvey,
};
