/**
 * Products catalog for the MSD Marketplace prototype.
 *
 * Generated on Sep 3 2026 from the live `/agency/products` response for this
 * agency (74 sellable products; hosting families excluded — they live on the
 * Hosting page). Descriptions, category membership, vendors and WooCommerce.com
 * URLs are lifted verbatim from Main's client-side maps, since the API carries
 * none of them:
 *  - descriptions: client/jetpack-cloud/sections/partner-portal/hooks (useProductDescription)
 *  - categories:   client/a8c-for-agencies/sections/marketplace/lib/product-slugs.ts
 *  - vendors:      products-overview/lib/get-vendor-info.ts
 *  - Woo URLs:     products-overview/product-card/lib/get-woo-product-url.ts
 * Never invent prices: regenerate from the API when the catalog changes.
 */

export type ProductKind = 'plan' | 'product' | 'add-on' | 'extension';

export interface CatalogProduct {
	name: string;
	slug: string;
	family: string;
	kind: ProductKind;
	productId: number;
	monthly: number | null;
	yearly: number | null;
	description: string;
	categories: string[];
	vendorName: string;
	vendorUrl: string;
	wooUrl: string | null;
	/** Main's lightbox bullets (calypso-products getJetpackProductsBenefits). */
	benefits: string[];
	/** Main's "Great for:" tags (JETPACK_PRODUCT_RECCOMENDATION_MAP). */
	greatFor: string[];
}

export const CATALOG: CatalogProduct[] = [
	{
		name: 'Jetpack Scan Daily',
		slug: 'jetpack-scan',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2106,
		monthly: 4.95,
		yearly: 59.4,
		description: 'Automatic malware scanning with one-click fixes.',
		categories: [ 'Security' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Protect your revenue stream and content',
			'Learn about issues before your customers are impacted',
			'Fix most issues in one click from desktop or mobile',
			'Best-in-class support from WordPress experts',
		],
		greatFor: [ 'WooCommerce stores', 'News organizations', 'Membership sites', 'Online forums' ],
	},
	{
		name: 'Jetpack VaultPress Backup (10GB)',
		slug: 'jetpack-backup-t1',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2112,
		monthly: 4.95,
		yearly: 59.4,
		description: 'Real-time cloud backups with one-click restores.',
		categories: [ 'Security' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Protect your revenue stream and content',
			'Restore your site in one click from desktop or mobile',
			'Restore or clone offline sites',
			'Fix your site without a developer',
			'Protect Woo order and customer data',
			'Best-in-class support from WordPress experts',
		],
		greatFor: [ 'WooCommerce stores', 'News organizations', 'Membership sites', 'Online forums' ],
	},
	{
		name: 'Jetpack Akismet Anti-spam',
		slug: 'jetpack-anti-spam',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2110,
		monthly: 4.95,
		yearly: 59.4,
		description: 'Automatically clear spam from your comments and forms.',
		categories: [ 'Security' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Set up in minutes without a developer',
			'Save time manually reviewing spam',
			'Increase engagement by removing CAPTCHAs',
			'Best-in-class support from WordPress experts',
		],
		greatFor: [
			'Blogs',
			'News organizations',
			'Membership sites',
			'Online forums',
			'WooCommerce stores',
		],
	},
	{
		name: 'Jetpack Search',
		slug: 'jetpack-search',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2104,
		monthly: 8.25,
		yearly: 100,
		description: 'Help your site visitors find answers instantly.',
		categories: [ 'Performance' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			"Customizable to fit your site's design",
			'Increase conversion with accurate search results',
			'Tiered pricing - pay for only what you need',
			'No developer required',
			'Best-in-class support from WordPress experts',
		],
		greatFor: [ 'WooCommerce stores', 'News organizations', 'Membership sites', 'Online forums' ],
	},
	{
		name: 'Jetpack VideoPress',
		slug: 'jetpack-videopress',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2116,
		monthly: 4.95,
		yearly: 59.4,
		description: 'High-quality, ad-free video built specifically for WordPress.',
		categories: [ 'Performance' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Increase engagement and get your message across',
			'Drag and drop videos through the WordPress editor',
			'Manage videos in the WordPress media library',
			'Remove distracting ads',
			'Customizable colors to fit your brand and site',
			'Best-in-class support from WordPress experts',
		],
		greatFor: [ 'WooCommerce stores', 'Videographers', 'Educators', 'Blogs' ],
	},
	{
		name: 'Jetpack AI Assistant',
		slug: 'jetpack-ai',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2451,
		monthly: 8.33,
		yearly: 59.4,
		description: 'Unleash the power of AI to boost your content creation.',
		categories: [ 'Growth' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Harness AI power directly from your editor',
			'Unlock high-quality, tailored content at your command',
			'Maintain professional standards with ease',
			'Best-in-class support from WordPress experts',
		],
		greatFor: [
			'Bloggers',
			'News organizations',
			'Membership sites',
			'Online forums',
			'WooCommerce stores',
		],
	},
	{
		name: 'Jetpack Stats (Paid)',
		slug: 'jetpack-stats',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2219,
		monthly: 8.33,
		yearly: 100,
		description: 'Powerful analytics to help you understand your audience.',
		categories: [ 'Growth' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Better understand your audience',
			'Discover your top performing posts & pages',
			'Get detailed insights on the referrers that bring traffic from your site',
			'See what countries your visitors are coming from',
			'Find who is creating the most popular content on your team with our author metrics',
			'View weekly and yearly trends with 7-day Highlights and Year in Review',
			'UTM tracking',
			'Traffic spike forgiveness',
			'Overage forgiveness',
			'Commercial use',
		],
		greatFor: [ 'WooCommerce stores', 'News organizations', 'Membership sites' ],
	},
	{
		name: 'Jetpack Monitor',
		slug: 'jetpack-monitor',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2242,
		monthly: 1,
		yearly: 14.64,
		description:
			'Upgrade Monitor with swift 1-minute monitoring alert intervals, SMS notifications, and multiple email recipients.',
		categories: [ 'Security' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Rapid detection: With our 1-minute interval monitoring, we detect potential issues faster than ever before.',
			'Multi-channel alerts: Get notified immediately when a site that you manage is down via SMS and email (multiple recipients).',
			'Enhanced uptime: Experience less downtime and increased service reliability through prompt response and resolution.',
			'Reduce potential revenue losses because your site went down.',
		],
		greatFor: [],
	},
	{
		name: 'Jetpack Boost',
		slug: 'jetpack-boost',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2401,
		monthly: 9.95,
		yearly: 119.4,
		description: 'Essential tools to speed up your site - no developer required.',
		categories: [ 'Performance' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Quickly test and improve your site speed',
			"Improve your site's SEO",
			'Get faster FCP and LCP',
			'No developer required',
			'Best-in-class support from WordPress experts',
		],
		greatFor: [ 'All sites' ],
	},
	{
		name: 'Jetpack Social',
		slug: 'jetpack-social-v1',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2605,
		monthly: 4.95,
		yearly: 59.4,
		description: 'Write once, post everywhere.',
		categories: [ 'Social' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [
			'Bloggers',
			'News organizations',
			'Membership sites',
			'Online forums',
			'WooCommerce stores',
		],
	},
	{
		name: 'Jetpack Creator',
		slug: 'jetpack-creator',
		family: 'jetpack-products',
		kind: 'product',
		productId: 2611,
		monthly: 9.95,
		yearly: 119.4,
		description:
			'Craft stunning content, boost your subscriber base, and monetize your online presence.',
		categories: [ 'Growth' ],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [
			'Quickly create content that stands out',
			'Grow your subscribers with simple subscribe forms',
			'Create content for paid subscribers',
			'Sell access to premium content',
			'Easily accept tips and donations',
		],
		greatFor: [ 'Educators', 'Bloggers', 'Videographers', 'Membership sites' ],
	},
	{
		name: 'Jetpack VaultPress Backup Add-on Storage (10GB)',
		slug: 'jetpack-backup-addon-storage-10gb-monthly',
		family: 'jetpack-backup-storage',
		kind: 'add-on',
		productId: 2040,
		monthly: 2.95,
		yearly: null,
		description: 'Additional storage for your Jetpack VaultPress Backup plan.',
		categories: [],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [],
	},
	{
		name: 'Jetpack VaultPress Backup Add-on Storage (100GB)',
		slug: 'jetpack-backup-addon-storage-100gb-monthly',
		family: 'jetpack-backup-storage',
		kind: 'add-on',
		productId: 2044,
		monthly: 5.95,
		yearly: null,
		description: 'Additional storage for your Jetpack VaultPress Backup plan.',
		categories: [],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [],
	},
	{
		name: 'Jetpack VaultPress Backup Add-on Storage (1TB)',
		slug: 'jetpack-backup-addon-storage-1tb-monthly',
		family: 'jetpack-backup-storage',
		kind: 'add-on',
		productId: 2048,
		monthly: 9.95,
		yearly: null,
		description: 'Additional storage for your Jetpack VaultPress Backup plan.',
		categories: [],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [],
	},
	{
		name: 'Jetpack VaultPress Backup Add-on Storage (3TB)',
		slug: 'jetpack-backup-addon-storage-3tb-monthly',
		family: 'jetpack-backup-storage',
		kind: 'add-on',
		productId: 2052,
		monthly: 19.95,
		yearly: null,
		description: 'Additional storage for your Jetpack VaultPress Backup plan.',
		categories: [],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [],
	},
	{
		name: 'Jetpack VaultPress Backup Add-on Storage (5TB)',
		slug: 'jetpack-backup-addon-storage-5tb-monthly',
		family: 'jetpack-backup-storage',
		kind: 'add-on',
		productId: 2056,
		monthly: 29.95,
		yearly: null,
		description: 'Additional storage for your Jetpack VaultPress Backup plan.',
		categories: [],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [],
	},
	{
		name: 'Jetpack Complete',
		slug: 'jetpack-complete',
		family: 'jetpack-packs',
		kind: 'plan',
		productId: 2014,
		monthly: 24.95,
		yearly: 299.4,
		description: 'Includes all Security products (1TB storage) and the full Jetpack suite.',
		categories: [],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [],
	},
	{
		name: 'Jetpack Security (10GB)',
		slug: 'jetpack-security-t1',
		family: 'jetpack-packs',
		kind: 'plan',
		productId: 2016,
		monthly: 9.95,
		yearly: 119.4,
		description: 'Includes VaultPress Backup 10GB, Scan Daily, and Akismet Anti-spam.',
		categories: [],
		vendorName: 'Jetpack',
		vendorUrl: 'https://jetpack.com/',
		wooUrl: null,
		benefits: [],
		greatFor: [],
	},
	{
		name: 'WooCommerce Bookings',
		slug: 'woocommerce-bookings',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2700,
		monthly: 20.75,
		yearly: 249,
		description:
			'Allow customers to book appointments, make reservations or rent equipment without leaving your site.',
		categories: [ 'Store content' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-bookings/',
		benefits: [
			'Let your customers book reservations, appointments, or rentals independently - no phone calls are required.',
			'Offer discounts for groups or people booking multiple slots, show lower prices for early birds, higher prices on weekends, or special prices for kids.',
			'Your customers see availability in their time zone',
			'Reduce no-shows with reminder notifications',
			'An intelligent booking system to avoid double-bookings',
			'Boost your bookings with a range of add-ons',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Subscriptions',
		slug: 'woocommerce-subscriptions',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2701,
		monthly: 23.25,
		yearly: 279,
		description:
			'Let customers subscribe to your products or services and pay on a weekly, monthly, or annual basis.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-subscriptions/',
		benefits: [
			'Multiple billing schedules available to suit your store’s needs',
			'Integration with over 25 payment gateways for automatic recurring payments',
			'Supports manual renewal payments through any WooCommerce payment gateway, along with automatic email invoices and receipts',
			'Supports automatic rebilling on failed subscription payments',
			'Give subscribers the ability to manage their own plan',
			'Built-in renewal notifications and automatic emails',
			'Detailed reports allow you to keep track of recurring revenue, the number of active subscribers, and more',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Product Bundles',
		slug: 'woocommerce-product-bundles',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2702,
		monthly: 6.58,
		yearly: 79,
		description:
			'Offer personalized product bundles, bulk discount packages, and assembled products.',
		categories: [ 'Conversion' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/product-bundles/',
		benefits: [
			'Sell more by creating discounted bundles or personalized boxes',
			'Create product offerings made from multiple inventory-managed parts.',
			'Boost your average order value by adding recommendations to popular products, and use discounts to maximize their impact.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Product Add-Ons',
		slug: 'woocommerce-product-add-ons',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2703,
		monthly: 6.58,
		yearly: 79,
		description:
			'Offer add-ons like gift wrapping, special messages, or other special options for your products.',
		categories: [ 'Conversion' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/product-add-ons/',
		benefits: [
			'You can offer special options to your customers.',
			'Enable your customers to personalize products while they are shopping on your online store',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Min/Max Quantities',
		slug: 'woocommerce-minmax-quantities',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2704,
		monthly: 4.08,
		yearly: 49,
		description: 'Minimum and maximum quantity rules for products, orders, and categories.',
		categories: [ 'Store content' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/minmax-quantities/',
		benefits: [
			'Specify minimum and maximum quantity limits per product/variation or order.',
			'Require specific products, or product categories, to be purchased in predefined quantity multiples.',
			'Prevent overstocking or stockouts, maintain optimal inventory levels, and reduce storage costs.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce AutomateWoo',
		slug: 'woocommerce-automatewoo',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2705,
		monthly: 13.25,
		yearly: 159,
		description:
			'Powerful marketing automation for WooCommerce - grow your store and make more money.',
		categories: [ 'Customer service' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/automatewoo/',
		benefits: [
			'Effortless setup and management right from your WordPress backend',
			'Send targeted, multi-step campaigns and offer customer incentives',
			'Measure the success of your campaigns',
			'Unlimited email sends',
			'AutomateWoo is %(extentablePercent)s extendable',
			'Multilingual support. AutomateWoo has support for the popular WPML plugin',
			'AutomateWoo integrates with your favorite plugins and services',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Advanced Notifications',
		slug: 'woocommerce-advanced-notifications',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2706,
		monthly: 3.25,
		yearly: 39,
		description:
			'Easily setup new order and stock email notifications for multiple recipients of your choosing.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/advanced-notifications/',
		benefits: [
			'Set up order and stock notifications for multiple recipients beyond admin',
			'Notify staff, suppliers, or drop shippers of sales and inventory changes',
			'Customize notification criteria and content',
			'Choose between plain text or HTML email formats',
			'Set up per-product notifications',
			'Include or exclude prices and order totals in notifications',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'All Products for Woo Subscriptions',
		slug: 'woocommerce-all-products-woo-subscriptions',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2707,
		monthly: 8.25,
		yearly: 99,
		description:
			'Add subscription plans to your existing products and start capturing residual revenue with All Products for WooCommerce Subscriptions.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/all-products-for-woocommerce-subscriptions/',
		benefits: [
			'Add subscription plans to existing Simple or Variable products',
			'Sell any product one-time or on a subscription',
			'Allow customers to add products to existing subscriptions',
			'Create personalized subscription boxes with Product Bundles integration',
			'Define global or custom subscription plans for individual products',
			'Limit subscription options to specific product categories',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'AutomateWoo - Birthdays Add-on',
		slug: 'woocommerce-automatewoo-birthdays',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2708,
		monthly: 4.08,
		yearly: 49,
		description:
			'Delight customers and boost organic sales with a special WooCommerce birthday email (and coupon!) on their special day.',
		categories: [ 'Customer service' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/automatewoo-birthdays/',
		benefits: [
			'Send automated birthday emails and coupons to customers',
			'Increase brand loyalty and boost sales with personalized birthday messages',
			'Collect customer birthdays during checkout or on account pages',
			'Configure workflows to run before, on, or after customer birthdays',
			'Personalize email content with customer data and birthday-specific offers',
			'Supports GDPR compliance for customer data',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'AutomateWoo - Refer a Friend Add-on',
		slug: 'woocommerce-automatewoo-refer-a-friend',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2709,
		monthly: 8.25,
		yearly: 99,
		description:
			'Boost your organic sales by adding a customer referral program to your WooCommerce store.',
		categories: [ 'Customer service' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/automatewoo-refer-a-friend/',
		benefits: [
			'Boost word-of-mouth sales with a customer referral program',
			'Run coupon-based or link-based referral campaigns',
			'Allow advocates to share referrals via email, Facebook, X, and WhatsApp',
			'Reward advocates with store credit for successful referrals',
			'Include post-purchase share widgets on order confirmation pages and emails',
			'Implement fraud prevention measures to protect the referral program',
			'Provide detailed reporting on referral program performance',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Back in Stock Notifications',
		slug: 'woocommerce-back-in-stock-notifications',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2710,
		monthly: 4.92,
		yearly: 59,
		description:
			'Notify customers when your out-of-stock products become available. Recover lost sales, build customer loyalty, and gain deeper insights into your inventory.',
		categories: [ 'Conversion' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/back-in-stock-notifications/',
		benefits: [
			'Allow customers to subscribe for stock notifications',
			'Automatically notify customers when products are back in stock',
			'Works with Simple, Variable, Grouped, and Subscription products',
			'Manage all notification sign-ups from a central admin area',
			'Export subscriber data for use in email marketing platforms',
			'Process notifications in batches using Action Scheduler for scalability',
			'Set minimum quantity thresholds for sending restock notifications',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Bulk Stock Management',
		slug: 'woocommerce-bulk-stock-management',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2711,
		monthly: 4.08,
		yearly: 49,
		description: 'Edit product and variation stock levels in bulk via this handy interface.',
		categories: [ 'Store management' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/bulk-stock-management/',
		benefits: [
			'Manage product stock levels from a single interface',
			'Filter products by type, stock management status, and stock status',
			'Order products by name, ID, SKU, or stock quantity',
			'Set stock quantities for multiple products at once',
			'Apply bulk actions like setting stock status or allowing backorders',
			'Generate printable stock reports for inventory management',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Checkout Field Editor',
		slug: 'woocommerce-checkout-field-editor',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2712,
		monthly: 4.08,
		yearly: 49,
		description:
			'Optimize your checkout process by adding, removing or editing fields to suit your needs.',
		categories: [ 'Conversion' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-checkout-field-editor/',
		benefits: [
			'Customize checkout fields',
			'Add, edit, or remove fields on the checkout page',
			'Rearrange the order of checkout fields',
			'Set custom field validations',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Composite Products',
		slug: 'woocommerce-composite-products',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2713,
		monthly: 12.42,
		yearly: 149,
		description:
			'The definitive product builder plugin for WooCommerce. Create and offer personalized product kits and custom product configurators.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/composite-products/',
		benefits: [
			'Create complex product kits or bundles',
			'Allow customers to configure custom product combinations',
			'Set component options and quantity limits',
			'Apply conditional logic to component visibility',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Conditional Shipping and Payments',
		slug: 'woocommerce-conditional-shipping-payments',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2714,
		monthly: 9.08,
		yearly: 109,
		description:
			'Use conditional logic to restrict the shipping methods, payment gateways and shipping countries or states available to customers at checkout.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/conditional-shipping-and-payments/',
		benefits: [
			'Set rules for shipping/payment methods based on cart contents',
			'Customize available options based on customer location or purchase',
			'Create complex rules combining multiple conditions',
			'Hide or show shipping/payment methods based on product categories, tags, or attributes',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'EU VAT Number',
		slug: 'woocommerce-eu-vat-number',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2715,
		monthly: 3.25,
		yearly: 39,
		description:
			'Collect VAT numbers at checkout and remove the VAT charge for eligible EU businesses.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/eu-vat-number/',
		benefits: [
			'Collect and validate EU VAT numbers',
			'Apply correct VAT rates for B2B transactions',
			'Ensure compliance with EU tax regulations',
			'Automatically validate VAT numbers in real-time',
			'Generate VAT reports for easy tax filing',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Flat Rate Box Shipping',
		slug: 'woocommerce-flat-rate-box-shipping',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2716,
		monthly: 4.92,
		yearly: 59,
		description: 'Pack items into boxes with pre-defined costs per destination.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/flat-rate-box-shipping/',
		benefits: [
			'Offer flat rate shipping based on box sizes',
			'Optimize shipping costs for differently sized products',
			'Define multiple box sizes and their respective shipping rates',
			'Automatically select the most cost-effective box for each order',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Gift Cards',
		slug: 'woocommerce-gift-cards',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2717,
		monthly: 6.58,
		yearly: 79,
		description:
			'Offer digital prepaid gift cards and e-gift certificates that customers can redeem at your WooCommerce store.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/gift-cards/',
		benefits: [
			'Sell and redeem gift cards',
			'Offer store credit as a product',
			'Allow customers to purchase and send digital gift cards',
			'Set expiration dates and custom designs for gift cards',
			'Track gift card usage and balances',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Per Product Shipping',
		slug: 'woocommerce-per-product-shipping',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2719,
		monthly: 8.25,
		yearly: 99,
		description:
			'Define separate shipping costs per product which are combined at checkout to provide a total shipping cost.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/per-product-shipping/',
		benefits: [
			'Set unique shipping costs for individual products',
			'Customize shipping rates based on product characteristics',
			'Define shipping costs at the product level',
			'Override global shipping settings for specific products',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Product CSV Import Suite',
		slug: 'woocommerce-product-csv-import-suite',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2720,
		monthly: 4.92,
		yearly: 59,
		description:
			'Import, merge, and export products and variations to and from WooCommerce using a CSV file.',
		categories: [ 'Store management' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/product-csv-import-suite/',
		benefits: [
			'Bulk import/export products via CSV',
			'Easily manage large product catalogs',
			'Map CSV columns to product fields',
			'Schedule automated imports/exports',
			'Handle complex product types including variable products',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Product Recommendations',
		slug: 'woocommerce-product-recommendations',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2721,
		monthly: 8.25,
		yearly: 99,
		description:
			'Offer smarter upsells, cross-sells, and frequently bought together recommendations. Use analytics to measure their impact and optimize your strategies.',
		categories: [ 'Conversion' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/product-recommendations/',
		benefits: [
			'Display personalized product recommendations',
			'Increase average order value with targeted suggestions',
			'Use AI-powered algorithms for smart recommendations',
			'Place recommendation widgets on various store pages',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Product Vendors',
		slug: 'woocommerce-product-vendors',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2722,
		monthly: 9.92,
		yearly: 119,
		description:
			'Turn your store into a multi-vendor marketplace. Allow multiple vendors to sell via your site and in return take a commission on sales.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/product-vendors/',
		benefits: [
			'Create a multi-vendor marketplace',
			'Allow multiple sellers on a single WooCommerce store',
			'Manage vendor accounts and commissions',
			'Set up individual vendor storefronts',
			'Automate commission calculations and payouts',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Returns and Warranty Requests',
		slug: 'woocommerce-returns-warranty-requests',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2723,
		monthly: 8.25,
		yearly: 99,
		description:
			'Manage the RMA process, add warranties to products, and let customers request and manage returns/exchanges from their account.',
		categories: [ 'Customer service' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/warranty-requests/',
		benefits: [
			'Streamline returns and warranty claim process',
			'Manage customer service requests efficiently',
			'Create custom return/warranty forms',
			'Automate return approval processes',
			'Generate return labels and track return shipments',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Subscription Downloads',
		slug: 'woocommerce-subscription-downloads',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2724,
		monthly: 4.92,
		yearly: 59,
		description:
			'Offer additional downloads to your subscribers, via downloadable products listed in your store.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-subscription-downloads/',
		benefits: [
			'Offer downloadable content on a subscription basis',
			'Control access to files based on subscription status',
			'Set download limits and expiration dates',
			'Integrate with membership plugins for advanced access control',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Shipment Tracking',
		slug: 'woocommerce-shipment-tracking',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2725,
		monthly: 4.92,
		yearly: 59,
		description: 'Add shipment tracking information to your orders.',
		categories: [ 'Customer service' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/shipment-tracking/',
		benefits: [
			'Add shipment tracking information to orders',
			'Keep customers informed about order status and delivery',
			'Integrate with major shipping carriers',
			'Automatically send tracking emails to customers',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Shipping Multiple Addresses',
		slug: 'woocommerce-shipping-multiple-addresses',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2726,
		monthly: 4.92,
		yearly: 59,
		description:
			'Allow your customers to ship individual items in a single order to multiple addresses.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/shipping-multiple-addresses/',
		benefits: [
			'Allow customers to ship items to multiple addresses in one order',
			'Set up different shipping methods for each address',
			'Calculate shipping costs separately for each destination',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Table Rate Shipping',
		slug: 'woocommerce-table-rate-shipping',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2728,
		monthly: 9.92,
		yearly: 119,
		description:
			"The Table Rate shipping module extends WooCommerce's default shipping options giving you highly customisable shipping options.",
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/table-rate-shipping/',
		benefits: [
			'Create complex shipping rules based on various factors',
			'Offer flexible shipping rates tailored to specific needs',
			'Set up shipping zones with custom rates',
			'Use conditions like weight, price, item count, or shipping class',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Additional Variation Images',
		slug: 'woocommerce-additional-image-variations',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2729,
		monthly: 4.92,
		yearly: 59,
		description: 'Unlimited images for your product variations.',
		categories: [ 'Store content' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-additional-variation-images/',
		benefits: [
			'Add multiple images for product variations',
			'Improve product presentation for variable products',
			'Display variation-specific image galleries',
			'Easily manage variation images from the product editor',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Bookings Availability',
		slug: 'woocommerce-bookings-availability',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2730,
		monthly: 4.92,
		yearly: 59,
		description:
			'Sell more bookings by presenting a calendar or schedule of available slots in a page or post.',
		categories: [ 'Store content' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-bookings-availability/',
		benefits: [
			'Display availability calendars for bookable products',
			'Manage capacity and scheduling for services or rentals',
			'Set up complex availability rules',
			'Allow customers to check real-time availability',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Box Office',
		slug: 'woocommerce-box-office',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2731,
		monthly: 10.75,
		yearly: 129,
		description:
			'Sell tickets for your next event, concert, function, fundraiser or conference directly on your own site.',
		categories: [ 'Store content' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-box-office/',
		benefits: [
			'Sell tickets for events',
			'Manage attendee information and check-ins',
			'Create printable or digital tickets',
			'Set up seating charts and ticket types',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Coupon Campaigns',
		slug: 'woocommerce-coupon-campaigns',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2733,
		monthly: 4.08,
		yearly: 49,
		description:
			'Categorize coupons within coupon campaigns, making it easier to track the performance of a collection of coupons.',
		categories: [ 'Conversion' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-coupon-campaigns/',
		benefits: [
			'Create and manage advanced coupon campaigns',
			'Boost sales with targeted promotions',
			'Set up time-limited or usage-limited coupons',
			'Create bulk coupon codes for mass distribution',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Deposits',
		slug: 'woocommerce-deposits',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2734,
		monthly: 18.25,
		yearly: 219,
		description:
			'Enable custom payment schedules with WooCommerce Deposits. Accept payments as deposits, layaway plans, or any desired payment structure.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-deposits/',
		benefits: [
			'Allow customers to pay deposits on orders',
			'Manage partial payments and payment plans',
			'Set up fixed or percentage-based deposits',
			'Configure automatic billing for remaining balances',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Distance Rate Shipping',
		slug: 'woocommerce-distance-rate-shipping',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2735,
		monthly: 8.25,
		yearly: 99,
		description:
			'WooCommerce Distance Rate shipping allows you to charge shipping rates based on the distance or total travel time to your customers as well as charge based on weight, total value or number of items in cart.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-distance-rate-shipping/',
		benefits: [
			'Calculate shipping rates based on distance',
			'Offer location-based shipping costs',
			'Integrate with mapping services for distance calculation',
			'Set up distance-based pricing tiers',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce One Page Checkout',
		slug: 'woocommerce-one-page-checkout',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2736,
		monthly: 6.58,
		yearly: 79,
		description:
			'Create special pages where customers can choose products, checkout & pay all on the one page.',
		categories: [ 'Store content' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-one-page-checkout/',
		benefits: [
			'Streamline checkout process to a single page',
			'Improve conversion rates with simplified purchasing',
			'Customize checkout page layout',
			'Add product selection directly to the checkout page',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Order Barcodes',
		slug: 'woocommerce-order-barcodes',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2737,
		monthly: 8.25,
		yearly: 99,
		description:
			'Generates a unique barcode for each order on your site perfect for e-tickets, packing slips, reservations and a variety of other uses.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-order-barcodes/',
		benefits: [
			'Generate barcodes for orders',
			'Simplify order processing and tracking',
			'Print barcodes on packing slips or labels',
			'Scan barcodes to quickly access order details',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Points and Rewards',
		slug: 'woocommerce-points-and-rewards',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2738,
		monthly: 14.92,
		yearly: 179,
		description:
			'Reward your customers for purchases and other actions with points which can be redeemed for discounts.',
		categories: [ 'Conversion' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-points-and-rewards/',
		benefits: [
			'Implement a customer loyalty program',
			'Reward customers with points for purchases and actions',
			'Set up point earning and redemption rules',
			'Create tiered reward levels for VIP customers',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Pre-Orders',
		slug: 'woocommerce-pre-orders',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2739,
		monthly: 14.92,
		yearly: 179,
		description: 'Allow customers to order products before they are available.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-pre-orders/',
		benefits: [
			'Allow customers to pre-order upcoming products',
			'Manage and fulfill pre-orders efficiently',
			'Set release dates and charge options',
			'Automatically update order status on release date',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Purchase Order Gateway',
		slug: 'woocommerce-purchase-order-gateway',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2740,
		monthly: 4.08,
		yearly: 49,
		description: 'Seamlessly accept purchase orders as a payment method on your WooCommerce store.',
		categories: [ 'Merchandising' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-gateway-purchase-order/',
		benefits: [
			'Accept purchase orders as a payment method',
			'Cater to B2B customers with specific payment needs',
			'Set up custom approval processes for purchase orders',
			'Generate invoices for approved purchase orders',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Shipping',
		slug: 'woocommerce-shipping',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2741,
		monthly: 0,
		yearly: 0,
		description:
			'Print USPS and DHL labels right from your WooCommerce dashboard and instantly save on shipping. WooCommerce Shipping is free to use and saves you time and money.',
		categories: [ 'Shipping' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/shipping/',
		benefits: [
			'Print USPS and DHL labels',
			'Streamline shipping process with carrier integration',
			'Compare rates from multiple carriers',
			'Automatically mark orders as completed upon shipping',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Accommodations Bookings',
		slug: 'woocommerce-accommodations-bookings',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2742,
		monthly: 0,
		yearly: 0,
		description: 'Book accommodation using WooCommerce and the WooCommerce Bookings extension.',
		categories: [ 'Store content' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-accommodation-bookings/',
		benefits: [
			'Manage bookings for accommodations',
			'Handle reservations for hotels, rentals, etc',
			'Set up room types and rates',
			'Manage seasonal pricing and availability',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooCommerce Tax',
		slug: 'woocommerce-tax',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2743,
		monthly: 0,
		yearly: 0,
		description:
			'Automatically calculate how much sales tax should be collected for WooCommerce orders — by city, country, or state — at checkout.',
		categories: [ 'Store management' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/tax/',
		benefits: [
			'Automate sales tax calculations',
			'Ensure compliance with tax regulations',
			'Integrate with major tax calculation services',
			'Generate tax reports for easy filing',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'WooPayments',
		slug: 'woocommerce-woopayments',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2744,
		monthly: 0,
		yearly: 0,
		description:
			'The only payment solution fully integrated to Woo. Accept credit/debit cards and local payment options with no setup or monthly fees.',
		categories: [ 'Payments', 'Store management' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-payments/',
		benefits: [
			'WooPayments is available {{a}}in 38 countries{{/a}} and accepts payments in 135+ currencies, no other extensions needed.',
			'Get started for free. Pay-as-you-go fees per transaction. There are no monthly fees, either. {{a}}Learn more about our fees{{/a}}.',
			'Try Tap to Pay or {{OrderCardReaderLink}}order a card reader{{/OrderCardReaderLink}} that syncs with your inventory through WooPayments. {{LearnMoreLink}}Learn more about Tap to Pay on iPhone and Android{{/LearnMoreLink}}.',
			'Multi-Currency support is built-in. Accept payments in 135+ currencies using WooPayments.',
			'Increase conversions by enabling payment methods including {{WooPayLink}}WooPay{{/WooPayLink}}, {{ApplePayLink}}Apple Pay®{{/ApplePayLink}}, {{GooglePayLink}}Google Pay{{/GooglePayLink}}, {{IDealLink}}iDeal{{/IDealLink}}, {{P24Link}}P24{{/P24Link}}, {{EPSLink}}EPS{{/EPSLink}}, and {{BancontactLink}}Bancontact{{/BancontactLink}}.',
			'Enable buy now, pay later (BNPL) in one click. Sell more and reach new customers with {{a}}top BNPL options{{/a}} built into your dashboard (not available in all geographies).',
			"Simplify your workflow. No more logging into third-party payment processor sites - manage everything from the comfort of your store's dashboard.",
			'Set a custom payout schedule to get your funds into your bank account as often as you need — daily, weekly, monthly, or even on-demand.',
			'Reduce cart abandonment with a streamlined checkout flow.',
			'Stay on top of chargebacks, disputes, and refunds thanks to the integrated dashboard.',
			'Stay on top of chargebacks, disputes, and refunds thanks to the integrated dashboard.',
		],
		greatFor: [],
	},
	{
		name: 'WooCommerce Product Filters',
		slug: 'woocommerce-product-filters',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2745,
		monthly: 6.59,
		yearly: 79.08,
		description:
			'This is a tool to create ajax product filters that make the process of finding products in your store simple and fast.',
		categories: [],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/product-filters/',
		benefits: [
			'Create ajax product filters for quick and simple product search',
			'Filter by categories, attributes, tags, taxonomies, price, and stock status',
			'Use AJAX technology for fast filtering without page reloads',
			'Offer multiple filter elements: price slider, checkbox list, radio list, dropdown, color list, box list, text list, and more',
			'Provide widgets for "Products Filter" and "Notes for Product Filters"',
			'Include shortcodes and integration with product shortcodes',
			'Feature adaptive filter options and product counts',
			'Display adaptive product thumbnails',
			'Easy 5-minute setup for beginners and developers',
			'Improve user experience by helping customers find products quickly',
			'Increase sales by directing customers to desired products',
			'Allow expansion of inventory without confusing customers',
			'Potentially boost SEO when implemented correctly',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Constellation',
		slug: 'woocommerce-constellation',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2746,
		monthly: 20.75,
		yearly: 249,
		description:
			'A flexible, WooCommerce memberships platform to support publishers, purchasing clubs, online learning, associations, and more.',
		categories: [],
		vendorName: 'Kestrel',
		vendorUrl: 'https://woocommerce.com/vendor/kestrel/',
		wooUrl: 'https://woocommerce.com/products/constellation/',
		benefits: [
			'Integrates seamlessly with WooCommerce to manage memberships, offering perks like exclusive content and discounts.',
			'Supports publishers, purchasing clubs, online learning, associations, and more.',
			'Offers one-time payments, recurring billing, and free trials to suit various business models.',
			'Schedules access to content over time, enhancing member engagement and retention.',
			'Allows unlimited membership plans and unlimited members without restrictions.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Rental Products',
		slug: 'woocommerce-rental-products',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2747,
		monthly: 15.75,
		yearly: 189,
		description: 'Sell rental products in your store, manage rental orders and more.',
		categories: [],
		vendorName: 'Kestrel',
		vendorUrl: 'https://woocommerce.com/vendor/kestrel/',
		wooUrl: 'https://woocommerce.com/products/rental-products/',
		benefits: [
			'Enables the sale and management of rental products with advanced pricing, availability, and deposit options.',
			'Allows customers to select rental dates via a calendar, calculate costs, and add items to their cart.',
			'Provides a rentals dashboard with summaries, calendars, inventory management, and tools for efficient oversight.',
			'Sends return reminder emails to customers, ensuring timely returns and improved inventory management.',
			'Supports both shipped rentals and in-person pick-up/returns, accommodating various business models.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Smart Coupons',
		slug: 'woocommerce-smart-coupons',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2748,
		monthly: 10.75,
		yearly: 129,
		description:
			'Boost sales and customer loyalty. Create advanced discounts, sell gift cards, set BOGO deals, give store credits, and all types of rule based dynamic discounts with this all-in-one Smart Coupons plugin for WooCommerce.',
		categories: [],
		vendorName: 'StoreApps',
		vendorUrl: 'https://woocommerce.com/vendor/storeapps/',
		wooUrl: 'https://woocommerce.com/products/smart-coupons/',
		benefits: [
			'Creates dynamic pricing rules, bulk discounts, and percentage-based offers to boost sales.',
			'Sells gift cards with scheduling options, enhancing customer loyalty and increasing revenue.',
			'Easily sets up "Buy One, Get One" promotions and offers free gifts based on customizable rules.',
			'Generates, exports, and emails thousands of unique coupon codes efficiently.',
			'Creates shareable links that auto-apply discounts, simplifying the customer experience and increasing conversions.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Dynamic Pricing',
		slug: 'woocommerce-dynamic-pricing',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2749,
		monthly: 10.75,
		yearly: 129,
		description: 'Bulk discounts, role-based pricing and much more.',
		categories: [],
		vendorName: 'Element Stark',
		vendorUrl: 'https://woocommerce.com/vendor/element-stark/',
		wooUrl: 'https://woocommerce.com/products/dynamic-pricing/',
		benefits: [
			'Sets up bulk discounts for products with flexible pricing adjustments, including fixed or percentage.',
			'Offers discounts based on user roles, allowing for targeted pricing strategies for different customer segments.',
			'Applies bulk discounts across entire product categories, streamlining promotional efforts.',
			'Allows custom quantity calculations for pricing rules, accommodating various sales strategies.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Variation Swatches and Photos',
		slug: 'woocommerce-variation-swatches-and-photos',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2750,
		monthly: 8.25,
		yearly: 99,
		description: 'Show color and image swatches instead of dropdowns for variable products.',
		categories: [],
		vendorName: 'Element Stark',
		vendorUrl: 'https://woocommerce.com/vendor/element-stark/',
		wooUrl: 'https://woocommerce.com/products/variation-swatches-and-photos/',
		benefits: [
			'Replaces dropdowns with color and image swatches, providing a more intuitive and visually appealing shopping experience.',
			'Defines colors and images at both attribute and product levels, offering flexibility in product display.',
			'Allows customers to view product variations more clearly, aiding in decision-making and reducing return rates.',
			'Integrates smoothly with WooCommerce, ensuring compatibility and ease of use.',
			'Enhances product listings by showcasing variations in color, size, style, or any other attribute.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Afterpay for WooCommerce',
		slug: 'woocommerce-afterpay',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2751,
		monthly: null,
		yearly: 0,
		description:
			'Afterpay allows customers to purchase products and choose to pay in four installments over six weeks or pay monthly (US only).',
		categories: [ 'Payments' ],
		vendorName: 'Afterpay',
		vendorUrl: 'https://woocommerce.com/vendor/afterpay/',
		wooUrl: 'https://woocommerce.com/products/afterpay/',
		benefits: [
			'Attract millions of millennial and Gen Z shoppers by adding Afterpay as a payment method, allowing them to pay in 4 installments over 6 weeks, interest-free.',
			'Get paid upfront, with payments processed quickly so you can focus on growing your business.',
			'Afterpay takes on all customer fraud risk, minimizing your financial exposure while you fulfill orders.',
			'Express Checkout reduces checkout steps, streamlining the buying process for higher conversions and improved customer experience.',
			"Access the Afterpay Business Hub for deep performance insights, daily settlement reports, and marketing best practices to optimize your store's growth.",
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Square for WooCommerce',
		slug: 'woocommerce-square',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2753,
		monthly: null,
		yearly: 0,
		description:
			'Accepting payments is easy with Square. Clear rates, fast deposits (1-2 business days). Sell online and in person, and sync all payments, items and inventory.',
		categories: [ 'Payments' ],
		vendorName: 'Woo',
		vendorUrl: 'https://woocommerce.com/',
		wooUrl: 'https://woocommerce.com/products/square/',
		benefits: [
			'Accept payments online and in-person, allowing flexibility for your customers to pay anytime, anywhere.',
			'Automatic product and inventory synchronization between WooCommerce and Square to prevent overselling and streamline operations.',
			'Supports a variety of payment methods including credit/debit cards, digital wallets (Apple Pay/Google Pay), Square Gift Cards, and Cash App for diverse customer preferences.',
			'Ensures secure payment processing with end-to-end encryption, PCI compliance, and fraud detection measures.',
			'Offers fast deposits, with options for instant funding or customizable close-of-day schedules, improving cash flow for your business.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Affirm Payments for WooCommerce',
		slug: 'woocommerce-affirm',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2755,
		monthly: null,
		yearly: 0,
		description:
			'Buy now, pay later for your business—but smarter. Increase conversions and AOV by offering shoppers flexible payment plans from Affirm.',
		categories: [ 'Payments' ],
		vendorName: 'Affirm',
		vendorUrl: 'https://woocommerce.com/vendor/affirm/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-gateway-affirm/',
		benefits: [
			'Flexible payment options allowing customers to choose interest-free payment plans such as 30 days, 4 payments every 2 weeks, or longer terms up to 36 months.',
			'Immediate payment to merchants upon purchase completion, enhancing cash flow and reducing payment collection anxiety.',
			'Access to a broad network of high-value shoppers who can afford to transact, accelerating customer acquisition.',
			'Transparent financing with no hidden fees, late charges, or surprises, fostering customer trust and satisfaction.',
			'Customizable promotional messaging settings to align Affirm as a preferred payment method on various pages, enhancing visibility during checkout.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Mollie Payments for WooCommerce',
		slug: 'woocommerce-mollie',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2757,
		monthly: null,
		yearly: 0,
		description:
			'Offer global and local payment methods and get onboarded in minutes, with support in your language.',
		categories: [ 'Payments' ],
		vendorName: 'Mollie',
		vendorUrl: 'https://woocommerce.com/vendor/mollie/',
		wooUrl: 'https://woocommerce.com/products/mollie-payments-for-woocommerce/',
		benefits: [
			'Customizable checkout options to optimize conversions and create a seamless customer journey.',
			'Supports a wide range of local and global payment methods including credit cards, iDEAL, Apple Pay, and more.',
			'Simplified management of subscriptions with integration for recurring payments through various payment methods.',
			'Easy refund process for both full and partial refunds, enhancing customer satisfaction.',
			'Transparent pricing model, charging only for successful transactions, ensuring cost-effectiveness for your business.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Stripe for WooCommerce',
		slug: 'woocommerce-stripe',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2759,
		monthly: null,
		yearly: 0,
		description: 'Maximize revenue with the new checkout from Stripe.',
		categories: [ 'Payments' ],
		vendorName: 'Stripe',
		vendorUrl: 'https://woocommerce.com/vendor/stripe/',
		wooUrl: 'https://woocommerce.com/products/stripe/',
		benefits: [
			'Optimized checkout experience across mobile, tablet, and desktop to boost conversion rates.',
			'Supports a wide range of payment methods, including credit/debit cards, buy now pay later options, and local payment methods to expand the customer base.',
			'Integrated fraud detection with Stripe Radar to identify and flag potentially fraudulent transactions.',
			'Ability to accept in-person payments using Stripe Terminal or Tap to Pay technology on mobile devices.',
			'Quick access to funds with Stripe Instant Payouts feature, allowing eligible businesses to get paid within minutes.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Klarna for WooCommerce',
		slug: 'woocommerce-klarna',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2761,
		monthly: null,
		yearly: 0,
		description:
			'Grow your business with increased sales and an enhanced shopping experience — at no extra cost.',
		categories: [ 'Payments' ],
		vendorName: 'Klarna',
		vendorUrl: 'https://woocommerce.com/vendor/klarna/',
		wooUrl: 'https://woocommerce.com/products/klarna-payments/',
		benefits: [
			'Flexible payment options such as Pay in Full, Buy Now Pay Later, and Pay in N allow customers to choose their preferred method of payment.',
			'Offers long-term financing options with monthly payments for larger purchases, available in various terms (6, 12, 18, and 24 months).',
			'Express checkout feature provides a 5x faster checkout process, reducing friction for customers during purchase.',
			'On-site messaging enhances the shopping experience with personalized communication, potentially increasing conversion rates.',
			'Klarna payments ensure merchants receive their funds immediately, while offering customers the flexibility to pay later.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'PayPal Payments for WooCommerce',
		slug: 'woocommerce-paypal',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2763,
		monthly: null,
		yearly: 0,
		description:
			'PayPal’s brand recognition helps give customers the confidence to buy. PayPal’s all-in-one checkout solution allows you to offer PayPal, Venmo (US), Pay Later, credit and debit cards, country-specific payment options and more.',
		categories: [ 'Payments' ],
		vendorName: 'PayPal',
		vendorUrl: 'https://woocommerce.com/vendor/paypal/',
		wooUrl: 'https://woocommerce.com/products/woocommerce-paypal-payments/',
		benefits: [
			'All-in-one checkout solution that integrates PayPal, Venmo (US only), and Pay Later options to maximize conversion rates.',
			'Automatically offers PayPal buttons on product pages and at checkout, significantly increasing the likelihood of completing a purchase.',
			'Enables customers to pay in installments with Pay Later options, boosting cart size by 35% compared to standard transactions.',
			'Fast and simple guest checkout feature allows for autofill of details for millions of guest shoppers, increasing conversion rates up to 80%.',
			'Provides various card processing capabilities including Standard and Advanced options to meet different business needs while ensuring compliance and fraud protection.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
	{
		name: 'Klaviyo for WooCommerce',
		slug: 'woocommerce-klaviyo',
		family: 'woocommerce-products',
		kind: 'extension',
		productId: 2765,
		monthly: null,
		yearly: 0,
		description:
			'As Woo’s preferred marketing automation platform, Klaviyo unifies email and SMS marketing, customer analytics, and product reviews to help your brand achieve better marketing ROI.',
		categories: [ 'Conversion' ],
		vendorName: 'Klaviyo',
		vendorUrl: 'https://woocommerce.com/vendor/klaviyo/',
		wooUrl: 'https://woocommerce.com/products/klaviyo-for-woocommerce/',
		benefits: [
			'Compatible with the new Cart and Checkout blocks for a customizable, conversion-optimized checkout experience.',
			'Comprehensive marketing automation tools to engage customers and drive revenue through real-time data and AI.',
			'Advanced email and SMS marketing features for immediate sales and lasting customer loyalty.',
			'Robust data-driven insights from 350+ integrations to empower store and customer data management.',
			'Flexible segmentation and automated flows for personalized marketing experiences that enhance conversion rates.',
		],
		greatFor: [ 'WooCommerce stores' ],
	},
];

export const KIND_LABEL: Record< ProductKind, string > = {
	plan: 'Plan',
	product: 'Product',
	'add-on': 'Add-on',
	extension: 'Extension',
};

/** Main's featured list, in its order ("hardcoded until we understand how we want to pick featured products"). */
export const FEATURED_SLUGS = [
	'woocommerce-woopayments',
	'woocommerce-constellation',
	'woocommerce-dynamic-pricing',
	'woocommerce-rental-products',
	'woocommerce-smart-coupons',
	'woocommerce-variation-swatches-and-photos',
];

/** Main's custom featured card for WooPayments (title + description verbatim). */
export const WOOPAYMENTS_CARD = {
	slug: 'woocommerce-woopayments',
	title: 'Revenue share available',
	description:
		"Accept credit/debit cards and local payment options with no setup or monthly fees. Earn revenue share on transactions from your clients' sites within Automattic for Agencies.",
};

/** Main strips the vendor prefix from card titles. */
export function shortTitle( product: CatalogProduct ): string {
	return product.name.replace( /^WooCommerce /, '' );
}

/**
 * Price display for the chosen term, in the "monthly equivalent, billed
 * annually" pattern: the number is always per month (annual ÷ 12), and the
 * note carries the cadence. `charge` is what actually gets billed per term,
 * for the cart. Products sold on one term only (the backup storage add-ons
 * are monthly-only) fall back to the term they have and say so.
 */
export function priceFor(
	product: CatalogProduct,
	term: 'monthly' | 'yearly'
): { price: number; charge: number; interval: string; note: string } {
	const yearly = product.yearly;
	const monthly = product.monthly;
	if ( term === 'yearly' && yearly !== null ) {
		return { price: yearly / 12, charge: yearly, interval: '/month', note: 'billed annually' };
	}
	if ( monthly !== null ) {
		return { price: monthly, charge: monthly, interval: '/month', note: 'billed monthly' };
	}
	return {
		price: ( yearly ?? 0 ) / 12,
		charge: yearly ?? 0,
		interval: '/month',
		note: 'billed annually',
	};
}

/** Referral commission on Jetpack and Woo products (getProductCommissionPercentage). */
export const PRODUCT_REFERRAL_COMMISSION_RATE = 0.5;
