const root = 'https://support.wordpress.com';

export default {
	ACCOUNT_RECOVERY: `${ root }/account-recovery`,
	ADDING_GOOGLE_APPS_TO_YOUR_SITE: `${ root }/adding-g-suite-to-your-site`,
	ADDING_USERS: `${ root }/adding-users`,
	ALL_ABOUT_DOMAINS: `${ root }/all-about-domains`,
	AUTO_RENEWAL: `${ root }/auto-renewal`,
	BANDPAGE_WIDGET: `${ root }/widgets/bandpage-widget`,
	CATEGORIES_VS_TAGS: `${ root }/posts/categories-vs-tags`,
	CHANGE_NAME_SERVERS: `${ root }/domains/change-name-servers`,
	CHANGE_NAME_SERVERS_FINDING_OUT_NEW_NS: `${ root }/domains/change-name-servers/#finding-out-your-new-name-server`,
	COMMENTS: `${ root }/category/comments`,
	COMMUNITY_TRANSLATOR: `${ root }/community-translator`,
	COMPLETING_GOOGLE_APPS_SIGNUP: `${ root }/adding-g-suite-to-your-site/#completing-sign-up`,
	CONNECT: `${ root }/connect`,
	CONTACT: `${ root }/contact`,
	CALYPSO_CONTACT: '/help/contact',
	CALYPSO_COURSES: '/help/courses',
	CREATE: `${ root }/create`,
	CUSTOM_DNS: `${ root }/domains/custom-dns`,
	DESIGNATED_AGENT: `${ root }/designated-agent/`,
	DOMAIN_HELPER_PREFIX: `${ root }/domain-helper/?host=`,
	DOMAIN_REGISTRATION_AGREEMENTS: `${ root }/domain-registration-agreements/`,
	DOMAINS: `${ root }/domains`,
	EMAIL_FORWARDING: `${ root }/email-forwarding`,
	EMAIL_VALIDATION_AND_VERIFICATION: `${ root }/domains/register-domain/#email-validation-and-verification`,
	EMPTY_SITE: `${ root }/empty-site/`,
	ENABLE_DISABLE_COMMENTS: `${ root }/enable-disable-comments`,
	EVENTBRITE: `${ root }/eventbrite`,
	EVENTBRITE_EVENT_CALENDARLISTING_WIDGET: `${ root }/widgets/eventbrite-event-calendarlisting-widget`,
	EXPORT: `${ root }/export`,
	FACEBOOK_EMBEDS: `${ root }/facebook-integration/facebook-embeds`,
	FACEBOOK_LIKE_BOX: `${ root }/facebook-integration/#facebook-like-box`,
	FOLLOWERS: `${ root }/followers`,
	GETTING_MORE_VIEWS_AND_TRAFFIC: `${ root }/getting-more-views-and-traffic`,
	GOOGLE_ANALYTICS: `${ root }/google-analytics`,
	GOOGLE_APPS_LEARNING_CENTER: 'https://gsuite.google.com/learning-center/',
	GOOGLE_PLUS_EMBEDS: `${ root }/google-plus-embeds`,
	GRAVATAR_HOVERCARDS: `${ root }/gravatar-hovercards`,
	GUIDED_TRANSFER: `${ root }/guided-transfer`,
	IMPORT: `${ root }/import`,
	INSTAGRAM_WIDGET: `${ root }/instagram/instagram-widget`,
	JETPACK_SUPPORT: 'https://jetpack.com/support/',
	JETPACK_CONTACT_SUPPORT: 'https://jetpack.com/contact-support/',
	JETPACK_SERVICE_VAULTPRESS: 'https://help.vaultpress.com/',
	JETPACK_SERVICE_AKISMET: 'https://akismet.com/support/',
	JETPACK_SERVICE_POLLDADDY: 'https://support.polldaddy.com/',
	LIVE_CHAT: `${ root }/live-chat`,
	MANAGE_PURCHASES: `${ root }/manage-purchases`,
	MAP_EXISTING_DOMAIN: `${ root }/domains/map-existing-domain`,
	MAP_EXISTING_DOMAIN_UPDATE_DNS: `${ root }/domains/map-existing-domain#2-ask-your-domain-provider-to-update-your-dns-settings`,
	MAP_SUBDOMAIN: `${ root }/domains/map-subdomain`,
	MEDIA: `${ root }/media`,
	PUBLICIZE: `${ root }/publicize`,
	PUBLIC_VS_PRIVATE: `${ root }/domains/register-domain/#public-versus-private`,
	REFUNDS: `${ root }/refunds`,
	REGISTER_DOMAIN: `${ root }/domains/register-domain/`,
	SEO_TAGS: `${ root }/getting-more-views-and-traffic/#use-appropriate-tags`,
	SETTING_PRIMARY_DOMAIN: `${ root }/domains/#setting-the-primary-domain`,
	SETTING_UP_PREMIUM_SERVICES: `${ root }/setting-up-premium-services`,
	STRONG_PASSWORD: `${ root }/selecting-a-strong-password/`,
	SHARING: `${ root }/sharing`,
	START: `${ root }/start`,
	STATS_CLICKS: `${ root }/stats/#clicks`,
	STATS_REFERRERS: `${ root }/stats/#referrers`,
	STATS_SEO_TERMS: `${ root }/stats/#search-engine-terms`,
	STATS_SPAM_REFERRER: `${ root }/stats/#marking-spam-referrers`,
	STATS_TOP_POSTS_PAGES: `${ root }/stats/#top-posts-pages`,
	STATS_VIEWS_BY_COUNTRY: `${ root }/stats/#views-by-country`,
	SUPPORT_ROOT: `${ root }/`,
	TRANSFER_DOMAIN_REGISTRATION: `${ root }/transfer-domain-registration`,
	TWITTER_TIMELINE_WIDGET: `${ root }/widgets/twitter-timeline-widget`,
	UPDATE_CONTACT_INFORMATION: `${ root }/update-contact-information/`,
	UPDATE_NAMESERVERS: `${ root }/domains/domain-management/#update-nameservers`,
	USERS: `${ root }/category/users`,
	USER_ROLES: `${ root }/user-roles`,
	VIDEOS: `${ root }/videos`
};
