/**
 * Please keep this list alphabetized!
 */
export const READER_EXPAND_CARD = 'READER_EXPAND_CARD';
export const READER_RESET_CARD_EXPANSIONS = 'READER_RESET_CARD_EXPANSIONS';
export const READER_SIDEBAR_FOLLOWING_TOGGLE = 'READER_SIDEBAR_FOLLOWING_TOGGLE';
export const READER_SIDEBAR_LISTS_TOGGLE = 'READER_SIDEBAR_LISTS_TOGGLE';
export const READER_SIDEBAR_ORGANIZATIONS_TOGGLE = 'READER_SIDEBAR_ORGANIZATIONS_TOGGLE';
export const READER_SIDEBAR_TAGS_TOGGLE = 'READER_SIDEBAR_TAGS_TOGGLE';
export const READER_SIDEBAR_SELECT_RECENT_SITE = 'READER_SIDEBAR_SELECT_RECENT_SITE';
export const READER_UNSEEN_STATUS_RECEIVE = 'READER_UNSEEN_STATUS_RECEIVE';
export const READER_UNSEEN_STATUS_REQUEST = 'READER_UNSEEN_STATUS_REQUEST';
export const READER_VIEW_STREAM = 'READER_VIEW_STREAM';
export const READER_REGISTER_LAST_ACTION_REQUIRES_LOGIN =
	'READER_REGISTER_LAST_ACTION_REQUIRES_LOGIN';
export const READER_CLEAR_LAST_ACTION_REQUIRES_LOGIN = 'READER_CLEAR_LAST_ACTION_REQUIRES_LOGIN';
