export const STATUS_UNINITIALIZED = 'STATUS_UNINITIALIZED';
export const STATUS_INITIALIZING = 'STATUS_INITIALIZING';
export const STATUS_READY = 'STATUS_READY';
export const STATUS_ERROR = 'STATUS_ERROR';
