@startuml

'red: #facfd2
'orange: #f7dcc6
'yellow: #f5e6b3
'green: #b8e6bf

skinparam ParticipantPadding 5
skinparam BoxPadding 5
box " " #f7dcc6
  participant WordPress.com
end box
box "Calypso" #f5e6b3
  participant Undocumented
end box
box "Composite Checkout" #b8e6bf
  participant useShoppingCart
  participant useCartUpdateAndRevalidate
  participant useShoppingCartReducer
  participant useShoppingCartManager
  participant ShoppingCartProvider
  participant CheckoutSystemDecider
end box

'Imports
Undocumented -> CheckoutSystemDecider : import\nsetCart
CheckoutSystemDecider -> ShoppingCartProvider : cartKey, setCart
ShoppingCartProvider -> useShoppingCartManager : cartKey, setCart
activate useShoppingCartManager
return
note over ShoppingCartProvider : manager\nstored as provider value
useShoppingCartManager -> useShoppingCartReducer
activate useShoppingCartReducer
return cacheStatus, dispatcher
useShoppingCartManager -> useCartUpdateAndRevalidate : cacheStatus, dispatcher
hnote over useCartUpdateAndRevalidate
	cacheStatus => 'invalid'
end hnote
useCartUpdateAndRevalidate -> useShoppingCartReducer : dispatch\nREQUEST_UPDATED_RESPONSE_CART
note over useShoppingCartReducer
	cacheStatus: 'pending'
end note
useShoppingCartReducer -> useShoppingCartManager : cacheStatus
...set cart asynchronously...
useCartUpdateAndRevalidate -> Undocumented : << setCart >>
activate Undocumented
Undocumented -> WordPress.com : POST\n/me/shopping-cart/{cartKey}
activate WordPress.com
'Explain renewal flags
note over WordPress.com
	May be passed:

	{ extra: {
		purchaseType: 'renewal'
	} }
end note
return
return
useCartUpdateAndRevalidate -> useShoppingCartReducer : dispatch\nRECEIVE_UPDATED_RESPONSE_CART
note over useShoppingCartReducer
	cacheStatus: 'valid'
end note
useShoppingCartReducer -> useShoppingCartManager : cacheStatus\nresponseCart
useShoppingCartManager -> ShoppingCartProvider
note over ShoppingCartProvider
	stored manager is updated
end note
ShoppingCartProvider -> useShoppingCart

@enduml
