import {
	PLAN_JETPACK_COMPLETE,
	PLAN_JETPACK_COMPLETE_MONTHLY,
	PLAN_JETPACK_SECURITY_REALTIME,
	PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
	PLAN_JETPACK_SECURITY_DAILY,
	PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
} from '@automattic/api-core';

/**
 * Matrix of available dowgradable plans for each plan.
 */
//used
export const DOWNGRADEABLE_PLANS_FROM_PLAN: Record< string, string[] > = {
	[ PLAN_JETPACK_SECURITY_DAILY_MONTHLY ]: [],
	[ PLAN_JETPACK_SECURITY_DAILY ]: [ PLAN_JETPACK_SECURITY_DAILY_MONTHLY ],
	[ PLAN_JETPACK_SECURITY_REALTIME_MONTHLY ]: [
		PLAN_JETPACK_SECURITY_DAILY,
		PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
	[ PLAN_JETPACK_SECURITY_REALTIME ]: [
		PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
		PLAN_JETPACK_SECURITY_DAILY,
		PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
	[ PLAN_JETPACK_COMPLETE ]: [
		PLAN_JETPACK_COMPLETE_MONTHLY,
		PLAN_JETPACK_SECURITY_REALTIME,
		PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
		PLAN_JETPACK_SECURITY_DAILY,
		PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
	[ PLAN_JETPACK_COMPLETE_MONTHLY ]: [
		PLAN_JETPACK_SECURITY_REALTIME,
		PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
		PLAN_JETPACK_SECURITY_DAILY,
		PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
};
