import { JetpackPlans } from '@automattic/api-core';

/**
 * Matrix of available dowgradable plans for each plan.
 */
export const DOWNGRADEABLE_PLANS_FROM_PLAN: Record< string, string[] > = {
	[ JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY ]: [],
	[ JetpackPlans.PLAN_JETPACK_SECURITY_DAILY ]: [
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
	[ JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME_MONTHLY ]: [
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY,
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
	[ JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME ]: [
		JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY,
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
	[ JetpackPlans.PLAN_JETPACK_COMPLETE ]: [
		JetpackPlans.PLAN_JETPACK_COMPLETE_MONTHLY,
		JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME,
		JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY,
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
	[ JetpackPlans.PLAN_JETPACK_COMPLETE_MONTHLY ]: [
		JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME,
		JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY,
		JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	],
};
