import {
	JetpackPlans,
	FEATURE_13GB_STORAGE,
	FEATURE_200GB_STORAGE,
	PREMIUM_DESIGN_FOR_STORES,
	FEATURE_3GB_STORAGE,
	FEATURE_1GB_STORAGE,
	FEATURE_50GB_STORAGE,
	FEATURE_6GB_STORAGE,
	FEATURE_ACCEPT_PAYMENTS,
	FEATURE_ACTIVITY_LOG,
	FEATURE_ACTIVITY_LOG_1_YEAR_V2,
	FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
	FEATURE_ADVANCED_SEO,
	FEATURE_ADVANCED_SEO_EXPANDED_ABBR,
	FEATURE_ADVANCED_SEO_TOOLS,
	FEATURE_ALL_BUSINESS_FEATURES,
	FEATURE_ALL_FREE_FEATURES,
	FEATURE_ALL_FREE_FEATURES_JETPACK,
	FEATURE_ALL_PERSONAL_FEATURES,
	FEATURE_ALL_PREMIUM_FEATURES,
	FEATURE_ALL_PREMIUM_FEATURES_JETPACK,
	FEATURE_ANTISPAM_V2,
	FEATURE_WAF,
	FEATURE_AUDIO_UPLOADS,
	FEATURE_AUTOMATED_RESTORES,
	FEATURE_AUTOMATIC_SECURITY_FIXES,
	FEATURE_BACKUP_ARCHIVE_30,
	FEATURE_BACKUP_ARCHIVE_UNLIMITED,
	FEATURE_BACKUP_DAILY_V2,
	FEATURE_BACKUP_REALTIME_V2,
	FEATURE_BACKUP_STORAGE_SPACE_UNLIMITED,
	FEATURE_BLANK,
	FEATURE_BLOG_DOMAIN,
	FEATURE_COLLECT_PAYMENTS_V2,
	FEATURE_COMMUNITY_SUPPORT,
	FEATURE_CRM_V2,
	FEATURE_CUSTOM_DOMAIN,
	FEATURE_EARN_AD,
	FEATURE_EASY_SITE_MIGRATION,
	FEATURE_ECOMMERCE_MARKETING,
	FEATURE_EMAIL_FORWARDING_EXTENDED_LIMIT,
	FEATURE_FAST_SUPPORT_FROM_EXPERTS,
	FEATURE_FREE_BLOG_DOMAIN,
	FEATURE_FREE_DOMAIN,
	FEATURE_FREE_THEMES,
	FEATURE_FREE_THEMES_SIGNUP,
	FEATURE_FREE_WORDPRESS_THEMES,
	FEATURE_GOOGLE_ANALYTICS,
	FEATURE_GOOGLE_MY_BUSINESS,
	FEATURE_HOSTING,
	FEATURE_INSTALL_PLUGINS,
	WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS,
	FEATURE_JETPACK_1TB_BACKUP_STORAGE,
	FEATURE_JETPACK_ADVANCED,
	FEATURE_JETPACK_ALL_BACKUP_SECURITY_FEATURES,
	FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
	FEATURE_JETPACK_ANTI_SPAM,
	FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
	FEATURE_JETPACK_BACKUP_DAILY,
	FEATURE_JETPACK_BACKUP_DAILY_MONTHLY,
	FEATURE_JETPACK_BACKUP_REALTIME,
	FEATURE_JETPACK_BACKUP_REALTIME_MONTHLY,
	FEATURE_JETPACK_BACKUP_T0_MONTHLY,
	FEATURE_JETPACK_BACKUP_T0_YEARLY,
	FEATURE_JETPACK_BACKUP_T1_MONTHLY,
	FEATURE_JETPACK_BACKUP_T1_YEARLY,
	FEATURE_JETPACK_BACKUP_T1_BI_YEARLY,
	FEATURE_JETPACK_BACKUP_T2_MONTHLY,
	FEATURE_JETPACK_BACKUP_T2_YEARLY,
	FEATURE_JETPACK_CRM,
	FEATURE_JETPACK_CRM_MONTHLY,
	FEATURE_JETPACK_ESSENTIAL,
	FEATURE_JETPACK_PRODUCT_BACKUP,
	FEATURE_JETPACK_PRODUCT_VIDEOPRESS,
	FEATURE_JETPACK_REAL_TIME_MALWARE_SCANNING,
	FEATURE_JETPACK_SCAN_DAILY,
	FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
	FEATURE_JETPACK_SEARCH_BI_YEARLY,
	FEATURE_JETPACK_SEARCH,
	FEATURE_JETPACK_SEARCH_MONTHLY,
	FEATURE_JETPACK_VIDEOPRESS_BI_YEARLY,
	FEATURE_JETPACK_VIDEOPRESS,
	FEATURE_JETPACK_VIDEOPRESS_MONTHLY,
	FEATURE_MALWARE_SCANNING_DAILY,
	FEATURE_MALWARE_SCANNING_DAILY_AND_ON_DEMAND,
	FEATURE_MANAGE,
	FEATURE_MEMBERSHIPS,
	FEATURE_MONETISE,
	FEATURE_NO_ADS,
	FEATURE_NO_BRANDING,
	FEATURE_OFFSITE_BACKUP_VAULTPRESS_DAILY,
	FEATURE_OFFSITE_BACKUP_VAULTPRESS_REALTIME,
	FEATURE_ONE_CLICK_THREAT_RESOLUTION,
	FEATURE_P2_13GB_STORAGE,
	FEATURE_P2_3GB_STORAGE,
	FEATURE_P2_ACTIVITY_OVERVIEW,
	FEATURE_P2_ADVANCED_SEARCH,
	FEATURE_P2_CUSTOMIZATION_OPTIONS,
	FEATURE_P2_MORE_FILE_TYPES,
	FEATURE_P2_PRIORITY_CHAT_EMAIL_SUPPORT,
	FEATURE_P2_SIMPLE_SEARCH,
	FEATURE_P2_UNLIMITED_POSTS_PAGES,
	FEATURE_P2_UNLIMITED_USERS,
	FEATURE_P2_VIDEO_SHARING,
	FEATURE_PLAN_SECURITY_DAILY,
	FEATURE_PREMIUM_CONTENT_BLOCK,
	FEATURE_PREMIUM_CUSTOMIZABE_THEMES,
	FEATURE_PREMIUM_SUPPORT,
	FEATURE_PRODUCT_BACKUP_DAILY_V2,
	FEATURE_PRODUCT_BACKUP_REALTIME_V2,
	FEATURE_PRODUCT_SCAN_DAILY_V2,
	FEATURE_PRODUCT_SCAN_REALTIME_V2,
	FEATURE_PRODUCT_SEARCH_V2,
	FEATURE_REPUBLICIZE,
	FEATURE_SCAN_V2,
	FEATURE_SEO_PREVIEW_TOOLS,
	FEATURE_SITE_STAGING_SITES,
	FEATURE_SFTP_DATABASE,
	FEATURE_SHIPPING_CARRIERS,
	FEATURE_SIMPLE_PAYMENTS,
	FEATURE_SITE_BACKUPS_AND_RESTORE,
	FEATURE_SITE_STATS,
	FEATURE_SOCIAL_MEDIA_TOOLS,
	FEATURE_SPAM_AKISMET_PLUS,
	FEATURE_STANDARD_SECURITY_TOOLS,
	FEATURE_TITAN_EMAIL,
	FEATURE_TRAFFIC_TOOLS,
	FEATURE_UNLIMITED_PRODUCTS_SERVICES,
	FEATURE_UPLOAD_PLUGINS,
	FEATURE_UPLOAD_THEMES,
	FEATURE_UPLOAD_THEMES_PLUGINS,
	FEATURE_VIDEO_UPLOADS,
	FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
	FEATURE_WORDADS_INSTANT,
	FEATURE_WP_SUBDOMAIN,
	FEATURE_WP_SUBDOMAIN_SIGNUP,
	FEATURE_UNLIMITED_ADMINS,
	FEATURE_UNLIMITED_TRAFFIC,
	FEATURE_PAYMENT_BLOCKS,
	FEATURE_WOOCOMMERCE,
	FEATURE_MANAGED_HOSTING,
	FEATURE_UNLIMITED_SUBSCRIBERS,
	FEATURE_AD_FREE_EXPERIENCE,
	FEATURE_99_999_UPTIME,
	FEATURE_STYLE_CUSTOMIZATION,
	FEATURE_PLUGINS_THEMES,
	FEATURE_WAF_V2,
	FEATURE_CDN,
	FEATURE_SECURITY_DDOS,
	FEATURE_DEV_TOOLS,
	FEATURE_DEV_TOOLS_SSH,
	FEATURE_DEV_TOOLS_GIT,
	FEATURE_SELL_SHIP,
	FEATURE_ACCEPT_PAYMENTS_V2,
	FEATURE_SALES_REPORTS,
	FEATURE_CLOUD_CRITICAL_CSS,
	FEATURE_JETPACK_SOCIAL_ADVANCED,
	FEATURE_JETPACK_SOCIAL_ADVANCED_MONTHLY,
	FEATURE_JETPACK_BOOST_BI_YEARLY,
	FEATURE_JETPACK_BOOST,
	FEATURE_JETPACK_BOOST_MONTHLY,
	FEATURE_AUTOMATED_BACKUPS_SECURITY_SCAN,
	FEATURE_INTEGRATED_SHIPMENT_TRACKING,
	FEATURE_BACK_IN_STOCK_NOTIFICATIONS,
	FEATURE_MARKETING_AUTOMATION,
	FEATURE_MIN_MAX_ORDER_QUANTITY,
	FEATURE_WOOCOMMERCE_STORE,
	FEATURE_WOOCOMMERCE_MOBILE_APP,
	FEATURE_WORDPRESS_CMS,
	FEATURE_WORDPRESS_MOBILE_APP,
	FEATURE_FREE_SSL_CERTIFICATE,
	FEATURE_GOOGLE_ANALYTICS_V3,
	FEATURE_LIST_UNLIMITED_PRODUCTS,
	FEATURE_GIFT_CARDS,
	FEATURE_PRODUCT_BUNDLES,
	FEATURE_LIST_PRODUCTS_BY_BRAND,
	FEATURE_PRODUCT_RECOMMENDATIONS,
	FEATURE_INTEGRATED_PAYMENTS,
	FEATURE_INTERNATIONAL_PAYMENTS,
	FEATURE_AUTOMATED_SALES_TAXES,
	FEATURE_ACCEPT_LOCAL_PAYMENTS,
	FEATURE_RECURRING_PAYMENTS,
	FEATURE_PROMOTE_ON_TIKTOK,
	FEATURE_SYNC_WITH_PINTEREST,
	FEATURE_CONNECT_WITH_FACEBOOK,
	FEATURE_ABANDONED_CART_RECOVERY,
	FEATURE_ADVERTISE_ON_GOOGLE,
	FEATURE_CUSTOM_ORDER_EMAILS,
	FEATURE_LIVE_SHIPPING_RATES,
	FEATURE_DISCOUNTED_SHIPPING,
	FEATURE_PRINT_SHIPPING_LABELS,
	FEATURE_PAYMENT_TRANSACTION_FEES_8,
	FEATURE_PAYMENT_TRANSACTION_FEES_4,
	FEATURE_PAYMENT_TRANSACTION_FEES_2,
	FEATURE_PAYMENT_TRANSACTION_FEES_0,
	FEATURE_PRODUCT_ADD_ONS,
	FEATURE_STATS_PAID,
	FEATURE_STATS_COMMERCIAL,
	FEATURE_JETPACK_SOCIAL_ADVANCED_BI_YEARLY,
	FEATURE_AI_ASSISTED_PRODUCT_DESCRIPTION,
	FEATURE_JETPACK_30_DAY_ARCHIVE_ACTIVITY_LOG,
	FEATURE_JETPACK_1_YEAR_ARCHIVE_ACTIVITY_LOG,
	WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED,
	WPCOM_FEATURES_BACKUPS_RESTORE,
	FEATURE_REAL_TIME_SECURITY_SCANS,
	FEATURE_SEAMLESS_STAGING_PRODUCTION_SYNCING,
	FEATURE_PRIORITY_24_7_SUPPORT,
	FEATURE_JETPACK_SOCIAL_V1_MONTHLY,
	FEATURE_WOO_AUTOMATE,
	FEATURE_WOO_SHIPPING_TRACKING,
	FEATURE_GOOGLE_LISTING_ADS,
	WPCOM_FEATURES_ATOMIC,
	WPCOM_FEATURES_SCAN,
	WPCOM_FEATURES_ANTISPAM,
	WPCOM_FEATURES_BACKUPS,
	JETPACK_LEGACY_PLANS,
	JETPACK_SECURITY_PLANS,
	PLAN_BLOGGER,
	PLAN_BLOGGER_2_YEARS,
	PLAN_BUSINESS,
	PLAN_BUSINESS_2_YEARS,
	PLAN_BUSINESS_3_YEARS,
	PLAN_100_YEARS,
	PLAN_BUSINESS_MONTHLY,
	PLAN_ECOMMERCE,
	PLAN_ECOMMERCE_2_YEARS,
	PLAN_ECOMMERCE_3_YEARS,
	PLAN_ECOMMERCE_MONTHLY,
	PLAN_ECOMMERCE_TRIAL_MONTHLY,
	PLAN_ENTERPRISE_GRID_WPCOM,
	PLAN_FREE,
	PLAN_P2_FREE,
	PLAN_P2_PLUS,
	PLAN_PERSONAL,
	PLAN_PERSONAL_2_YEARS,
	PLAN_PERSONAL_3_YEARS,
	PLAN_PERSONAL_MONTHLY,
	PLAN_PREMIUM,
	PLAN_PREMIUM_2_YEARS,
	PLAN_PREMIUM_3_YEARS,
	PLAN_PREMIUM_MONTHLY,
	PLAN_WPCOM_FLEXIBLE,
	PLAN_WPCOM_STARTER,
	PLAN_WPCOM_PRO,
	PLAN_WPCOM_PRO_MONTHLY,
	PLAN_WPCOM_PRO_2_YEARS,
	PLAN_WOOEXPRESS_MEDIUM_MONTHLY,
	PLAN_WOOEXPRESS_MEDIUM,
	PLAN_WOOEXPRESS_SMALL_MONTHLY,
	PLAN_WOOEXPRESS_SMALL,
	PLAN_WOOEXPRESS_PLUS,
	PLAN_MIGRATION_TRIAL_MONTHLY,
	PLAN_HOSTING_TRIAL_MONTHLY,
} from '@automattic/api-core';
import { isEnabled } from '@automattic/calypso-config';
import type { PlanProduct, Purchase } from '@automattic/api-core';

declare global {
	interface Window {
		isGlobalStylesOnPersonal?: boolean;
	}
}

function isGlobalStylesOnPersonalEnabled(): boolean {
	if ( typeof window === 'undefined' ) {
		return false;
	}

	if ( window.isGlobalStylesOnPersonal ) {
		return true;
	}

	window.isGlobalStylesOnPersonal = isEnabled( 'global-styles/on-personal-plan' );

	return !! window.isGlobalStylesOnPersonal;
}

function isValueTruthy< T >( value: T ): value is Exclude< T, null | undefined | false | 0 | '' > {
	return !! value;
}

function compact( elements: ( string | false | undefined | null )[] ): string[] {
	return elements.filter( isValueTruthy );
}

type TimeFrame = {
	term: string;
};
type TemporaryPlanProductFeaturesAndGrouping = {
	group: string;
	type: string;
	term?: string;
	getMonthlySlug?: () => string;
	getAnnualSlug?: () => string;
	availableFor?: ( plan: string ) => boolean;
	getPlanCompareFeatures?: () => string[];
	getPlanCardFeatures?: () => string[];
	getSignupFeatures?: () => string[];
	getBlogSignupFeatures?: () => string[];
	getPortfolioSignupFeatures?: () => string[];
	getIncludedFeatures?: () => string[];
	getCancellationFeatures?: () => string[];
	getSignupCompareAvailableFeatures?: () => string[];
	getPromotedFeatures?: () => string[];
	getVisualSplitCommerceFeatures?: () => string[];
	getVisualSplitBusinessFeatures?: () => string[];
};

const getBiAnnualTimeframe = (): TimeFrame => ( {
	term: 'TERM_BIENNIALLY',
} );

const getAnnualTimeframe = (): TimeFrame => ( {
	term: 'TERM_ANNUALLY',
} );

const getMonthlyTimeframe = (): TimeFrame => ( {
	term: 'TERM_MONTHLY',
} );

const getJetpackCommonPlanDetails = () => ( {} );
const getDotcomPlanDetails = () => ( {
	// Features only available for annual plans
	getAnnualPlansOnlyFeatures: () => [
		FEATURE_FREE_DOMAIN,
		FEATURE_CUSTOM_DOMAIN,
		FEATURE_PRIORITY_24_7_SUPPORT,
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
	],
} );

const getPlanFreeDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_FREE',
	getPlanCompareFeatures: () => [
		// pay attention to ordering, shared features should align on /plan page
		FEATURE_WP_SUBDOMAIN,
		FEATURE_JETPACK_ESSENTIAL,
		FEATURE_COMMUNITY_SUPPORT,
		FEATURE_FREE_THEMES,
		FEATURE_3GB_STORAGE,
	],
	getSignupFeatures: () => [
		FEATURE_COMMUNITY_SUPPORT,
		FEATURE_WP_SUBDOMAIN_SIGNUP,
		FEATURE_FREE_THEMES_SIGNUP,
	],
	getBlogSignupFeatures: () => [
		FEATURE_COMMUNITY_SUPPORT,
		FEATURE_WP_SUBDOMAIN_SIGNUP,
		FEATURE_FREE_THEMES_SIGNUP,
	],
	getPortfolioSignupFeatures: () => [
		FEATURE_COMMUNITY_SUPPORT,
		FEATURE_WP_SUBDOMAIN_SIGNUP,
		FEATURE_FREE_THEMES_SIGNUP,
	],
	getIncludedFeatures: () => [],
} );

const getPlanBloggerDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_BLOGGER',
	getPlanCompareFeatures: () => [
		// pay attention to ordering, shared features should align on /plan page
		FEATURE_BLOG_DOMAIN,
		FEATURE_JETPACK_ESSENTIAL,
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_FREE_THEMES,
		FEATURE_6GB_STORAGE,
		FEATURE_NO_ADS,
		FEATURE_MEMBERSHIPS,
		FEATURE_PREMIUM_CONTENT_BLOCK,
	],
	getSignupFeatures: () => [
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_BLOG_DOMAIN,
		FEATURE_ALL_FREE_FEATURES,
	],
	getBlogSignupFeatures: () => [
		FEATURE_FREE_BLOG_DOMAIN,
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_ALL_FREE_FEATURES,
	],
	getPortfolioSignupFeatures: () => [
		FEATURE_FREE_BLOG_DOMAIN,
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_ALL_FREE_FEATURES,
	],
	// Features not displayed but used for checking plan abilities
	getIncludedFeatures: () => [ FEATURE_AUDIO_UPLOADS ],
	getCancellationFeatures: () => [
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_AUDIO_UPLOADS,
		FEATURE_NO_ADS,
		FEATURE_MEMBERSHIPS,
	],
} );

const getPlanPersonalDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_PERSONAL',
	getPlanCompareFeatures: () =>
		compact(
			[
				// pay attention to ordering, shared features should align on /plan page
				FEATURE_CUSTOM_DOMAIN,
				FEATURE_HOSTING,
				FEATURE_JETPACK_ESSENTIAL,
				FEATURE_FAST_SUPPORT_FROM_EXPERTS,
				FEATURE_FREE_THEMES,
				isGlobalStylesOnPersonalEnabled() ? FEATURE_STYLE_CUSTOMIZATION : null,
				FEATURE_6GB_STORAGE,
				FEATURE_NO_ADS,
				FEATURE_MEMBERSHIPS,
				FEATURE_PREMIUM_CONTENT_BLOCK,
				FEATURE_PAYMENT_TRANSACTION_FEES_8,
			].filter( ( feature ) => feature !== null )
		),
	getSignupFeatures: () => {
		const baseFeatures = [
			FEATURE_FREE_DOMAIN,
			FEATURE_FAST_SUPPORT_FROM_EXPERTS,
			FEATURE_FREE_THEMES,
		];

		return isGlobalStylesOnPersonalEnabled()
			? [ ...baseFeatures, FEATURE_STYLE_CUSTOMIZATION ]
			: baseFeatures;
	},
	getBlogSignupFeatures: () => [
		FEATURE_FREE_DOMAIN,
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_ALL_FREE_FEATURES,
	],
	getPortfolioSignupFeatures: () => [
		FEATURE_FREE_DOMAIN,
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_ALL_FREE_FEATURES,
	],
	getSignupCompareAvailableFeatures: () => {
		const baseFeatures = [
			FEATURE_CUSTOM_DOMAIN,
			FEATURE_HOSTING,
			FEATURE_NO_ADS,
			FEATURE_COLLECT_PAYMENTS_V2,
			FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		];

		return isGlobalStylesOnPersonalEnabled()
			? [ ...baseFeatures, FEATURE_STYLE_CUSTOMIZATION ]
			: baseFeatures;
	},
	// Features not displayed but used for checking plan abilities
	getIncludedFeatures: () => [ FEATURE_AUDIO_UPLOADS ],
	getCancellationFeatures: () => [
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		FEATURE_AD_FREE_EXPERIENCE,
		FEATURE_AUDIO_UPLOADS,
	],
} );

const getPlanEcommerceDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_ECOMMERCE',
	getPlanCompareFeatures: () =>
		compact( [
			// pay attention to ordering, shared features should align on /plan page
			FEATURE_CUSTOM_DOMAIN,
			FEATURE_HOSTING,
			FEATURE_JETPACK_ADVANCED,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_50GB_STORAGE,
			FEATURE_NO_ADS,
			FEATURE_MEMBERSHIPS,
			FEATURE_PREMIUM_CONTENT_BLOCK,
			FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
			FEATURE_SIMPLE_PAYMENTS,
			FEATURE_GOOGLE_ANALYTICS,
			FEATURE_REPUBLICIZE,
			FEATURE_WORDADS_INSTANT,
			FEATURE_VIDEO_UPLOADS,
			FEATURE_ADVANCED_SEO,
			FEATURE_UPLOAD_PLUGINS,
			FEATURE_UPLOAD_THEMES,
			FEATURE_SFTP_DATABASE,
			FEATURE_NO_BRANDING,
			FEATURE_ACCEPT_PAYMENTS,
			FEATURE_SHIPPING_CARRIERS,
			FEATURE_UNLIMITED_PRODUCTS_SERVICES,
			FEATURE_ECOMMERCE_MARKETING,
			FEATURE_PREMIUM_CUSTOMIZABE_THEMES,
			FEATURE_PAYMENT_TRANSACTION_FEES_0,
		] ),
	getPromotedFeatures: () => [
		FEATURE_200GB_STORAGE,
		FEATURE_CUSTOM_DOMAIN,
		FEATURE_NO_ADS,
		FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
	],
	getSignupFeatures: () => [
		FEATURE_ACCEPT_PAYMENTS,
		FEATURE_SHIPPING_CARRIERS,
		FEATURE_ALL_BUSINESS_FEATURES,
	],
	getBlogSignupFeatures: () => [
		FEATURE_ACCEPT_PAYMENTS,
		FEATURE_SHIPPING_CARRIERS,
		FEATURE_ALL_BUSINESS_FEATURES,
	],
	getPortfolioSignupFeatures: () => [
		FEATURE_ACCEPT_PAYMENTS,
		FEATURE_SHIPPING_CARRIERS,
		FEATURE_ALL_BUSINESS_FEATURES,
	],
	getSignupCompareAvailableFeatures: () =>
		[
			FEATURE_CUSTOM_DOMAIN,
			FEATURE_HOSTING,
			FEATURE_NO_ADS,
			FEATURE_COLLECT_PAYMENTS_V2,
			FEATURE_FAST_SUPPORT_FROM_EXPERTS,
			FEATURE_PRIORITY_24_7_SUPPORT,
			FEATURE_EARN_AD,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_GOOGLE_ANALYTICS,
			FEATURE_INSTALL_PLUGINS,
			FEATURE_ADVANCED_SEO_EXPANDED_ABBR,
			FEATURE_SITE_BACKUPS_AND_RESTORE,
			FEATURE_SFTP_DATABASE,
			FEATURE_ACCEPT_PAYMENTS,
			FEATURE_SHIPPING_CARRIERS,
			PREMIUM_DESIGN_FOR_STORES,
		].filter( isValueTruthy ),
	// Features not displayed but used for checking plan abilities
	getIncludedFeatures: () => [
		FEATURE_AUDIO_UPLOADS,
		FEATURE_GOOGLE_MY_BUSINESS,
		WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS,
		FEATURE_UPLOAD_THEMES_PLUGINS,
		FEATURE_EMAIL_FORWARDING_EXTENDED_LIMIT,
		FEATURE_SEO_PREVIEW_TOOLS,
		WPCOM_FEATURES_ATOMIC,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
	// getInferiorFeatures: () => [],
	getCancellationFeatures: () => [
		FEATURE_ACCEPT_PAYMENTS_V2,
		FEATURE_SHIPPING_CARRIERS,
		FEATURE_ECOMMERCE_MARKETING,
		FEATURE_SELL_SHIP,
		FEATURE_PLUGINS_THEMES,
		FEATURE_ADVANCED_SEO_TOOLS,
	],
	getVisualSplitCommerceFeatures: () => [
		// All Business hosting features
		FEATURE_UNLIMITED_TRAFFIC,
		FEATURE_CUSTOM_DOMAIN,
		FEATURE_CDN,
		WPCOM_FEATURES_BACKUPS_RESTORE,
		FEATURE_EASY_SITE_MIGRATION,
		FEATURE_WAF_V2,
		FEATURE_SECURITY_DDOS,
		FEATURE_REAL_TIME_SECURITY_SCANS,
		FEATURE_99_999_UPTIME,
		FEATURE_SITE_STAGING_SITES,
		FEATURE_DEV_TOOLS_GIT,
		FEATURE_DEV_TOOLS_SSH,
		FEATURE_PRIORITY_24_7_SUPPORT,
		// Additional Commerce features
		FEATURE_ACCEPT_PAYMENTS,
		FEATURE_WOO_AUTOMATE,
		FEATURE_PRODUCT_ADD_ONS,
		FEATURE_WOO_SHIPPING_TRACKING,
		FEATURE_GOOGLE_LISTING_ADS,
	],
} );

const getWooExpressMediumPlanCompareFeatures = (): string[] => [
	FEATURE_WOOCOMMERCE_STORE,
	FEATURE_WOOCOMMERCE_MOBILE_APP,
	FEATURE_WORDPRESS_CMS,
	FEATURE_WORDPRESS_MOBILE_APP,
	FEATURE_CUSTOM_DOMAIN,
	FEATURE_FREE_SSL_CERTIFICATE,
	FEATURE_AUTOMATED_BACKUPS_SECURITY_SCAN,
	FEATURE_AD_FREE_EXPERIENCE,
	FEATURE_UNLIMITED_ADMINS,
	FEATURE_PRIORITY_24_7_SUPPORT,
	FEATURE_FAST_SUPPORT_FROM_EXPERTS,
	WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED,
	FEATURE_SALES_REPORTS,
	FEATURE_GOOGLE_ANALYTICS_V3,
	FEATURE_LIST_UNLIMITED_PRODUCTS,
	FEATURE_GIFT_CARDS,
	FEATURE_MIN_MAX_ORDER_QUANTITY,
	FEATURE_PRODUCT_BUNDLES,
	FEATURE_LIST_PRODUCTS_BY_BRAND,
	FEATURE_PRODUCT_RECOMMENDATIONS,
	FEATURE_INTEGRATED_PAYMENTS,
	FEATURE_INTERNATIONAL_PAYMENTS,
	FEATURE_AUTOMATED_SALES_TAXES,
	FEATURE_ACCEPT_LOCAL_PAYMENTS,
	FEATURE_RECURRING_PAYMENTS,
	FEATURE_MIN_MAX_ORDER_QUANTITY,
	FEATURE_PROMOTE_ON_TIKTOK,
	FEATURE_SYNC_WITH_PINTEREST,
	FEATURE_CONNECT_WITH_FACEBOOK,
	FEATURE_BACK_IN_STOCK_NOTIFICATIONS,
	FEATURE_MARKETING_AUTOMATION,
	FEATURE_ABANDONED_CART_RECOVERY,
	FEATURE_ADVANCED_SEO_TOOLS,
	FEATURE_ADVERTISE_ON_GOOGLE,
	FEATURE_CUSTOM_ORDER_EMAILS,
	FEATURE_INTEGRATED_SHIPMENT_TRACKING,
	FEATURE_LIVE_SHIPPING_RATES,
	FEATURE_DISCOUNTED_SHIPPING,
	FEATURE_PRINT_SHIPPING_LABELS,
	FEATURE_AI_ASSISTED_PRODUCT_DESCRIPTION,
];
const getWooExpressSmallPlanCompareFeatures = (): string[] => [
	FEATURE_WOOCOMMERCE_STORE,
	FEATURE_WOOCOMMERCE_MOBILE_APP,
	FEATURE_WORDPRESS_CMS,
	FEATURE_WORDPRESS_MOBILE_APP,
	FEATURE_CUSTOM_DOMAIN,
	FEATURE_FREE_SSL_CERTIFICATE,
	FEATURE_AUTOMATED_BACKUPS_SECURITY_SCAN,
	FEATURE_AD_FREE_EXPERIENCE,
	FEATURE_UNLIMITED_ADMINS,
	FEATURE_PRIORITY_24_7_SUPPORT,
	FEATURE_FAST_SUPPORT_FROM_EXPERTS,
	WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED,
	FEATURE_SALES_REPORTS,
	FEATURE_GOOGLE_ANALYTICS_V3,
	FEATURE_LIST_UNLIMITED_PRODUCTS,
	FEATURE_GIFT_CARDS,
	FEATURE_LIST_PRODUCTS_BY_BRAND,
	FEATURE_INTEGRATED_PAYMENTS,
	FEATURE_INTERNATIONAL_PAYMENTS,
	FEATURE_AUTOMATED_SALES_TAXES,
	FEATURE_ACCEPT_LOCAL_PAYMENTS,
	FEATURE_RECURRING_PAYMENTS,
	FEATURE_PROMOTE_ON_TIKTOK,
	FEATURE_SYNC_WITH_PINTEREST,
	FEATURE_CONNECT_WITH_FACEBOOK,
	FEATURE_ADVANCED_SEO_TOOLS,
	FEATURE_ADVERTISE_ON_GOOGLE,
	FEATURE_CUSTOM_ORDER_EMAILS,
	FEATURE_INTEGRATED_SHIPMENT_TRACKING,
	FEATURE_LIVE_SHIPPING_RATES,
	FEATURE_PRINT_SHIPPING_LABELS,
	FEATURE_AI_ASSISTED_PRODUCT_DESCRIPTION,
];

const getWooExpressPlanCompareFeatures = (): string[] => [
	...getWooExpressSmallPlanCompareFeatures(),
	...getWooExpressMediumPlanCompareFeatures(),
];

const getPlanWooExpressMediumDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getPlanEcommerceDetails(),
	getPlanCompareFeatures: () => getWooExpressPlanCompareFeatures(),
} );

const getPlanWooExpressSmallDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getPlanEcommerceDetails(),
	getPlanCompareFeatures: () => getWooExpressPlanCompareFeatures(),
} );

const getPlanPremiumDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_PREMIUM',
	getPlanCompareFeatures: () =>
		compact( [
			// pay attention to ordering, shared features should align on /plan page
			FEATURE_CUSTOM_DOMAIN,
			FEATURE_HOSTING,
			FEATURE_JETPACK_ESSENTIAL,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_13GB_STORAGE,
			FEATURE_NO_ADS,
			FEATURE_MEMBERSHIPS,
			FEATURE_PREMIUM_CONTENT_BLOCK,
			FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
			FEATURE_SIMPLE_PAYMENTS,
			FEATURE_GOOGLE_ANALYTICS,
			FEATURE_REPUBLICIZE,
			FEATURE_WORDADS_INSTANT,
			FEATURE_VIDEO_UPLOADS,
			FEATURE_PAYMENT_TRANSACTION_FEES_4,
		] ),
	getPromotedFeatures: () => [
		FEATURE_CUSTOM_DOMAIN,
		FEATURE_NO_ADS,
		FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
		FEATURE_13GB_STORAGE,
	],
	getSignupFeatures: () => [
		FEATURE_PRIORITY_24_7_SUPPORT,
		FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
		FEATURE_ALL_PERSONAL_FEATURES,
	],

	getBlogSignupFeatures: () =>
		[
			FEATURE_MONETISE,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_ALL_PERSONAL_FEATURES,
		].filter( isValueTruthy ),
	getPortfolioSignupFeatures: () =>
		[
			FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_ALL_PERSONAL_FEATURES,
		].filter( isValueTruthy ),
	getSignupCompareAvailableFeatures: () =>
		[
			FEATURE_CUSTOM_DOMAIN,
			FEATURE_HOSTING,
			FEATURE_NO_ADS,
			FEATURE_COLLECT_PAYMENTS_V2,
			FEATURE_FAST_SUPPORT_FROM_EXPERTS,
			FEATURE_PRIORITY_24_7_SUPPORT,
			FEATURE_EARN_AD,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_GOOGLE_ANALYTICS,
		].filter( isValueTruthy ),
	// Features not displayed but used for checking plan abilities
	getIncludedFeatures: () => [
		FEATURE_AUDIO_UPLOADS,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
	getCancellationFeatures: () => [
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
		WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED,
		FEATURE_STYLE_CUSTOMIZATION,
		FEATURE_WORDADS_INSTANT,
		FEATURE_AD_FREE_EXPERIENCE,
	],
} );

const getPlanBusinessDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_BUSINESS',
	getPlanCompareFeatures: () =>
		compact( [
			// pay attention to ordering, shared features should align on /plan page
			FEATURE_CUSTOM_DOMAIN,
			FEATURE_HOSTING,
			FEATURE_JETPACK_ADVANCED,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_50GB_STORAGE,
			FEATURE_NO_ADS,
			FEATURE_MEMBERSHIPS,
			FEATURE_PREMIUM_CONTENT_BLOCK,
			FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
			FEATURE_SIMPLE_PAYMENTS,
			FEATURE_GOOGLE_ANALYTICS,
			FEATURE_REPUBLICIZE,
			FEATURE_WORDADS_INSTANT,
			FEATURE_VIDEO_UPLOADS,
			FEATURE_ADVANCED_SEO,
			FEATURE_UPLOAD_PLUGINS,
			FEATURE_UPLOAD_THEMES,
			FEATURE_SFTP_DATABASE,
			FEATURE_NO_BRANDING,
			FEATURE_PAYMENT_TRANSACTION_FEES_2,
		] ),
	getPromotedFeatures: () => [
		FEATURE_200GB_STORAGE,
		FEATURE_CUSTOM_DOMAIN,
		FEATURE_NO_ADS,
		FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
		FEATURE_VIDEO_UPLOADS,
	],
	getSignupFeatures: () => [
		FEATURE_UPLOAD_THEMES_PLUGINS,
		FEATURE_ADVANCED_SEO_TOOLS,
		FEATURE_ALL_PREMIUM_FEATURES,
	],
	getBlogSignupFeatures: () => [
		FEATURE_UPLOAD_THEMES_PLUGINS,
		FEATURE_ADVANCED_SEO_TOOLS,
		FEATURE_ALL_PREMIUM_FEATURES,
	],
	getPortfolioSignupFeatures: () => [
		FEATURE_UPLOAD_THEMES_PLUGINS,
		FEATURE_200GB_STORAGE,
		FEATURE_ALL_PREMIUM_FEATURES,
	],
	getSignupCompareAvailableFeatures: () =>
		[
			FEATURE_CUSTOM_DOMAIN,
			FEATURE_HOSTING,
			FEATURE_NO_ADS,
			FEATURE_COLLECT_PAYMENTS_V2,
			FEATURE_FAST_SUPPORT_FROM_EXPERTS,
			FEATURE_PRIORITY_24_7_SUPPORT,
			FEATURE_EARN_AD,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_GOOGLE_ANALYTICS,
			FEATURE_INSTALL_PLUGINS,
			FEATURE_ADVANCED_SEO_EXPANDED_ABBR,
			FEATURE_SITE_BACKUPS_AND_RESTORE,
			FEATURE_SFTP_DATABASE,
		].filter( isValueTruthy ),

	// Features not displayed but used for checking plan abilities
	getIncludedFeatures: () => [
		FEATURE_AUDIO_UPLOADS,
		FEATURE_GOOGLE_MY_BUSINESS,
		WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS,
		FEATURE_EMAIL_FORWARDING_EXTENDED_LIMIT,
		FEATURE_SEO_PREVIEW_TOOLS,
		WPCOM_FEATURES_ATOMIC,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
	getCancellationFeatures: () => [
		FEATURE_PLUGINS_THEMES,
		FEATURE_ADVANCED_SEO_TOOLS,
		FEATURE_DEV_TOOLS,
		FEATURE_SEAMLESS_STAGING_PRODUCTION_SYNCING,
		FEATURE_SITE_BACKUPS_AND_RESTORE,
		FEATURE_AD_FREE_EXPERIENCE,
		FEATURE_FAST_SUPPORT_FROM_EXPERTS,
	],
	getVisualSplitBusinessFeatures: () => [
		FEATURE_UNLIMITED_TRAFFIC,
		FEATURE_CUSTOM_DOMAIN,
		FEATURE_CDN,
		WPCOM_FEATURES_BACKUPS_RESTORE,
		FEATURE_EASY_SITE_MIGRATION,
		FEATURE_WAF_V2,
		FEATURE_SECURITY_DDOS,
		FEATURE_REAL_TIME_SECURITY_SCANS,
		FEATURE_99_999_UPTIME,
		FEATURE_SITE_STAGING_SITES,
		FEATURE_DEV_TOOLS_GIT,
		FEATURE_DEV_TOOLS_SSH,
		FEATURE_PRIORITY_24_7_SUPPORT,
	],
} );
const getPlanProDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_PRO',
	getPlanCompareFeatures: () => [
		FEATURE_UNLIMITED_TRAFFIC,
		FEATURE_MANAGED_HOSTING,
		FEATURE_FREE_THEMES,
		FEATURE_CUSTOM_DOMAIN,
		WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED,
		FEATURE_INSTALL_PLUGINS,
		WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS,
		FEATURE_PREMIUM_SUPPORT,
		FEATURE_WOOCOMMERCE,
		FEATURE_50GB_STORAGE,
		FEATURE_NO_ADS,
		FEATURE_ADVANCED_SEO,
		FEATURE_UNLIMITED_ADMINS,
		FEATURE_VIDEO_UPLOADS,
		FEATURE_PAYMENT_BLOCKS,
		FEATURE_SOCIAL_MEDIA_TOOLS,
		FEATURE_TITAN_EMAIL,
		FEATURE_MONETISE,
		FEATURE_SFTP_DATABASE,
		FEATURE_SITE_BACKUPS_AND_RESTORE,
		FEATURE_JETPACK_ESSENTIAL,
		FEATURE_SIMPLE_PAYMENTS,
		FEATURE_WORDADS_INSTANT,
		FEATURE_GOOGLE_ANALYTICS,
	],
	getIncludedFeatures: () => [
		FEATURE_ADVANCED_SEO_EXPANDED_ABBR,
		FEATURE_AUDIO_UPLOADS,
		FEATURE_COLLECT_PAYMENTS_V2,
		FEATURE_EARN_AD,
		FEATURE_EMAIL_FORWARDING_EXTENDED_LIMIT,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_GOOGLE_MY_BUSINESS,
		FEATURE_HOSTING,
		FEATURE_ADVANCED_DESIGN_CUSTOMIZATION,
		FEATURE_MEMBERSHIPS,
		FEATURE_NO_BRANDING,
		FEATURE_REPUBLICIZE,
		FEATURE_PREMIUM_CONTENT_BLOCK,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_SFTP_DATABASE,
		FEATURE_SITE_BACKUPS_AND_RESTORE,
		FEATURE_UPLOAD_PLUGINS,
		FEATURE_UPLOAD_THEMES,
		FEATURE_UPLOAD_THEMES_PLUGINS,
		WPCOM_FEATURES_ATOMIC,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
} );

// The following is not a real plan, we are adding it here so that
// Woo Express Plus gets its own column in the plans grid.
const getPlanWooExpressPlusDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_WOO_EXPRESS_PLUS',
} );

// The following is not a real plan, we are adding it here so that
// VIP (a.k.a Enterprise) gets its own column in the plans grid.
// Check pdgrnI-1Qp-p2 for more details.
const get2023EnterprisGrideDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_ENTERPRISE_GRID_WPCOM',
} );

const getJetpackPersonalDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	group: 'GROUP_JETPACK',
	type: 'TYPE_PERSONAL',
	availableFor: ( plan ) => ( [ JetpackPlans.PLAN_JETPACK_FREE ] as string[] ).includes( plan ),
	getPlanCardFeatures: () => [ FEATURE_BACKUP_DAILY_V2, FEATURE_ANTISPAM_V2 ],
	getIncludedFeatures: () => [
		FEATURE_OFFSITE_BACKUP_VAULTPRESS_DAILY,
		FEATURE_BACKUP_ARCHIVE_30,
		FEATURE_BACKUP_STORAGE_SPACE_UNLIMITED,
		FEATURE_AUTOMATED_RESTORES,
		FEATURE_SPAM_AKISMET_PLUS,
		FEATURE_EASY_SITE_MIGRATION,
		FEATURE_PREMIUM_SUPPORT,
		FEATURE_JETPACK_BACKUP_DAILY,
		FEATURE_JETPACK_BACKUP_DAILY_MONTHLY,
		FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
		FEATURE_JETPACK_ANTI_SPAM,
		FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_ADVANCED_SEO,
		FEATURE_OFFSITE_BACKUP_VAULTPRESS_DAILY,
		FEATURE_SPAM_AKISMET_PLUS,
		FEATURE_ACTIVITY_LOG,
		FEATURE_PREMIUM_SUPPORT,
		FEATURE_ALL_FREE_FEATURES_JETPACK,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
} );

const getJetpackPremiumDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	group: 'GROUP_JETPACK',
	type: 'TYPE_PREMIUM',
	availableFor: ( plan ) =>
		(
			[
				JetpackPlans.PLAN_JETPACK_FREE,
				JetpackPlans.PLAN_JETPACK_PERSONAL,
				JetpackPlans.PLAN_JETPACK_PERSONAL_MONTHLY,
			] as string[]
		 ).includes( plan ),
	getPlanCardFeatures: () => [ FEATURE_BACKUP_DAILY_V2, FEATURE_SCAN_V2, FEATURE_ANTISPAM_V2 ],
	getIncludedFeatures: () =>
		compact( [
			// pay attention to ordering, shared features should align on /plan page
			FEATURE_OFFSITE_BACKUP_VAULTPRESS_DAILY,
			FEATURE_BACKUP_ARCHIVE_30,
			FEATURE_BACKUP_STORAGE_SPACE_UNLIMITED,
			FEATURE_AUTOMATED_RESTORES,
			FEATURE_SPAM_AKISMET_PLUS,
			FEATURE_EASY_SITE_MIGRATION,
			FEATURE_PREMIUM_SUPPORT,
			FEATURE_REPUBLICIZE,
			FEATURE_SIMPLE_PAYMENTS,
			FEATURE_WORDADS_INSTANT,
			FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
			FEATURE_MALWARE_SCANNING_DAILY,
			FEATURE_ADVANCED_SEO,
			FEATURE_GOOGLE_ANALYTICS,
			FEATURE_JETPACK_BACKUP_DAILY,
			FEATURE_JETPACK_BACKUP_DAILY_MONTHLY,
			FEATURE_JETPACK_SCAN_DAILY,
			FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
			FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
			FEATURE_JETPACK_ANTI_SPAM,
			FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
			FEATURE_JETPACK_VIDEOPRESS_BI_YEARLY,
			FEATURE_JETPACK_VIDEOPRESS,
			FEATURE_JETPACK_VIDEOPRESS_MONTHLY,
			FEATURE_SEO_PREVIEW_TOOLS,
			FEATURE_OFFSITE_BACKUP_VAULTPRESS_DAILY,
			FEATURE_SPAM_AKISMET_PLUS,
			FEATURE_MALWARE_SCANNING_DAILY,
			FEATURE_AUTOMATIC_SECURITY_FIXES,
			FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
			FEATURE_WORDADS_INSTANT,
			FEATURE_ADVANCED_SEO,
			FEATURE_ALL_FREE_FEATURES_JETPACK,
			WPCOM_FEATURES_SCAN,
			WPCOM_FEATURES_ANTISPAM,
			WPCOM_FEATURES_BACKUPS,
		] ),
} );

const getJetpackBusinessDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	group: 'GROUP_JETPACK',
	type: 'TYPE_BUSINESS',
	availableFor: ( plan ) =>
		(
			[
				JetpackPlans.PLAN_JETPACK_FREE,
				JetpackPlans.PLAN_JETPACK_PREMIUM,
				JetpackPlans.PLAN_JETPACK_PREMIUM_MONTHLY,
				JetpackPlans.PLAN_JETPACK_PERSONAL,
				JetpackPlans.PLAN_JETPACK_PERSONAL_MONTHLY,
			] as string[]
		 ).includes( plan ),
	getPlanCardFeatures: () => [
		FEATURE_BACKUP_REALTIME_V2,
		FEATURE_PRODUCT_SCAN_REALTIME_V2,
		FEATURE_ANTISPAM_V2,
	],
	getIncludedFeatures: () =>
		compact( [
			// pay attention to ordering, shared features should align on /plan page
			FEATURE_OFFSITE_BACKUP_VAULTPRESS_REALTIME,
			FEATURE_BACKUP_ARCHIVE_UNLIMITED,
			FEATURE_BACKUP_STORAGE_SPACE_UNLIMITED,
			FEATURE_AUTOMATED_RESTORES,
			FEATURE_SPAM_AKISMET_PLUS,
			FEATURE_EASY_SITE_MIGRATION,
			FEATURE_PREMIUM_SUPPORT,
			FEATURE_REPUBLICIZE,
			FEATURE_SIMPLE_PAYMENTS,
			FEATURE_WORDADS_INSTANT,
			FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
			FEATURE_MALWARE_SCANNING_DAILY_AND_ON_DEMAND,
			FEATURE_ONE_CLICK_THREAT_RESOLUTION,
			FEATURE_ADVANCED_SEO,
			FEATURE_GOOGLE_ANALYTICS,
			FEATURE_JETPACK_BACKUP_REALTIME,
			FEATURE_JETPACK_BACKUP_REALTIME_MONTHLY,
			FEATURE_JETPACK_SCAN_DAILY,
			FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
			FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
			FEATURE_JETPACK_ANTI_SPAM,
			FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
			FEATURE_JETPACK_VIDEOPRESS_BI_YEARLY,
			FEATURE_JETPACK_VIDEOPRESS,
			FEATURE_JETPACK_VIDEOPRESS_MONTHLY,
			FEATURE_SEO_PREVIEW_TOOLS,
			FEATURE_OFFSITE_BACKUP_VAULTPRESS_REALTIME,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_ALL_PREMIUM_FEATURES_JETPACK,
			WPCOM_FEATURES_SCAN,
			WPCOM_FEATURES_ANTISPAM,
			WPCOM_FEATURES_BACKUPS,
			isEnabled( 'stats/paid-wpcom-v3' ) ? FEATURE_STATS_COMMERCIAL : FEATURE_STATS_PAID,
		] ),
} );

const getPlanJetpackSecurityDailyDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	group: 'GROUP_JETPACK',
	type: 'TYPE_SECURITY_DAILY',
	availableFor: ( plan ) =>
		( [ JetpackPlans.PLAN_JETPACK_FREE, ...JETPACK_LEGACY_PLANS ] as string[] ).includes( plan ),
	getPlanCardFeatures: () => [
		FEATURE_PRODUCT_BACKUP_DAILY_V2,
		FEATURE_PRODUCT_SCAN_DAILY_V2,
		FEATURE_ANTISPAM_V2,
		FEATURE_WAF,
	],
	getIncludedFeatures: () => [
		FEATURE_JETPACK_BACKUP_DAILY,
		FEATURE_JETPACK_BACKUP_DAILY_MONTHLY,
		FEATURE_JETPACK_SCAN_DAILY,
		FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
		FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
		FEATURE_JETPACK_ANTI_SPAM,
		FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
		FEATURE_BACKUP_ARCHIVE_30,
		FEATURE_REPUBLICIZE,
		FEATURE_ADVANCED_SEO,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_SIMPLE_PAYMENTS,
		FEATURE_WORDADS_INSTANT,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_PREMIUM_SUPPORT,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
} );

const getPlanJetpackSecurityRealtimeDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	group: 'GROUP_JETPACK',
	type: 'TYPE_SECURITY_REALTIME',
	availableFor: ( plan ) =>
		(
			[
				JetpackPlans.PLAN_JETPACK_FREE,
				JetpackPlans.PLAN_JETPACK_SECURITY_DAILY,
				JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
				...JETPACK_LEGACY_PLANS,
			] as string[]
		 ).includes( plan ),
	getPlanCardFeatures: () => [
		FEATURE_PLAN_SECURITY_DAILY,
		FEATURE_PRODUCT_BACKUP_REALTIME_V2,
		FEATURE_PRODUCT_SCAN_REALTIME_V2,
		FEATURE_ACTIVITY_LOG_1_YEAR_V2,
	],
	getIncludedFeatures: () => [
		FEATURE_JETPACK_BACKUP_REALTIME,
		FEATURE_JETPACK_BACKUP_REALTIME_MONTHLY,
		FEATURE_JETPACK_SCAN_DAILY,
		FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
		FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
		FEATURE_JETPACK_ANTI_SPAM,
		FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
		FEATURE_BACKUP_ARCHIVE_UNLIMITED,
		FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
		FEATURE_REPUBLICIZE,
		FEATURE_ADVANCED_SEO,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_SIMPLE_PAYMENTS,
		FEATURE_WORDADS_INSTANT,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_PREMIUM_SUPPORT,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
} );

const getPlanJetpackSecurityT1Details = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getJetpackCommonPlanDetails(),
	group: 'GROUP_JETPACK',
	type: 'TYPE_SECURITY_T1',
	availableFor: ( plan ) =>
		( [ JetpackPlans.PLAN_JETPACK_FREE, ...JETPACK_LEGACY_PLANS ] as string[] ).includes( plan ),
	getPlanCardFeatures: () => [
		FEATURE_JETPACK_PRODUCT_BACKUP,
		FEATURE_JETPACK_REAL_TIME_MALWARE_SCANNING,
		FEATURE_ANTISPAM_V2,
		FEATURE_WAF,
		FEATURE_JETPACK_30_DAY_ARCHIVE_ACTIVITY_LOG,
	],
	getIncludedFeatures: () => [
		FEATURE_JETPACK_BACKUP_T1_BI_YEARLY,
		FEATURE_JETPACK_BACKUP_T1_YEARLY,
		FEATURE_JETPACK_BACKUP_T1_MONTHLY,
		FEATURE_JETPACK_SCAN_DAILY,
		FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
		FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
		FEATURE_JETPACK_ANTI_SPAM,
		FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
		FEATURE_BACKUP_ARCHIVE_UNLIMITED,
		FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
		FEATURE_REPUBLICIZE,
		FEATURE_ADVANCED_SEO,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_SIMPLE_PAYMENTS,
		FEATURE_WORDADS_INSTANT,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_PREMIUM_SUPPORT,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
} );

const getPlanJetpackSecurityT2Details = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getPlanJetpackSecurityT1Details(),
	type: 'TYPE_SECURITY_T2',
	getPlanCardFeatures: () => [
		FEATURE_PLAN_SECURITY_DAILY,
		FEATURE_PRODUCT_BACKUP_REALTIME_V2,
		FEATURE_PRODUCT_SCAN_REALTIME_V2,
		FEATURE_WAF,
		FEATURE_JETPACK_1_YEAR_ARCHIVE_ACTIVITY_LOG,
	],
	getIncludedFeatures: () => [
		FEATURE_JETPACK_BACKUP_T2_YEARLY,
		FEATURE_JETPACK_BACKUP_T2_MONTHLY,
		FEATURE_JETPACK_SCAN_DAILY,
		FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
		FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
		FEATURE_JETPACK_ANTI_SPAM,
		FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
		FEATURE_BACKUP_ARCHIVE_UNLIMITED,
		FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
		FEATURE_REPUBLICIZE,
		FEATURE_ADVANCED_SEO,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_SIMPLE_PAYMENTS,
		FEATURE_WORDADS_INSTANT,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_PREMIUM_SUPPORT,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
} );

const getPlanJetpackCompleteDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getJetpackCommonPlanDetails(),
	group: 'GROUP_JETPACK',
	type: 'TYPE_ALL',
	availableFor: ( plan ) =>
		(
			[
				JetpackPlans.PLAN_JETPACK_FREE,
				...JETPACK_SECURITY_PLANS,
				...JETPACK_LEGACY_PLANS,
			] as string[]
		 ).includes( plan ),
	getPlanCardFeatures: () => [
		FEATURE_JETPACK_ALL_BACKUP_SECURITY_FEATURES,
		FEATURE_JETPACK_1TB_BACKUP_STORAGE,
		FEATURE_JETPACK_PRODUCT_VIDEOPRESS,
		FEATURE_PRODUCT_SEARCH_V2,
		FEATURE_CRM_V2,
		FEATURE_JETPACK_1_YEAR_ARCHIVE_ACTIVITY_LOG,
	],
	getIncludedFeatures: () =>
		compact( [
			FEATURE_JETPACK_BACKUP_T2_YEARLY,
			FEATURE_JETPACK_BACKUP_T2_MONTHLY,
			FEATURE_JETPACK_SCAN_DAILY,
			FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
			FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
			FEATURE_JETPACK_ANTI_SPAM,
			FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
			FEATURE_JETPACK_SEARCH_BI_YEARLY,
			FEATURE_JETPACK_SEARCH,
			FEATURE_JETPACK_SEARCH_MONTHLY,
			FEATURE_JETPACK_CRM,
			FEATURE_JETPACK_CRM_MONTHLY,
			FEATURE_BACKUP_ARCHIVE_UNLIMITED,
			FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
			FEATURE_JETPACK_BOOST_BI_YEARLY,
			FEATURE_JETPACK_BOOST,
			FEATURE_JETPACK_BOOST_MONTHLY,
			FEATURE_JETPACK_SOCIAL_ADVANCED_BI_YEARLY,
			FEATURE_JETPACK_SOCIAL_ADVANCED,
			FEATURE_JETPACK_SOCIAL_ADVANCED_MONTHLY,
			FEATURE_JETPACK_VIDEOPRESS_BI_YEARLY,
			FEATURE_JETPACK_VIDEOPRESS,
			FEATURE_JETPACK_VIDEOPRESS_MONTHLY,
			FEATURE_CLOUD_CRITICAL_CSS,
			FEATURE_REPUBLICIZE,
			FEATURE_ADVANCED_SEO,
			FEATURE_SEO_PREVIEW_TOOLS,
			FEATURE_SIMPLE_PAYMENTS,
			FEATURE_WORDADS_INSTANT,
			FEATURE_GOOGLE_ANALYTICS,
			isEnabled( 'themes/premium' ) ? WPCOM_FEATURES_PREMIUM_THEMES_UNLIMITED : null,
			FEATURE_PREMIUM_SUPPORT,
			WPCOM_FEATURES_SCAN,
			WPCOM_FEATURES_ANTISPAM,
			WPCOM_FEATURES_BACKUPS,
			isEnabled( 'stats/paid-wpcom-v3' ) ? FEATURE_STATS_COMMERCIAL : FEATURE_STATS_PAID,
		] ),
} );

const getPlanJetpackStarterDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getJetpackCommonPlanDetails(),
	group: 'GROUP_JETPACK',
	type: 'TYPE_JETPACK_STARTER',
	availableFor: ( plan ) =>
		( [ JetpackPlans.PLAN_JETPACK_FREE, ...JETPACK_LEGACY_PLANS ] as string[] ).includes( plan ),
	getPlanCardFeatures: () => [ FEATURE_JETPACK_PRODUCT_BACKUP, FEATURE_ANTISPAM_V2 ],
	getIncludedFeatures: () => [
		FEATURE_JETPACK_BACKUP_T0_YEARLY,
		FEATURE_JETPACK_BACKUP_T0_MONTHLY,
		FEATURE_JETPACK_ANTI_SPAM_BI_YEARLY,
		FEATURE_JETPACK_ANTI_SPAM,
		FEATURE_JETPACK_ANTI_SPAM_MONTHLY,
		FEATURE_BACKUP_ARCHIVE_UNLIMITED,
		FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
		FEATURE_REPUBLICIZE,
		FEATURE_ADVANCED_SEO,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_SIMPLE_PAYMENTS,
		FEATURE_WORDADS_INSTANT,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_PREMIUM_SUPPORT,
		WPCOM_FEATURES_ANTISPAM,
		WPCOM_FEATURES_BACKUPS,
	],
} );

const getPlanJetpackGrowthDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	...getJetpackCommonPlanDetails(),
	group: 'GROUP_JETPACK',
	type: 'TYPE_JETPACK_GROWTH',
	availableFor: ( plan ) =>
		( [ JetpackPlans.PLAN_JETPACK_FREE, ...JETPACK_LEGACY_PLANS ] as string[] ).includes( plan ),
	getPlanCardFeatures: () => [
		FEATURE_JETPACK_SOCIAL_V1_MONTHLY,
		isEnabled( 'stats/paid-wpcom-v3' ) ? FEATURE_STATS_COMMERCIAL : FEATURE_STATS_PAID,
	],
	getIncludedFeatures: () => [
		FEATURE_EARN_AD,
		FEATURE_UNLIMITED_SUBSCRIBERS,
		FEATURE_SIMPLE_PAYMENTS,
	],
} );

const getPlanJetpackGoldenTokenDetails = (): TemporaryPlanProductFeaturesAndGrouping => ( {
	group: 'GROUP_JETPACK',
	type: 'TYPE_GOLDEN_TOKEN',
	availableFor: ( plan ) =>
		( [ JetpackPlans.PLAN_JETPACK_FREE, ...JETPACK_LEGACY_PLANS ] as string[] ).includes( plan ),
	getPlanCardFeatures: () => [
		FEATURE_PRODUCT_BACKUP_REALTIME_V2,
		FEATURE_PRODUCT_SCAN_REALTIME_V2,
		FEATURE_ACTIVITY_LOG_1_YEAR_V2,
	],
	getIncludedFeatures: () => [
		FEATURE_JETPACK_BACKUP_REALTIME,
		FEATURE_JETPACK_BACKUP_REALTIME_MONTHLY,
		FEATURE_JETPACK_SCAN_DAILY,
		FEATURE_JETPACK_SCAN_DAILY_MONTHLY,
		FEATURE_BACKUP_ARCHIVE_UNLIMITED,
		FEATURE_VIDEO_UPLOADS_JETPACK_PRO,
		FEATURE_REPUBLICIZE,
		FEATURE_ADVANCED_SEO,
		FEATURE_SEO_PREVIEW_TOOLS,
		FEATURE_SIMPLE_PAYMENTS,
		FEATURE_WORDADS_INSTANT,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_PREMIUM_SUPPORT,
		WPCOM_FEATURES_SCAN,
		WPCOM_FEATURES_BACKUPS,
	],
} );

// DO NOT import. Use `getPlanFeaturesAndAvailability` instead.
const PLAN_FEATURES_AND_AVAILABILITY_LIST: Record<
	string,
	TemporaryPlanProductFeaturesAndGrouping
> = {
	[ PLAN_FREE ]: {
		...getPlanFreeDetails(),
		term: 'TERM_ANNUALLY',
	},

	[ PLAN_BLOGGER ]: {
		...getPlanBloggerDetails(),
		term: 'TERM_ANNUALLY',
		availableFor: ( plan ) => [ PLAN_FREE ].includes( plan ),
	},

	[ PLAN_BLOGGER_2_YEARS ]: {
		...getPlanBloggerDetails(),
		term: 'TERM_BIENNIALLY',
		availableFor: ( plan ) => [ PLAN_FREE, PLAN_BLOGGER ].includes( plan ),
	},

	[ PLAN_PERSONAL_MONTHLY ]: {
		...getPlanPersonalDetails(),
		...getMonthlyTimeframe(),
		availableFor: ( plan ) => [ PLAN_FREE, PLAN_BLOGGER, PLAN_BLOGGER_2_YEARS ].includes( plan ),
	},

	[ PLAN_PERSONAL ]: {
		...getPlanPersonalDetails(),
		term: 'TERM_ANNUALLY',
		availableFor: ( plan ) =>
			[ PLAN_FREE, PLAN_BLOGGER, PLAN_BLOGGER_2_YEARS, PLAN_PERSONAL_MONTHLY ].includes( plan ),
	},

	[ PLAN_PERSONAL_2_YEARS ]: {
		...getPlanPersonalDetails(),
		term: 'TERM_BIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
			].includes( plan ),
	},

	[ PLAN_PERSONAL_3_YEARS ]: {
		...getPlanPersonalDetails(),
		term: 'TERM_TRIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
			].includes( plan ),
	},

	[ PLAN_PREMIUM_MONTHLY ]: {
		...getPlanPremiumDetails(),
		...getMonthlyTimeframe(),
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
			].includes( plan ),
	},

	[ PLAN_PREMIUM ]: {
		...getPlanPremiumDetails(),
		term: 'TERM_ANNUALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_WPCOM_STARTER,
			].includes( plan ),
	},

	[ PLAN_PREMIUM_2_YEARS ]: {
		...getPlanPremiumDetails(),
		term: 'TERM_BIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
			].includes( plan ),
	},

	[ PLAN_PREMIUM_3_YEARS ]: {
		...getPlanPremiumDetails(),
		term: 'TERM_TRIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PERSONAL_3_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
			].includes( plan ),
	},

	[ PLAN_BUSINESS_MONTHLY ]: {
		...getPlanBusinessDetails(),
		...getMonthlyTimeframe(),
		availableFor: ( plan ) =>
			isEnabled( 'upgrades/wpcom-monthly-plans' ) &&
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_BUSINESS ]: {
		...getPlanBusinessDetails(),
		term: 'TERM_ANNUALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WPCOM_STARTER,
				PLAN_WPCOM_PRO,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_BUSINESS_2_YEARS ]: {
		...getPlanBusinessDetails(),
		term: 'TERM_BIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WPCOM_STARTER,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_BUSINESS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_WPCOM_PRO,
				PLAN_WPCOM_PRO_2_YEARS,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_BUSINESS_3_YEARS ]: {
		...getPlanBusinessDetails(),
		term: 'TERM_TRIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WPCOM_STARTER,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PERSONAL_3_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_PREMIUM_3_YEARS,
				PLAN_BUSINESS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_BUSINESS_2_YEARS,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_WPCOM_PRO,
				PLAN_WPCOM_PRO_2_YEARS,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_100_YEARS ]: {
		...getPlanBusinessDetails(),
		term: 'TERM_CENTENNIALLY',
		group: 'GROUP_WPCOM',
		type: 'TYPE_100_YEAR',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WPCOM_STARTER,
				PLAN_WPCOM_PRO,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_ECOMMERCE_MONTHLY ]: {
		...getPlanEcommerceDetails(),
		...getMonthlyTimeframe(),
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_BUSINESS,
				PLAN_BUSINESS_2_YEARS,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_ECOMMERCE_TRIAL_MONTHLY,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_ECOMMERCE ]: {
		...getPlanEcommerceDetails(),
		term: 'TERM_ANNUALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WPCOM_STARTER,
				PLAN_WPCOM_PRO,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_BUSINESS,
				PLAN_BUSINESS_2_YEARS,
				PLAN_ECOMMERCE_MONTHLY,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_ECOMMERCE_TRIAL_MONTHLY,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_ECOMMERCE_2_YEARS ]: {
		...getPlanEcommerceDetails(),
		term: 'TERM_BIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WPCOM_STARTER,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_WPCOM_PRO,
				PLAN_WPCOM_PRO_2_YEARS,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_BUSINESS,
				PLAN_BUSINESS_2_YEARS,
				PLAN_ECOMMERCE_MONTHLY,
				PLAN_ECOMMERCE,
				PLAN_ECOMMERCE_TRIAL_MONTHLY,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_WOOEXPRESS_MEDIUM_MONTHLY ]: {
		...getPlanWooExpressMediumDetails(),
		...getMonthlyTimeframe(),
		type: 'TYPE_WOOEXPRESS_MEDIUM',
		availableFor: ( plan ) =>
			[ PLAN_FREE, PLAN_ECOMMERCE_TRIAL_MONTHLY, PLAN_WOOEXPRESS_SMALL_MONTHLY ].includes( plan ),
	},

	[ PLAN_WOOEXPRESS_MEDIUM ]: {
		...getPlanWooExpressMediumDetails(),
		term: 'TERM_ANNUALLY',
		type: 'TYPE_WOOEXPRESS_MEDIUM',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WOOEXPRESS_MEDIUM_MONTHLY,
				PLAN_ECOMMERCE_TRIAL_MONTHLY,
				PLAN_WOOEXPRESS_SMALL,
				PLAN_WOOEXPRESS_SMALL_MONTHLY,
			].includes( plan ),
	},

	[ PLAN_WOOEXPRESS_SMALL_MONTHLY ]: {
		...getPlanWooExpressSmallDetails(),
		...getMonthlyTimeframe(),
		type: 'TYPE_WOOEXPRESS_SMALL',
		availableFor: ( plan ) => [ PLAN_FREE, PLAN_ECOMMERCE_TRIAL_MONTHLY ].includes( plan ),
	},

	[ PLAN_WOOEXPRESS_SMALL ]: {
		...getPlanWooExpressSmallDetails(),
		type: 'TYPE_WOOEXPRESS_SMALL',
		term: 'TERM_ANNUALLY',
		availableFor: ( plan ) =>
			[ PLAN_FREE, PLAN_WOOEXPRESS_SMALL_MONTHLY, PLAN_ECOMMERCE_TRIAL_MONTHLY ].includes( plan ),
	},

	// Not a real plan. This is used to show the Plus offering in the Woo Express plans grid
	[ PLAN_WOOEXPRESS_PLUS ]: {
		...getPlanWooExpressPlusDetails(),
		term: 'TERM_ANNUALLY',
	},

	// Not a real plan. This is used to show the Enterprise (VIP) offering in
	// the main plans grid as part of pdgrnI-1Qp-p2.
	[ PLAN_ENTERPRISE_GRID_WPCOM ]: {
		...get2023EnterprisGrideDetails(),
		term: 'TERM_ANNUALLY',
	},
	[ PLAN_ECOMMERCE_3_YEARS ]: {
		...getPlanEcommerceDetails(),
		term: 'TERM_TRIENNIALLY',
		availableFor: ( plan ) =>
			[
				PLAN_FREE,
				PLAN_WPCOM_STARTER,
				PLAN_WPCOM_PRO_MONTHLY,
				PLAN_WPCOM_PRO,
				PLAN_WPCOM_PRO_2_YEARS,
				PLAN_BLOGGER,
				PLAN_BLOGGER_2_YEARS,
				PLAN_PERSONAL_MONTHLY,
				PLAN_PERSONAL,
				PLAN_PERSONAL_2_YEARS,
				PLAN_PERSONAL_3_YEARS,
				PLAN_PREMIUM_MONTHLY,
				PLAN_PREMIUM,
				PLAN_PREMIUM_2_YEARS,
				PLAN_PREMIUM_3_YEARS,
				PLAN_BUSINESS_MONTHLY,
				PLAN_BUSINESS,
				PLAN_BUSINESS_2_YEARS,
				PLAN_BUSINESS_3_YEARS,
				PLAN_ECOMMERCE_MONTHLY,
				PLAN_ECOMMERCE,
				PLAN_ECOMMERCE_2_YEARS,
				PLAN_ECOMMERCE_TRIAL_MONTHLY,
				PLAN_MIGRATION_TRIAL_MONTHLY,
				PLAN_HOSTING_TRIAL_MONTHLY,
			].includes( plan ),
	},

	[ JetpackPlans.PLAN_JETPACK_FREE ]: {
		term: 'TERM_ANNUALLY',
		group: 'GROUP_JETPACK',
		type: 'TYPE_FREE',
		getIncludedFeatures: () => [
			//used
			FEATURE_STANDARD_SECURITY_TOOLS,
			FEATURE_SITE_STATS,
			FEATURE_TRAFFIC_TOOLS,
			FEATURE_MANAGE,
			FEATURE_ADVANCED_SEO,
			FEATURE_SEO_PREVIEW_TOOLS,
			FEATURE_FREE_WORDPRESS_THEMES,
			FEATURE_SITE_STATS,
			FEATURE_STANDARD_SECURITY_TOOLS,
			FEATURE_TRAFFIC_TOOLS,
			FEATURE_BLANK,
		],
	},

	[ JetpackPlans.PLAN_JETPACK_PREMIUM ]: {
		...getJetpackPremiumDetails(),
		...getAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_PREMIUM_MONTHLY ]: {
		...getJetpackPremiumDetails(),
		...getMonthlyTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_PERSONAL ]: {
		...getJetpackPersonalDetails(),
		...getAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_PERSONAL_MONTHLY ]: {
		...getJetpackPersonalDetails(),
		...getMonthlyTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_BUSINESS ]: {
		...getJetpackBusinessDetails(),
		...getAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_BUSINESS_MONTHLY ]: {
		...getJetpackBusinessDetails(),
		...getMonthlyTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_DAILY ]: {
		...getPlanJetpackSecurityDailyDetails(),
		...getAnnualTimeframe(),
		getMonthlySlug: () => JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY, //used
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_DAILY_MONTHLY ]: {
		...getPlanJetpackSecurityDailyDetails(),
		...getMonthlyTimeframe(),
		getAnnualSlug: () => JetpackPlans.PLAN_JETPACK_SECURITY_DAILY,
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME ]: {
		...getPlanJetpackSecurityRealtimeDetails(),
		...getAnnualTimeframe(),
		getMonthlySlug: () => JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME_MONTHLY ]: {
		...getPlanJetpackSecurityRealtimeDetails(),
		...getMonthlyTimeframe(),
		getAnnualSlug: () => JetpackPlans.PLAN_JETPACK_SECURITY_REALTIME,
	},

	[ JetpackPlans.PLAN_JETPACK_COMPLETE_BI_YEARLY ]: {
		...getPlanJetpackCompleteDetails(),
		...getBiAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_COMPLETE ]: {
		...getPlanJetpackCompleteDetails(),
		...getAnnualTimeframe(),
		getMonthlySlug: () => JetpackPlans.PLAN_JETPACK_COMPLETE_MONTHLY,
	},

	[ JetpackPlans.PLAN_JETPACK_COMPLETE_MONTHLY ]: {
		...getPlanJetpackCompleteDetails(),
		...getMonthlyTimeframe(),
		getAnnualSlug: () => JetpackPlans.PLAN_JETPACK_COMPLETE,
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_T1_BI_YEARLY ]: {
		...getPlanJetpackSecurityT1Details(),
		...getBiAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_T1_YEARLY ]: {
		...getPlanJetpackSecurityT1Details(),
		...getAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_T1_MONTHLY ]: {
		...getPlanJetpackSecurityT1Details(),
		...getMonthlyTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_T2_YEARLY ]: {
		...getPlanJetpackSecurityT2Details(),
		...getAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_SECURITY_T2_MONTHLY ]: {
		...getPlanJetpackSecurityT2Details(),
		...getMonthlyTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_STARTER_YEARLY ]: {
		...getPlanJetpackStarterDetails(),
		...getAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_STARTER_MONTHLY ]: {
		...getPlanJetpackStarterDetails(),
		...getMonthlyTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_GROWTH_MONTHLY ]: {
		...getPlanJetpackGrowthDetails(),
		...getMonthlyTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_GROWTH_YEARLY ]: {
		...getPlanJetpackGrowthDetails(),
		...getAnnualTimeframe(),
		getMonthlySlug: () => JetpackPlans.PLAN_JETPACK_GROWTH_MONTHLY,
	},

	[ JetpackPlans.PLAN_JETPACK_GROWTH_BI_YEARLY ]: {
		...getPlanJetpackGrowthDetails(),
		...getBiAnnualTimeframe(),
	},

	[ JetpackPlans.PLAN_JETPACK_GOLDEN_TOKEN ]: {
		...getPlanJetpackGoldenTokenDetails(),
		...getAnnualTimeframe(),
		getMonthlySlug: () => JetpackPlans.PLAN_JETPACK_GOLDEN_TOKEN,
	},

	[ PLAN_P2_PLUS ]: {
		...getDotcomPlanDetails(),
		group: 'GROUP_P2',
		type: 'TYPE_P2_PLUS',
		getPlanCompareFeatures: () => [
			// pay attention to ordering, shared features should align on /plan page
			FEATURE_P2_13GB_STORAGE,
			FEATURE_P2_ADVANCED_SEARCH,
			FEATURE_P2_VIDEO_SHARING,
			FEATURE_P2_MORE_FILE_TYPES,
			FEATURE_P2_PRIORITY_CHAT_EMAIL_SUPPORT,
			FEATURE_P2_ACTIVITY_OVERVIEW,
		],

		// TODO: update this once we put P2+ in the signup.
		getSignupFeatures: () => [ FEATURE_FAST_SUPPORT_FROM_EXPERTS ],

		// TODO: no idea about this, copied from the WP.com Premium plan.
		// Features not displayed but used for checking plan abilities
		getIncludedFeatures: () => [
			FEATURE_AUDIO_UPLOADS,
			FEATURE_JETPACK_SEARCH_BI_YEARLY,
			FEATURE_JETPACK_SEARCH,
			FEATURE_JETPACK_SEARCH_MONTHLY,
		],

		...getMonthlyTimeframe(),
		availableFor: ( plan ) => [ PLAN_FREE ].includes( plan ), //TODO: only for P2 sites.
	},
};

PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_P2_FREE ] = {
	...PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_FREE ],
	group: 'GROUP_P2',
	getPlanCompareFeatures: () => [
		// pay attention to ordering, shared features should align on /plan page
		FEATURE_P2_3GB_STORAGE,
		FEATURE_P2_UNLIMITED_USERS,
		FEATURE_P2_UNLIMITED_POSTS_PAGES,
		FEATURE_P2_SIMPLE_SEARCH,
		FEATURE_P2_CUSTOMIZATION_OPTIONS,
	],
};

// Brand new WPCOM plans
PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_WPCOM_STARTER ] = {
	...getDotcomPlanDetails(),
	group: 'GROUP_WPCOM',
	type: 'TYPE_STARTER',
	term: 'TERM_ANNUALLY',
	getPlanCompareFeatures: () => [
		FEATURE_UNLIMITED_TRAFFIC,
		FEATURE_MANAGED_HOSTING,
		FEATURE_FREE_THEMES,
		FEATURE_CUSTOM_DOMAIN,
		FEATURE_UNLIMITED_ADMINS,
		FEATURE_6GB_STORAGE,
		FEATURE_GOOGLE_ANALYTICS,
		FEATURE_PAYMENT_BLOCKS,
		FEATURE_TITAN_EMAIL,
	],
	getIncludedFeatures: () => [ WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS ],
};

PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_WPCOM_FLEXIBLE ] = {
	// Inherits the free plan
	...PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_FREE ],
	group: 'GROUP_WPCOM',
	type: 'TYPE_FLEXIBLE',
	getPlanCompareFeatures: () => [ FEATURE_1GB_STORAGE ],
};

PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_WPCOM_PRO ] = {
	...getPlanProDetails(),
	term: 'TERM_ANNUALLY',
};

PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_WPCOM_PRO_MONTHLY ] = {
	...getPlanProDetails(),
	...getMonthlyTimeframe(),
	availableFor: ( plan ) => [ PLAN_FREE ].includes( plan ),
};

PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_WPCOM_PRO_2_YEARS ] = {
	...getPlanProDetails(),
	term: 'TERM_BIENNIALLY',
	availableFor: ( plan ) =>
		[ PLAN_FREE, PLAN_WPCOM_STARTER, PLAN_WPCOM_PRO, PLAN_WPCOM_PRO_MONTHLY ].includes( plan ),
};

PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_ECOMMERCE_TRIAL_MONTHLY ] = {
	...getDotcomPlanDetails(),
	type: 'TYPE_ECOMMERCE',
	group: 'GROUP_WPCOM',
	term: 'TERM_MONTHLY',
};

if ( isEnabled( 'plans/migration-trial' ) ) {
	PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_MIGRATION_TRIAL_MONTHLY ] = {
		...getPlanBusinessDetails(),
		type: 'TYPE_BUSINESS',
		group: 'GROUP_WPCOM',
		term: 'TERM_MONTHLY',
	};
}

PLAN_FEATURES_AND_AVAILABILITY_LIST[ PLAN_HOSTING_TRIAL_MONTHLY ] = {
	...getPlanBusinessDetails(),
	type: 'TYPE_BUSINESS',
	group: 'GROUP_WPCOM',
	term: 'TERM_MONTHLY',
};

interface PlanMatchesQuery {
	term?: string;
	group?: string;
	type?: string;
}

/**
 * Matches plan specified by `planKey` against `query`.
 * Only compares `type`, `group`, and `term` properties.
 *
 * For example:
 *
 * > planMatches( 'TYPE_BUSINESS', { term: 'TERM_ANNUALLY', group: 'GROUP_WPCOM', type: 'TYPE_BUSINESS' } );
 * true
 *
 * > planMatches( 'TYPE_BUSINESS', { term: 'TERM_BIENNIALLY' } );
 * false
 */
function planMatches( planKey: string, query: PlanMatchesQuery = {} ): boolean {
	const acceptedKeys = [ 'type', 'group', 'term' ];
	const unknownKeys = Object.keys( query ).filter( ( key ) => ! acceptedKeys.includes( key ) );
	if ( unknownKeys.length ) {
		throw new Error(
			`planMatches can only match against ${ acceptedKeys.join( ',' ) }, ` +
				`but unknown keys ${ unknownKeys.join( ',' ) } were passed.`
		);
	}

	// @TODO: make getPlanFeaturesAndAvailability() throw an error on failure. This is going to be a larger change with a separate PR.
	const plan = getPlanFeaturesAndAvailability( planKey );
	if ( ! plan ) {
		return false;
	}
	if (
		( ! ( 'type' in query ) || plan.type === query.type ) &&
		( ! ( 'group' in query ) || plan.group === query.group ) &&
		( ! ( 'term' in query ) || plan.term === query.term )
	) {
		return true;
	}
	return false;
}

function findFirstSimilarPlanKey( planKey: string, diff: PlanMatchesQuery ): string | undefined {
	return findSimilarPlansKeys( planKey, diff )[ 0 ];
}

/**
 * A similar plan is one that has the same `type`, `group`, and `term` as first
 * argument, except for differences specified in the second argument.
 *
 * For example:
 *
 * > findSimilarPlansKeys( 'TYPE_BUSINESS', { term: 'TERM_BIENNIALLY' } );
 * [PLAN_BUSINESS_2_YEARS]
 * > findSimilarPlansKeys( TYPE_JETPACK_BUSINESS_MONTHLY, { type: TYPE_ANNUALLY } );
 * [TYPE_JETPACK_BUSINESS]
 */
function findSimilarPlansKeys( planKey: string, diff: PlanMatchesQuery = {} ): string[] {
	const plan = getPlanFeaturesAndAvailability( planKey );
	// @TODO: make getPlanFeaturesAndAvailability() throw an error on failure. This is going to be a larger change with a separate PR.
	if ( ! plan ) {
		return [];
	}
	return findPlansKeys( {
		type: plan.type,
		group: plan.group,
		term: plan.term,
		...diff,
	} );
}

/**
 * Finds all keys of plans matching a query
 *
 * For example:
 *
 * > findPlansKeys( { term: 'TERM_BIENNIALLY' } );
 * [PLAN_PERSONAL_2_YEARS, PLAN_PREMIUM_2_YEARS, PLAN_BUSINESS_2_YEARS]
 */
function findPlansKeys( query: PlanMatchesQuery = {} ): string[] {
	const plans = getPlans();
	return Object.keys( plans ).filter( ( k ) => planMatches( k, query ) );
}

export function isFreePlan( planSlug: string ): boolean {
	return planMatches( planSlug, { type: 'TYPE_FREE' } );
}

//used
export function isJetpackPlanSlug( productSlug: string ): boolean {
	return planMatches( productSlug, { group: 'GROUP_JETPACK' } );
}

function getPlans(): Record< string, TemporaryPlanProductFeaturesAndGrouping > {
	return PLAN_FEATURES_AND_AVAILABILITY_LIST;
}

//used
export function getPlanFeaturesAndAvailability(
	planKey: string | TemporaryPlanProductFeaturesAndGrouping
): TemporaryPlanProductFeaturesAndGrouping | undefined {
	if ( typeof planKey !== 'string' ) {
		if ( Object.values( PLAN_FEATURES_AND_AVAILABILITY_LIST ).includes( planKey ) ) {
			return planKey;
		}
		return undefined;
	}
	return PLAN_FEATURES_AND_AVAILABILITY_LIST[ planKey ];
}
//replace with
export function getPlanFromPlans(
	plans: PlanProduct[],
	planSlug: string
): PlanProduct | undefined {
	return plans ? plans.find( ( plan ) => planSlug === plan.product_slug ) : undefined;
}

/**
 * Returns the monthly slug which corresponds to the provided yearly slug or "" if the slug is
 * not a recognized or cannot be converted.
 */
//used
export function getMonthlyPlanByYearly( planSlug: string ): string {
	const plan = getPlanFeaturesAndAvailability( planSlug );
	if ( plan && 'getMonthlySlug' in plan && plan.getMonthlySlug ) {
		return plan.getMonthlySlug();
	}
	return findFirstSimilarPlanKey( planSlug, { term: 'TERM_MONTHLY' } ) || '';
}

//used
export const getDowngradePlanFromPurchase = ( plans: PlanProduct[], purchase: Purchase ) => {
	const plan = getPlanFeaturesAndAvailability( purchase.product_slug );
	if ( ! plan ) {
		return null;
	}

	const newPlanKeys = findPlansKeys( {
		group: plan.group,
		type: 'TYPE_PERSONAL',
		term: plan.term,
	} );

	return getPlanFromPlans( plans, newPlanKeys[ 0 ] );
};

//used
export function isSecurityDailyPlan( planSlug: string ): boolean {
	return planMatches( planSlug, { type: 'TYPE_SECURITY_DAILY' } );
}

//used
export function isSecurityRealTimePlan( planSlug: string ): boolean {
	return planMatches( planSlug, { type: 'TYPE_SECURITY_REALTIME' } );
}

//used
export function isCompletePlan( planSlug: string ): boolean {
	return planMatches( planSlug, { type: 'TYPE_ALL' } );
}

//used
export function isWpComBusinessPlan( planSlug: string ): boolean {
	return planMatches( planSlug, { type: 'TYPE_BUSINESS', group: 'GROUP_WPCOM' } );
}

//used
export function isWpComEcommercePlan( planSlug: string ): boolean {
	return planMatches( planSlug, { type: 'TYPE_ECOMMERCE', group: 'GROUP_WPCOM' } );
}

//used
export function isWpComPremiumPlan( planSlug: string ): boolean {
	return planMatches( planSlug, { type: 'TYPE_PREMIUM', group: 'GROUP_WPCOM' } );
}

//used
export function isWpComAnnualPlan( planSlug: string ): boolean {
	return planMatches( planSlug, { term: 'TERM_ANNUALLY', group: 'GROUP_WPCOM' } );
}

//used
export function isWpComBiennialPlan( planSlug: string ): boolean {
	return planMatches( planSlug, { term: 'TERM_BIENNIALLY', group: 'GROUP_WPCOM' } );
}

//used
export function isWpComTriennialPlan( planSlug: string ): boolean {
	return planMatches( planSlug, { term: 'TERM_TRIENNIALLY', group: 'GROUP_WPCOM' } );
}

//used
export function isWpComMonthlyPlan( planSlug: string ): boolean {
	return planMatches( planSlug, { term: 'TERM_MONTHLY', group: 'GROUP_WPCOM' } );
}
