name: Flaky E2E Spec Report
description: Noticed an erratic E2E spec? Report it!
title: "Flaky E2E:"
labels: "Flaky e2e"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a flaky spec!
  - type: input
    id: spec
    attributes:
      label: Spec file
      placeholder: eg. wp-likes__post.js
    validations:
      required: true
  - type: input
    id: suite
    attributes:
      label: Suite or step
      placeholder: eg. Like new post
  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which framework does the spec belong to?
      options:
        - Selenium
        - Playwright
      multiple: true
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add relevant logs.
    validations:
      required: true
