---
name: Gutenberg Plugin Upgrade
about: Installing and activating a new version of the Gutenberg plugin
title: 'Gutenberg: [v#.#.#] plugin upgrade'
labels: [Type] Task, gutenberg-upgrade
assignees: ''
body:
 - type: markdown
   attributes:
     value: |
       <!--
       Thanks for updating the current version of Gutenberg! Please be sure to update the title above with the version number you're upgrading.
       If you're updating multiple versions (for example, 11.0.0 to production and 11.0.1 to edge), please indicate with an 'x' where appropriate
       (for example, v11.0.x)

       - Previous Upgrade issue should be linked using Github issue numbers (for example, #53725)
       - Release notes for the version(s) you're implementing should be linked directly to the WordPress/gutenberg repo tag
       (for example, linking the text 'v11.0.0-rc.1' to https://github.com/WordPress/gutenberg/releases/tag/v11.0.0-rc.1)
        -->
        Previous upgrade:  
        Release notes:

        <!--
        As you complete the tasks in this list, please update the relevant lines with diff and other IDs
        -->
- type: checkboxes
  id: upgrade-steps
  attributes:
    options:
       -label: Install and activate
          - label: 'Copy & install [version #] (######-code, ######-code)'
          - label: 'Activate [version #] on edge (######-code)'
          - label: 'Copy & install [version #] (######-code, ######-code)'
          - label: 'Activate [version #] on edge (######-code)'
          - label: 'Activate [version #] on production (######-code)'
          - label: 'Request AT upgrade (######-p2)'
       - label: Testing
          - label: Desktop viewport E2E
          - label: Mobile viewport E2E
          - label: WPCOM (######-code)
       - label: Publish internal announcements
          - label: 'Slack: #team-calypso'
          - label: 'Slack: #wpcom-happy-announce'
          - label: 'P2: wpcomhappy'
       - label: Clean up unused releases
       - label: Add log entry to the Gutenberg Upgrade Log (######-p2)
       - label: Open a new issue for the next upgrade, transfer remaining tasks, close this issue.
- type: markdown
  attributes:
    value: |
      ### Blockers 🤷‍♀️

      ### Other Issues 🐛

      **Issues transferred from previous release(s)**

 ___
 cc @inaikem @simison
---

