name: Happiness Bug Report
description: Helps us improve our product!
labels: "User Report, [Type] Bug"
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for contributing to calypso! Pick a clear title and proceed.
        
        &nbsp;
        
  - type: textarea
    id: summary
    attributes:
        label: Quick summary

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Start at /home.
        2. Click on View Site.
        3. Click on 'Like' button.
        ...

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
 - type: textarea
    id: expected
    attributes:
      label: What I expected to happen
      placeholder: |
        e.g. Post should be liked.
    validations:
      required: true
 
  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
 - type: textarea
    id: actual
    attributes:
      label: What actually happened
      placeholder: |
        eg. Clicking the button does nothing visibly.

        Attach screenshot(s) or recording(s) by dragging into this field.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
  - type: textarea
    id: issue_context
    attributes:
      label: Context
      placeholder: |
        eg. Customer report, exploratory testing...

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
  - type: markdown
    attributes:
      value: |
        ---

  - type: markdown
    attributes:
      value: |
        
        &nbsp;

   - type: markdown
    attributes:
      value: |
        ### Screenshots
        
        &nbsp;

        Please complete submit this form then upload your screenshots as a reply.
        
        &nbsp;
        
 - type: dropdown
    id: os
    attributes:
      label: OS
      description: Multiple selection is supported.
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
      multiple: true

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Multiple selection is supported.
      options:
        - Chrome/Chromium
        - Firefox
        - Microsoft Edge
        - Microsoft Edge (legacy)
        - Safari
      multiple: true

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
  - type: dropdown
    id: site-type
    attributes:
      label: Simple or Atomic
      description: Multiple selection is supported.
      options:
        - Simple
        - Atomic
      multiple: true
  - type: input

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
    id: theme
    attributes:
      label: Theme-specific issue?
      placeholder: |
        If yes - what is the theme name?

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
  - type: textarea
    id: other_notes
    attributes:
      label: Other notes
      placeholder: |
        Logs, console errors, notes, observations, etc.
  - type: markdown

  - type: markdown
    attributes:
      value: |
        
        &nbsp;
        
  - type: markdown
    attributes:
      value: |
        ---

  - type: markdown
    attributes:
      value: |
        
        &nbsp;

  - type: dropdown

    id: reproducibility
    attributes:
      label: Reproducibility
      options:
        - Consistent
        - Intermittent
        - Once
  - type: dropdown

    id: users-affected 
    attributes:
      label: Number of users impacted
      description: How many users do you think might encounter this bug? Best guesses are fine!
      options:
        - One user
        - Some users (<50%)
        - Most users (>50%)
        - All users

  - type: textarea
    id: workarounds
    attributes:
      label: Any available workarounds?
      description: Are there any workarounds to this bug? How difficult are those workarounds to implement?
      placeholder: |
        e.g. There is alternative access to this setting in the sidebar, but it's not readily apparent.
