name: Happiness Bug Report
description: Helps us improve our product!
labels: "User Report, [Type] Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to calypso! Pick a clear title and proceed.
  - type: textarea
    id: summary
    attributes:
        label: Summary
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Start at /home.
        2. Click on View Site.
        3. Click on 'Like' button.
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What I expected to happen
      placeholder: |
        eg. Post should be liked.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened
      placeholder: |
        eg. Clicking the button does nothing visibly.
    validations:
      required: true
  - type: textarea
    id: issue_context
    attributes:
      label: Context
      placeholder: |
        eg. Customer report, exploratory testing...
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Multiple selection is supported.
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
      multiple: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Multiple selection is supported.
      options:
        - Chrome/Chromium
        - Firefox
        - Microsoft Edge
        - Microsoft Edge (legacy)
        - Safari
      multiple: true
  - type: input
    id: browser_versions
    attributes:
      label: Browser Version(s)
  - type: input
    id: theme
    attributes:
      label: Is this specific to applied theme? If so, what is the theme name?
  - type: textareas
    id: other_notes
    attributes:
      label: Other notes
      description: Logs, console errors, notes, observations, etc.
  - type: dropdown
    id: site-type
    attributes:
      label: Simple/Atomic
      description: Multiple selection is supported.
      options:
        - Simple
        - Atomic
      multiple: true
  - type: markdown
        attributes:
          value: Reproducibility Information
  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      options:
        - Consistent
        - Intermittent
        - Once
        - Never
  - type: dropdown
    id: users-affected
    attributes:
      label: Number of Users Impacted
      description: How many users do you think might encounter this bug? Best guesses are fine!
      options:
        - One user
        - Some users (<50%)
        - Most users (>50%)
        - All users
  - type: textarea
    id: workarounds
    attributes:
      label: Available Workarounds
      description: Are there any workarounds to this bug? How difficult are those workarounds?
      placeholder: |
        eg. There is alternative access to this setting in the sidebar, but it's not readily apparent.
