name: Simple-Atomic Feature Parity
description: Did you find something inconsistent or unexpected between the two platforms?
title: "Feature Parity:"
labels: "Simple/Atomic Parity"
body:
  - type: dropdown
    id: plan
    attributes:
      label: What plan tier(s) are affected?
      multiple: true
      options:
        - Free
        - Personal
        - Premium
        - Business
        - eCommerce
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: expected-simple
    attributes:
      label: Expected (Simple)
      description: Behavior expected on a simple WordPress.com site.
    validations:
      required: true
  - type: textarea
    id: expected-atomic
    attributes:
      label: Expected (Atomic)
      description: Behavior expected on an atomic WordPress.com site.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
      description: Behavior observed.
    validations:
      required: true
  - type: input
    id: theme-specific
    attributes:
      label: Is this specific to the applied theme? If so, which one?
