/** @format */
export const fromApi = ( {
	job_manager_allowed_application_method,
	job_manager_category_filter_type,
	job_manager_date_format,
	job_manager_enable_categories,
	job_manager_enable_default_category_multiselect,
	job_manager_enable_registration,
	job_manager_enable_types,
	job_manager_generate_username_from_email,
	job_manager_google_maps_api_key,
	job_manager_hide_expired,
	job_manager_hide_expired_content,
	job_manager_hide_filled_positions,
	job_manager_job_dashboard_page_id,
	job_manager_jobs_page_id,
	job_manager_multi_job_type,
	job_manager_per_page,
	job_manager_registration_role,
	job_manager_submission_duration,
	job_manager_submission_requires_approval,
	job_manager_submit_job_form_page_id,
	job_manager_use_standard_password_setup_email,
	job_manager_user_can_edit_pending_submissions,
	job_manager_user_requires_account,
} ) => ( {
	account: {
		enableRegistration: job_manager_enable_registration,
		generateUsername: job_manager_generate_username_from_email,
		isAccountRequired: job_manager_user_requires_account,
		role: job_manager_registration_role,
		sendPassword: job_manager_use_standard_password_setup_email,
	},
	apiKey: {
		googleMapsApiKey: job_manager_google_maps_api_key,
	},
	approval: {
		canEdit: job_manager_user_can_edit_pending_submissions,
		isApprovalRequired: job_manager_submission_requires_approval,
	},
	categories: {
		categoryFilterType: job_manager_category_filter_type,
		enableCategories: job_manager_enable_categories,
		enableDefaultCategory: job_manager_enable_default_category_multiselect,
	},
	duration: {
		submissionDuration: job_manager_submission_duration,
	},
	format: {
		dateFormat: job_manager_date_format,
	},
	listings: {
		hideExpired: job_manager_hide_expired,
		hideExpiredContent: job_manager_hide_expired_content,
		hideFilledPositions: job_manager_hide_filled_positions,
		perPage: job_manager_per_page,
	},
	method: {
		applicationMethod: job_manager_allowed_application_method,
	},
	pages: {
		dashboardPage: job_manager_job_dashboard_page_id,
		listingsPage: job_manager_jobs_page_id,
		submitFormPage: job_manager_submit_job_form_page_id,
	},
	types: {
		enableTypes: job_manager_enable_types,
		multiJobType: job_manager_multi_job_type,
	},
} );

export const toApi = ( {
	applicationMethod,
	canEdit,
	categoryFilterType,
	dashboardPage,
	dateFormat,
	enableCategories,
	enableDefaultCategory,
	enableRegistration,
	enableTypes,
	generateUsername,
	googleMapsApiKey,
	hideExpired,
	hideExpiredContent,
	hideFilledPositions,
	isAccountRequired,
	isApprovalRequired,
	listingsPage,
	multiJobType,
	perPage,
	role,
	sendPassword,
	submissionDuration,
	submitFormPage,
} ) => ( {
	job_manager_allowed_application_method: applicationMethod,
	job_manager_category_filter_type: categoryFilterType,
	job_manager_date_format: dateFormat,
	job_manager_enable_categories: enableCategories,
	job_manager_enable_default_category_multiselect: enableDefaultCategory,
	job_manager_enable_registration: enableRegistration,
	job_manager_enable_types: enableTypes,
	job_manager_generate_username_from_email: generateUsername,
	job_manager_google_maps_api_key: googleMapsApiKey,
	job_manager_hide_expired: hideExpired,
	job_manager_hide_expired_content: hideExpiredContent,
	job_manager_hide_filled_positions: hideFilledPositions,
	job_manager_job_dashboard_page_id: dashboardPage,
	job_manager_jobs_page_id: listingsPage,
	job_manager_multi_job_type: multiJobType,
	job_manager_per_page: perPage,
	job_manager_registration_role: role,
	job_manager_submission_duration: submissionDuration,
	job_manager_submission_requires_approval: isApprovalRequired,
	job_manager_submit_job_form_page_id: submitFormPage,
	job_manager_use_standard_password_setup_email: sendPassword,
	job_manager_user_can_edit_pending_submissions: canEdit,
	job_manager_user_requires_account: isAccountRequired,
} );
