/** @format */

export const hints = [
	'3D',
	'Abuse',
	'Academic research',
	'Accessories',
	'Accountant',
	'Accounting services',
	'Acoustics',
	'Acting',
	'Activisim',
	'Adventure',
	'Advertising',
	'Advocacy and human rights',
	'Advocacy group',
	'Advocate',
	'Affiliate',
	'Agriculture',
	'Air conditioning',
	'Allah',
	'Allergies',
	'Animals',
	'Animation',
	'Anime',
	'Antiques',
	'Anxiety',
	'Anxiety and depression',
	'App',
	'Apparel',
	'Architecture',
	'Archive',
	'Armed forces',
	'Army',
	'Art',
	'Art lessons',
	'Art school',
	'Artist',
	'Artists',
	'Arts',
	'Assistant',
	'Association',
	'Astronomy',
	'Aurthor',
	'Author',
	'Autisim',
	'Auto body repair',
	'Automotive business',
	'Babies',
	'Baby showers',
	'Bags',
	'Bakery',
	'Baking',
	'Band',
	'Barber',
	'Basketball',
	'Bathroom fitter',
	'Beautician',
	'Beauty',
	'Beauty and wellness',
	'Beauty blog',
	'Beauty business',
	'Beauty salon',
	'Beauty services',
	'Beauty treatments',
	'Bed and breakfast',
	'Beer',
	'Bible',
	'Bible studies',
	'Biofuels',
	'Biofuels and biotechnology',
	'Biotechnology',
	'Blog',
	'Bonsai',
	'Bonsai trees',
	'Book',
	'Book reviews',
	'Bookbinder',
	'Bookbinding',
	'Bookkeeping',
	'Books',
	'Brain injury',
	'Bread',
	'Broadcasting',
	'Buddhism',
	'Building',
	'Business',
	'Business consultant',
	'Business consulting services',
	'Business development',
	'Business life',
	'Business services',
	'CBD',
	'CCTV',
	'Cafe',
	'Cake',
	'Cakes',
	'Cancer',
	'Cannabis',
	'Car audio',
	'Car repairs',
	'Cars',
	'Cats',
	'Celebrities',
	'Ceramics',
	'Charity',
	'Child abuse',
	'Childbirth',
	'Chinese restaurant',
	'Choir',
	'Christ',
	'Christianity',
	'Church',
	'Classified ads',
	'Cleaning services',
	'Climate change',
	'Clinic',
	'Clothes',
	'Clothing',
	'Coach',
	'Coaching',
	'Coding',
	'Coffee',
	'Coffee shop',
	'College',
	'Comedy',
	'Commercial',
	'Communication',
	'Community',
	'Community association',
	'Community services',
	'Computer',
	'Computer repairs',
	'Computing',
	'Concrete restorations',
	'Conduits',
	'Conference',
	'Construction',
	'Construction engineer',
	'Consultant',
	'Consulting',
	'Consulting agency',
	'Consulting business',
	'Consulting engineering',
	'Consumables',
	'Content creation',
	'Cooking',
	'Copywriting',
	'Corporate services',
	'Corrosion engineering',
	'Cosmetics',
	'Cosplay',
	'Councelling',
	'Counseling',
	'Counseling services',
	'Craft beer',
	'Crafting',
	'Creative writing',
	'Credit repair',
	'Crime prevention',
	'Crossfit',
	'Crowd funding',
	'Crypto currency',
	'Culture',
	'Cupcakes',
	'Current affairs',
	'Cycling',
	'DIY',
	'DJ',
	'DVDs',
	'Daily life',
	'Data',
	'Data visualization',
	'Dating',
	'Daycare',
	'Deals',
	'Depression',
	'Design',
	'Design portfolio',
	'Dessert',
	'Devops',
	'Diagnostic machine design',
	'Diary',
	'Digital design',
	'Digital portfolio',
	'Digitization',
	'Disease',
	'Dog boarding kennel',
	'Dog grooming',
	'Dogs',
	'Domestic violence prevention',
	'Drawing portfolio',
	'Drawings',
	'Dream coaching',
	'Dream interpretations',
	'Dreams',
	'Dresses',
	'Drinks',
	'Drugs',
	'Dungeons and dragons',
	'E-book',
	'E-books',
	'E-commerce',
	'Early childhood services',
	'Ecological',
	'Ecosystem',
	'Editing',
	'Education',
	'Educational books',
	'Educational services',
	'Eggs',
	'Electrical design',
	'Electrical panels',
	'Electrician',
	'Electronic components',
	'Electronic music',
	'Electronics',
	'Embroidery',
	'Emotions',
	'Employment',
	'Energy efficient appliances',
	'Engineering',
	'Engineering services',
	'Engineering software',
	'English',
	'English lessons',
	'Enterprise',
	'Entertainment',
	'Entrepreneur',
	'Entrepreneurship',
	'Environment',
	'Environment consultant',
	'Equestrian',
	'Equity',
	'Esteticien',
	'Esthetician',
	'Evangelisim',
	'Event',
	'Event promotion',
	'Events',
	'Excel',
	'Exploration',
	'Eye doctor',
	'Face painting',
	'Faith',
	'Family',
	'Fan fiction',
	'Farm',
	'Farming',
	'Fashion',
	'Fashion critic',
	'Fashion design',
	'Feelings',
	'Festival',
	'Fiction writing',
	'Film production',
	'Films',
	'Financial',
	'Financial consultant',
	'Financial services',
	'Fine art',
	'First nations',
	'Fishing',
	'Fitness',
	'Florist',
	'Flying club',
	'Food',
	'Food critic',
	'Football',
	'Freelance designer',
	'Freelance developer',
	'Freelance marketer',
	'Freelance services',
	'Freelance writer',
	'Funeral services',
	'Furniture',
	'Games',
	'Gaming',
	'Garments',
	'Genealogy',
	'Glamour',
	'Gloves',
	'God',
	'Golf',
	'Gospel',
	'Government and politics',
	'Graphic design',
	'Graphic novels',
	'Graphics',
	'Green technology',
	'Groceries',
	'Guitar teacher',
	'Guns',
	'Gym',
	'HIV',
	'HVAC',
	'Hacking',
	'Hair salon',
	'Hair styles',
	'Happiness',
	'Hardware',
	'Healing',
	'Health',
	'Health and beauty',
	'Health and fitness',
	'Healthcare',
	'Heat transfer vinyl',
	'Hinduism',
	'History',
	'Hobbies',
	'Holiday',
	'Holiday rentals',
	'Holidays',
	'Holistic healing',
	'Home',
	'Home decor',
	'Home improvement',
	'Home inspection',
	'Home renovation',
	'Homework',
	'Horses',
	'Hospital',
	'Hospitality',
	'Hotel',
	'House cleaning',
	'Housekeeping',
	'How to',
	'Human rights issues',
	'Humanitarian aid',
	'Hunting',
	'IT',
	'IVF treatment',
	'Ideas',
	'Illustration',
	'Image editing',
	'Importing and exporting',
	'Information',
	'Information technology',
	'Inspiration',
	'Insurance',
	'Intellectual property lawyer',
	'Interior design',
	'International logistics',
	'Internet provider',
	'Investing',
	'Investment consultancy',
	'Islam',
	'Issues',
	'Italian restaurant',
	'Japanese cartoons',
	'Jesus',
	'Jewelry',
	'Job consultancy',
	'Job listing',
	'Job posting',
	'Jobs',
	'Jokes',
	'Journalisim',
	'Journalism',
	'Juicebar',
	'Kids',
	'Kids yoga',
	'Kitchen',
	'Knowledge',
	'LARP',
	'Law',
	'Leadership',
	'Leather',
	'Lemons',
	'Life',
	'Life coach',
	'Life inspiration',
	'Lifestyle',
	'Lifestyle blog',
	'Literary portfolio',
	'Literature',
	'Living',
	'Local music',
	'Local news',
	'Love',
	'Love stories',
	'Maid services',
	'Makeup',
	'Manga',
	'Maps',
	'Marketing',
	'Marketing services',
	'Massages',
	'Mathematics',
	'Mechanic',
	'Medial news',
	'Medical',
	'Medical technology',
	'Medicine',
	'Meditation',
	'Men',
	"Men's heatlh",
	'Mental health',
	'Mexican restaurant',
	'Military',
	'Militia',
	'Milk',
	'Minecraft',
	'Ministry',
	'Mobile app',
	'Mobile electronics',
	'Mommy blog',
	'Motivation',
	'Motivational speaker',
	'Motorhomes',
	'Movie production',
	'Movies',
	'Moving service',
	'Moving services',
	'Multimedia',
	'Multimedia law',
	'Multimedia production',
	'Music',
	'Music classes',
	'Music lessons',
	'Music production',
	'Musician',
	'Mystery',
	'Natural health products',
	'Natural health remedies',
	'Network marketing',
	'Networking',
	'News',
	'Newspaper',
	'Non-profit',
	'Novel',
	'Nutrition',
	'Online business',
	'Online store',
	'Optician',
	'Optomitrist',
	'Organic farming',
	'Organization',
	'Outdoors',
	'Outfits',
	'Painter',
	'Painting',
	'Paranormal',
	'Parenting',
	'Parties',
	'Party promotion',
	'Performance art',
	'Performer',
	'Perfume',
	'Personal',
	'Personal blog',
	'Personal development',
	'Personal experiences',
	'Personal finance',
	'Personal issues',
	'Personal trainer',
	'Personal training',
	'Personal website',
	'Pet services',
	'Pets',
	'Philosopher',
	'Philosophy',
	'Photocopier',
	'Photocopy repairs',
	'Photographer',
	'Photography',
	'Photos',
	'Physical therapy',
	'Physiotherapy',
	'Pizza shop',
	'Plumber',
	'Podcast',
	'Poems',
	'Poetry',
	'Pokémon',
	'Polical activisim',
	'Policial candidate',
	'Political analysis',
	'Politics',
	'Pollution',
	'Portfolio',
	'Portrait artist',
	'Pregnancy',
	'Presentations',
	'Print design',
	'Printing',
	'Private consulting',
	'Product',
	'Product marketing',
	'Product reviews',
	'Product sales',
	'Professional cleaning service',
	'Professional portfolio',
	'Professional profile',
	'Professional services',
	'Promotional marketing',
	'Promotional products',
	'Promotions',
	'Property',
	'Psychotherapy',
	'Quiz',
	'Quotes',
	'Quran',
	'RVs',
	'Racism',
	'Real estate',
	'Recipes',
	'Recreation center',
	'Recruiting',
	'Recruitment',
	'Recruitment consultant',
	'Relationships',
	'Religion',
	'Renewable energy',
	'Renovation',
	'Reporter',
	'Research',
	'Researcher',
	'Resort',
	'Resources',
	'Restaurant',
	'Resume',
	'Retail',
	'Reviews',
	'Robotics',
	'Romance',
	'Running',
	'Sailing',
	'Sales',
	'Salon',
	'Saving money',
	'Savings',
	'Scholarship',
	'School',
	'School activities',
	'School project',
	'School website',
	'Science',
	'Scouts',
	'Security',
	'Self cae',
	'Self help',
	'Self improvement',
	'Self improvement services',
	'Self-help',
	'Selling art',
	'Selling clothes',
	'Selling products',
	'Seniors',
	'Seo services',
	'Service agency',
	'Sewing',
	'Shamanism',
	'Shirts',
	'Shoes',
	'Shopping',
	'Short stories',
	'Singing',
	'Singing lessons',
	'Skincare',
	'Smoothies',
	'Soccer',
	'Social media',
	'Software',
	'Software and hardware',
	'Solutions',
	'Songs',
	'Space',
	'Speed dating',
	'Spiritual',
	'Spiritual coaching',
	'Spirituality',
	'Sport',
	'Sports',
	'Stationary supplies',
	'Statistics',
	'Steel protection',
	'Stock market',
	'Stocks',
	'Store',
	'Storefront',
	'Stories',
	'Student',
	'Student association',
	'Student housing',
	'Students union',
	'Style',
	'Stylist',
	'Subscriptions',
	'Suicide prevention',
	'Supplements',
	'Supplies',
	'Support',
	'Sustainable development',
	'Swimmping pools',
	'Swimmping pools repairs',
	'TV',
	'TV shows',
	'Tactical gear',
	'Tattoo parlor',
	'Tattoos',
	'Taxes',
	'Taxi business',
	'Taxidermy',
	'Teaching',
	'Tech',
	'Tech blog',
	'Technical recruiting',
	'Technical support',
	'Technology',
	'Telecommunications',
	'Therapy',
	'Thoughts',
	'Time',
	'Tips',
	'Tourism',
	'Tourism accomodation',
	'Toys',
	'Trading',
	'Translation services',
	'Transport',
	'Travel',
	'Travel agent',
	'Traveller blog',
	'Troubleshooting',
	'Turorials',
	'UI',
	'UI designer',
	'University',
	'User interface',
	'User interface design',
	'VR',
	'VR glasses',
	'Vacation rental',
	'Vacations',
	'Vaccinations',
	'Vaccines',
	'Veterans',
	'Veterans affairs',
	'Video',
	'Video games',
	'Videography',
	'Virtual assistant',
	'Virtual reality',
	'Walking',
	'War',
	'Warehouse',
	'Watches',
	'Watchmaking',
	'Web design',
	'Web designer',
	'Web developer',
	'Wedding',
	'Wedding planner',
	'Weight loss',
	'Weightlifting',
	'Well-being',
	'Wellness',
	'Window blinds',
	'Wine',
	'Women',
	"Women's health",
	'Words',
	'Work performance',
	'Workshop',
	'World issues',
	'World news',
	'Writer',
	'Writing',
	'Yoga',
	'Yoga for kids',
	'Youtube videos',
];
