/** @format */
/**
 * External dependencies
 */
import i18n from 'i18n-calypso';

export const hints = {
	'3D': i18n.translate( '3D' ),
	Abuse: i18n.translate( 'Abuse' ),
	'Academic research': i18n.translate( 'Academic research' ),
	Accessories: i18n.translate( 'Accessories' ),
	Accountant: i18n.translate( 'Accountant' ),
	'Accounting services': i18n.translate( 'Accounting services' ),
	Acoustics: i18n.translate( 'Acoustics' ),
	Acting: i18n.translate( 'Acting' ),
	Activism: i18n.translate( 'Activism' ),
	Adventure: i18n.translate( 'Adventure' ),
	Advertising: i18n.translate( 'Advertising' ),
	'Advocacy of human rights': i18n.translate( 'Advocacy of human rights' ),
	'Advocacy group': i18n.translate( 'Advocacy group' ),
	Advocate: i18n.translate( 'Advocate' ),
	Aesthetician: i18n.translate( 'Aesthetician' ),
	Affiliate: i18n.translate( 'Affiliate' ),
	Agriculture: i18n.translate( 'Agriculture' ),
	'Air conditioning': i18n.translate( 'Air conditioning' ),
	Allah: i18n.translate( 'Allah' ),
	Allergies: i18n.translate( 'Allergies' ),
	Animals: i18n.translate( 'Animals' ),
	Animation: i18n.translate( 'Animation' ),
	Anime: i18n.translate( 'Anime' ),
	Antiques: i18n.translate( 'Antiques' ),
	Anxiety: i18n.translate( 'Anxiety' ),
	'Anxiety and depression': i18n.translate( 'Anxiety and depression' ),
	App: i18n.translate( 'App' ),
	Apparel: i18n.translate( 'Apparel' ),
	Architecture: i18n.translate( 'Architecture' ),
	Archive: i18n.translate( 'Archive' ),
	'Armed forces': i18n.translate( 'Armed forces' ),
	Army: i18n.translate( 'Army' ),
	Art: i18n.translate( 'Art' ),
	'Art lessons': i18n.translate( 'Art lessons' ),
	'Art school': i18n.translate( 'Art school' ),
	Artist: i18n.translate( 'Artist' ),
	Artists: i18n.translate( 'Artists' ),
	Arts: i18n.translate( 'Arts' ),
	Assistant: i18n.translate( 'Assistant' ),
	Association: i18n.translate( 'Association' ),
	Astronomy: i18n.translate( 'Astronomy' ),
	Author: i18n.translate( 'Author' ),
	Autisim: i18n.translate( 'Autisim' ),
	'Auto body repair': i18n.translate( 'Auto body repair' ),
	'Automotive business': i18n.translate( 'Automotive business' ),
	Babies: i18n.translate( 'Babies' ),
	'Baby showers': i18n.translate( 'Baby showers' ),
	Bags: i18n.translate( 'Bags' ),
	Bakery: i18n.translate( 'Bakery' ),
	Baking: i18n.translate( 'Baking' ),
	Band: i18n.translate( 'Band' ),
	Barber: i18n.translate( 'Barber' ),
	Basketball: i18n.translate( 'Basketball' ),
	'Bathroom fitter': i18n.translate( 'Bathroom fitter' ),
	Beautician: i18n.translate( 'Beautician' ),
	Beauty: i18n.translate( 'Beauty' ),
	'Beauty and wellness': i18n.translate( 'Beauty and wellness' ),
	'Beauty blog': i18n.translate( 'Beauty blog' ),
	'Beauty business': i18n.translate( 'Beauty business' ),
	'Beauty salon': i18n.translate( 'Beauty salon' ),
	'Beauty services': i18n.translate( 'Beauty services' ),
	'Beauty treatments': i18n.translate( 'Beauty treatments' ),
	'Bed and breakfast': i18n.translate( 'Bed and breakfast' ),
	Beer: i18n.translate( 'Beer' ),
	Bible: i18n.translate( 'Bible' ),
	'Bible studies': i18n.translate( 'Bible studies' ),
	Biofuels: i18n.translate( 'Biofuels' ),
	'Biofuels and biotechnology': i18n.translate( 'Biofuels and biotechnology' ),
	Biotechnology: i18n.translate( 'Biotechnology' ),
	Blog: i18n.translate( 'Blog' ),
	Bonsai: i18n.translate( 'Bonsai' ),
	'Bonsai trees': i18n.translate( 'Bonsai trees' ),
	Book: i18n.translate( 'Book' ),
	'Book reviews': i18n.translate( 'Book reviews' ),
	Bookbinder: i18n.translate( 'Bookbinder' ),
	Bookbinding: i18n.translate( 'Bookbinding' ),
	Bookkeeping: i18n.translate( 'Bookkeeping' ),
	Books: i18n.translate( 'Books' ),
	'Brain injury': i18n.translate( 'Brain injury' ),
	Bread: i18n.translate( 'Bread' ),
	Broadcasting: i18n.translate( 'Broadcasting' ),
	Buddhism: i18n.translate( 'Buddhism' ),
	Building: i18n.translate( 'Building' ),
	Business: i18n.translate( 'Business' ),
	'Business consultant': i18n.translate( 'Business consultant' ),
	'Business consulting services': i18n.translate( 'Business consulting services' ),
	'Business development': i18n.translate( 'Business development' ),
	'Business life': i18n.translate( 'Business life' ),
	'Business services': i18n.translate( 'Business services' ),
	CBD: 'CBD',
	CCTV: i18n.translate( 'CCTV' ),
	Cafe: i18n.translate( 'Cafe' ),
	Cake: i18n.translate( 'Cake' ),
	Cakes: i18n.translate( 'Cakes' ),
	Cancer: i18n.translate( 'Cancer' ),
	Cannabis: i18n.translate( 'Cannabis' ),
	'Car audio': i18n.translate( 'Car audio' ),
	'Car repairs': i18n.translate( 'Car repairs' ),
	Cars: i18n.translate( 'Cars' ),
	Cats: i18n.translate( 'Cats' ),
	Celebrities: i18n.translate( 'Celebrities' ),
	Ceramics: i18n.translate( 'Ceramics' ),
	Charity: i18n.translate( 'Charity' ),
	'Child abuse': i18n.translate( 'Child abuse' ),
	Childbirth: i18n.translate( 'Childbirth' ),
	'Chinese restaurant': i18n.translate( 'Chinese restaurant' ),
	Choir: i18n.translate( 'Choir' ),
	Christ: i18n.translate( 'Christ' ),
	Christianity: i18n.translate( 'Christianity' ),
	Church: i18n.translate( 'Church' ),
	'Classified ads': i18n.translate( 'Classified ads' ),
	'Cleaning services': i18n.translate( 'Cleaning services' ),
	'Climate change': i18n.translate( 'Climate change' ),
	Clinic: i18n.translate( 'Clinic' ),
	Clothes: i18n.translate( 'Clothes' ),
	Clothing: i18n.translate( 'Clothing' ),
	Coach: i18n.translate( 'Coach' ),
	Coaching: i18n.translate( 'Coaching' ),
	Coding: i18n.translate( 'Coding' ),
	Coffee: i18n.translate( 'Coffee' ),
	'Coffee shop': i18n.translate( 'Coffee shop' ),
	College: i18n.translate( 'College' ),
	Comedy: i18n.translate( 'Comedy' ),
	Commercial: i18n.translate( 'Commercial' ),
	Communication: i18n.translate( 'Communication' ),
	Community: i18n.translate( 'Community' ),
	'Community association': i18n.translate( 'Community association' ),
	'Community services': i18n.translate( 'Community services' ),
	Computer: i18n.translate( 'Computer' ),
	'Computer repairs': i18n.translate( 'Computer repairs' ),
	Computing: i18n.translate( 'Computing' ),
	'Concrete restorations': i18n.translate( 'Concrete restorations' ),
	Conduits: i18n.translate( 'Conduits' ),
	Conference: i18n.translate( 'Conference' ),
	Construction: i18n.translate( 'Construction' ),
	'Construction engineer': i18n.translate( 'Construction engineer' ),
	Consultant: i18n.translate( 'Consultant' ),
	Consulting: i18n.translate( 'Consulting' ),
	'Consulting agency': i18n.translate( 'Consulting agency' ),
	'Consulting business': i18n.translate( 'Consulting business' ),
	'Consulting engineering': i18n.translate( 'Consulting engineering' ),
	Consumables: i18n.translate( 'Consumables' ),
	'Content creation': i18n.translate( 'Content creation' ),
	Cooking: i18n.translate( 'Cooking' ),
	Copywriting: i18n.translate( 'Copywriting' ),
	'Corporate services': i18n.translate( 'Corporate services' ),
	'Corrosion engineering': i18n.translate( 'Corrosion engineering' ),
	Cosmetics: i18n.translate( 'Cosmetics' ),
	Cosplay: i18n.translate( 'Cosplay' ),
	Counseling: i18n.translate( 'Counseling' ),
	'Counseling services': i18n.translate( 'Counseling services' ),
	'Craft beer': i18n.translate( 'Craft beer' ),
	Crafting: i18n.translate( 'Crafting' ),
	'Creative writing': i18n.translate( 'Creative writing' ),
	'Credit repair': i18n.translate( 'Credit repair' ),
	'Crime prevention': i18n.translate( 'Crime prevention' ),
	Crossfit: i18n.translate( 'Crossfit' ),
	'Crowd funding': i18n.translate( 'Crowd funding' ),
	'Crypto currency': i18n.translate( 'Crypto currency' ),
	Culture: i18n.translate( 'Culture' ),
	Cupcakes: i18n.translate( 'Cupcakes' ),
	'Current affairs': i18n.translate( 'Current affairs' ),
	Cycling: i18n.translate( 'Cycling' ),
	DIY: i18n.translate( 'DIY' ),
	DJ: i18n.translate( 'DJ' ),
	DVDs: i18n.translate( 'DVDs' ),
	'Daily life': i18n.translate( 'Daily life' ),
	Data: i18n.translate( 'Data' ),
	'Data visualization': i18n.translate( 'Data visualization' ),
	Dating: i18n.translate( 'Dating' ),
	Daycare: i18n.translate( 'Daycare' ),
	Deals: i18n.translate( 'Deals' ),
	Depression: i18n.translate( 'Depression' ),
	Design: i18n.translate( 'Design' ),
	'Design portfolio': i18n.translate( 'Design portfolio' ),
	Dessert: i18n.translate( 'Dessert' ),
	Devops: i18n.translate( 'Devops' ),
	'Diagnostic machine design': i18n.translate( 'Diagnostic machine design' ),
	Diary: i18n.translate( 'Diary' ),
	'Digital design': i18n.translate( 'Digital design' ),
	'Digital portfolio': i18n.translate( 'Digital portfolio' ),
	Digitization: i18n.translate( 'Digitization' ),
	Disease: i18n.translate( 'Disease' ),
	'Dog boarding kennel': i18n.translate( 'Dog boarding kennel' ),
	'Dog grooming': i18n.translate( 'Dog grooming' ),
	Dogs: i18n.translate( 'Dogs' ),
	'Domestic violence prevention': i18n.translate( 'Domestic violence prevention' ),
	'Drawing portfolio': i18n.translate( 'Drawing portfolio' ),
	Drawings: i18n.translate( 'Drawings' ),
	'Dream coaching': i18n.translate( 'Dream coaching' ),
	'Dream interpretations': i18n.translate( 'Dream interpretations' ),
	Dreams: i18n.translate( 'Dreams' ),
	Dresses: i18n.translate( 'Dresses' ),
	Drinks: i18n.translate( 'Drinks' ),
	Drugs: i18n.translate( 'Drugs' ),
	'Dungeons and dragons': i18n.translate( 'Dungeons and dragons' ),
	'E-book': i18n.translate( 'E-book' ),
	'E-books': i18n.translate( 'E-books' ),
	'E-commerce': i18n.translate( 'E-commerce' ),
	'Early childhood services': i18n.translate( 'Early childhood services' ),
	Ecological: i18n.translate( 'Ecological' ),
	Ecosystem: i18n.translate( 'Ecosystem' ),
	Editing: i18n.translate( 'Editing' ),
	Education: i18n.translate( 'Education' ),
	'Educational books': i18n.translate( 'Educational books' ),
	'Educational services': i18n.translate( 'Educational services' ),
	Eggs: i18n.translate( 'Eggs' ),
	'Electrical design': i18n.translate( 'Electrical design' ),
	'Electrical panels': i18n.translate( 'Electrical panels' ),
	Electrician: i18n.translate( 'Electrician' ),
	'Electronic components': i18n.translate( 'Electronic components' ),
	'Electronic music': i18n.translate( 'Electronic music' ),
	Electronics: i18n.translate( 'Electronics' ),
	Embroidery: i18n.translate( 'Embroidery' ),
	Emotions: i18n.translate( 'Emotions' ),
	Employment: i18n.translate( 'Employment' ),
	'Energy efficient appliances': i18n.translate( 'Energy efficient appliances' ),
	Engineering: i18n.translate( 'Engineering' ),
	'Engineering services': i18n.translate( 'Engineering services' ),
	'Engineering software': i18n.translate( 'Engineering software' ),
	English: i18n.translate( 'English' ),
	'English lessons': i18n.translate( 'English lessons' ),
	Enterprise: i18n.translate( 'Enterprise' ),
	Entertainment: i18n.translate( 'Entertainment' ),
	Entrepreneur: i18n.translate( 'Entrepreneur' ),
	Entrepreneurship: i18n.translate( 'Entrepreneurship' ),
	Environment: i18n.translate( 'Environment' ),
	'Environment consultant': i18n.translate( 'Environment consultant' ),
	Equestrian: i18n.translate( 'Equestrian' ),
	Equity: i18n.translate( 'Equity' ),
	Evangelism: i18n.translate( 'Evangelism' ),
	Event: i18n.translate( 'Event' ),
	'Event promotion': i18n.translate( 'Event promotion' ),
	Events: i18n.translate( 'Events' ),
	Excel: i18n.translate( 'Excel' ),
	Exploration: i18n.translate( 'Exploration' ),
	'Eye doctor': i18n.translate( 'Eye doctor' ),
	'Face painting': i18n.translate( 'Face painting' ),
	Faith: i18n.translate( 'Faith' ),
	Family: i18n.translate( 'Family' ),
	'Fan fiction': i18n.translate( 'Fan fiction' ),
	Farm: i18n.translate( 'Farm' ),
	Farming: i18n.translate( 'Farming' ),
	Fashion: i18n.translate( 'Fashion' ),
	'Fashion critic': i18n.translate( 'Fashion critic' ),
	'Fashion design': i18n.translate( 'Fashion design' ),
	Feelings: i18n.translate( 'Feelings' ),
	Festival: i18n.translate( 'Festival' ),
	'Fiction writing': i18n.translate( 'Fiction writing' ),
	'Film production': i18n.translate( 'Film production' ),
	Films: i18n.translate( 'Films' ),
	Financial: i18n.translate( 'Financial' ),
	'Financial consultant': i18n.translate( 'Financial consultant' ),
	'Financial services': i18n.translate( 'Financial services' ),
	'Fine art': i18n.translate( 'Fine art' ),
	'First nations': i18n.translate( 'First nations' ),
	Fishing: i18n.translate( 'Fishing' ),
	Fitness: i18n.translate( 'Fitness' ),
	Florist: i18n.translate( 'Florist' ),
	'Flying club': i18n.translate( 'Flying club' ),
	Food: i18n.translate( 'Food' ),
	'Food critic': i18n.translate( 'Food critic' ),
	Football: i18n.translate( 'Football' ),
	'Freelance designer': i18n.translate( 'Freelance designer' ),
	'Freelance developer': i18n.translate( 'Freelance developer' ),
	'Freelance marketer': i18n.translate( 'Freelance marketer' ),
	'Freelance services': i18n.translate( 'Freelance services' ),
	'Freelance writer': i18n.translate( 'Freelance writer' ),
	'Funeral services': i18n.translate( 'Funeral services' ),
	Furniture: i18n.translate( 'Furniture' ),
	Games: i18n.translate( 'Games' ),
	Gaming: i18n.translate( 'Gaming' ),
	Garments: i18n.translate( 'Garments' ),
	Genealogy: i18n.translate( 'Genealogy' ),
	Glamour: i18n.translate( 'Glamour' ),
	Gloves: i18n.translate( 'Gloves' ),
	God: i18n.translate( 'God' ),
	Golf: i18n.translate( 'Golf' ),
	Gospel: i18n.translate( 'Gospel' ),
	'Government and politics': i18n.translate( 'Government and politics' ),
	'Graphic design': i18n.translate( 'Graphic design' ),
	'Graphic novels': i18n.translate( 'Graphic novels' ),
	Graphics: i18n.translate( 'Graphics' ),
	'Green technology': i18n.translate( 'Green technology' ),
	Groceries: i18n.translate( 'Groceries' ),
	'Guitar teacher': i18n.translate( 'Guitar teacher' ),
	Guns: i18n.translate( 'Guns' ),
	Gym: i18n.translate( 'Gym' ),
	HIV: i18n.translate( 'HIV' ),
	HVAC: i18n.translate( 'HVAC' ),
	Hacking: i18n.translate( 'Hacking' ),
	'Hair salon': i18n.translate( 'Hair salon' ),
	'Hair styles': i18n.translate( 'Hair styles' ),
	Happiness: i18n.translate( 'Happiness' ),
	Hardware: i18n.translate( 'Hardware' ),
	Healing: i18n.translate( 'Healing' ),
	Health: i18n.translate( 'Health' ),
	'Health and beauty': i18n.translate( 'Health and beauty' ),
	'Health and fitness': i18n.translate( 'Health and fitness' ),
	Healthcare: i18n.translate( 'Healthcare' ),
	'Heat transfer vinyl': i18n.translate( 'Heat transfer vinyl' ),
	Hinduism: i18n.translate( 'Hinduism' ),
	History: i18n.translate( 'History' ),
	Hobbies: i18n.translate( 'Hobbies' ),
	Holiday: i18n.translate( 'Holiday' ),
	'Holiday rentals': i18n.translate( 'Holiday rentals' ),
	Holidays: i18n.translate( 'Holidays' ),
	'Holistic healing': i18n.translate( 'Holistic healing' ),
	Home: i18n.translate( 'Home' ),
	'Home decor': i18n.translate( 'Home decor' ),
	'Home improvement': i18n.translate( 'Home improvement' ),
	'Home inspection': i18n.translate( 'Home inspection' ),
	'Home renovation': i18n.translate( 'Home renovation' ),
	Homework: i18n.translate( 'Homework' ),
	Horses: i18n.translate( 'Horses' ),
	Hospital: i18n.translate( 'Hospital' ),
	Hospitality: i18n.translate( 'Hospitality' ),
	Hotel: i18n.translate( 'Hotel' ),
	'House cleaning': i18n.translate( 'House cleaning' ),
	Housekeeping: i18n.translate( 'Housekeeping' ),
	'How to': i18n.translate( 'How to' ),
	'Human rights issues': i18n.translate( 'Human rights issues' ),
	'Humanitarian aid': i18n.translate( 'Humanitarian aid' ),
	Hunting: i18n.translate( 'Hunting' ),
	IT: i18n.translate( 'IT' ),
	'IVF treatment': i18n.translate( 'IVF treatment' ),
	Ideas: i18n.translate( 'Ideas' ),
	Illustration: i18n.translate( 'Illustration' ),
	'Image editing': i18n.translate( 'Image editing' ),
	'Importing and exporting': i18n.translate( 'Importing and exporting' ),
	Information: i18n.translate( 'Information' ),
	'Information technology': i18n.translate( 'Information technology' ),
	Inspiration: i18n.translate( 'Inspiration' ),
	Insurance: i18n.translate( 'Insurance' ),
	'Intellectual property lawyer': i18n.translate( 'Intellectual property lawyer' ),
	'Interior design': i18n.translate( 'Interior design' ),
	'International logistics': i18n.translate( 'International logistics' ),
	'Internet provider': i18n.translate( 'Internet provider' ),
	Investing: i18n.translate( 'Investing' ),
	'Investment consultancy': i18n.translate( 'Investment consultancy' ),
	Islam: i18n.translate( 'Islam' ),
	Issues: i18n.translate( 'Issues' ),
	'Italian restaurant': i18n.translate( 'Italian restaurant' ),
	'Japanese cartoons': i18n.translate( 'Japanese cartoons' ),
	Jesus: i18n.translate( 'Jesus' ),
	Jewelry: i18n.translate( 'Jewelry' ),
	'Job consultancy': i18n.translate( 'Job consultancy' ),
	'Job listing': i18n.translate( 'Job listing' ),
	'Job posting': i18n.translate( 'Job posting' ),
	Jobs: i18n.translate( 'Jobs' ),
	Jokes: i18n.translate( 'Jokes' ),
	Journalism: i18n.translate( 'Journalism' ),
	Juicebar: i18n.translate( 'Juicebar' ),
	Kids: i18n.translate( 'Kids' ),
	'Kids yoga': i18n.translate( 'Kids yoga' ),
	Kitchen: i18n.translate( 'Kitchen' ),
	Knowledge: i18n.translate( 'Knowledge' ),
	LARP: i18n.translate( 'LARP' ),
	Law: i18n.translate( 'Law' ),
	Leadership: i18n.translate( 'Leadership' ),
	Leather: i18n.translate( 'Leather' ),
	Lemons: i18n.translate( 'Lemons' ),
	Life: i18n.translate( 'Life' ),
	'Life coach': i18n.translate( 'Life coach' ),
	'Life inspiration': i18n.translate( 'Life inspiration' ),
	Lifestyle: i18n.translate( 'Lifestyle' ),
	'Lifestyle blog': i18n.translate( 'Lifestyle blog' ),
	'Literary portfolio': i18n.translate( 'Literary portfolio' ),
	Literature: i18n.translate( 'Literature' ),
	Living: i18n.translate( 'Living' ),
	'Local music': i18n.translate( 'Local music' ),
	'Local news': i18n.translate( 'Local news' ),
	Love: i18n.translate( 'Love' ),
	'Love stories': i18n.translate( 'Love stories' ),
	'Maid services': i18n.translate( 'Maid services' ),
	Makeup: i18n.translate( 'Makeup' ),
	Manga: i18n.translate( 'Manga' ),
	Maps: i18n.translate( 'Maps' ),
	Marketing: i18n.translate( 'Marketing' ),
	'Marketing services': i18n.translate( 'Marketing services' ),
	Massages: i18n.translate( 'Massages' ),
	Mathematics: i18n.translate( 'Mathematics' ),
	Mechanic: i18n.translate( 'Mechanic' ),
	Medical: i18n.translate( 'Medical' ),
	'Medical news': i18n.translate( 'Medical news' ),
	'Medical technology': i18n.translate( 'Medical technology' ),
	Medicine: i18n.translate( 'Medicine' ),
	Meditation: i18n.translate( 'Meditation' ),
	Men: i18n.translate( 'Men' ),
	"Men's heatlh": i18n.translate( "Men's heatlh" ),
	'Mental health': i18n.translate( 'Mental health' ),
	'Mexican restaurant': i18n.translate( 'Mexican restaurant' ),
	Military: i18n.translate( 'Military' ),
	Militia: i18n.translate( 'Militia' ),
	Milk: i18n.translate( 'Milk' ),
	Minecraft: i18n.translate( 'Minecraft' ),
	Ministry: i18n.translate( 'Ministry' ),
	'Mobile app': i18n.translate( 'Mobile app' ),
	'Mobile electronics': i18n.translate( 'Mobile electronics' ),
	'Mommy blog': i18n.translate( 'Mommy blog' ),
	Motivation: i18n.translate( 'Motivation' ),
	'Motivational speaker': i18n.translate( 'Motivational speaker' ),
	Motorhomes: i18n.translate( 'Motorhomes' ),
	'Movie production': i18n.translate( 'Movie production' ),
	Movies: i18n.translate( 'Movies' ),
	'Moving service': i18n.translate( 'Moving service' ),
	'Moving services': i18n.translate( 'Moving services' ),
	Multimedia: i18n.translate( 'Multimedia' ),
	'Multimedia law': i18n.translate( 'Multimedia law' ),
	'Multimedia production': i18n.translate( 'Multimedia production' ),
	Music: i18n.translate( 'Music' ),
	'Music classes': i18n.translate( 'Music classes' ),
	'Music lessons': i18n.translate( 'Music lessons' ),
	'Music production': i18n.translate( 'Music production' ),
	Musician: i18n.translate( 'Musician' ),
	Mystery: i18n.translate( 'Mystery' ),
	'Natural health products': i18n.translate( 'Natural health products' ),
	'Natural health remedies': i18n.translate( 'Natural health remedies' ),
	'Network marketing': i18n.translate( 'Network marketing' ),
	Networking: i18n.translate( 'Networking' ),
	News: i18n.translate( 'News' ),
	Newspaper: i18n.translate( 'Newspaper' ),
	'Non-profit': i18n.translate( 'Non-profit' ),
	Novel: i18n.translate( 'Novel' ),
	Nutrition: i18n.translate( 'Nutrition' ),
	'Online business': i18n.translate( 'Online business' ),
	'Online store': i18n.translate( 'Online store' ),
	Optician: i18n.translate( 'Optician' ),
	Optometrist: i18n.translate( 'Optometrist' ),
	'Organic farming': i18n.translate( 'Organic farming' ),
	Organization: i18n.translate( 'Organization' ),
	Outdoors: i18n.translate( 'Outdoors' ),
	Outfits: i18n.translate( 'Outfits' ),
	Painter: i18n.translate( 'Painter' ),
	Painting: i18n.translate( 'Painting' ),
	Paranormal: i18n.translate( 'Paranormal' ),
	Parenting: i18n.translate( 'Parenting' ),
	'Parties and Festivities': i18n.translate( 'Parties and Festivities' ),
	'Party promotion': i18n.translate( 'Party promotion' ),
	'Performance art': i18n.translate( 'Performance art' ),
	Performer: i18n.translate( 'Performer' ),
	Perfume: i18n.translate( 'Perfume' ),
	Personal: i18n.translate( 'Personal' ),
	'Personal blog': i18n.translate( 'Personal blog' ),
	'Personal development': i18n.translate( 'Personal development' ),
	'Personal experiences': i18n.translate( 'Personal experiences' ),
	'Personal finance': i18n.translate( 'Personal finance' ),
	'Personal issues': i18n.translate( 'Personal issues' ),
	'Personal trainer': i18n.translate( 'Personal trainer' ),
	'Personal training': i18n.translate( 'Personal training' ),
	'Personal website': i18n.translate( 'Personal website' ),
	'Pet services': i18n.translate( 'Pet services' ),
	Pets: i18n.translate( 'Pets' ),
	Philosopher: i18n.translate( 'Philosopher' ),
	Philosophy: i18n.translate( 'Philosophy' ),
	Photocopier: i18n.translate( 'Photocopier' ),
	'Photocopier repairs': i18n.translate( 'Photocopier repairs' ),
	Photographer: i18n.translate( 'Photographer' ),
	Photography: i18n.translate( 'Photography' ),
	Photos: i18n.translate( 'Photos' ),
	'Physical therapy': i18n.translate( 'Physical therapy' ),
	Physiotherapy: i18n.translate( 'Physiotherapy' ),
	'Pizza shop': i18n.translate( 'Pizza shop' ),
	Plumber: i18n.translate( 'Plumber' ),
	Podcast: i18n.translate( 'Podcast' ),
	Poems: i18n.translate( 'Poems' ),
	Poetry: i18n.translate( 'Poetry' ),
	Pokémon: i18n.translate( 'Pokémon' ),
	'Political activism': i18n.translate( 'Political activism' ),
	'Political candidate': i18n.translate( 'Political candidate' ),
	'Political analysis': i18n.translate( 'Political analysis' ),
	'Political party': i18n.translate( 'Political party' ),
	Politics: i18n.translate( 'Politics' ),
	Pollution: i18n.translate( 'Pollution' ),
	Portfolio: i18n.translate( 'Portfolio' ),
	'Portrait artist': i18n.translate( 'Portrait artist' ),
	Pregnancy: i18n.translate( 'Pregnancy' ),
	Presentations: i18n.translate( 'Presentations' ),
	'Print design': i18n.translate( 'Print design' ),
	Printing: i18n.translate( 'Printing' ),
	'Private consulting': i18n.translate( 'Private consulting' ),
	Product: i18n.translate( 'Product' ),
	'Product marketing': i18n.translate( 'Product marketing' ),
	'Product reviews': i18n.translate( 'Product reviews' ),
	'Product sales': i18n.translate( 'Product sales' ),
	'Professional cleaning service': i18n.translate( 'Professional cleaning service' ),
	'Professional portfolio': i18n.translate( 'Professional portfolio' ),
	'Professional profile': i18n.translate( 'Professional profile' ),
	'Professional services': i18n.translate( 'Professional services' ),
	'Promotional marketing': i18n.translate( 'Promotional marketing' ),
	'Promotional products': i18n.translate( 'Promotional products' ),
	Promotions: i18n.translate( 'Promotions' ),
	Property: i18n.translate( 'Property' ),
	Psychotherapy: i18n.translate( 'Psychotherapy' ),
	Quiz: i18n.translate( 'Quiz' ),
	Quotes: i18n.translate( 'Quotes' ),
	Quran: i18n.translate( 'Quran' ),
	RVs: i18n.translate( 'RVs' ),
	Racism: i18n.translate( 'Racism' ),
	'Real estate': i18n.translate( 'Real estate' ),
	Recipes: i18n.translate( 'Recipes' ),
	'Recreation center': i18n.translate( 'Recreation center' ),
	Recruiting: i18n.translate( 'Recruiting' ),
	Recruitment: i18n.translate( 'Recruitment' ),
	'Recruitment consultant': i18n.translate( 'Recruitment consultant' ),
	Relationships: i18n.translate( 'Relationships' ),
	Religion: i18n.translate( 'Religion' ),
	'Renewable energy': i18n.translate( 'Renewable energy' ),
	Renovation: i18n.translate( 'Renovation' ),
	Reporter: i18n.translate( 'Reporter' ),
	Research: i18n.translate( 'Research' ),
	Researcher: i18n.translate( 'Researcher' ),
	Resort: i18n.translate( 'Resort' ),
	Resources: i18n.translate( 'Resources' ),
	Restaurant: i18n.translate( 'Restaurant' ),
	Resume: i18n.translate( 'Resume' ),
	Retail: i18n.translate( 'Retail' ),
	Reviews: i18n.translate( 'Reviews' ),
	Robotics: i18n.translate( 'Robotics' ),
	Romance: i18n.translate( 'Romance' ),
	Running: i18n.translate( 'Running' ),
	Sailing: i18n.translate( 'Sailing' ),
	Sales: i18n.translate( 'Sales' ),
	Salon: i18n.translate( 'Salon' ),
	'Saving money': i18n.translate( 'Saving money' ),
	Savings: i18n.translate( 'Savings' ),
	Scholarship: i18n.translate( 'Scholarship' ),
	School: i18n.translate( 'School' ),
	'School activities': i18n.translate( 'School activities' ),
	'School project': i18n.translate( 'School project' ),
	'School website': i18n.translate( 'School website' ),
	Science: i18n.translate( 'Science' ),
	Scouts: i18n.translate( 'Scouts' ),
	Security: i18n.translate( 'Security' ),
	'Self care': i18n.translate( 'Self care' ),
	'Self improvement': i18n.translate( 'Self improvement' ),
	'Self improvement services': i18n.translate( 'Self improvement services' ),
	'Self-help': i18n.translate( 'Self-help' ),
	'Selling art': i18n.translate( 'Selling art' ),
	'Selling clothes': i18n.translate( 'Selling clothes' ),
	'Selling products': i18n.translate( 'Selling products' ),
	Seniors: i18n.translate( 'Seniors' ),
	'Seo services': i18n.translate( 'Seo services' ),
	'Service agency': i18n.translate( 'Service agency' ),
	Sewing: i18n.translate( 'Sewing' ),
	Shamanism: i18n.translate( 'Shamanism' ),
	Shirts: i18n.translate( 'Shirts' ),
	Shoes: i18n.translate( 'Shoes' ),
	Shopping: i18n.translate( 'Shopping' ),
	'Short stories': i18n.translate( 'Short stories' ),
	Singing: i18n.translate( 'Singing' ),
	'Singing lessons': i18n.translate( 'Singing lessons' ),
	Skincare: i18n.translate( 'Skincare' ),
	Smoothies: i18n.translate( 'Smoothies' ),
	Soccer: i18n.translate( 'Soccer' ),
	'Social media': i18n.translate( 'Social media' ),
	Software: i18n.translate( 'Software' ),
	'Software and hardware': i18n.translate( 'Software and hardware' ),
	Solutions: i18n.translate( 'Solutions' ),
	Songs: i18n.translate( 'Songs' ),
	Space: i18n.translate( 'Space' ),
	'Speed dating': i18n.translate( 'Speed dating' ),
	Spiritual: i18n.translate( 'Spiritual' ),
	'Spiritual coaching': i18n.translate( 'Spiritual coaching' ),
	Spirituality: i18n.translate( 'Spirituality' ),
	Sport: i18n.translate( 'Sport' ),
	Sports: i18n.translate( 'Sports' ),
	'Stationary supplies': i18n.translate( 'Stationary supplies' ),
	Statistics: i18n.translate( 'Statistics' ),
	'Steel protection': i18n.translate( 'Steel protection' ),
	'Stock market': i18n.translate( 'Stock market' ),
	Stocks: i18n.translate( 'Stocks' ),
	Store: i18n.translate( 'Store' ),
	Storefront: i18n.translate( 'Storefront' ),
	Stories: i18n.translate( 'Stories' ),
	Student: i18n.translate( 'Student' ),
	'Student association': i18n.translate( 'Student association' ),
	'Student housing': i18n.translate( 'Student housing' ),
	'Students union': i18n.translate( 'Students union' ),
	Style: i18n.translate( 'Style' ),
	Stylist: i18n.translate( 'Stylist' ),
	Subscriptions: i18n.translate( 'Subscriptions' ),
	'Suicide prevention': i18n.translate( 'Suicide prevention' ),
	Supplements: i18n.translate( 'Supplements' ),
	Supplies: i18n.translate( 'Supplies' ),
	Support: i18n.translate( 'Support' ),
	'Sustainable development': i18n.translate( 'Sustainable development' ),
	'Swimming pools': i18n.translate( 'Swimming pools' ),
	'Swimming pools repairs': i18n.translate( 'Swimming pools repairs' ),
	TV: i18n.translate( 'TV' ),
	'TV shows': i18n.translate( 'TV shows' ),
	'Tactical gear': i18n.translate( 'Tactical gear' ),
	'Tattoo parlor': i18n.translate( 'Tattoo parlor' ),
	Tattoos: i18n.translate( 'Tattoos' ),
	Taxes: i18n.translate( 'Taxes' ),
	'Taxi business': i18n.translate( 'Taxi business' ),
	Taxidermy: i18n.translate( 'Taxidermy' ),
	Teaching: i18n.translate( 'Teaching' ),
	Tech: i18n.translate( 'Tech' ),
	'Tech blog': i18n.translate( 'Tech blog' ),
	'Technical recruiting': i18n.translate( 'Technical recruiting' ),
	'Technical support': i18n.translate( 'Technical support' ),
	Technology: i18n.translate( 'Technology' ),
	Telecommunications: i18n.translate( 'Telecommunications' ),
	Therapy: i18n.translate( 'Therapy' ),
	Thoughts: i18n.translate( 'Thoughts' ),
	Time: i18n.translate( 'Time' ),
	Tips: i18n.translate( 'Tips' ),
	Tourism: i18n.translate( 'Tourism' ),
	'Tourism accommodation': i18n.translate( 'Tourism accommodation' ),
	Toys: i18n.translate( 'Toys' ),
	Trading: i18n.translate( 'Trading' ),
	'Translation services': i18n.translate( 'Translation services' ),
	Transport: i18n.translate( 'Transport' ),
	Travel: i18n.translate( 'Travel' ),
	'Travel agent': i18n.translate( 'Travel agent' ),
	'Traveler blog': i18n.translate( 'Traveler blog' ),
	Troubleshooting: i18n.translate( 'Troubleshooting' ),
	Tutorials: i18n.translate( 'Tutorials' ),
	UI: i18n.translate( 'UI' ),
	'UI designer': i18n.translate( 'UI designer' ),
	University: i18n.translate( 'University' ),
	'User interface': i18n.translate( 'User interface' ),
	'User interface design': i18n.translate( 'User interface design' ),
	VR: i18n.translate( 'VR' ),
	'VR glasses': i18n.translate( 'VR glasses' ),
	'Vacation rental': i18n.translate( 'Vacation rental' ),
	Vacations: i18n.translate( 'Vacations' ),
	Vaccinations: i18n.translate( 'Vaccinations' ),
	Vaccines: i18n.translate( 'Vaccines' ),
	Veterans: i18n.translate( 'Veterans' ),
	'Veterans affairs': i18n.translate( 'Veterans affairs' ),
	Video: i18n.translate( 'Video' ),
	'Video games': i18n.translate( 'Video games' ),
	Videography: i18n.translate( 'Videography' ),
	'Virtual assistant': i18n.translate( 'Virtual assistant' ),
	'Virtual reality': i18n.translate( 'Virtual reality' ),
	Walking: i18n.translate( 'Walking' ),
	War: i18n.translate( 'War' ),
	Warehouse: i18n.translate( 'Warehouse' ),
	Watches: i18n.translate( 'Watches' ),
	Watchmaking: i18n.translate( 'Watchmaking' ),
	'Web design': i18n.translate( 'Web design' ),
	'Web designer': i18n.translate( 'Web designer' ),
	'Web developer': i18n.translate( 'Web developer' ),
	Wedding: i18n.translate( 'Wedding' ),
	'Wedding planner': i18n.translate( 'Wedding planner' ),
	'Weight loss': i18n.translate( 'Weight loss' ),
	Weightlifting: i18n.translate( 'Weightlifting' ),
	'Well-being': i18n.translate( 'Well-being' ),
	Wellness: i18n.translate( 'Wellness' ),
	'Window blinds': i18n.translate( 'Window blinds' ),
	Wine: i18n.translate( 'Wine' ),
	Women: i18n.translate( 'Women' ),
	"Women's health": i18n.translate( "Women's health" ),
	Words: i18n.translate( 'Words' ),
	'Work performance': i18n.translate( 'Work performance' ),
	Workshop: i18n.translate( 'Workshop' ),
	'World issues': i18n.translate( 'World issues' ),
	'World news': i18n.translate( 'World news' ),
	Writer: i18n.translate( 'Writer' ),
	Writing: i18n.translate( 'Writing' ),
	Yoga: i18n.translate( 'Yoga' ),
	'Yoga for kids': i18n.translate( 'Yoga for kids' ),
	'YouTube videos': i18n.translate( 'YouTube videos' ),
};
