/**
 * External dependencies
 */
import { translate } from 'i18n-calypso'
import { findKey } from 'lodash';

const getTopicList = () => ( {
	'3D': translate( '3D' ),
	Abuse: translate( 'Abuse' ),
	'Academic research': translate( 'Academic research' ),
	Accessories: translate( 'Accessories' ),
	Accountant: translate( 'Accountant' ),
	'Accounting services': translate( 'Accounting services' ),
	Acoustics: translate( 'Acoustics' ),
	Acting: translate( 'Acting' ),
	Activism: translate( 'Activism' ),
	Adventure: translate( 'Adventure' ),
	Advertising: translate( 'Advertising' ),
	'Advocacy of human rights': translate( 'Advocacy of human rights' ),
	'Advocacy group': translate( 'Advocacy group' ),
	Advocate: translate( 'Advocate' ),
	Aesthetician: translate( 'Aesthetician' ),
	Affiliate: translate( 'Affiliate' ),
	Agriculture: translate( 'Agriculture' ),
	'Air conditioning': translate( 'Air conditioning' ),
	Allah: translate( 'Allah' ),
	Allergies: translate( 'Allergies' ),
	Animals: translate( 'Animals' ),
	Animation: translate( 'Animation' ),
	Anime: translate( 'Anime' ),
	Antiques: translate( 'Antiques' ),
	Anxiety: translate( 'Anxiety' ),
	'Anxiety and depression': translate( 'Anxiety and depression' ),
	App: translate( 'App' ),
	Apparel: translate( 'Apparel' ),
	Architecture: translate( 'Architecture' ),
	Archive: translate( 'Archive' ),
	'Armed forces': translate( 'Armed forces' ),
	Army: translate( 'Army' ),
	Art: translate( 'Art' ),
	'Art lessons': translate( 'Art lessons' ),
	'Art school': translate( 'Art school' ),
	Artist: translate( 'Artist' ),
	Artists: translate( 'Artists' ),
	Arts: translate( 'Arts' ),
	Assistant: translate( 'Assistant' ),
	Association: translate( 'Association' ),
	Astronomy: translate( 'Astronomy' ),
	Author: translate( 'Author' ),
	Autisim: translate( 'Autisim' ),
	'Auto body repair': translate( 'Auto body repair' ),
	'Automotive business': translate( 'Automotive business' ),
	Babies: translate( 'Babies' ),
	'Baby showers': translate( 'Baby showers' ),
	Bags: translate( 'Bags' ),
	Bakery: translate( 'Bakery' ),
	Baking: translate( 'Baking' ),
	Band: translate( 'Band' ),
	Barber: translate( 'Barber' ),
	Basketball: translate( 'Basketball' ),
	'Bathroom fitter': translate( 'Bathroom fitter' ),
	Beautician: translate( 'Beautician' ),
	Beauty: translate( 'Beauty' ),
	'Beauty and wellness': translate( 'Beauty and wellness' ),
	'Beauty blog': translate( 'Beauty blog' ),
	'Beauty business': translate( 'Beauty business' ),
	'Beauty salon': translate( 'Beauty salon' ),
	'Beauty services': translate( 'Beauty services' ),
	'Beauty treatments': translate( 'Beauty treatments' ),
	'Bed and breakfast': translate( 'Bed and breakfast' ),
	Beer: translate( 'Beer' ),
	Bible: translate( 'Bible' ),
	'Bible studies': translate( 'Bible studies' ),
	Biofuels: translate( 'Biofuels' ),
	'Biofuels and biotechnology': translate( 'Biofuels and biotechnology' ),
	Biotechnology: translate( 'Biotechnology' ),
	Blog: translate( 'Blog' ),
	Bonsai: translate( 'Bonsai' ),
	'Bonsai trees': translate( 'Bonsai trees' ),
	Book: translate( 'Book' ),
	'Book reviews': translate( 'Book reviews' ),
	Bookbinder: translate( 'Bookbinder' ),
	Bookbinding: translate( 'Bookbinding' ),
	Bookkeeping: translate( 'Bookkeeping' ),
	Books: translate( 'Books' ),
	'Brain injury': translate( 'Brain injury' ),
	Bread: translate( 'Bread' ),
	Broadcasting: translate( 'Broadcasting' ),
	Buddhism: translate( 'Buddhism' ),
	Building: translate( 'Building' ),
	Business: translate( 'Business' ),
	'Business consultant': translate( 'Business consultant' ),
	'Business consulting services': translate( 'Business consulting services' ),
	'Business development': translate( 'Business development' ),
	'Business life': translate( 'Business life' ),
	'Business services': translate( 'Business services' ),
	CBD: 'CBD',
	CCTV: translate( 'CCTV' ),
	Cafe: translate( 'Cafe' ),
	Cake: translate( 'Cake' ),
	Cakes: translate( 'Cakes' ),
	Cancer: translate( 'Cancer' ),
	Cannabis: translate( 'Cannabis' ),
	'Car audio': translate( 'Car audio' ),
	'Car repairs': translate( 'Car repairs' ),
	Cars: translate( 'Cars' ),
	Cats: translate( 'Cats' ),
	Celebrities: translate( 'Celebrities' ),
	Ceramics: translate( 'Ceramics' ),
	Charity: translate( 'Charity' ),
	'Child abuse': translate( 'Child abuse' ),
	Childbirth: translate( 'Childbirth' ),
	'Chinese restaurant': translate( 'Chinese restaurant' ),
	Choir: translate( 'Choir' ),
	Christ: translate( 'Christ' ),
	Christianity: translate( 'Christianity' ),
	Church: translate( 'Church' ),
	'Classified ads': translate( 'Classified ads' ),
	'Cleaning services': translate( 'Cleaning services' ),
	'Climate change': translate( 'Climate change' ),
	Clinic: translate( 'Clinic' ),
	Clothes: translate( 'Clothes' ),
	Clothing: translate( 'Clothing' ),
	Coach: translate( 'Coach' ),
	Coaching: translate( 'Coaching' ),
	Coding: translate( 'Coding' ),
	Coffee: translate( 'Coffee' ),
	'Coffee shop': translate( 'Coffee shop' ),
	College: translate( 'College' ),
	Comedy: translate( 'Comedy' ),
	Commercial: translate( 'Commercial' ),
	Communication: translate( 'Communication' ),
	Community: translate( 'Community' ),
	'Community association': translate( 'Community association' ),
	'Community services': translate( 'Community services' ),
	Computer: translate( 'Computer' ),
	'Computer repairs': translate( 'Computer repairs' ),
	Computing: translate( 'Computing' ),
	'Concrete restorations': translate( 'Concrete restorations' ),
	Conduits: translate( 'Conduits' ),
	Conference: translate( 'Conference' ),
	Construction: translate( 'Construction' ),
	'Construction engineer': translate( 'Construction engineer' ),
	Consultant: translate( 'Consultant' ),
	Consulting: translate( 'Consulting' ),
	'Consulting agency': translate( 'Consulting agency' ),
	'Consulting business': translate( 'Consulting business' ),
	'Consulting engineering': translate( 'Consulting engineering' ),
	Consumables: translate( 'Consumables' ),
	'Content creation': translate( 'Content creation' ),
	Cooking: translate( 'Cooking' ),
	Copywriting: translate( 'Copywriting' ),
	'Corporate services': translate( 'Corporate services' ),
	'Corrosion engineering': translate( 'Corrosion engineering' ),
	Cosmetics: translate( 'Cosmetics' ),
	Cosplay: translate( 'Cosplay' ),
	Counseling: translate( 'Counseling' ),
	'Counseling services': translate( 'Counseling services' ),
	'Craft beer': translate( 'Craft beer' ),
	Crafting: translate( 'Crafting' ),
	'Creative writing': translate( 'Creative writing' ),
	'Credit repair': translate( 'Credit repair' ),
	'Crime prevention': translate( 'Crime prevention' ),
	Crossfit: translate( 'Crossfit' ),
	'Crowd funding': translate( 'Crowd funding' ),
	'Crypto currency': translate( 'Crypto currency' ),
	Culture: translate( 'Culture' ),
	Cupcakes: translate( 'Cupcakes' ),
	'Current affairs': translate( 'Current affairs' ),
	Cycling: translate( 'Cycling' ),
	DIY: translate( 'DIY' ),
	DJ: translate( 'DJ' ),
	DVDs: translate( 'DVDs' ),
	'Daily life': translate( 'Daily life' ),
	Data: translate( 'Data' ),
	'Data visualization': translate( 'Data visualization' ),
	Dating: translate( 'Dating' ),
	Daycare: translate( 'Daycare' ),
	Deals: translate( 'Deals' ),
	Depression: translate( 'Depression' ),
	Design: translate( 'Design' ),
	'Design portfolio': translate( 'Design portfolio' ),
	Dessert: translate( 'Dessert' ),
	Devops: translate( 'Devops' ),
	'Diagnostic machine design': translate( 'Diagnostic machine design' ),
	Diary: translate( 'Diary' ),
	'Digital design': translate( 'Digital design' ),
	'Digital portfolio': translate( 'Digital portfolio' ),
	Digitization: translate( 'Digitization' ),
	Disease: translate( 'Disease' ),
	'Dog boarding kennel': translate( 'Dog boarding kennel' ),
	'Dog grooming': translate( 'Dog grooming' ),
	Dogs: translate( 'Dogs' ),
	'Domestic violence prevention': translate( 'Domestic violence prevention' ),
	'Drawing portfolio': translate( 'Drawing portfolio' ),
	Drawings: translate( 'Drawings' ),
	'Dream coaching': translate( 'Dream coaching' ),
	'Dream interpretations': translate( 'Dream interpretations' ),
	Dreams: translate( 'Dreams' ),
	Dresses: translate( 'Dresses' ),
	Drinks: translate( 'Drinks' ),
	Drugs: translate( 'Drugs' ),
	'Dungeons and dragons': translate( 'Dungeons and dragons' ),
	'E-book': translate( 'E-book' ),
	'E-books': translate( 'E-books' ),
	'E-commerce': translate( 'E-commerce' ),
	'Early childhood services': translate( 'Early childhood services' ),
	Ecological: translate( 'Ecological' ),
	Ecosystem: translate( 'Ecosystem' ),
	Editing: translate( 'Editing' ),
	Education: translate( 'Education' ),
	'Educational books': translate( 'Educational books' ),
	'Educational services': translate( 'Educational services' ),
	Eggs: translate( 'Eggs' ),
	'Electrical design': translate( 'Electrical design' ),
	'Electrical panels': translate( 'Electrical panels' ),
	Electrician: translate( 'Electrician' ),
	'Electronic components': translate( 'Electronic components' ),
	'Electronic music': translate( 'Electronic music' ),
	Electronics: translate( 'Electronics' ),
	Embroidery: translate( 'Embroidery' ),
	Emotions: translate( 'Emotions' ),
	Employment: translate( 'Employment' ),
	'Energy efficient appliances': translate( 'Energy efficient appliances' ),
	Engineering: translate( 'Engineering' ),
	'Engineering services': translate( 'Engineering services' ),
	'Engineering software': translate( 'Engineering software' ),
	English: translate( 'English' ),
	'English lessons': translate( 'English lessons' ),
	Enterprise: translate( 'Enterprise' ),
	Entertainment: translate( 'Entertainment' ),
	Entrepreneur: translate( 'Entrepreneur' ),
	Entrepreneurship: translate( 'Entrepreneurship' ),
	Environment: translate( 'Environment' ),
	'Environment consultant': translate( 'Environment consultant' ),
	Equestrian: translate( 'Equestrian' ),
	Equity: translate( 'Equity' ),
	Evangelism: translate( 'Evangelism' ),
	Event: translate( 'Event' ),
	'Event promotion': translate( 'Event promotion' ),
	Events: translate( 'Events' ),
	Excel: translate( 'Excel' ),
	Exploration: translate( 'Exploration' ),
	'Eye doctor': translate( 'Eye doctor' ),
	'Face painting': translate( 'Face painting' ),
	Faith: translate( 'Faith' ),
	Family: translate( 'Family' ),
	'Fan fiction': translate( 'Fan fiction' ),
	Farm: translate( 'Farm' ),
	Farming: translate( 'Farming' ),
	Fashion: translate( 'Fashion' ),
	'Fashion critic': translate( 'Fashion critic' ),
	'Fashion design': translate( 'Fashion design' ),
	Feelings: translate( 'Feelings' ),
	Festival: translate( 'Festival' ),
	'Fiction writing': translate( 'Fiction writing' ),
	'Film production': translate( 'Film production' ),
	Films: translate( 'Films' ),
	Financial: translate( 'Financial' ),
	'Financial consultant': translate( 'Financial consultant' ),
	'Financial services': translate( 'Financial services' ),
	'Fine art': translate( 'Fine art' ),
	'First nations': translate( 'First nations' ),
	Fishing: translate( 'Fishing' ),
	Fitness: translate( 'Fitness' ),
	Florist: translate( 'Florist' ),
	'Flying club': translate( 'Flying club' ),
	Food: translate( 'Food' ),
	'Food critic': translate( 'Food critic' ),
	Football: translate( 'Football' ),
	'Freelance designer': translate( 'Freelance designer' ),
	'Freelance developer': translate( 'Freelance developer' ),
	'Freelance marketer': translate( 'Freelance marketer' ),
	'Freelance services': translate( 'Freelance services' ),
	'Freelance writer': translate( 'Freelance writer' ),
	'Funeral services': translate( 'Funeral services' ),
	Furniture: translate( 'Furniture' ),
	Games: translate( 'Games' ),
	Gaming: translate( 'Gaming' ),
	Garments: translate( 'Garments' ),
	Genealogy: translate( 'Genealogy' ),
	Glamour: translate( 'Glamour' ),
	Gloves: translate( 'Gloves' ),
	God: translate( 'God' ),
	Golf: translate( 'Golf' ),
	Gospel: translate( 'Gospel' ),
	'Government and politics': translate( 'Government and politics' ),
	'Graphic design': translate( 'Graphic design' ),
	'Graphic novels': translate( 'Graphic novels' ),
	Graphics: translate( 'Graphics' ),
	'Green technology': translate( 'Green technology' ),
	Groceries: translate( 'Groceries' ),
	'Guitar teacher': translate( 'Guitar teacher' ),
	Guns: translate( 'Guns' ),
	Gym: translate( 'Gym' ),
	HIV: translate( 'HIV' ),
	HVAC: translate( 'HVAC' ),
	Hacking: translate( 'Hacking' ),
	'Hair salon': translate( 'Hair salon' ),
	'Hair styles': translate( 'Hair styles' ),
	Happiness: translate( 'Happiness' ),
	Hardware: translate( 'Hardware' ),
	Healing: translate( 'Healing' ),
	Health: translate( 'Health' ),
	'Health and beauty': translate( 'Health and beauty' ),
	'Health and fitness': translate( 'Health and fitness' ),
	Healthcare: translate( 'Healthcare' ),
	'Heat transfer vinyl': translate( 'Heat transfer vinyl' ),
	Hinduism: translate( 'Hinduism' ),
	History: translate( 'History' ),
	Hobbies: translate( 'Hobbies' ),
	Holiday: translate( 'Holiday' ),
	'Holiday rentals': translate( 'Holiday rentals' ),
	Holidays: translate( 'Holidays' ),
	'Holistic healing': translate( 'Holistic healing' ),
	Home: translate( 'Home' ),
	'Home decor': translate( 'Home decor' ),
	'Home improvement': translate( 'Home improvement' ),
	'Home inspection': translate( 'Home inspection' ),
	'Home renovation': translate( 'Home renovation' ),
	Homework: translate( 'Homework' ),
	Horses: translate( 'Horses' ),
	Hospital: translate( 'Hospital' ),
	Hospitality: translate( 'Hospitality' ),
	Hotel: translate( 'Hotel' ),
	'House cleaning': translate( 'House cleaning' ),
	Housekeeping: translate( 'Housekeeping' ),
	'How to': translate( 'How to' ),
	'Human rights issues': translate( 'Human rights issues' ),
	'Humanitarian aid': translate( 'Humanitarian aid' ),
	Hunting: translate( 'Hunting' ),
	IT: translate( 'IT' ),
	'IVF treatment': translate( 'IVF treatment' ),
	Ideas: translate( 'Ideas' ),
	Illustration: translate( 'Illustration' ),
	'Image editing': translate( 'Image editing' ),
	'Importing and exporting': translate( 'Importing and exporting' ),
	Information: translate( 'Information' ),
	'Information technology': translate( 'Information technology' ),
	Inspiration: translate( 'Inspiration' ),
	Insurance: translate( 'Insurance' ),
	'Intellectual property lawyer': translate( 'Intellectual property lawyer' ),
	'Interior design': translate( 'Interior design' ),
	'International logistics': translate( 'International logistics' ),
	'Internet provider': translate( 'Internet provider' ),
	Investing: translate( 'Investing' ),
	'Investment consultancy': translate( 'Investment consultancy' ),
	Islam: translate( 'Islam' ),
	Issues: translate( 'Issues' ),
	'Italian restaurant': translate( 'Italian restaurant' ),
	'Japanese cartoons': translate( 'Japanese cartoons' ),
	Jesus: translate( 'Jesus' ),
	Jewelry: translate( 'Jewelry' ),
	'Job consultancy': translate( 'Job consultancy' ),
	'Job listing': translate( 'Job listing' ),
	'Job posting': translate( 'Job posting' ),
	Jobs: translate( 'Jobs' ),
	Jokes: translate( 'Jokes' ),
	Journalism: translate( 'Journalism' ),
	Juicebar: translate( 'Juicebar' ),
	Kids: translate( 'Kids' ),
	'Kids yoga': translate( 'Kids yoga' ),
	Kitchen: translate( 'Kitchen' ),
	Knowledge: translate( 'Knowledge' ),
	LARP: translate( 'LARP' ),
	Law: translate( 'Law' ),
	Leadership: translate( 'Leadership' ),
	Leather: translate( 'Leather' ),
	Lemons: translate( 'Lemons' ),
	Life: translate( 'Life' ),
	'Life coach': translate( 'Life coach' ),
	'Life inspiration': translate( 'Life inspiration' ),
	Lifestyle: translate( 'Lifestyle' ),
	'Lifestyle blog': translate( 'Lifestyle blog' ),
	'Literary portfolio': translate( 'Literary portfolio' ),
	Literature: translate( 'Literature' ),
	Living: translate( 'Living' ),
	'Local music': translate( 'Local music' ),
	'Local news': translate( 'Local news' ),
	Love: translate( 'Love' ),
	'Love stories': translate( 'Love stories' ),
	'Maid services': translate( 'Maid services' ),
	Makeup: translate( 'Makeup' ),
	Manga: translate( 'Manga' ),
	Maps: translate( 'Maps' ),
	Marketing: translate( 'Marketing' ),
	'Marketing services': translate( 'Marketing services' ),
	Massages: translate( 'Massages' ),
	Mathematics: translate( 'Mathematics' ),
	Mechanic: translate( 'Mechanic' ),
	Medical: translate( 'Medical' ),
	'Medical news': translate( 'Medical news' ),
	'Medical technology': translate( 'Medical technology' ),
	Medicine: translate( 'Medicine' ),
	Meditation: translate( 'Meditation' ),
	Men: translate( 'Men' ),
	"Men's heatlh": translate( "Men's heatlh" ),
	'Mental health': translate( 'Mental health' ),
	'Mexican restaurant': translate( 'Mexican restaurant' ),
	Military: translate( 'Military' ),
	Militia: translate( 'Militia' ),
	Milk: translate( 'Milk' ),
	Minecraft: translate( 'Minecraft' ),
	Ministry: translate( 'Ministry' ),
	'Mobile app': translate( 'Mobile app' ),
	'Mobile electronics': translate( 'Mobile electronics' ),
	'Mommy blog': translate( 'Mommy blog' ),
	Motivation: translate( 'Motivation' ),
	'Motivational speaker': translate( 'Motivational speaker' ),
	Motorhomes: translate( 'Motorhomes' ),
	'Movie production': translate( 'Movie production' ),
	Movies: translate( 'Movies' ),
	'Moving service': translate( 'Moving service' ),
	'Moving services': translate( 'Moving services' ),
	Multimedia: translate( 'Multimedia' ),
	'Multimedia law': translate( 'Multimedia law' ),
	'Multimedia production': translate( 'Multimedia production' ),
	Music: translate( 'Music' ),
	'Music classes': translate( 'Music classes' ),
	'Music lessons': translate( 'Music lessons' ),
	'Music production': translate( 'Music production' ),
	Musician: translate( 'Musician' ),
	Mystery: translate( 'Mystery' ),
	'Natural health products': translate( 'Natural health products' ),
	'Natural health remedies': translate( 'Natural health remedies' ),
	'Network marketing': translate( 'Network marketing' ),
	Networking: translate( 'Networking' ),
	News: translate( 'News' ),
	Newspaper: translate( 'Newspaper' ),
	'Non-profit': translate( 'Non-profit' ),
	Novel: translate( 'Novel' ),
	Nutrition: translate( 'Nutrition' ),
	'Online business': translate( 'Online business' ),
	'Online store': translate( 'Online store' ),
	Optician: translate( 'Optician' ),
	Optometrist: translate( 'Optometrist' ),
	'Organic farming': translate( 'Organic farming' ),
	Organization: translate( 'Organization' ),
	Outdoors: translate( 'Outdoors' ),
	Outfits: translate( 'Outfits' ),
	Painter: translate( 'Painter' ),
	Painting: translate( 'Painting' ),
	Paranormal: translate( 'Paranormal' ),
	Parenting: translate( 'Parenting' ),
	'Parties and Festivities': translate( 'Parties and Festivities' ),
	'Party promotion': translate( 'Party promotion' ),
	'Performance art': translate( 'Performance art' ),
	Performer: translate( 'Performer' ),
	Perfume: translate( 'Perfume' ),
	Personal: translate( 'Personal' ),
	'Personal blog': translate( 'Personal blog' ),
	'Personal development': translate( 'Personal development' ),
	'Personal experiences': translate( 'Personal experiences' ),
	'Personal finance': translate( 'Personal finance' ),
	'Personal issues': translate( 'Personal issues' ),
	'Personal trainer': translate( 'Personal trainer' ),
	'Personal training': translate( 'Personal training' ),
	'Personal website': translate( 'Personal website' ),
	'Pet services': translate( 'Pet services' ),
	Pets: translate( 'Pets' ),
	Philosopher: translate( 'Philosopher' ),
	Philosophy: translate( 'Philosophy' ),
	Photocopier: translate( 'Photocopier' ),
	'Photocopier repairs': translate( 'Photocopier repairs' ),
	Photographer: translate( 'Photographer' ),
	Photography: translate( 'Photography' ),
	Photos: translate( 'Photos' ),
	'Physical therapy': translate( 'Physical therapy' ),
	Physiotherapy: translate( 'Physiotherapy' ),
	'Pizza shop': translate( 'Pizza shop' ),
	Plumber: translate( 'Plumber' ),
	Podcast: translate( 'Podcast' ),
	Poems: translate( 'Poems' ),
	Poetry: translate( 'Poetry' ),
	Pokémon: translate( 'Pokémon' ),
	'Political activism': translate( 'Political activism' ),
	'Political candidate': translate( 'Political candidate' ),
	'Political analysis': translate( 'Political analysis' ),
	'Political party': translate( 'Political party' ),
	Politics: translate( 'Politics' ),
	Pollution: translate( 'Pollution' ),
	Portfolio: translate( 'Portfolio' ),
	'Portrait artist': translate( 'Portrait artist' ),
	Pregnancy: translate( 'Pregnancy' ),
	Presentations: translate( 'Presentations' ),
	'Print design': translate( 'Print design' ),
	Printing: translate( 'Printing' ),
	'Private consulting': translate( 'Private consulting' ),
	Product: translate( 'Product' ),
	'Product marketing': translate( 'Product marketing' ),
	'Product reviews': translate( 'Product reviews' ),
	'Product sales': translate( 'Product sales' ),
	'Professional cleaning service': translate( 'Professional cleaning service' ),
	'Professional portfolio': translate( 'Professional portfolio' ),
	'Professional profile': translate( 'Professional profile' ),
	'Professional services': translate( 'Professional services' ),
	'Promotional marketing': translate( 'Promotional marketing' ),
	'Promotional products': translate( 'Promotional products' ),
	Promotions: translate( 'Promotions' ),
	Property: translate( 'Property' ),
	Psychotherapy: translate( 'Psychotherapy' ),
	Quiz: translate( 'Quiz' ),
	Quotes: translate( 'Quotes' ),
	Quran: translate( 'Quran' ),
	RVs: translate( 'RVs' ),
	Racism: translate( 'Racism' ),
	'Real estate': translate( 'Real estate' ),
	Recipes: translate( 'Recipes' ),
	'Recreation center': translate( 'Recreation center' ),
	Recruiting: translate( 'Recruiting' ),
	Recruitment: translate( 'Recruitment' ),
	'Recruitment consultant': translate( 'Recruitment consultant' ),
	Relationships: translate( 'Relationships' ),
	Religion: translate( 'Religion' ),
	'Renewable energy': translate( 'Renewable energy' ),
	Renovation: translate( 'Renovation' ),
	Reporter: translate( 'Reporter' ),
	Research: translate( 'Research' ),
	Researcher: translate( 'Researcher' ),
	Resort: translate( 'Resort' ),
	Resources: translate( 'Resources' ),
	Restaurant: translate( 'Restaurant' ),
	Resume: translate( 'Resume' ),
	Retail: translate( 'Retail' ),
	Reviews: translate( 'Reviews' ),
	Robotics: translate( 'Robotics' ),
	Romance: translate( 'Romance' ),
	Running: translate( 'Running' ),
	Sailing: translate( 'Sailing' ),
	Sales: translate( 'Sales' ),
	Salon: translate( 'Salon' ),
	'Saving money': translate( 'Saving money' ),
	Savings: translate( 'Savings' ),
	Scholarship: translate( 'Scholarship' ),
	School: translate( 'School' ),
	'School activities': translate( 'School activities' ),
	'School project': translate( 'School project' ),
	'School website': translate( 'School website' ),
	Science: translate( 'Science' ),
	Scouts: translate( 'Scouts' ),
	Security: translate( 'Security' ),
	'Self care': translate( 'Self care' ),
	'Self improvement': translate( 'Self improvement' ),
	'Self improvement services': translate( 'Self improvement services' ),
	'Self-help': translate( 'Self-help' ),
	'Selling art': translate( 'Selling art' ),
	'Selling clothes': translate( 'Selling clothes' ),
	'Selling products': translate( 'Selling products' ),
	Seniors: translate( 'Seniors' ),
	'Seo services': translate( 'Seo services' ),
	'Service agency': translate( 'Service agency' ),
	Sewing: translate( 'Sewing' ),
	Shamanism: translate( 'Shamanism' ),
	Shirts: translate( 'Shirts' ),
	Shoes: translate( 'Shoes' ),
	Shopping: translate( 'Shopping' ),
	'Short stories': translate( 'Short stories' ),
	Singing: translate( 'Singing' ),
	'Singing lessons': translate( 'Singing lessons' ),
	Skincare: translate( 'Skincare' ),
	Smoothies: translate( 'Smoothies' ),
	Soccer: translate( 'Soccer' ),
	'Social media': translate( 'Social media' ),
	Software: translate( 'Software' ),
	'Software and hardware': translate( 'Software and hardware' ),
	Solutions: translate( 'Solutions' ),
	Songs: translate( 'Songs' ),
	Space: translate( 'Space' ),
	'Speed dating': translate( 'Speed dating' ),
	Spiritual: translate( 'Spiritual' ),
	'Spiritual coaching': translate( 'Spiritual coaching' ),
	Spirituality: translate( 'Spirituality' ),
	Sport: translate( 'Sport' ),
	Sports: translate( 'Sports' ),
	'Stationary supplies': translate( 'Stationary supplies' ),
	Statistics: translate( 'Statistics' ),
	'Steel protection': translate( 'Steel protection' ),
	'Stock market': translate( 'Stock market' ),
	Stocks: translate( 'Stocks' ),
	Store: translate( 'Store' ),
	Storefront: translate( 'Storefront' ),
	Stories: translate( 'Stories' ),
	Student: translate( 'Student' ),
	'Student association': translate( 'Student association' ),
	'Student housing': translate( 'Student housing' ),
	'Students union': translate( 'Students union' ),
	Style: translate( 'Style' ),
	Stylist: translate( 'Stylist' ),
	Subscriptions: translate( 'Subscriptions' ),
	'Suicide prevention': translate( 'Suicide prevention' ),
	Supplements: translate( 'Supplements' ),
	Supplies: translate( 'Supplies' ),
	Support: translate( 'Support' ),
	'Sustainable development': translate( 'Sustainable development' ),
	'Swimming pools': translate( 'Swimming pools' ),
	'Swimming pools repairs': translate( 'Swimming pools repairs' ),
	TV: translate( 'TV' ),
	'TV shows': translate( 'TV shows' ),
	'Tactical gear': translate( 'Tactical gear' ),
	'Tattoo parlor': translate( 'Tattoo parlor' ),
	Tattoos: translate( 'Tattoos' ),
	Taxes: translate( 'Taxes' ),
	'Taxi business': translate( 'Taxi business' ),
	Taxidermy: translate( 'Taxidermy' ),
	Teaching: translate( 'Teaching' ),
	Tech: translate( 'Tech' ),
	'Tech blog': translate( 'Tech blog' ),
	'Technical recruiting': translate( 'Technical recruiting' ),
	'Technical support': translate( 'Technical support' ),
	Technology: translate( 'Technology' ),
	Telecommunications: translate( 'Telecommunications' ),
	Therapy: translate( 'Therapy' ),
	Thoughts: translate( 'Thoughts' ),
	Time: translate( 'Time' ),
	Tips: translate( 'Tips' ),
	Tourism: translate( 'Tourism' ),
	'Tourism accommodation': translate( 'Tourism accommodation' ),
	Toys: translate( 'Toys' ),
	Trading: translate( 'Trading' ),
	'Translation services': translate( 'Translation services' ),
	Transport: translate( 'Transport' ),
	Travel: translate( 'Travel' ),
	'Travel agent': translate( 'Travel agent' ),
	'Traveler blog': translate( 'Traveler blog' ),
	Troubleshooting: translate( 'Troubleshooting' ),
	Tutorials: translate( 'Tutorials' ),
	UI: translate( 'UI' ),
	'UI designer': translate( 'UI designer' ),
	University: translate( 'University' ),
	'User interface': translate( 'User interface' ),
	'User interface design': translate( 'User interface design' ),
	VR: translate( 'VR' ),
	'VR glasses': translate( 'VR glasses' ),
	'Vacation rental': translate( 'Vacation rental' ),
	Vacations: translate( 'Vacations' ),
	Vaccinations: translate( 'Vaccinations' ),
	Vaccines: translate( 'Vaccines' ),
	Veterans: translate( 'Veterans' ),
	'Veterans affairs': translate( 'Veterans affairs' ),
	Video: translate( 'Video' ),
	'Video games': translate( 'Video games' ),
	Videography: translate( 'Videography' ),
	'Virtual assistant': translate( 'Virtual assistant' ),
	'Virtual reality': translate( 'Virtual reality' ),
	Walking: translate( 'Walking' ),
	War: translate( 'War' ),
	Warehouse: translate( 'Warehouse' ),
	Watches: translate( 'Watches' ),
	Watchmaking: translate( 'Watchmaking' ),
	'Web design': translate( 'Web design' ),
	'Web designer': translate( 'Web designer' ),
	'Web developer': translate( 'Web developer' ),
	Wedding: translate( 'Wedding' ),
	'Wedding planner': translate( 'Wedding planner' ),
	'Weight loss': translate( 'Weight loss' ),
	Weightlifting: translate( 'Weightlifting' ),
	'Well-being': translate( 'Well-being' ),
	Wellness: translate( 'Wellness' ),
	'Window blinds': translate( 'Window blinds' ),
	Wine: translate( 'Wine' ),
	Women: translate( 'Women' ),
	"Women's health": translate( "Women's health" ),
	Words: translate( 'Words' ),
	'Work performance': translate( 'Work performance' ),
	Workshop: translate( 'Workshop' ),
	'World issues': translate( 'World issues' ),
	'World news': translate( 'World news' ),
	Writer: translate( 'Writer' ),
	Writing: translate( 'Writing' ),
	Yoga: translate( 'Yoga' ),
	'Yoga for kids': translate( 'Yoga for kids' ),
	'YouTube videos': translate( 'YouTube videos' ),
} );

export function getSiteTopicSuggestions() {
	return Object.values( getTopicList() );
}

export function toSiteTopicSlug( siteTopicInput ) {
	const trimmedInput = siteTopicInput.trim();

	return findKey( getTopicList(), siteTopic => siteTopic === trimmedInput ) || siteTopicInput;
}

