/** @format */
export const themes = [
	{
		name: 'Shoreditch',
		slug: 'shoreditch',
		repo: 'pub',
		fallback: true,
		design: [ 'page', 'store' ],
		demo_uri: 'https://wordpress.com/theme/shoreditch',
		verticals: [],
	},
	{
		name: 'Independent Publisher',
		slug: 'independent-publisher-2',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'http://independentpublisher2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Libre',
		slug: 'libre-2',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://libre2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Penscratch',
		slug: 'penscratch-2',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://penscratch2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Libretto',
		slug: 'libretto',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://librettodemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Twenty Fifteen',
		slug: 'twentyfifteen',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://twentyfifteendemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Intergalactic',
		slug: 'intergalactic-2',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://intergalactic2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Radcliffe',
		slug: 'radcliffe-2',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://radcliffe2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Karuna',
		slug: 'karuna',
		repo: 'pub',
		fallback: false,
		design: [ 'page', 'store' ],
		demo_uri: 'https://karunademo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Dara',
		slug: 'dara',
		repo: 'pub',
		fallback: true,
		design: [ 'page', 'store' ],
		demo_uri: 'https://darademo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Lodestar',
		slug: 'lodestar',
		repo: 'pub',
		fallback: true,
		design: 'page',
		demo_uri: 'https://lodestardemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'AltoFocus',
		slug: 'altofocus',
		repo: 'pub',
		fallback: false,
		design: 'grid',
		demo_uri: 'https://altofocusdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Apostrophe',
		slug: 'apostrophe-2',
		repo: 'pub',
		fallback: false,
		design: 'grid',
		demo_uri: 'https://apostrophe2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Dyad',
		slug: 'dyad-2',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://dyad2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Gazette',
		slug: 'gazette',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://gazettedemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Illustratr',
		slug: 'illustratr',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://illustratrdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Canard',
		slug: 'canard',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://canarddemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Publication',
		slug: 'publication',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://publicationdemo.wordpress.com',
		verticals: [],
	},
];
