/** @format */
export const themes = [
	{
		name: 'Shoreditch',
		slug: 'shoreditch',
		repo: 'pub',
		fallback: true,
		design: [ 'page', 'store' ],
		demo_uri: 'https://wordpress.com/theme/shoreditch',
		verticals: [],
	},
	{
		name: 'Independent Publisher',
		slug: 'independent-publisher-2',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'http://independentpublisher2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Hemingway Rewritten',
		slug: 'hemingway-rewritten',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://hemingwayrewrittendemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Penscratch',
		slug: 'penscratch-2',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://penscratch2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Cols',
		slug: 'cols',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://colsdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Twenty Fifteen',
		slug: 'twentyfifteen',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://twentyfifteendemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Bushwick',
		slug: 'bushwick',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://bushwickdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Radcliffe',
		slug: 'radcliffe-2',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://radcliffe2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Karuna',
		slug: 'karuna',
		repo: 'pub',
		fallback: false,
		design: [ 'page', 'store' ],
		demo_uri: 'https://karunademo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Dara',
		slug: 'dara',
		repo: 'pub',
		fallback: true,
		design: [ 'page', 'store' ],
		demo_uri: 'https://darademo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Lodestar',
		slug: 'lodestar',
		repo: 'pub',
		fallback: true,
		design: 'page',
		demo_uri: 'https://lodestardemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'AltoFocus',
		slug: 'altofocus',
		repo: 'pub',
		fallback: false,
		design: 'grid',
		demo_uri: 'https://altofocusdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Apostrophe',
		slug: 'apostrophe-2',
		repo: 'pub',
		fallback: false,
		design: 'grid',
		demo_uri: 'https://apostrophe2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Dyad',
		slug: 'dyad-2',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://dyad2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Cubic',
		slug: 'cubic',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://cubicdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Baskerville',
		slug: 'baskerville-2',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://baskerville2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Rowling',
		slug: 'rowling',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://rowlingdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Boardwalk',
		slug: 'boardwalk',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://boardwalkdemo.wordpress.com',
		verticals: [],
	},
];
