/** @format */
export const themes = [
	{
		name: 'Button',
		slug: 'button-2',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'https://button2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Franklin',
		slug: 'franklin',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'https://franklindemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Hemingway Rewritten',
		slug: 'hemingway-rewritten',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://hemingwayrewrittendemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Independent Publisher',
		slug: 'independent-publisher-2',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'http://independentpublisher2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Intergalactic 2',
		slug: 'intergalactic-2',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://intergalactic2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Libre',
		slug: 'libre-2',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'https://libre2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Libretto',
		slug: 'libretto',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'https://librettodemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Penscratch',
		slug: 'penscratch-2',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://penscratch2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Sapor',
		slug: 'sapor',
		repo: 'pub',
		fallback: false,
		design: 'blog',
		demo_uri: 'https://sapordemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Twenty Sixteen',
		slug: 'twentysixteen',
		repo: 'pub',
		fallback: true,
		design: 'blog',
		demo_uri: 'https://twentysixteendemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Affinity',
		slug: 'affinity',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://affinitydemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Edin',
		slug: 'edin',
		repo: 'pub',
		fallback: true,
		design: 'page',
		demo_uri: 'https://edindemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Gateway',
		slug: 'gateway',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://gatewaydemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Goran',
		slug: 'goran',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://gorandemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Twenty Seventeen',
		slug: 'twentyseventeen',
		repo: 'pub',
		fallback: true,
		design: 'page',
		demo_uri: 'https://twentyseventeendemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Karuna',
		slug: 'karuna',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://karunademo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Pique',
		slug: 'pique',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://piquedemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Dara',
		slug: 'dara',
		repo: 'pub',
		fallback: true,
		design: 'page',
		demo_uri: 'https://darademo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Shoreditch',
		slug: 'shoreditch',
		repo: 'pub',
		fallback: false,
		design: 'page',
		demo_uri: 'https://shoreditchdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'AltoFocus',
		slug: 'altofocus',
		repo: 'pub',
		fallback: false,
		design: 'grid',
		demo_uri: 'https://altofocusdemo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Apostrophe',
		slug: 'apostrophe-2',
		repo: 'pub',
		fallback: false,
		design: 'grid',
		demo_uri: 'https://apostrophe2demo.wordpress.com',
		verticals: [],
	},
	{
		name: 'Dyad',
		slug: 'dyad-2',
		repo: 'pub',
		fallback: true,
		design: 'grid',
		demo_uri: 'https://dyad2demo.wordpress.com',
		verticals: [],
	},
];
