export default {
	site_intent: 'free',
	launchpad_screen: 'full',
	checklist_statuses: {
		setup_free: true,
		setup_general: true,
		design_completed: true,
		site_theme_selected: true,
	},
	checklist: [
		{
			id: 'plan_selected',
			title: 'Choose a plan',
			completed: true,
			disabled: false,
			subtitle: '',
			badge_text: '',
			isLaunchTask: false,
			calypso_path: '/plans/site62798.wordpress.com',
		},
		{
			id: 'setup_free',
			title: 'Personalize your site',
			completed: true,
			disabled: false,
			subtitle: '',
			badge_text: '',
			isLaunchTask: false,
			calypso_path: '/settings/general/site62798.wordpress.com',
		},
		{
			id: 'design_selected',
			title: 'Select a design',
			completed: true,
			disabled: false,
			subtitle: '',
			badge_text: '',
			isLaunchTask: false,
			calypso_path: '/setup/update-design/design-setup?siteSlug=site62798.wordpress.com',
		},
		{
			id: 'domain_upsell',
			title: 'Choose a domain',
			completed: false,
			disabled: false,
			subtitle: '',
			badge_text: 'Upgrade plan',
			isLaunchTask: false,
			calypso_path: '/setup/domain-upsell/domains?siteSlug=site62798.wordpress.com',
		},
		{
			id: 'first_post_published',
			title: 'Write your first post',
			completed: false,
			disabled: false,
			subtitle: '',
			badge_text: '',
			isLaunchTask: false,
			calypso_path: '/post/site62798.wordpress.com',
		},
		{
			id: 'design_edited',
			title: 'Edit site design',
			completed: false,
			disabled: false,
			subtitle: '',
			badge_text: '',
			isLaunchTask: false,
			calypso_path: '/site-editor/site62798.wordpress.com',
		},
		{
			id: 'site_launched',
			title: 'Launch your site',
			completed: false,
			disabled: false,
			subtitle: '',
			badge_text: '',
			isLaunchTask: true,
		},
	],
	is_enabled: true,
	is_dismissed: false,
	is_dismissible: false,
	title: 'Next steps for your site',
};
