FROM circleci/node:12.16.2-browsers

WORKDIR /home/circleci/wp-calypso/

# Number of workers to use for bundling the client app
ARG workers

COPY .

# Install deps
RUN yarn install

# Build the app
RUN WORKERS=$workers CALYPSO_ENV=production BUILD_TRANSLATION_CHUNKS=true yarn run build
