export const transferStates = {
	INQUIRING: 'inquiring',
	START: 'start',
	SETUP: 'setup',
	CONFLICTS: 'conflicts',
	COMPLETE: 'complete',
};

export const eligibilityHolds = {
	MULTIPLE_USERS: 'MULTIPLE_USERS',
	NO_BUSINESS_PLAN: 'NO_BUSINESS_PLAN',
	NO_VIP_SITES: 'NO_VIP_SITES',
	NO_WPCOM_NAMESERVERS: 'NO_WPCOM_NAMESERVERS',
	NON_ADMIN_USER: 'NON_ADMIN_USER',
	NOT_USING_CUSTOM_DOMAIN: 'NOT_USING_CUSTOM_DOMAIN',
	SITE_GRAYLISTED: 'SITE_GRAYLISTED',
	SITE_PRIVATE: 'SITE_PRIVATE',
};
