import {
	PLAN_BLOGGER,
	PLAN_BLOGGER_2_YEARS,
	PLAN_BUSINESS,
	PLAN_BUSINESS_2_YEARS,
	PLAN_BUSINESS_3_YEARS,
	PLAN_BUSINESS_MONTHLY,
	PLAN_ECOMMERCE,
	PLAN_ECOMMERCE_2_YEARS,
	PLAN_ECOMMERCE_3_YEARS,
	PLAN_ECOMMERCE_MONTHLY,
	PLAN_ECOMMERCE_TRIAL_MONTHLY,
	PLAN_ENTERPRISE_GRID_WPCOM,
	PLAN_FREE,
	PLAN_JETPACK_BUSINESS,
	PLAN_JETPACK_BUSINESS_MONTHLY,
	PLAN_JETPACK_COMPLETE,
	PLAN_JETPACK_COMPLETE_MONTHLY,
	PLAN_JETPACK_FREE,
	// PLAN_JETPACK_GOLDEN_TOKEN,
	PLAN_JETPACK_PERSONAL,
	PLAN_JETPACK_PERSONAL_MONTHLY,
	PLAN_JETPACK_PREMIUM,
	PLAN_JETPACK_PREMIUM_MONTHLY,
	PLAN_JETPACK_SECURITY_DAILY,
	PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	PLAN_JETPACK_SECURITY_REALTIME,
	PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
	PLAN_JETPACK_SECURITY_T1_MONTHLY,
	PLAN_JETPACK_SECURITY_T1_YEARLY,
	PLAN_JETPACK_SECURITY_T1_BI_YEARLY,
	PLAN_JETPACK_SECURITY_T2_MONTHLY,
	PLAN_JETPACK_SECURITY_T2_YEARLY,
	// PLAN_JETPACK_STARTER_MONTHLY,
	// PLAN_JETPACK_STARTER_YEARLY,
	PLAN_PERSONAL,
	PLAN_PERSONAL_2_YEARS,
	PLAN_PERSONAL_3_YEARS,
	PLAN_PERSONAL_MONTHLY,
	PLAN_PREMIUM,
	PLAN_PREMIUM_2_YEARS,
	PLAN_PREMIUM_3_YEARS,
	PLAN_PREMIUM_MONTHLY,
	PLAN_WPCOM_FLEXIBLE,
	PLAN_WPCOM_STARTER,
	PLAN_WPCOM_PRO,
	PLAN_WPCOM_PRO_MONTHLY,
	PLAN_WPCOM_PRO_2_YEARS,
} from './constants';
import { PLANS_LIST } from './plans-list';
import type { PlanSlug } from './types';

/**
 * Return a commission fee based on a plan slug.
 * Note that source of truth for these is at the billing backend.
 *
 * @param {PlanSlug} slug Slug/name of the plan
 * @returns {number} Percentage for transaction fee
 */
export function getPlanCommissionFee( slug: PlanSlug | string | null ): number {
	// The default commission for all sites are 10%.
	// However, the 10% commission is typically used for sites on the free plan.
	const defaultCommissionForAllSites = 0.1;

	if ( ! slug ) {
		return defaultCommissionForAllSites * 100;
	}

	const plan = PLANS_LIST[ slug ];
	console.log( 'getPlanCommissionFee:', slug, plan ); //eslint-disable-line no-console

	const commissionMap = {
		// Jetpack plans
		[ PLAN_JETPACK_BUSINESS ]: 0.02,
		[ PLAN_JETPACK_BUSINESS_MONTHLY ]: 0.02,
		[ PLAN_JETPACK_COMPLETE ]: 0.02,
		[ PLAN_JETPACK_COMPLETE_MONTHLY ]: 0.02,
		[ PLAN_JETPACK_FREE ]: 0.1,
		// [ PLAN_JETPACK_GOLDEN_TOKEN ]: 0,
		[ PLAN_JETPACK_PERSONAL ]: 0.08,
		[ PLAN_JETPACK_PERSONAL_MONTHLY ]: 0.08,
		[ PLAN_JETPACK_PREMIUM ]: 0.04,
		[ PLAN_JETPACK_PREMIUM_MONTHLY ]: 0.04,
		[ PLAN_JETPACK_SECURITY_DAILY ]: 0.04,
		[ PLAN_JETPACK_SECURITY_DAILY_MONTHLY ]: 0.04,
		[ PLAN_JETPACK_SECURITY_REALTIME ]: 0.02,
		[ PLAN_JETPACK_SECURITY_REALTIME_MONTHLY ]: 0.02,
		[ PLAN_JETPACK_SECURITY_T1_MONTHLY ]: 0.02,
		[ PLAN_JETPACK_SECURITY_T1_YEARLY ]: 0.02,
		[ PLAN_JETPACK_SECURITY_T1_BI_YEARLY ]: 0.02,
		[ PLAN_JETPACK_SECURITY_T2_MONTHLY ]: 0.02,
		[ PLAN_JETPACK_SECURITY_T2_YEARLY ]: 0.02,
		// [ PLAN_JETPACK_STARTER_MONTHLY ]: 0,
		// [ PLAN_JETPACK_STARTER_YEARLY ]: 0,

		// WordPress.com plans
		[ PLAN_BLOGGER ]: 0.1,
		[ PLAN_BLOGGER_2_YEARS ]: 0.1,
		[ PLAN_BUSINESS ]: 0.02,
		[ PLAN_BUSINESS_2_YEARS ]: 0.02,
		[ PLAN_BUSINESS_3_YEARS ]: 0.02,
		[ PLAN_BUSINESS_MONTHLY ]: 0.02,
		[ PLAN_ECOMMERCE ]: 0,
		[ PLAN_ECOMMERCE_2_YEARS ]: 0,
		[ PLAN_ECOMMERCE_3_YEARS ]: 0,
		[ PLAN_ECOMMERCE_MONTHLY ]: 0,
		[ PLAN_ECOMMERCE_TRIAL_MONTHLY ]: 0,
		[ PLAN_ENTERPRISE_GRID_WPCOM ]: 0,
		[ PLAN_FREE ]: 0.1,
		[ PLAN_PERSONAL ]: 0.08,
		[ PLAN_PERSONAL_2_YEARS ]: 0.08,
		[ PLAN_PERSONAL_3_YEARS ]: 0.08,
		[ PLAN_PERSONAL_MONTHLY ]: 0.08,
		[ PLAN_PREMIUM ]: 0.04,
		[ PLAN_PREMIUM_2_YEARS ]: 0.04,
		[ PLAN_PREMIUM_3_YEARS ]: 0.04,
		[ PLAN_PREMIUM_MONTHLY ]: 0.04,
		[ PLAN_WPCOM_FLEXIBLE ]: 0.03,
		[ PLAN_WPCOM_STARTER ]: 0.03,
		[ PLAN_WPCOM_PRO ]: 0.02,
		[ PLAN_WPCOM_PRO_MONTHLY ]: 0.02,
		[ PLAN_WPCOM_PRO_2_YEARS ]: 0.02,
		[ PLAN_ENTERPRISE_GRID_WPCOM ]: 0,
	};
	console.log( 'commissionMap:', commissionMap ); //eslint-disable-line no-console

	if ( plan ) {
		return 0.02 * 100;
	}

	return defaultCommissionForAllSites * 100;
}
