export const OPTIONS_RECEIVE = 'OPTIONS_RECEIVE';
export const OPTIONS_REQUEST = 'OPTIONS_REQUEST';
export const OPTIONS_REQUEST_SUCCESS = 'OPTIONS_REQUEST_SUCCESS';
export const OPTIONS_REQUEST_FAILURE = 'OPTIONS_REQUEST_FAILURE';
