export const TEST_EXTENSION_FETCH = 'TEST_EXTENSION_FETCH';
export const TEST_EXTENSION_FETCH_FAILURE = 'TEST_EXTENSION_FETCH_FAILURE';
export const TEST_EXTENSION_FETCH_SUCCESS = 'TEST_EXTENSION_FETCH_SUCCESS';
