module.exports = {
	action: {
		FETCH_NEXT_PAGE: 'FETCH_NEXT_FEED_STREAM_PAGE',
		RECEIVE_PAGE: 'RECEIVE_FEED_STREAM_PAGE',
		SHOW_UPDATES: 'SHOW_FEED_STREAM_UPDATES',
		RECEIVE_UPDATES: 'RECEIVE_FEED_STREAM_UPDATES',
		FILL_GAP: 'FILL_FEED_STREAM_GAP',
		RECEIVE_GAP: 'RECEIVE_FEED_STREAM_GAP',
		SELECT_ITEM: 'SELECT_ITEM',
		SELECT_NEXT_ITEM: 'SELECT_NEXT_ITEM',
		SELECT_PREV_ITEM: 'SELECT_PREV_ITEM',
		SELECT_FIRST_ITEM: 'SELECT_FIRST_ITEM',
		DISMISS_POST: 'DISMISS_FEED_STREAM_POST',
		SHUFFLE_POSTS: 'SHUFFLE_FEED_STREAM_POSTS'
	}
};
