export const ZONINATOR_REQUEST_ZONES = 'ZONINATOR_REQUEST_ZONES';
export const ZONINATOR_UPDATE_ZONES = 'ZONINATOR_UPDATE_ZONES';
export const ZONINATOR_REQUEST_ERROR = 'ZONINATOR_REQUEST_ERROR';
export const ZONINATOR_ADD_ZONE = 'ZONINATOR_ADD_ZONE';
export const ZONINATOR_UPDATE_ZONE = 'ZONINATOR_UPDATE_ZONE';
