import { useTranslate } from 'i18n-calypso';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const BlazePressStrings = () => {
	const translate = useTranslate();
	translate( 'All topics' );
	translate( 'Everywhere' );
	translate( 'Devices' );
	translate( 'Location' );
	translate( 'Interests' );
	translate( 'Ad Preview' );
	translate( 'total over' );
	translate( 'days' );
	translate( 'Budget & Duration' );
	translate( 'What will be the Goal?' );
	translate( 'What kind of Ad will be?' );
	translate( 'Not enough impressions with current Audience settings' );
	translate( 'Cannot calculate' );
	translate( 'Calculating' );
	translate( 'Estimated impressions' );
	translate( 'Volume' );
	translate( 'How much do you want to spend per day?' );
	translate( 'Number of Days the campaign will run for' );
	translate( 'How long do you want to promote your post from now?' );
	translate( "Let's add some final details" );
	translate( 'Campaign name' );
	translate( 'Campaign description' );
	translate( 'Promoting your post' );
	translate( 'Oops!' );
	translate( 'The campaign cannot be created. Please {{a}}contact our support team{{/a}}.' );
	translate( 'All set!' );
	translate(
		'The ad has been submitted for approval and we’ll send you a confirmation email once it’s approved and running.'
	);
	translate( 'Go to campaigns' );
	translate( 'Learn more about the' );
	translate( 'Advertising Terms' );
	translate( 'First Name' );
	translate( 'Last Name' );
	translate( 'Address 1' );
	translate( 'Address 2' );
	translate( 'State' );
	translate( 'City' );
	translate( 'Postcode' );
	translate( 'Payment' );
	translate( 'Creating Subscription' );
	translate( "Let's add a payment method" );
	translate( 'How the ad will be purchased' );
	translate( 'Appearance' );
	translate( 'Please upload an image' );
	translate( 'For a 300x250 ad, the image has a 300x140 format.' );
	translate( 'Title' );
	translate( '%(charactersLeft)s characters remaining' );
	translate( 'Snippet' );
	translate( 'Article Snippet' );
	translate( '%(snippetCharactersLeft)s characters remaining' );
	translate( "Let's configure the campaign" );
	translate( 'All devices' );
	translate( 'Card Number' );
	translate( 'Exp. Date' );
	translate( 'CVV' );
	translate( 'Previous' );
	translate( 'Continue' );
};
