export const AUTO_SHARED_SOCIAL_POST_PREVIEW = 'AUTO_SHARED_SOCIAL_POST_PREVIEW';
export const AUTO_SHARED_LINK_PREVIEW = 'AUTO_SHARED_LINK_PREVIEW';
export const DEFAULT_LINK_PREVIEW = 'DEFAULT_LINK_PREVIEW';
