export const STORE_KEY = 'automattic/launchpad-navigator';
export const LAUNCHPAD_NAVIGATOR_RECEIVE_ACTIVE_CHECKLIST_SLUG =
	'LAUNCHPAD_NAVIGATOR_RECEIVE_ACTIVE_CHECKLIST_SLUG';
export const LAUNCHPAD_NAVIGATOR_REMOVE_CHECKLIST = 'LAUNCHPAD_NAVIGATOR_REMOVE_CHECKLIST';
