export const PRODUCT_AKISMET_PLUS_YEARLY = 'ak_plus_yearly_1';
export const PRODUCT_AKISMET_PLUS_MONTHLY = 'ak_plus_monthly_1';
export const PRODUCT_AKISMET_PLUS_20K_YEARLY = 'ak_plus_yearly_2';
export const PRODUCT_AKISMET_PLUS_20K_MONTHLY = 'ak_plus_monthly_2';
export const PRODUCT_AKISMET_PLUS_30K_YEARLY = 'ak_plus_yearly_3';
export const PRODUCT_AKISMET_PLUS_30K_MONTHLY = 'ak_plus_monthly_3';
export const PRODUCT_AKISMET_PLUS_40K_YEARLY = 'ak_plus_yearly_4';
export const PRODUCT_AKISMET_PLUS_40K_MONTHLY = 'ak_plus_monthly_4';
export const PRODUCT_AKISMET_ENTERPRISE_YEARLY = 'ak_ent_yearly_1';
export const PRODUCT_AKISMET_ENTERPRISE_MONTHLY = 'ak_ent_monthly_1';
export const PRODUCT_AKISMET_ENTERPRISE_350K_YEARLY = 'ak_ep350k_yearly_1';
export const PRODUCT_AKISMET_ENTERPRISE_350K_MONTHLY = 'ak_ep350k_monthly_1';
export const PRODUCT_AKISMET_ENTERPRISE_2M_YEARLY = 'ak_ep2m_yearly_1';
export const PRODUCT_AKISMET_ENTERPRISE_2M_MONTHLY = 'ak_ep2m_monthly_1';
export const PRODUCT_AKISMET_ENTERPRISE_GT2M_YEARLY = 'ak_epgt2m_yearly_1';
export const PRODUCT_AKISMET_ENTERPRISE_GT2M_MONTHLY = 'ak_epgt2m_monthly_1';

export const AKISTMET_PLUS_MONTHLY_PRODUCTS = <const>[
	PRODUCT_AKISMET_PLUS_MONTHLY,
	PRODUCT_AKISMET_PLUS_20K_MONTHLY,
	PRODUCT_AKISMET_PLUS_30K_MONTHLY,
	PRODUCT_AKISMET_PLUS_40K_MONTHLY,
];

export const AKISMET_ENTERPRISE_MONTHLY_PRODUCTS = <const>[
	PRODUCT_AKISMET_ENTERPRISE_2M_YEARLY,
	PRODUCT_AKISMET_ENTERPRISE_2M_MONTHLY,
	PRODUCT_AKISMET_ENTERPRISE_GT2M_YEARLY,
	PRODUCT_AKISMET_ENTERPRISE_GT2M_MONTHLY,
];

export const AKISMET_PLUS_YEARLY_PRODUCTS = <const>[
	PRODUCT_AKISMET_PLUS_YEARLY,
	PRODUCT_AKISMET_PLUS_20K_YEARLY,
	PRODUCT_AKISMET_PLUS_30K_YEARLY,
	PRODUCT_AKISMET_PLUS_40K_YEARLY,
];

export const AKISMET_ENTERPRISE_YEARLY_PRODUCTS = <const>[
	PRODUCT_AKISMET_ENTERPRISE_YEARLY,
	PRODUCT_AKISMET_ENTERPRISE_350K_YEARLY,
	PRODUCT_AKISMET_ENTERPRISE_2M_YEARLY,
	PRODUCT_AKISMET_ENTERPRISE_GT2M_YEARLY,
];

export const AKISMET_PLUS_PRODUCTS = <const>[
	...AKISTMET_PLUS_MONTHLY_PRODUCTS,
	...AKISMET_PLUS_YEARLY_PRODUCTS,
];

export const AKISMET_ENTERPRISE_PRODUCTS = <const>[
	...AKISMET_ENTERPRISE_MONTHLY_PRODUCTS,
	...AKISMET_ENTERPRISE_YEARLY_PRODUCTS,
];

export const AKISMET_MONTHLY_PRODUCTS = <const>[
	...AKISTMET_PLUS_MONTHLY_PRODUCTS,
	...AKISMET_ENTERPRISE_MONTHLY_PRODUCTS,
];

export const AKISMET_YEARLY_PRODUCTS = <const>[
	...AKISMET_PLUS_YEARLY_PRODUCTS,
	...AKISMET_ENTERPRISE_YEARLY_PRODUCTS,
];

export const AKISMET_PRODUCTS = <const>[ ...AKISMET_PLUS_PRODUCTS, ...AKISMET_ENTERPRISE_PRODUCTS ];
