import { PRODUCT_WPCOM_SEARCH, PRODUCT_WPCOM_SEARCH_MONTHLY } from './wpcom';

export const GROUP_JETPACK = 'GROUP_JETPACK';

// Products
export const PRODUCT_JETPACK_AI_BI_YEARLY = 'jetpack_ai_bi_yearly';
export const PRODUCT_JETPACK_AI_BI_YEARLY_100 = 'jetpack_ai_bi_yearly:-q-100';
export const PRODUCT_JETPACK_AI_BI_YEARLY_200 = 'jetpack_ai_bi_yearly:-q-200';
export const PRODUCT_JETPACK_AI_BI_YEARLY_500 = 'jetpack_ai_bi_yearly:-q-500';
export const PRODUCT_JETPACK_AI_BI_YEARLY_750 = 'jetpack_ai_bi_yearly:-q-750';
export const PRODUCT_JETPACK_AI_BI_YEARLY_1000 = 'jetpack_ai_bi_yearly:-q-1000';
export const PRODUCT_JETPACK_AI_MONTHLY = 'jetpack_ai_monthly';
export const PRODUCT_JETPACK_AI_MONTHLY_100 = 'jetpack_ai_monthly:-q-100';
export const PRODUCT_JETPACK_AI_MONTHLY_200 = 'jetpack_ai_monthly:-q-200';
export const PRODUCT_JETPACK_AI_MONTHLY_500 = 'jetpack_ai_monthly:-q-500';
export const PRODUCT_JETPACK_AI_MONTHLY_750 = 'jetpack_ai_monthly:-q-750';
export const PRODUCT_JETPACK_AI_MONTHLY_1000 = 'jetpack_ai_monthly:-q-1000';
export const PRODUCT_JETPACK_AI_YEARLY = 'jetpack_ai_yearly';
export const PRODUCT_JETPACK_AI_YEARLY_100 = 'jetpack_ai_yearly:-q-100';
export const PRODUCT_JETPACK_AI_YEARLY_200 = 'jetpack_ai_yearly:-q-200';
export const PRODUCT_JETPACK_AI_YEARLY_500 = 'jetpack_ai_yearly:-q-500';
export const PRODUCT_JETPACK_AI_YEARLY_750 = 'jetpack_ai_yearly:-q-750';
export const PRODUCT_JETPACK_AI_YEARLY_1000 = 'jetpack_ai_yearly:-q-1000';
export const PRODUCT_JETPACK_BOOST_BI_YEARLY = 'jetpack_boost_bi_yearly';
export const PRODUCT_JETPACK_BOOST = 'jetpack_boost_yearly';
export const PRODUCT_JETPACK_BOOST_MONTHLY = 'jetpack_boost_monthly';
export const PRODUCT_JETPACK_BACKUP = 'jetpack_backup';
export const PRODUCT_JETPACK_BACKUP_T0_YEARLY = 'jetpack_backup_t0_yearly';
export const PRODUCT_JETPACK_BACKUP_T0_MONTHLY = 'jetpack_backup_t0_monthly';
export const PRODUCT_JETPACK_BACKUP_T1_YEARLY = 'jetpack_backup_t1_yearly';
export const PRODUCT_JETPACK_BACKUP_T1_BI_YEARLY = 'jetpack_backup_t1_bi_yearly';
export const PRODUCT_JETPACK_BACKUP_T1_MONTHLY = 'jetpack_backup_t1_monthly';
export const PRODUCT_JETPACK_BACKUP_T2_YEARLY = 'jetpack_backup_t2_yearly';
export const PRODUCT_JETPACK_BACKUP_T2_MONTHLY = 'jetpack_backup_t2_monthly';
export const PRODUCT_JETPACK_SCAN_BI_YEARLY = 'jetpack_scan_bi_yearly';
export const PRODUCT_JETPACK_SCAN = 'jetpack_scan';
export const PRODUCT_JETPACK_SCAN_MONTHLY = 'jetpack_scan_monthly';
export const PRODUCT_JETPACK_SCAN_REALTIME = 'jetpack_scan_realtime';
export const PRODUCT_JETPACK_SCAN_REALTIME_MONTHLY = 'jetpack_scan_realtime_monthly';
export const PRODUCT_JETPACK_ANTI_SPAM_BI_YEARLY = 'jetpack_anti_spam_bi_yearly';
export const PRODUCT_JETPACK_ANTI_SPAM = 'jetpack_anti_spam';
export const PRODUCT_JETPACK_ANTI_SPAM_MONTHLY = 'jetpack_anti_spam_monthly';
export const PRODUCT_JETPACK_SEARCH_BI_YEARLY = 'jetpack_search_bi_yearly';
export const PRODUCT_JETPACK_SEARCH = 'jetpack_search';
export const PRODUCT_JETPACK_SEARCH_FREE = 'jetpack_search_free';
export const PRODUCT_JETPACK_SEARCH_MONTHLY = 'jetpack_search_monthly';
export const PRODUCT_JETPACK_CRM = 'jetpack_crm';
export const PRODUCT_JETPACK_CRM_MONTHLY = 'jetpack_crm_monthly';
export const PRODUCT_JETPACK_CRM_FREE = 'jetpack_crm_free';
export const PRODUCT_JETPACK_CRM_FREE_MONTHLY = 'jetpack_crm_free_monthly';
export const PRODUCT_JETPACK_VIDEOPRESS_BI_YEARLY = 'jetpack_videopress_bi_yearly';
export const PRODUCT_JETPACK_VIDEOPRESS = 'jetpack_videopress';
export const PRODUCT_JETPACK_VIDEOPRESS_MONTHLY = 'jetpack_videopress_monthly';
export const PRODUCT_JETPACK_SOCIAL_BASIC_BI_YEARLY = 'jetpack_social_basic_bi_yearly';
export const PRODUCT_JETPACK_SOCIAL_BASIC = 'jetpack_social_basic_yearly';
export const PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY = 'jetpack_social_basic_monthly';
export const PRODUCT_JETPACK_SOCIAL_ADVANCED_BI_YEARLY = 'jetpack_social_advanced_bi_yearly';
export const PRODUCT_JETPACK_SOCIAL_ADVANCED = 'jetpack_social_advanced_yearly';
export const PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY = 'jetpack_social_advanced_monthly';
export const PRODUCT_JETPACK_SOCIAL_V1_BI_YEARLY = 'jetpack_social_v1_bi_yearly';
export const PRODUCT_JETPACK_SOCIAL_V1_YEARLY = 'jetpack_social_v1_yearly';
export const PRODUCT_JETPACK_SOCIAL_V1_MONTHLY = 'jetpack_social_v1_monthly';
export const PRODUCT_JETPACK_STATS_MONTHLY = 'jetpack_stats_monthly';
export const PRODUCT_JETPACK_STATS_MONTHLY_10K = 'jetpack_stats_monthly:-q-10000';
export const PRODUCT_JETPACK_STATS_MONTHLY_100K = 'jetpack_stats_monthly:-q-100000';
export const PRODUCT_JETPACK_STATS_MONTHLY_250K = 'jetpack_stats_monthly:-q-250000';
export const PRODUCT_JETPACK_STATS_MONTHLY_500K = 'jetpack_stats_monthly:-q-500000';
export const PRODUCT_JETPACK_STATS_MONTHLY_1M = 'jetpack_stats_monthly:-q-1000000';
export const PRODUCT_JETPACK_STATS_YEARLY = 'jetpack_stats_yearly';
export const PRODUCT_JETPACK_STATS_YEARLY_10K = 'jetpack_stats_yearly:-q-10000';
export const PRODUCT_JETPACK_STATS_YEARLY_100K = 'jetpack_stats_yearly:-q-100000';
export const PRODUCT_JETPACK_STATS_YEARLY_250K = 'jetpack_stats_yearly:-q-250000';
export const PRODUCT_JETPACK_STATS_YEARLY_500K = 'jetpack_stats_yearly:-q-500000';
export const PRODUCT_JETPACK_STATS_YEARLY_1M = 'jetpack_stats_yearly:-q-1000000';
export const PRODUCT_JETPACK_STATS_BI_YEARLY = 'jetpack_stats_bi_yearly';
export const PRODUCT_JETPACK_STATS_BI_YEARLY_10K = 'jetpack_stats_bi_yearly:-q-10000';
export const PRODUCT_JETPACK_STATS_BI_YEARLY_100K = 'jetpack_stats_bi_yearly:-q-100000';
export const PRODUCT_JETPACK_STATS_BI_YEARLY_250K = 'jetpack_stats_bi_yearly:-q-250000';
export const PRODUCT_JETPACK_STATS_BI_YEARLY_500K = 'jetpack_stats_bi_yearly:-q-500000';
export const PRODUCT_JETPACK_STATS_BI_YEARLY_1M = 'jetpack_stats_bi_yearly:-q-1000000';
export const PRODUCT_JETPACK_STATS_PWYW_YEARLY = 'jetpack_stats_pwyw_yearly';
export const PRODUCT_JETPACK_STATS_FREE = 'jetpack_stats_free_yearly';
export const PRODUCT_JETPACK_MONITOR_YEARLY = 'jetpack_monitor_yearly';
export const PRODUCT_JETPACK_MONITOR_MONTHLY = 'jetpack_monitor_monthly';
export const PRODUCT_JETPACK_MONITOR = PRODUCT_JETPACK_MONITOR_YEARLY;
export const PRODUCT_JETPACK_CREATOR_BI_YEARLY = 'jetpack_creator_bi_yearly';
export const PRODUCT_JETPACK_CREATOR_YEARLY = 'jetpack_creator_yearly';
export const PRODUCT_JETPACK_CREATOR_MONTHLY = 'jetpack_creator_monthly';

//add-on products
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_10GB_MONTHLY =
	'jetpack_backup_addon_storage_10gb_monthly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_100GB_MONTHLY =
	'jetpack_backup_addon_storage_100gb_monthly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_1TB_MONTHLY =
	'jetpack_backup_addon_storage_1tb_monthly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_3TB_MONTHLY =
	'jetpack_backup_addon_storage_3tb_monthly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_5TB_MONTHLY =
	'jetpack_backup_addon_storage_5tb_monthly';

export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_10GB_YEARLY =
	'jetpack_backup_addon_storage_10gb_yearly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_100GB_YEARLY =
	'jetpack_backup_addon_storage_100gb_yearly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_1TB_YEARLY =
	'jetpack_backup_addon_storage_1tb_yearly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_3TB_YEARLY =
	'jetpack_backup_addon_storage_3tb_yearly';
export const PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_5TB_YEARLY =
	'jetpack_backup_addon_storage_5tb_yearly';

// Legacy Products
export const PRODUCT_JETPACK_BACKUP_DAILY = 'jetpack_backup_daily';
export const PRODUCT_JETPACK_BACKUP_REALTIME = 'jetpack_backup_realtime';
export const PRODUCT_JETPACK_BACKUP_DAILY_MONTHLY = 'jetpack_backup_daily_monthly';
export const PRODUCT_JETPACK_BACKUP_REALTIME_MONTHLY = 'jetpack_backup_realtime_monthly';

// Woo Extensions
export const PRODUCT_WOOCOMMERCE_BOOKINGS = 'woocommerce_bookings_yearly';
export const PRODUCT_WOOCOMMERCE_SUBSCRIPTIONS = 'woocommerce_subscriptions_yearly';
export const PRODUCT_WOOCOMMERCE_PRODUCT_BUNDLES = 'woocommerce_product_bundles_yearly';
export const PRODUCT_WOOCOMMERCE_PRODUCT_ADD_ONS = 'woocommerce_product_add_ons_yearly';
export const PRODUCT_WOOCOMMERCE_MINMAX_QUANTITIES = 'woocommerce_minmax_quantities_yearly';
export const PRODUCT_WOOCOMMERCE_AUTOMATEWOO = 'woocommerce_automatewoo_yearly';
export const PRODUCT_WOOCOMMERCE_ADVANCED_NOTIFICATIONS =
	'woocommerce_advanced_notifications_yearly';
export const PRODUCT_WOOCOMMERCE_ALL_PRODUCTS_WOO_SUBSCRIPTIONS =
	'woocommerce_all_products_woo_subscriptions_yearly';
export const PRODUCT_WOOCOMMERCE_AUTOMATEWOO_BIRTHDAYS = 'woocommerce_automatewoo_birthdays_yearly';
export const PRODUCT_WOOCOMMERCE_AUTOMATEWOO_REFER_A_FRIEND =
	'woocommerce_automatewoo_refer_a_friend_yearly';
export const PRODUCT_WOOCOMMERCE_BACK_IN_STOCK_NOTIFICATIONS =
	'woocommerce_back_in_stock_notifications_yearly';
export const PRODUCT_WOOCOMMERCE_BULK_STOCK_MANAGEMENT = 'woocommerce_bulk_stock_management_yearly';
export const PRODUCT_WOOCOMMERCE_CHECKOUT_FIELD_EDITOR = 'woocommerce_checkout_field_editor_yearly';
export const PRODUCT_WOOCOMMERCE_COMPOSITE_PRODUCTS = 'woocommerce_composite_products_yearly';
export const PRODUCT_WOOCOMMERCE_CONDITIONAL_SHIPPING_PAYMENTS =
	'woocommerce_conditional_shipping_payments_yearly';
export const PRODUCT_WOOCOMMERCE_EU_VAT_NUMBER = 'woocommerce_eu_vat_number_yearly';
export const PRODUCT_WOOCOMMERCE_FLAT_RATE_BOX_SHIPPING =
	'woocommerce_flat_rate_box_shipping_yearly';
export const PRODUCT_WOOCOMMERCE_GIFT_CARDS = 'woocommerce_gift_cards_yearly';
export const PRODUCT_WOOCOMMERCE_GIFTING_WC_SUBSCRIPTIONS =
	'woocommerce_gifting_wc_subscriptions_yearly';
export const PRODUCT_WOOCOMMERCE_PER_PRODUCT_SHIPPING = 'woocommerce_per_product_shipping_yearly';
export const PRODUCT_WOOCOMMERCE_PRODUCT_CSV_IMPORT_SUITE =
	'woocommerce_product_csv_import_suite_yearly';
export const PRODUCT_WOOCOMMERCE_PRODUCT_RECOMMENDATIONS =
	'woocommerce_product_recommendations_yearly';
export const PRODUCT_WOOCOMMERCE_PRODUCT_VENDORS = 'woocommerce_product_vendors_yearly';
export const PRODUCT_WOOCOMMERCE_RETURNS_WARRANTY_REQUESTS =
	'woocommerce_returns_warranty_requests_yearly';
export const PRODUCT_WOOCOMMERCE_SUBSCRIPTION_DOWNLOADS =
	'woocommerce_subscription_downloads_yearly';
export const PRODUCT_WOOCOMMERCE_SHIPMENT_TRACKING = 'woocommerce_shipment_tracking_yearly';
export const PRODUCT_WOOCOMMERCE_SHIPPING_MULTIPLE_ADDRESSES =
	'woocommerce_shipping_multiple_addresses_yearly';
export const PRODUCT_WOOCOMMERCE_STOREFRONT_EXTENSIONS_BUNDLE =
	'woocommerce_storefront_extensions_bundle_yearly';
export const PRODUCT_WOOCOMMERCE_TABLE_RATE_SHIPPING = 'woocommerce_table_rate_shipping_yearly';
export const PRODUCT_WOOCOMMERCE_ADDITIONAL_IMAGE_VARIATIONS =
	'woocommerce_additional_image_variations_yearly';
export const PRODUCT_WOOCOMMERCE_BOOKINGS_AVAILABILITY = 'woocommerce_bookings_availability_yearly';
export const PRODUCT_WOOCOMMERCE_BOX_OFFICE = 'woocommerce_box_office_yearly';
export const PRODUCT_WOOCOMMERCE_BRANDS = 'woocommerce_brands_yearly';
export const PRODUCT_WOOCOMMERCE_COUPON_CAMPAIGNS = 'woocommerce_coupon_campaigns_yearly';
export const PRODUCT_WOOCOMMERCE_DEPOSITS = 'woocommerce_deposits_yearly';
export const PRODUCT_WOOCOMMERCE_DISTANCE_RATE_SHIPPING =
	'woocommerce_distance_rate_shipping_yearly';
export const PRODUCT_WOOCOMMERCE_ONE_PAGE_CHECKOUT = 'woocommerce_one_page_checkout_yearly';
export const PRODUCT_WOOCOMMERCE_ORDER_BARCODES = 'woocommerce_order_barcodes_yearly';
export const PRODUCT_WOOCOMMERCE_POINTS_AND_REWARDS = 'woocommerce_points_and_rewards_yearly';
export const PRODUCT_WOOCOMMERCE_PRE_ORDERS = 'woocommerce_pre_orders_yearly';
export const PRODUCT_WOOCOMMERCE_PURCHASE_ORDER_GATEWAY =
	'woocommerce_purchase_order_gateway_yearly';
export const PRODUCT_WOOCOMMERCE_SHIPPING = 'woocommerce_shipping_yearly';
export const PRODUCT_WOOCOMMERCE_ACCOMMODATIONS_BOOKINGS =
	'woocommerce_accommodations_bookings_yearly';
export const PRODUCT_WOOCOMMERCE_TAX = 'woocommerce_tax_yearly';
export const PRODUCT_WOOCOMMERCE_WOOPAYMENTS = 'woocommerce_woopayments_yearly';
export const PRODUCT_WOOCOMMERCE_PRODUCT_FILTERS = 'woocommerce_product_filters_yearly';

// Backup
export const JETPACK_BACKUP_PRODUCTS_YEARLY = < const >[
	PRODUCT_JETPACK_BACKUP_DAILY,
	PRODUCT_JETPACK_BACKUP_REALTIME,
	PRODUCT_JETPACK_BACKUP_T0_YEARLY,
	PRODUCT_JETPACK_BACKUP_T1_YEARLY,
	PRODUCT_JETPACK_BACKUP_T2_YEARLY,
];
export const JETPACK_BACKUP_PRODUCTS_MONTHLY = < const >[
	PRODUCT_JETPACK_BACKUP_DAILY_MONTHLY,
	PRODUCT_JETPACK_BACKUP_REALTIME_MONTHLY,
	PRODUCT_JETPACK_BACKUP_T0_MONTHLY,
	PRODUCT_JETPACK_BACKUP_T1_MONTHLY,
	PRODUCT_JETPACK_BACKUP_T2_MONTHLY,
];
export const JETPACK_BACKUP_PRODUCTS = < const >[
	PRODUCT_JETPACK_BACKUP_T1_BI_YEARLY,
	...JETPACK_BACKUP_PRODUCTS_YEARLY,
	...JETPACK_BACKUP_PRODUCTS_MONTHLY,
];
export const JETPACK_BACKUP_ADDON_MONTHLY = < const >[
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_10GB_MONTHLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_100GB_MONTHLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_1TB_MONTHLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_3TB_MONTHLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_5TB_MONTHLY,
];
export const JETPACK_BACKUP_ADDON_YEARLY = < const >[
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_10GB_YEARLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_100GB_YEARLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_1TB_YEARLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_3TB_YEARLY,
	PRODUCT_JETPACK_BACKUP_ADDON_STORAGE_5TB_YEARLY,
];
export const JETPACK_BACKUP_ADDON_PRODUCTS = < const >[
	...JETPACK_BACKUP_ADDON_MONTHLY,
	...JETPACK_BACKUP_ADDON_YEARLY,
];
export const JETPACK_BACKUP_T0_PRODUCTS = < const >[
	PRODUCT_JETPACK_BACKUP_T0_MONTHLY,
	PRODUCT_JETPACK_BACKUP_T0_YEARLY,
];
export const JETPACK_BACKUP_T1_PRODUCTS = < const >[
	PRODUCT_JETPACK_BACKUP_T1_BI_YEARLY,
	PRODUCT_JETPACK_BACKUP_T1_MONTHLY,
	PRODUCT_JETPACK_BACKUP_T1_YEARLY,
];
export const JETPACK_BACKUP_T2_PRODUCTS = < const >[
	PRODUCT_JETPACK_BACKUP_T2_MONTHLY,
	PRODUCT_JETPACK_BACKUP_T2_YEARLY,
];
// Boost
export const JETPACK_BOOST_PRODUCTS = < const >[
	PRODUCT_JETPACK_BOOST_BI_YEARLY,
	PRODUCT_JETPACK_BOOST,
	PRODUCT_JETPACK_BOOST_MONTHLY,
];

// Scan
export const JETPACK_SCAN_PRODUCTS = < const >[
	PRODUCT_JETPACK_SCAN_BI_YEARLY,
	PRODUCT_JETPACK_SCAN,
	PRODUCT_JETPACK_SCAN_MONTHLY,
	PRODUCT_JETPACK_SCAN_REALTIME,
	PRODUCT_JETPACK_SCAN_REALTIME_MONTHLY,
];

// Social Basic
export const JETPACK_SOCIAL_BASIC_PRODUCTS = < const >[
	PRODUCT_JETPACK_SOCIAL_BASIC_BI_YEARLY,
	PRODUCT_JETPACK_SOCIAL_BASIC,
	PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY,
];

// Social Advanced
export const JETPACK_SOCIAL_ADVANCED_PRODUCTS = < const >[
	PRODUCT_JETPACK_SOCIAL_ADVANCED_BI_YEARLY,
	PRODUCT_JETPACK_SOCIAL_ADVANCED,
	PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY,
];

export const JETPACK_SOCIAL_V1_PRODUCTS = < const >[
	PRODUCT_JETPACK_SOCIAL_V1_BI_YEARLY,
	PRODUCT_JETPACK_SOCIAL_V1_YEARLY,
	PRODUCT_JETPACK_SOCIAL_V1_MONTHLY,
];

// Social
export const JETPACK_SOCIAL_PRODUCTS = < const >[
	...JETPACK_SOCIAL_BASIC_PRODUCTS,
	...JETPACK_SOCIAL_ADVANCED_PRODUCTS,
	...JETPACK_SOCIAL_V1_PRODUCTS,
];

// Stats
export const JETPACK_STATS_PRODUCTS = < const >[
	PRODUCT_JETPACK_STATS_BI_YEARLY,
	PRODUCT_JETPACK_STATS_YEARLY,
	PRODUCT_JETPACK_STATS_MONTHLY,
	PRODUCT_JETPACK_STATS_PWYW_YEARLY,
	PRODUCT_JETPACK_STATS_FREE,
];

// Anti-spam
export const JETPACK_ANTI_SPAM_PRODUCTS = < const >[
	PRODUCT_JETPACK_ANTI_SPAM_BI_YEARLY,
	PRODUCT_JETPACK_ANTI_SPAM,
	PRODUCT_JETPACK_ANTI_SPAM_MONTHLY,
];

// Search
export const JETPACK_SEARCH_PRODUCTS = < const >[
	PRODUCT_JETPACK_SEARCH_BI_YEARLY,
	PRODUCT_JETPACK_SEARCH,
	PRODUCT_JETPACK_SEARCH_MONTHLY,
	PRODUCT_JETPACK_SEARCH_FREE,
	PRODUCT_WPCOM_SEARCH,
	PRODUCT_WPCOM_SEARCH_MONTHLY,
];

// CRM
export const JETPACK_CRM_PRODUCTS = < const >[ PRODUCT_JETPACK_CRM, PRODUCT_JETPACK_CRM_MONTHLY ];
export const JETPACK_CRM_FREE_PRODUCTS = < const >[
	PRODUCT_JETPACK_CRM_FREE,
	PRODUCT_JETPACK_CRM_FREE_MONTHLY,
];

// VideoPress
export const JETPACK_VIDEOPRESS_PRODUCTS = < const >[
	PRODUCT_JETPACK_VIDEOPRESS_BI_YEARLY,
	PRODUCT_JETPACK_VIDEOPRESS,
	PRODUCT_JETPACK_VIDEOPRESS_MONTHLY,
];

// Monitor
export const JETPACK_MONITOR_PRODUCTS = < const >[
	PRODUCT_JETPACK_MONITOR_YEARLY,
	PRODUCT_JETPACK_MONITOR_MONTHLY,
];

export const JETPACK_AI_PRODUCTS = < const >[
	PRODUCT_JETPACK_AI_BI_YEARLY,
	PRODUCT_JETPACK_AI_MONTHLY,
	PRODUCT_JETPACK_AI_YEARLY,
];

export const JETPACK_AI_ALIASES = < const >[
	PRODUCT_JETPACK_AI_BI_YEARLY_100,
	PRODUCT_JETPACK_AI_BI_YEARLY_200,
	PRODUCT_JETPACK_AI_BI_YEARLY_500,
	PRODUCT_JETPACK_AI_BI_YEARLY_750,
	PRODUCT_JETPACK_AI_BI_YEARLY_1000,
	PRODUCT_JETPACK_AI_MONTHLY_100,
	PRODUCT_JETPACK_AI_MONTHLY_200,
	PRODUCT_JETPACK_AI_MONTHLY_500,
	PRODUCT_JETPACK_AI_MONTHLY_750,
	PRODUCT_JETPACK_AI_MONTHLY_1000,
	PRODUCT_JETPACK_AI_YEARLY_100,
	PRODUCT_JETPACK_AI_YEARLY_200,
	PRODUCT_JETPACK_AI_YEARLY_500,
	PRODUCT_JETPACK_AI_YEARLY_750,
	PRODUCT_JETPACK_AI_YEARLY_1000,
];

export const JETPACK_STATS_ALIASES = < const >[
	PRODUCT_JETPACK_STATS_BI_YEARLY_10K,
	PRODUCT_JETPACK_STATS_BI_YEARLY_100K,
	PRODUCT_JETPACK_STATS_BI_YEARLY_250K,
	PRODUCT_JETPACK_STATS_BI_YEARLY_500K,
	PRODUCT_JETPACK_STATS_BI_YEARLY_1M,
	PRODUCT_JETPACK_STATS_MONTHLY_10K,
	PRODUCT_JETPACK_STATS_MONTHLY_100K,
	PRODUCT_JETPACK_STATS_MONTHLY_250K,
	PRODUCT_JETPACK_STATS_MONTHLY_500K,
	PRODUCT_JETPACK_STATS_MONTHLY_1M,
	PRODUCT_JETPACK_STATS_YEARLY_10K,
	PRODUCT_JETPACK_STATS_YEARLY_100K,
	PRODUCT_JETPACK_STATS_YEARLY_250K,
	PRODUCT_JETPACK_STATS_YEARLY_500K,
	PRODUCT_JETPACK_STATS_YEARLY_1M,
];

// Creator
export const JETPACK_CREATOR_PRODUCTS = < const >[
	PRODUCT_JETPACK_CREATOR_BI_YEARLY,
	PRODUCT_JETPACK_CREATOR_YEARLY,
	PRODUCT_JETPACK_CREATOR_MONTHLY,
];

// WooCommerce Products
export const WOOCOMMERCE_PRODUCTS = < const >[
	PRODUCT_WOOCOMMERCE_BOOKINGS,
	PRODUCT_WOOCOMMERCE_SUBSCRIPTIONS,
	PRODUCT_WOOCOMMERCE_PRODUCT_BUNDLES,
	PRODUCT_WOOCOMMERCE_PRODUCT_ADD_ONS,
	PRODUCT_WOOCOMMERCE_MINMAX_QUANTITIES,
	PRODUCT_WOOCOMMERCE_AUTOMATEWOO,
	PRODUCT_WOOCOMMERCE_ADVANCED_NOTIFICATIONS,
	PRODUCT_WOOCOMMERCE_ALL_PRODUCTS_WOO_SUBSCRIPTIONS,
	PRODUCT_WOOCOMMERCE_AUTOMATEWOO_BIRTHDAYS,
	PRODUCT_WOOCOMMERCE_AUTOMATEWOO_REFER_A_FRIEND,
	PRODUCT_WOOCOMMERCE_BACK_IN_STOCK_NOTIFICATIONS,
	PRODUCT_WOOCOMMERCE_BULK_STOCK_MANAGEMENT,
	PRODUCT_WOOCOMMERCE_CHECKOUT_FIELD_EDITOR,
	PRODUCT_WOOCOMMERCE_COMPOSITE_PRODUCTS,
	PRODUCT_WOOCOMMERCE_CONDITIONAL_SHIPPING_PAYMENTS,
	PRODUCT_WOOCOMMERCE_EU_VAT_NUMBER,
	PRODUCT_WOOCOMMERCE_FLAT_RATE_BOX_SHIPPING,
	PRODUCT_WOOCOMMERCE_GIFT_CARDS,
	PRODUCT_WOOCOMMERCE_GIFTING_WC_SUBSCRIPTIONS,
	PRODUCT_WOOCOMMERCE_PER_PRODUCT_SHIPPING,
	PRODUCT_WOOCOMMERCE_PRODUCT_CSV_IMPORT_SUITE,
	PRODUCT_WOOCOMMERCE_PRODUCT_RECOMMENDATIONS,
	PRODUCT_WOOCOMMERCE_PRODUCT_VENDORS,
	PRODUCT_WOOCOMMERCE_RETURNS_WARRANTY_REQUESTS,
	PRODUCT_WOOCOMMERCE_SUBSCRIPTION_DOWNLOADS,
	PRODUCT_WOOCOMMERCE_SHIPMENT_TRACKING,
	PRODUCT_WOOCOMMERCE_SHIPPING_MULTIPLE_ADDRESSES,
	PRODUCT_WOOCOMMERCE_STOREFRONT_EXTENSIONS_BUNDLE,
	PRODUCT_WOOCOMMERCE_TABLE_RATE_SHIPPING,
	PRODUCT_WOOCOMMERCE_ADDITIONAL_IMAGE_VARIATIONS,
	PRODUCT_WOOCOMMERCE_BOOKINGS_AVAILABILITY,
	PRODUCT_WOOCOMMERCE_BOX_OFFICE,
	PRODUCT_WOOCOMMERCE_BRANDS,
	PRODUCT_WOOCOMMERCE_COUPON_CAMPAIGNS,
	PRODUCT_WOOCOMMERCE_DEPOSITS,
	PRODUCT_WOOCOMMERCE_DISTANCE_RATE_SHIPPING,
	PRODUCT_WOOCOMMERCE_ONE_PAGE_CHECKOUT,
	PRODUCT_WOOCOMMERCE_ORDER_BARCODES,
	PRODUCT_WOOCOMMERCE_POINTS_AND_REWARDS,
	PRODUCT_WOOCOMMERCE_PRE_ORDERS,
	PRODUCT_WOOCOMMERCE_PURCHASE_ORDER_GATEWAY,
	PRODUCT_WOOCOMMERCE_SHIPPING,
	PRODUCT_WOOCOMMERCE_ACCOMMODATIONS_BOOKINGS,
	PRODUCT_WOOCOMMERCE_TAX,
	PRODUCT_WOOCOMMERCE_WOOPAYMENTS,
	PRODUCT_WOOCOMMERCE_PRODUCT_FILTERS,
];

export const JETPACK_PRODUCTS_LIST = < const >[
	...JETPACK_BACKUP_PRODUCTS,
	...JETPACK_BOOST_PRODUCTS,
	...JETPACK_SCAN_PRODUCTS,
	...JETPACK_ANTI_SPAM_PRODUCTS,
	...JETPACK_SEARCH_PRODUCTS,
	...JETPACK_VIDEOPRESS_PRODUCTS,
	...JETPACK_SOCIAL_PRODUCTS,
	...JETPACK_BACKUP_ADDON_PRODUCTS,
	...JETPACK_AI_PRODUCTS,
	...JETPACK_STATS_PRODUCTS,
	...JETPACK_MONITOR_PRODUCTS,
	...JETPACK_CREATOR_PRODUCTS,
	...JETPACK_SOCIAL_V1_PRODUCTS,
];

// Aliases are for products with quantity slugs in checkout (ex. jetpack-ai-yearly:-q-100)
// These are here to help with handling product quantity in situations where infrastructure is not aware of it
export const JETPACK_ALIAS_LIST = < const >[ ...JETPACK_AI_ALIASES, ...JETPACK_STATS_ALIASES ];

// Defines Jetpack products with multiple tiers
export const JETPACK_TIERED_PRODUCTS = < const >[
	...JETPACK_AI_PRODUCTS,
	...JETPACK_STATS_PRODUCTS,
];

// Defines Jetpack products with multiple product options (ex. Social Basic/Social Advanced)
export const JETPACK_MULTI_OPTION_PRODUCTS = < const >[ ...JETPACK_SOCIAL_PRODUCTS ];

export const JETPACK_PRODUCTS_BY_TERM = < const >[
	{
		yearly: PRODUCT_JETPACK_BACKUP_DAILY,
		monthly: PRODUCT_JETPACK_BACKUP_DAILY_MONTHLY,
	},
	{
		yearly: PRODUCT_JETPACK_BACKUP_REALTIME,
		monthly: PRODUCT_JETPACK_BACKUP_REALTIME_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_SEARCH_BI_YEARLY,
		yearly: PRODUCT_JETPACK_SEARCH,
		monthly: PRODUCT_JETPACK_SEARCH_MONTHLY,
	},
	{
		yearly: PRODUCT_WPCOM_SEARCH,
		monthly: PRODUCT_WPCOM_SEARCH_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_SCAN_BI_YEARLY,
		yearly: PRODUCT_JETPACK_SCAN,
		monthly: PRODUCT_JETPACK_SCAN_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_ANTI_SPAM_BI_YEARLY,
		yearly: PRODUCT_JETPACK_ANTI_SPAM,
		monthly: PRODUCT_JETPACK_ANTI_SPAM_MONTHLY,
	},
	{
		yearly: PRODUCT_JETPACK_CRM,
		monthly: PRODUCT_JETPACK_CRM_MONTHLY,
	},
	{
		yearly: PRODUCT_JETPACK_CRM_FREE,
		monthly: PRODUCT_JETPACK_CRM_FREE_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_BACKUP_T1_BI_YEARLY,
		yearly: PRODUCT_JETPACK_BACKUP_T1_YEARLY,
		monthly: PRODUCT_JETPACK_BACKUP_T1_MONTHLY,
	},
	{
		yearly: PRODUCT_JETPACK_BACKUP_T2_YEARLY,
		monthly: PRODUCT_JETPACK_BACKUP_T2_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_VIDEOPRESS_BI_YEARLY,
		yearly: PRODUCT_JETPACK_VIDEOPRESS,
		monthly: PRODUCT_JETPACK_VIDEOPRESS_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_BOOST_BI_YEARLY,
		yearly: PRODUCT_JETPACK_BOOST,
		monthly: PRODUCT_JETPACK_BOOST_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_SOCIAL_BASIC_BI_YEARLY,
		yearly: PRODUCT_JETPACK_SOCIAL_BASIC,
		monthly: PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_SOCIAL_ADVANCED_BI_YEARLY,
		yearly: PRODUCT_JETPACK_SOCIAL_ADVANCED,
		monthly: PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_STATS_BI_YEARLY,
		yearly: PRODUCT_JETPACK_STATS_YEARLY,
		monthly: PRODUCT_JETPACK_STATS_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_AI_BI_YEARLY,
		yearly: PRODUCT_JETPACK_AI_YEARLY,
		monthly: PRODUCT_JETPACK_AI_MONTHLY,
	},
	{
		yearly: PRODUCT_JETPACK_MONITOR_YEARLY,
		monthly: PRODUCT_JETPACK_MONITOR_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_CREATOR_BI_YEARLY,
		yearly: PRODUCT_JETPACK_CREATOR_YEARLY,
		monthly: PRODUCT_JETPACK_CREATOR_MONTHLY,
	},
	{
		biYearly: PRODUCT_JETPACK_SOCIAL_V1_BI_YEARLY,
		yearly: PRODUCT_JETPACK_SOCIAL_V1_YEARLY,
		monthly: PRODUCT_JETPACK_SOCIAL_V1_MONTHLY,
	},
];
export const JETPACK_PRODUCT_PRICE_MATRIX = < const >{
	[ PRODUCT_JETPACK_BACKUP_DAILY ]: {
		relatedProduct: PRODUCT_JETPACK_BACKUP_DAILY_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_BACKUP_REALTIME ]: {
		relatedProduct: PRODUCT_JETPACK_BACKUP_REALTIME_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_BACKUP_T1_YEARLY ]: {
		relatedProduct: PRODUCT_JETPACK_BACKUP_T1_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_BACKUP_T2_YEARLY ]: {
		relatedProduct: PRODUCT_JETPACK_BACKUP_T2_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_BOOST ]: {
		relatedProduct: PRODUCT_JETPACK_BOOST_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_SOCIAL_BASIC ]: {
		relatedProduct: PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_SOCIAL_V1_YEARLY ]: {
		relatedProduct: PRODUCT_JETPACK_SOCIAL_V1_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_SOCIAL_ADVANCED ]: {
		relatedProduct: PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_SEARCH ]: {
		relatedProduct: PRODUCT_JETPACK_SEARCH_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_SCAN ]: {
		relatedProduct: PRODUCT_JETPACK_SCAN_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_ANTI_SPAM ]: {
		relatedProduct: PRODUCT_JETPACK_ANTI_SPAM_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_VIDEOPRESS ]: {
		relatedProduct: PRODUCT_JETPACK_VIDEOPRESS_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_MONITOR_YEARLY ]: {
		relatedProduct: PRODUCT_JETPACK_MONITOR_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_STATS_YEARLY ]: {
		relatedProduct: PRODUCT_JETPACK_STATS_MONTHLY,
		ratio: 12,
	},
	[ PRODUCT_JETPACK_CREATOR_YEARLY ]: {
		relatedProduct: PRODUCT_JETPACK_CREATOR_MONTHLY,
		ratio: 12,
	},
};
// Key/value: Superseding product/Products superseded (yearly terms)
export const JETPACK_PRODUCT_UPGRADE_MAP: Record< string, string[] > = {
	[ PRODUCT_JETPACK_BACKUP_T2_YEARLY ]: [ PRODUCT_JETPACK_BACKUP_T1_YEARLY ],
	[ PRODUCT_JETPACK_BACKUP_REALTIME ]: [ PRODUCT_JETPACK_BACKUP_DAILY ],
};

// Plans
export const PLAN_JETPACK_FREE = 'jetpack_free';
export const PLAN_JETPACK_PERSONAL = 'jetpack_personal';
export const PLAN_JETPACK_PERSONAL_MONTHLY = 'jetpack_personal_monthly';
export const PLAN_JETPACK_PREMIUM = 'jetpack_premium';
export const PLAN_JETPACK_PREMIUM_MONTHLY = 'jetpack_premium_monthly';
export const PLAN_JETPACK_BUSINESS = 'jetpack_business';
export const PLAN_JETPACK_BUSINESS_MONTHLY = 'jetpack_business_monthly';
export const PLAN_JETPACK_SECURITY_T1_YEARLY = 'jetpack_security_t1_yearly';
export const PLAN_JETPACK_SECURITY_T1_MONTHLY = 'jetpack_security_t1_monthly';
export const PLAN_JETPACK_SECURITY_T1_BI_YEARLY = 'jetpack_security_t1_bi_yearly';
export const PLAN_JETPACK_SECURITY_T2_YEARLY = 'jetpack_security_t2_yearly';
export const PLAN_JETPACK_SECURITY_T2_MONTHLY = 'jetpack_security_t2_monthly';
export const PLAN_JETPACK_COMPLETE_BI_YEARLY = 'jetpack_complete_bi_yearly';
export const PLAN_JETPACK_COMPLETE = 'jetpack_complete';
export const PLAN_JETPACK_COMPLETE_MONTHLY = 'jetpack_complete_monthly';
export const PLAN_JETPACK_STARTER_YEARLY = 'jetpack_starter_yearly';
export const PLAN_JETPACK_STARTER_MONTHLY = 'jetpack_starter_monthly';
export const PLAN_JETPACK_GOLDEN_TOKEN = 'jetpack_golden_token_lifetime';

// Legacy Security Plans
export const PLAN_JETPACK_SECURITY_DAILY = 'jetpack_security_daily';
export const PLAN_JETPACK_SECURITY_DAILY_MONTHLY = 'jetpack_security_daily_monthly';
export const PLAN_JETPACK_SECURITY_REALTIME = 'jetpack_security_realtime';
export const PLAN_JETPACK_SECURITY_REALTIME_MONTHLY = 'jetpack_security_realtime_monthly';

// Legacy (before offer reset)
export const JETPACK_LEGACY_PLANS = < const >[
	PLAN_JETPACK_PERSONAL,
	PLAN_JETPACK_PERSONAL_MONTHLY,
	PLAN_JETPACK_BUSINESS,
	PLAN_JETPACK_BUSINESS_MONTHLY,
	PLAN_JETPACK_PREMIUM,
	PLAN_JETPACK_PREMIUM_MONTHLY,
];

export const JETPACK_MONTHLY_LEGACY_PLANS = < const >[
	PLAN_JETPACK_PERSONAL_MONTHLY,
	PLAN_JETPACK_BUSINESS_MONTHLY,
	PLAN_JETPACK_PREMIUM_MONTHLY,
];

export const JETPACK_YEARLY_LEGACY_PLANS = < const >[
	PLAN_JETPACK_PERSONAL,
	PLAN_JETPACK_BUSINESS,
	PLAN_JETPACK_PREMIUM,
];

export const JETPACK_LEGACY_PLANS_MAX_PLUGIN_VERSION = '8.9.1'; // Jetpack versions prior to this one are not fully compatible with new plans

// Security
export const JETPACK_SECURITY_PLANS = < const >[
	PLAN_JETPACK_SECURITY_DAILY,
	PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	PLAN_JETPACK_SECURITY_REALTIME,
	PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
	PLAN_JETPACK_SECURITY_T1_YEARLY,
	PLAN_JETPACK_SECURITY_T1_MONTHLY,
	PLAN_JETPACK_SECURITY_T1_BI_YEARLY,
	PLAN_JETPACK_SECURITY_T2_YEARLY,
	PLAN_JETPACK_SECURITY_T2_MONTHLY,
];
export const JETPACK_SECURITY_T1_PLANS = < const >[
	PLAN_JETPACK_SECURITY_T1_MONTHLY,
	PLAN_JETPACK_SECURITY_T1_YEARLY,
	PLAN_JETPACK_SECURITY_T1_BI_YEARLY,
];

export const JETPACK_SECURITY_T2_PLANS = < const >[
	PLAN_JETPACK_SECURITY_T2_MONTHLY,
	PLAN_JETPACK_SECURITY_T2_YEARLY,
];

// Complete
export const JETPACK_COMPLETE_PLANS = < const >[
	PLAN_JETPACK_COMPLETE_BI_YEARLY,
	PLAN_JETPACK_COMPLETE,
	PLAN_JETPACK_COMPLETE_MONTHLY,
];

// Starter
export const JETPACK_STARTER_PLANS = < const >[
	PLAN_JETPACK_STARTER_YEARLY,
	PLAN_JETPACK_STARTER_MONTHLY,
];

export const JETPACK_MONTHLY_PLANS = < const >[
	PLAN_JETPACK_PREMIUM_MONTHLY,
	PLAN_JETPACK_BUSINESS_MONTHLY,
	PLAN_JETPACK_PERSONAL_MONTHLY,
	PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
	PLAN_JETPACK_SECURITY_T1_MONTHLY,
	PLAN_JETPACK_SECURITY_T2_MONTHLY,
	PLAN_JETPACK_COMPLETE_MONTHLY,
];
export const JETPACK_RESET_PLANS = < const >[
	...JETPACK_STARTER_PLANS,
	...JETPACK_SECURITY_PLANS,
	...JETPACK_COMPLETE_PLANS,
	PLAN_JETPACK_GOLDEN_TOKEN,
];
export const JETPACK_RESET_PLANS_BY_TERM = < const >[
	{
		biYearly: PLAN_JETPACK_COMPLETE_BI_YEARLY,
		yearly: PLAN_JETPACK_COMPLETE,
		monthly: PLAN_JETPACK_COMPLETE_MONTHLY,
	},
	{
		yearly: PLAN_JETPACK_SECURITY_DAILY,
		monthly: PLAN_JETPACK_SECURITY_DAILY_MONTHLY,
	},
	{
		yearly: PLAN_JETPACK_SECURITY_REALTIME,
		monthly: PLAN_JETPACK_SECURITY_REALTIME_MONTHLY,
	},
	{
		biYearly: PLAN_JETPACK_SECURITY_T1_BI_YEARLY,
		yearly: PLAN_JETPACK_SECURITY_T1_YEARLY,
		monthly: PLAN_JETPACK_SECURITY_T1_MONTHLY,
	},
	{
		yearly: PLAN_JETPACK_SECURITY_T2_YEARLY,
		monthly: PLAN_JETPACK_SECURITY_T2_MONTHLY,
	},
	{
		yearly: PLAN_JETPACK_STARTER_YEARLY,
		monthly: PLAN_JETPACK_STARTER_MONTHLY,
	},
];
export const JETPACK_PLANS = < const >[
	PLAN_JETPACK_FREE,
	...JETPACK_LEGACY_PLANS,
	...JETPACK_RESET_PLANS,
];
export const JETPACK_PLANS_BY_TERM = < const >[
	{
		yearly: PLAN_JETPACK_BUSINESS,
		monthly: PLAN_JETPACK_BUSINESS_MONTHLY,
	},
	{
		yearly: PLAN_JETPACK_PERSONAL,
		monthly: PLAN_JETPACK_PERSONAL_MONTHLY,
	},
	{
		yearly: PLAN_JETPACK_PREMIUM,
		monthly: PLAN_JETPACK_PREMIUM_MONTHLY,
	},
	...JETPACK_RESET_PLANS_BY_TERM,
];
export const BEST_VALUE_PLANS = < const >[ PLAN_JETPACK_PREMIUM, PLAN_JETPACK_PREMIUM_MONTHLY ];
// Key/value: Superseding plan/Plans superseded (yearly terms)
export const JETPACK_PLAN_UPGRADE_MAP: Record< string, string[] > = {
	[ PLAN_JETPACK_SECURITY_T2_YEARLY ]: [
		PLAN_JETPACK_SECURITY_T1_YEARLY,
		PLAN_JETPACK_STARTER_YEARLY,
	],
	[ PLAN_JETPACK_SECURITY_T1_YEARLY ]: [ PLAN_JETPACK_STARTER_YEARLY ],
	[ PLAN_JETPACK_SECURITY_REALTIME ]: [ PLAN_JETPACK_SECURITY_DAILY ],
	[ PLAN_JETPACK_COMPLETE ]: [
		PLAN_JETPACK_SECURITY_REALTIME,
		PLAN_JETPACK_SECURITY_DAILY,
		PLAN_JETPACK_SECURITY_T2_YEARLY,
		PLAN_JETPACK_SECURITY_T1_YEARLY,
		PLAN_JETPACK_STARTER_YEARLY,
	],
};

export const JETPACK_STARTER_UPGRADE_MAP: Record< string, string > = {
	[ PLAN_JETPACK_STARTER_YEARLY ]: PLAN_JETPACK_SECURITY_T1_YEARLY,
	[ PLAN_JETPACK_STARTER_MONTHLY ]: PLAN_JETPACK_SECURITY_T1_MONTHLY,
};

// Categories
export const JETPACK_SECURITY_CATEGORY = 'jetpack_security_category';
export const JETPACK_PERFORMANCE_CATEGORY = 'jetpack_performance_category';
export const JETPACK_GROWTH_CATEGORY = 'jetpack_growth_category';
export const JETPACK_PRODUCT_CATEGORIES = < const >[
	JETPACK_SECURITY_CATEGORY,
	JETPACK_PERFORMANCE_CATEGORY,
	JETPACK_GROWTH_CATEGORY,
];

// URL
export const JETPACK_BACKUP_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/upgrade/backup/';
export const JETPACK_SEARCH_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/upgrade/search/';
export const JETPACK_STATS_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/stats/';
export const JETPACK_SCAN_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/upgrade/scan/';
export const JETPACK_ANTI_SPAM_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/upgrade/anti-spam/';
export const JETPACK_BOOST_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/boost/';
export const JETPACK_SOCIAL_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/social/';
export const JETPACK_VIDEOPRESS_PRODUCT_LANDING_PAGE_URL = 'https://jetpack.com/videopress/';
export const JETPACK_CRM_PRODUCT_LANDING_PAGE_URL = 'https://jetpackcrm.com/';
// If JETPACK_CLOUD_REDIRECT_CHECKOUT_TO_WPADMIN is true, checkout will redirect to the site's wp-admin,
// otherwise it will redirect to the JETPACK_REDIRECT_URL. Checkout references these constants in:
// client/my-sites/checkout/src/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
export const JETPACK_REDIRECT_CHECKOUT_TO_WPADMIN = true;
export const JETPACK_REDIRECT_URL =
	'https://jetpack.com/redirect/?source=jetpack-checkout-thankyou';

// Key/value maps related products to a given one
export const JETPACK_RELATED_PRODUCTS_MAP: Record< string, string[] > = {
	[ PRODUCT_JETPACK_SOCIAL_BASIC_BI_YEARLY ]: [
		PRODUCT_JETPACK_SOCIAL_ADVANCED_BI_YEARLY,
		PRODUCT_JETPACK_SOCIAL_BASIC_BI_YEARLY,
	],
	[ PRODUCT_JETPACK_SOCIAL_ADVANCED_BI_YEARLY ]: [
		PRODUCT_JETPACK_SOCIAL_ADVANCED_BI_YEARLY,
		PRODUCT_JETPACK_SOCIAL_BASIC_BI_YEARLY,
	],
	[ PRODUCT_JETPACK_SOCIAL_BASIC ]: [
		PRODUCT_JETPACK_SOCIAL_ADVANCED,
		PRODUCT_JETPACK_SOCIAL_BASIC,
	],
	[ PRODUCT_JETPACK_SOCIAL_ADVANCED ]: [
		PRODUCT_JETPACK_SOCIAL_ADVANCED,
		PRODUCT_JETPACK_SOCIAL_BASIC,
	],
	[ PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY ]: [
		PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY,
		PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY,
	],
	[ PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY ]: [
		PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY,
		PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY,
	],
};

// Tags, 'Recommended for'
export const JETPACK_TAG_FOR_WOOCOMMERCE_STORES = 'jetpack_tag_for_woocommerce_stores';
export const JETPACK_TAG_FOR_NEWS_ORGANISATIONS = 'jetpack_tag_for_news_organisations';
export const JETPACK_TAG_FOR_MEMBERSHIP_SITES = 'jetpack_tag_for_membership_sites';
export const JETPACK_TAG_FOR_ONLINE_FORUMS = 'jetpack_tag_for_online_forums';
export const JETPACK_TAG_FOR_BLOGS = 'jetpack_tag_for_blogs';
export const JETPACK_TAG_FOR_VIDEOGRAPHERS = 'jetpack_tag_for_videographers';
export const JETPACK_TAG_FOR_EDUCATORS = 'jetpack_tag_for_educators';
export const JETPACK_TAG_FOR_BLOGGERS = 'jetpack_tag_for_bloggers';
export const JETPACK_TAG_FOR_ALL_SITES = 'jetpack_tag_for_all_sites';
export const JETPACK_TAG_FOR_SMALL_SITES = 'jetpack_tag_for_small_sites';

// Maps products to 'Recommended for' tags
export const JETPACK_PRODUCT_RECCOMENDATION_MAP: Record< string, string[] > = {
	[ PRODUCT_JETPACK_BACKUP_DAILY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BACKUP_DAILY_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BACKUP_REALTIME ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BACKUP_REALTIME_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BACKUP_T1_YEARLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BACKUP_T1_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BACKUP_T2_YEARLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BACKUP_T2_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_VIDEOPRESS ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_VIDEOGRAPHERS,
		JETPACK_TAG_FOR_EDUCATORS,
		JETPACK_TAG_FOR_BLOGS,
	],
	[ PRODUCT_JETPACK_VIDEOPRESS_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_VIDEOGRAPHERS,
		JETPACK_TAG_FOR_EDUCATORS,
		JETPACK_TAG_FOR_BLOGS,
	],
	[ PRODUCT_JETPACK_ANTI_SPAM ]: [
		JETPACK_TAG_FOR_BLOGS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_ANTI_SPAM_MONTHLY ]: [
		JETPACK_TAG_FOR_BLOGS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_SCAN ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_SCAN_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_SCAN_REALTIME ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_SCAN_REALTIME_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_SEARCH ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_SEARCH_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
	],
	[ PRODUCT_JETPACK_BOOST ]: [ JETPACK_TAG_FOR_ALL_SITES ],
	[ PRODUCT_JETPACK_BOOST_MONTHLY ]: [ JETPACK_TAG_FOR_ALL_SITES ],
	[ PRODUCT_JETPACK_SOCIAL_BASIC ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_SOCIAL_BASIC_MONTHLY ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_SOCIAL_ADVANCED ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_SOCIAL_ADVANCED_MONTHLY ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_SOCIAL_V1_YEARLY ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_SOCIAL_V1_MONTHLY ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_SOCIAL_V1_BI_YEARLY ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_STATS_YEARLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
	],
	[ PRODUCT_JETPACK_STATS_MONTHLY ]: [
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
	],
	[ PRODUCT_JETPACK_AI_MONTHLY ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_AI_YEARLY ]: [
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_NEWS_ORGANISATIONS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
		JETPACK_TAG_FOR_ONLINE_FORUMS,
		JETPACK_TAG_FOR_WOOCOMMERCE_STORES,
	],
	[ PRODUCT_JETPACK_CREATOR_YEARLY ]: [
		JETPACK_TAG_FOR_EDUCATORS,
		JETPACK_TAG_FOR_BLOGGERS,
		JETPACK_TAG_FOR_VIDEOGRAPHERS,
		JETPACK_TAG_FOR_MEMBERSHIP_SITES,
	],
	// WooCommerce Extensions
	[ PRODUCT_WOOCOMMERCE_BOOKINGS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_SUBSCRIPTIONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PRODUCT_BUNDLES ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PRODUCT_ADD_ONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_MINMAX_QUANTITIES ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_AUTOMATEWOO ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_ADVANCED_NOTIFICATIONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_ALL_PRODUCTS_WOO_SUBSCRIPTIONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_AUTOMATEWOO_BIRTHDAYS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_AUTOMATEWOO_REFER_A_FRIEND ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_BACK_IN_STOCK_NOTIFICATIONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_BULK_STOCK_MANAGEMENT ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_CHECKOUT_FIELD_EDITOR ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_COMPOSITE_PRODUCTS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_CONDITIONAL_SHIPPING_PAYMENTS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_EU_VAT_NUMBER ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_FLAT_RATE_BOX_SHIPPING ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_GIFT_CARDS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_GIFTING_WC_SUBSCRIPTIONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PER_PRODUCT_SHIPPING ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PRODUCT_CSV_IMPORT_SUITE ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PRODUCT_RECOMMENDATIONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PRODUCT_VENDORS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_RETURNS_WARRANTY_REQUESTS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_SUBSCRIPTION_DOWNLOADS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_SHIPMENT_TRACKING ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_SHIPPING_MULTIPLE_ADDRESSES ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_STOREFRONT_EXTENSIONS_BUNDLE ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_TABLE_RATE_SHIPPING ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_ADDITIONAL_IMAGE_VARIATIONS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_BOOKINGS_AVAILABILITY ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_BOX_OFFICE ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_BRANDS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_COUPON_CAMPAIGNS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_DEPOSITS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_DISTANCE_RATE_SHIPPING ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_ONE_PAGE_CHECKOUT ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_ORDER_BARCODES ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_POINTS_AND_REWARDS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PRE_ORDERS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PURCHASE_ORDER_GATEWAY ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_SHIPPING ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_ACCOMMODATIONS_BOOKINGS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_TAX ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_WOOPAYMENTS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
	[ PRODUCT_WOOCOMMERCE_PRODUCT_FILTERS ]: [ JETPACK_TAG_FOR_WOOCOMMERCE_STORES ],
};
