export const TERM_MONTHLY = 'TERM_MONTHLY';
export const TERM_ANNUALLY = 'TERM_ANNUALLY';
export const TERM_BIENNIALLY = 'TERM_BIENNIALLY';
export const TERM_TRIENNIALLY = 'TERM_TRIENNIALLY';
export const TERM_QUADRENNIALLY = 'TERM_QUADRENNIALLY';
export const TERM_QUINQUENNIALLY = 'TERM_QUINQUENNIALLY';
export const TERM_SEXENNIALLY = 'TERM_SEXENNIALLY';
export const TERM_SEPTENNIALLY = 'TERM_SEPTENNIALLY';
export const TERM_OCTENNIALLY = 'TERM_OCTENNIALLY';
export const TERM_NOVENNIALLY = 'TERM_NOVENNIALLY';
export const TERM_DECENNIALLY = 'TERM_DECENNIALLY';

export const TERMS_LIST = <const>[
	TERM_MONTHLY,
	TERM_ANNUALLY,
	TERM_BIENNIALLY,
	TERM_TRIENNIALLY,
	TERM_QUADRENNIALLY,
	TERM_QUINQUENNIALLY,
	TERM_SEXENNIALLY,
	TERM_SEPTENNIALLY,
	TERM_OCTENNIALLY,
	TERM_NOVENNIALLY,
	TERM_DECENNIALLY,
];

export const PLAN_MONTHLY_PERIOD = 31;
export const PLAN_ANNUAL_PERIOD = 365;
export const PLAN_BIENNIAL_PERIOD = 730;
export const PLAN_TRIENNIAL_PERIOD = 1095;
export const PLAN_QUADRENNIAL_PERIOD = 1460;
export const PLAN_QUINQUENNIAL_PERIOD = 1825;
export const PLAN_SEXENNIAL_PERIOD = 2190;
export const PLAN_SEPTENNIAL_PERIOD = 2555;
export const PLAN_OCTENNIAL_PERIOD = 2920;
export const PLAN_NOVENNIAL_PERIOD = 3285;
export const PLAN_DECENNIAL_PERIOD = 3650;

export const PERIOD_LIST = <const>[
	PLAN_MONTHLY_PERIOD,
	PLAN_ANNUAL_PERIOD,
	PLAN_BIENNIAL_PERIOD,
	PLAN_TRIENNIAL_PERIOD,
	PLAN_QUADRENNIAL_PERIOD,
	PLAN_QUINQUENNIAL_PERIOD,
	PLAN_SEXENNIAL_PERIOD,
	PLAN_SEPTENNIAL_PERIOD,
	PLAN_OCTENNIAL_PERIOD,
	PLAN_NOVENNIAL_PERIOD,
	PLAN_DECENNIAL_PERIOD,
];
