export const TYPE_FREE = 'TYPE_FREE';
export const TYPE_BLOGGER = 'TYPE_BLOGGER';
export const TYPE_PERSONAL = 'TYPE_PERSONAL';
export const TYPE_PREMIUM = 'TYPE_PREMIUM';
export const TYPE_BUSINESS = 'TYPE_BUSINESS';
export const TYPE_100_YEAR = 'TYPE_100_YEAR';
export const TYPE_ECOMMERCE = 'TYPE_ECOMMERCE';
export const TYPE_ENTERPRISE_GRID_WPCOM = 'TYPE_ENTERPRISE_GRID_WPCOM';
export const TYPE_WOOEXPRESS_SMALL = 'TYPE_WOOEXPRESS_SMALL';
export const TYPE_WOOEXPRESS_MEDIUM = 'TYPE_WOOEXPRESS_MEDIUM';
export const TYPE_WOO_EXPRESS_PLUS = 'TYPE_WOO_EXPRESS_PLUS';
export const TYPE_SECURITY_DAILY = 'TYPE_SECURITY_DAILY';
export const TYPE_SECURITY_REALTIME = 'TYPE_SECURITY_REALTIME';
export const TYPE_SECURITY_T1 = 'TYPE_SECURITY_T1';
export const TYPE_SECURITY_T2 = 'TYPE_SECURITY_T2';
export const TYPE_JETPACK_STARTER = 'TYPE_JETPACK_STARTER';
export const TYPE_JETPACK_GROWTH = 'TYPE_GROWTH';
export const TYPE_ALL = 'TYPE_ALL';
export const TYPE_P2_PLUS = 'TYPE_P2_PLUS';
export const TYPE_FLEXIBLE = 'TYPE_FLEXIBLE';
export const TYPE_PRO = 'TYPE_PRO';
export const TYPE_STARTER = 'TYPE_STARTER';
export const TYPE_GOLDEN_TOKEN = 'TYPE_GOLDEN_TOKEN';

export const TYPES_LIST = < const >[
	TYPE_FREE,
	TYPE_BLOGGER,
	TYPE_PERSONAL,
	TYPE_PREMIUM,
	TYPE_BUSINESS,
	TYPE_100_YEAR,
	TYPE_ECOMMERCE,
	TYPE_ENTERPRISE_GRID_WPCOM,
	TYPE_WOOEXPRESS_SMALL,
	TYPE_WOOEXPRESS_MEDIUM,
	TYPE_WOO_EXPRESS_PLUS,
	TYPE_SECURITY_DAILY,
	TYPE_SECURITY_REALTIME,
	TYPE_ALL,
	TYPE_P2_PLUS,
	TYPE_FLEXIBLE,
	TYPE_PRO,
	TYPE_STARTER,
	TYPE_GOLDEN_TOKEN,
	TYPE_JETPACK_GROWTH,
	TYPE_JETPACK_STARTER,
	TYPE_SECURITY_T1,
	TYPE_SECURITY_T2,
];
