module.exports.action = {
	ACTION_RECEIVE_READER_LIST_FEEDS: 'ACTION_RECEIVE_READER_LIST_FEEDS',
	ACTION_RECEIVE_READER_LIST_FEEDS_ERROR: 'ACTION_RECEIVE_READER_LIST_FEEDS_ERROR',
	ACTION_FETCH_READER_LIST_FEEDS: 'ACTION_FETCH_READER_LIST_FEEDS',
	ACTION_FETCH_READER_LIST_FEEDS_COMPLETE: 'ACTION_FETCH_READER_LIST_FEEDS_COMPLETE'
};
