/** @format */

// List from https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12

export default {
	Arts: [ 'Books', 'Design', 'Fashion & Beauty', 'Food', 'Performing Arts', 'Visual Arts' ],
	Business: [ 'Careers', 'Entrepreneurship', 'Investing', 'Management', 'Marketing', 'Non-profit' ],
	Comedy: [ 'Comedy Interviews', 'Improv', 'Standup' ],
	Education: [ 'Courses', 'How to', 'Language Learning', 'Self Improvement' ],
	Fiction: [ 'Comedy Fiction', 'Drama', 'Science Fiction' ],
	Government: [],
	History: [],
	'Health & Fitness': [
		'Alternative Health',
		'Fitness',
		'Medicine',
		'Mental Health',
		'Nutrition',
		'Sexuality',
	],
	'Kids & Family': [ 'Education for Kids', 'Parenting', 'Pets & Animals', 'Stories for Kids' ],
	Leisure: [
		'Animation & Manga',
		'Automotive',
		'Aviation',
		'Crafts',
		'Games',
		'Hobbies',
		'Home & Garden',
		'Video Games',
	],
	Music: [ 'Music Commentary', 'Music History', 'Music Interviews' ],
	News: [
		'Business News',
		'Daily News',
		'Entertainment News',
		'News Commentary',
		'Politics',
		'Sports News',
		'Tech News',
	],
	'Religion & Spirituality': [
		'Buddhism',
		'Christianity',
		'Hinduism',
		'Islam',
		'Judaism',
		'Religion',
		'Spirituality',
	],
	Science: [
		'Astronomy',
		'Chemistry',
		'Earth Sciences',
		'Life Sciences',
		'Mathematics',
		'Natural Sciences',
		'Nature',
		'Physics',
		'Social Sciences',
	],
	'Society & Culture': [
		'Documentary',
		'Personal Journals',
		'Philosophy',
		'Places & Travel',
		'Relationships',
	],
	Sports: [
		'Baseball',
		'Basketball',
		'Cricket',
		'Fantasy Sports',
		'Football',
		'Golf',
		'Hockey',
		'Rugby',
		'Running',
		'Swimming',
		'Tennis',
		'Volleyball',
		'Wilderness',
		'Wrestling',
	],
	Technology: [],
	'TV & Film': [ 'After Shows', 'Film History', 'Film Interviews', 'Film Reviews', 'TV Reviews' ],
};
