<?php
/**
 * Plugin Name: A8c Big Sky Patterns Metadata Sidebar
 * Description: Add pattern metadata configuration to the WordPress post editor sidebar.
 * Version: 1.0.0
 * Author: Automattic Inc.
 * License: GPL v2 or later
 * Text Domain: a8c-big-sky-patterns-metadata-sidebar
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Pattern Metadata Sidebar Plugin Class
 *
 * @package A8c_Big_Sky_Patterns_Metadata
 */
class A8c_Big_Sky_Patterns_Metadata_Sidebar {

	/**
	 * Instance of this class.
	 *
	 * @var A8c_Big_Sky_Patterns_Metadata_Sidebar
	 */
	private static $instance = null;

	/**
	 * Get the singleton instance of this class.
	 *
	 * @return A8c_Big_Sky_Patterns_Metadata_Sidebar
	 */
	public static function get_instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Private constructor to prevent direct instantiation.
	 */
	private function __construct() {
		// Safety check for WordPress.com deployment

		if ( ! has_blog_sticker( 'block-patterns-source-site' ) ) {
			return;
		}

		add_action( 'init', array( $this, 'init' ) );
		add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_editor_assets' ) );
	}

	/**
	 * Prevent cloning of the instance.
	 */
	private function __clone() {
		// Prevent cloning.
	}

	/**
	 * Prevent unserializing of the instance.
	 */
	private function __wakeup() {
		// Prevent unserializing.
	}

	/**
	 * Initialize the plugin.
	 */
	public function init() {

		// Register post meta for pattern metadata
		register_post_meta(
			'post',
			'_a8c_big_sky_patterns_metadata',
			array(
				'type'          => 'string',
				'description'   => 'Pattern metadata for intelligent pattern selection',
				'single'        => true,
				'show_in_rest'  => true,
				'auth_callback' => function () {
					return current_user_can( 'edit_posts' );
				},
			)
		);
	}

	/**
	 * Enqueue editor assets.
	 */
	public function enqueue_editor_assets() {
		$current_screen = get_current_screen();

		if ( ! $current_screen ) {
			return;
		}

		// Only load on post editor
		if ( 'post' !== $current_screen->base || 'post' !== $current_screen->post_type ) {
			return;
		}

		// Load asset file generated by wp-scripts build process
		$asset_file = plugin_dir_path( __FILE__ ) . 'build/index.asset.php';
		$asset      = file_exists( $asset_file )
			? include $asset_file
			: array(
				'dependencies' => array( 'wp-plugins', 'wp-edit-post', 'wp-element', 'wp-components', 'wp-data' ),
				'version'      => '1.0.0',
			);

		wp_enqueue_script(
			'a8c-big-sky-patterns-metadata-sidebar',
			plugin_dir_url( __FILE__ ) . 'build/index.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		wp_enqueue_style(
			'a8c-big-sky-patterns-metadata-sidebar',
			plugin_dir_url( __FILE__ ) . 'build/style-index.css',
			array(),
			$asset['version']
		);
	}
}

A8c_Big_Sky_Patterns_Metadata_Sidebar::get_instance();
