import { isPlan } from '@automattic/calypso-products';
import { Gridicon } from '@automattic/components';
import { useTranslate } from 'i18n-calypso';
import moment from 'moment';

interface AtomicRevertChangesProps {
	atomicTransfer: {
		created_at: string;
	};
	purchase: any;
	isRemovePlan?: boolean;
	isDowngradePlan?: boolean;
}

const AtomicRevertChanges: React.FC< AtomicRevertChangesProps > = ( {
	atomicTransfer,
	purchase,
	isRemovePlan = false,
	isDowngradePlan = false,
} ) => {
	const translate = useTranslate();

	// If no atomic transfer data, don't render anything
	if ( ! atomicTransfer?.created_at ) {
		return null;
	}

	const atomicTransferDate = moment( atomicTransfer.created_at ).format( 'LL' );
	const isPlanPurchase = isPlan( purchase );

	// Generate the list of changes based on the purchase type and action
	const getChangesList = () => {
		const changes = [];

		// Site will become private
		changes.push(
			translate( 'Your site will be set to private and will no longer be publicly accessible' )
		);

		// Site will revert to original state
		changes.push(
			translate(
				'Your site will revert to its original settings and theme from before the first plugin or custom theme was installed'
			)
		);

		// Plugins and themes will be removed
		if ( isPlanPurchase && ! isRemovePlan && ! isDowngradePlan ) {
			changes.push(
				translate(
					'Any themes and plugins you have installed will be removed on %(expiryDate)s, along with their data',
					{
						args: {
							expiryDate: moment( purchase.expiryDate ).format( 'LL' ),
						},
					}
				)
			);
		} else {
			changes.push(
				translate(
					'Any themes and plugins you have installed will be removed, along with their data'
				)
			);
		}

		// Content generated by plugins/themes will be lost
		changes.push( translate( 'Content generated by plugins or custom themes will be lost' ) );

		// Posts, pages, and media will be preserved
		changes.push( translate( 'Your posts, pages, and media will be preserved' ) );

		return changes;
	};

	const changes = getChangesList();

	return (
		<div className="cancel-purchase__atomic-revert-changes">
			<p>{ translate( 'We will also make these changes to your site:' ) }</p>
			<ul className="cancel-purchase__atomic-revert-changes-list">
				{ changes.map( ( change, index ) => (
					<li key={ index }>
						<Gridicon
							className="cancel-purchase__atomic-revert-changes--item-notice"
							size={ 18 }
							icon="notice-outline"
						/>
						<span>{ change }</span>
					</li>
				) ) }
			</ul>
			<p className="cancel-purchase__atomic-revert-changes-note">
				{ translate(
					'On %(atomicTransferDate)s, we automatically moved your site to a platform that supports plugins, custom themes, and hosting features. Cancelling will move your site back to its original platform.',
					{
						args: { atomicTransferDate },
					}
				) }
			</p>
		</div>
	);
};

export default AtomicRevertChanges;
