// Reference: https://www.w3.org/TR/wai-aria-1.0/states_and_properties#state_prop_def
export const ARIA_STATES = [
	'busy',
	'checked',
	'disabled',
	'expanded',
	'grabbed',
	'hidden',
	'invalid',
	'pressed',
	'selected',
] as const;
export const ARIA_PROPERTIES = [
	'activedescendant',
	'atomic',
	'autocomplete',
	'controls',
	'describedby',
	'dropeffect',
	'flowto',
	'haspopup',
	'label',
	'labelledby',
	'level',
	'live',
	'multiline',
	'multiselectable',
	'orientation',
	'owns',
	'posinset',
	'readonly',
	'relevant',
	'required',
	'setsize',
	'sort',
	'valuemax',
	'valuemin',
	'valuenow',
	'valuetext',
] as const;
