export const A4A_OVERVIEW_LINK = '/overview';
export const A4A_SITES_LINK = '/sites';
export const A4A_SITES_LINK_NEEDS_ATTENTION = '/sites?issue_types=all_issues';
export const A4A_SITES_LINK_FAVORITE = '/sites/favorite';
export const A4A_PLUGINS_LINK = '/plugins';
export const A4A_MARKETPLACE_LINK = '/marketplace';
export const A4A_MARKETPLACE_PRODUCTS_LINK = `${ A4A_MARKETPLACE_LINK }/products`;
export const A4A_MARKETPLACE_HOSTING_LINK = `${ A4A_MARKETPLACE_LINK }/hosting`;
export const A4A_MARKETPLACE_ASSIGN_LICENSE_LINK = `${ A4A_MARKETPLACE_LINK }/assign-license`;
export const A4A_PURCHASES_LINK = '/purchases';
export const A4A_LICENSES_LINK = `${ A4A_PURCHASES_LINK }/licenses`;
export const A4A_BILLING_LINK = `${ A4A_PURCHASES_LINK }/billing`;
export const A4A_INVOICES_LINK = `${ A4A_PURCHASES_LINK }/invoices`;
export const A4A_PAYMENT_METHODS_LINK = `${ A4A_PURCHASES_LINK }/payment-methods`;
export const A4A_PAYMENT_METHODS_ADD_LINK = `${ A4A_PURCHASES_LINK }/payment-methods/add`;
export const A4A_DOWNLOAD_PRODUCTS_LINK = `${ A4A_PURCHASES_LINK }/download-products`;
