export { deduceImageWidthAndHeight } from 'calypso/lib/post-normalizer/utils/deduce-image-width-and-height';
export { domForHtml } from 'calypso/lib/post-normalizer/utils/dom-for-html';
export { iframeIsAllowed } from 'calypso/lib/post-normalizer/utils/iframe-is-allowed';
export { imageSizeFromAttachments } from 'calypso/lib/post-normalizer/utils/image-size-from-attachments';
export { isCandidateForCanonicalImage } from 'calypso/lib/post-normalizer/utils/is-candidate-for-canonical-image';
export { isFeaturedImageInContent } from 'calypso/lib/post-normalizer/utils/is-featured-image-in-content';
export { isPhotonHost } from 'calypso/lib/post-normalizer/utils/is-photon-host';
export { isUrlLikelyAnImage } from 'calypso/lib/post-normalizer/utils/is-url-likely-an-image';
export { makeImageURLSafe } from 'calypso/lib/post-normalizer/utils/make-image-url-safe';
export { maxWidthPhotonishURL } from 'calypso/lib/post-normalizer/utils/max-width-photonish-url';
export { safeLink, safeLinkRe } from 'calypso/lib/post-normalizer/utils/safe-link';
export { thumbIsLikelyImage } from 'calypso/lib/post-normalizer/utils/thumb-is-likely-image';
