export const LASAGNA_SOCKET_CONNECT = 'LASAGNA_SOCKET_CONNECT';
export const LASAGNA_SOCKET_CONNECT_ERROR = 'LASAGNA_SOCKET_CONNECT_ERROR';
export const LASAGNA_SOCKET_DISCONNECT = 'LASAGNA_SOCKET_DISCONNECT';
export const LASAGNA_SOCKET_CLOSED = 'LASAGNA_SOCKET_CLOSED';
export const LASAGNA_SOCKET_CONNECTED = 'LASAGNA_SOCKET_CONNECTED';
export const LASAGNA_SOCKET_DISCONNECTED = 'LASAGNA_SOCKET_DISCONNECTED';

export const LASAGNA_CHANNEL_JOINED = 'LASAGNA_CHANNEL_JOINED';
export const LASAGNA_CHANNEL_JOIN_ERROR = 'LASAGNA_CHANNEL_JOIN_ERROR';
export const LASAGNA_CHANNEL_LEFT = 'LASAGNA_CHANNEL_LEFT';
