// @ts-nocheck - TODO: Fix TypeScript issues
import { getNewSiteParams } from 'calypso/lib/signup/step-actions';

describe( 'get-new-site-params', () => {
	test( 'should set the correct payload when flowToCheck is provided', () => {
		const { options } = getNewSiteParams( {
			dependencies: {},
			flowToCheck: 'myFlow',
		} );

		expect( options ).toHaveProperty( 'site_creation_flow', 'myFlow' );
		expect( options ).toHaveProperty( 'use_theme_annotation', false );
		expect( options ).toHaveProperty( 'default_annotation_as_primary_fallback', true );
		expect( options ).toHaveProperty( 'designType', undefined );
		expect( options ).toHaveProperty( 'wpcom_public_coming_soon', 1 );

		expect( options ).not.toHaveProperty( 'site_segment' );
	} );

	describe( 'For preselected url', () => {
		test( 'and a free domain it should generate the correct payload', () => {
			const result = getNewSiteParams( {
				dependencies: {},
				siteUrl: 'testing_free_domain',
			} );

			expect( result ).toHaveProperty( 'blog_name', 'testing_free_domain' );
			expect( result ).toHaveProperty( 'find_available_url', false );
		} );

		test( 'and a paid domain it should generate the correct payload', () => {
			const result = getNewSiteParams( {
				dependencies: {},
				isPurchasingDomainItem: true,
				siteUrl: 'test.com',
			} );

			expect( result ).toHaveProperty( 'blog_name', 'test.com' );
			expect( result ).toHaveProperty( 'find_available_url', true );
		} );
	} );

	describe( 'For no selected url', () => {
		test( 'and forceAutoGeneratedBlogName dependency it should send an empty blog_name', () => {
			const result = getNewSiteParams( {
				dependencies: {},
				state: {
					signup: {
						dependencyStore: {
							forceAutoGeneratedBlogName: true,
						},
					},
				},
			} );

			expect( result ).toHaveProperty( 'blog_name', '' );
			expect( result ).toHaveProperty( 'find_available_url', true );
		} );

		test.each( [ 'onboarding', 'onboarding-affiliate', 'do-it-for-me', 'myFlow' ] )(
			'and the %s flow it should send an empty blog_name when there is no site title',
			( flowToCheck ) => {
				const result = getNewSiteParams( {
					dependencies: {},
					flowToCheck,
					state: {},
				} );

				expect( result ).toHaveProperty( 'blog_name', '' );
				expect( result ).toHaveProperty( 'find_available_url', true );
			}
		);

		test( 'and a site title it should use the site title', () => {
			const result = getNewSiteParams( {
				dependencies: {},
				flowToCheck: 'onboarding',
				state: {
					signup: {
						dependencyStore: {
							siteTitle: 'Testing Inc.',
						},
					},
				},
			} );

			expect( result ).toHaveProperty( 'blog_name', 'Testing Inc.' );
			expect( result ).toHaveProperty( 'find_available_url', true );
		} );
	} );
} );
