import { __ } from '@wordpress/i18n';
export default {
	'/home/': __( 'home' ),
	'/stats/': __( 'statistics' ),
	'/add-ons/': __( 'add-ons' ),
	'/mailboxes': __( 'mail' ),
	'/comments/': __( 'comments' ),
	'/checkout/': __( 'checkout' ),
	'/backup/': __( 'backup' ),
	'/themes/': __( 'themes' ),
	'/plugins/manage': __( 'manage plugins' ),
	'/plugins': __( 'plugins' ),
	'/plans/': __( 'upgrade plan' ),
	'/email/': __( 'manage emails' ),
	'/domains/manage': __( 'manage domain' ),
	'/media/': __( 'media' ),
	'/posts/drafts': __( 'drafted post' ),
	'/posts/scheduled': __( 'scheduled post' ),
	'/posts/trashed': __( 'trash post' ),
	'/posts/': __( 'posts' ),
	'/posts': __( 'posts' ),
	'/pages/drafts': __( 'drafted pages' ),
	'/pages/scheduled': __( 'scheduled pages' ),
	'/pages/trashed': __( 'trash pages' ),
	'/pages/': __( 'pages' ),
	'/pages': __( 'pages' ),
	'/purchases/subscriptions/': __( 'subscription purchases' ),
	'/purchases/payment-methods/': __( 'payment methods' ),
	'/purchases/billing-history/': __( 'billing history' ),
	'/activity-log/': __( 'activity' ),
	'/woocommerce': __( 'woocommerce' ),
	'/wp-admin/admin.php?page=wc': __( 'woocommerce' ),
	'/people/team': __( 'site users' ),
	'/people/new': __( 'invite user' ),
	'/subscribers': __( 'subscribers' ),
	'/me/security': __( 'security' ),
	'/me/purchases': __( 'purchases' ),
	'/me/privacy': __( 'privacy' ),
	'/me/notifications': __( 'notification settings' ),
	'/me/account': __( 'account settings' ),
	'/me/site-blocks': __( 'blocked sites' ),
	'/me/get-apps': __( 'wordpress apps' ),
	'/me': __( 'my profile' ),
	'/settings/general/': __( 'general settings' ),
	'/settings/writing/': __( 'writing settings' ),
	'/settings/reading/': __( 'reading settings' ),
	'/settings/newsletter/': __( 'newsletter settings' ),
	'/settings/performance/': __( 'performance settings' ),
	'/settings/taxonomies/category/': __( 'site categories' ),
	'/settings/taxonomies/post_tag/': __( 'post tag' ),
	'/settings/podcasting/': __( 'podcasting' ),
	'/hosting-config/': __( 'hosting configuration' ),
	'/wp-admin/options-media.php': __( 'media settings' ),
	'/wp-admin/edit.php?post_type=jetpack-testimonial': __( 'testimonials' ),
	'/wp-admin/edit.php?post_type=page': __( 'pages' ),
	'/wp-admin/edit.php?post_type=feedback': __( 'feedback form' ),
	'/wp-admin/edit.php': __( 'posts' ),
	'/wp-admin/post-new.php?post_type=jetpack-testimonial': __( 'new testimonial' ),
	'/wp-admin/post-new.php?post_type=page': __( 'new page' ),
	'/wp-admin/post-new.php': __( 'new post' ),
	'/wp-admin/admin.php?page=akismet-key-config': __( 'site spam' ),
	'/wp-admin/admin.php?page=jetpack-search': __( 'jetpack search' ),
	'/wp-admin/admin.php?page=polls': __( 'crowdsignal' ),
	'/wp-admin/admin.php?page=ratings': __( 'ratings' ),
	'/wp-admin/options-general.php?page=debug-bar-extender': __( 'debug bar extender' ),
	'/wp-admin/index.php?page=my-blogs': __( 'my sites' ),
	'/read/conversations': __( 'conversations' ),
	'/read/notifications': __( 'notifications' ),
	'/read/subscriptions': __( 'manage subscriptions' ),
	'/read/list': __( 'reader list' ),
	'/read/search': __( 'search' ),
	'/read': __( 'reader' ),
	'/discover': __( 'discover blogs' ),
	'/tags': __( 'tags' ),
	'/sites': __( 'manage sites' ),
	'/marketing/tools/': __( 'marketing tools' ),
	'/marketing/traffic/': __( 'traffic' ),
	'/marketing/connections/': __( 'connections' ),
	'/marketing/sharing-buttons/': __( 'social share' ),
	'/marketing/business-tools/': __( 'business tools' ),
	'/earn/': __( 'monetize' ),
	'/advertising/': __( 'advertising' ),
	'/import/': __( 'import' ),
	'/export/': __( 'export' ),
};
