/**
 * Module vars
 */
export const READER_CONTENT_WIDTH = 800,
	PHOTO_ONLY_MIN_WIDTH = 440,
	PHOTO_ONLY_MAX_CHARACTER_COUNT = 85,
	GALLERY_MIN_IMAGES = 4,
	GALLERY_MIN_IMAGE_WIDTH = 300,
	MIN_IMAGE_WIDTH = 144,
	MIN_IMAGE_HEIGHT = 72;
