/**
 * Module vars
 */
export const READER_CONTENT_WIDTH = 600;
export const READER_FEATURED_MAX_IMAGE_HEIGHT = 300;
export const READER_COMPACT_POST_FEATURED_MAX_IMAGE_WIDTH = 200;
export const READER_COMPACT_POST_FEATURED_MAX_IMAGE_HEIGHT = 140;
export const READER_RELATED_IMAGE_WIDTH = 348;
export const PHOTO_ONLY_MIN_WIDTH = 440;
export const PHOTO_ONLY_MAX_CHARACTER_COUNT = 85;
export const GALLERY_MIN_IMAGES = 5;
export const GALLERY_MAX_IMAGES = 10;
export const GALLERY_MIN_IMAGE_WIDTH = 300;
export const MIN_IMAGE_WIDTH = 144;
export const MIN_IMAGE_HEIGHT = 72;
