import { CuratedBlogsList } from './index';

export const creativeArtsBlogs: CuratedBlogsList = {
	music: [
		{
			feed_ID: 84452094,
			site_ID: 148354167,
			site_URL: 'https://www.rollingstone.com/',
			site_name: 'Rolling Stone',
			feed_URL: 'http://www.rollingstone.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 74978,
			site_ID: 2865384,
			site_URL: 'higherplainmusic.com',
			site_name: 'Higher Plain Music',
			feed_URL: 'http://higherplainmusic.com',
			has_icon: true,
		},
		{
			feed_ID: 26828508,
			site_ID: 80366652,
			site_URL: 'https://musicjunkiepress.com',
			site_name: 'Music Junkie Press',
			feed_URL: 'http://musicjunkiepress.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 45553450,
			site_ID: 108354920,
			site_URL: '2loud2oldmusic.com',
			site_name: '2 Loud 2 Old Music',
			feed_URL: 'http://2loud2oldmusic.com',
			has_icon: true,
		},
		{
			feed_ID: 1105937,
			site_ID: 30124242,
			site_URL: 'http://avantmusicnews.com',
			site_name: 'Avant Music News',
			feed_URL: 'http://avantmusicnews.com',
			has_icon: true,
		},
		{
			feed_ID: 56921079,
			site_ID: 105816418,
			site_URL: 'https://musicaficionado.blog',
			site_name: 'Music Aficionado',
			feed_URL: 'http://musicaficionado.blog',
			has_icon: true,
		},
		{
			feed_ID: 47613982,
			site_ID: 74469258,
			site_URL: 'https://musicinjection.com.au',
			site_name: 'Music Injection',
			feed_URL: 'http://musicinjection.com.au',
			has_icon: true,
		},
		{
			feed_ID: 270115,
			site_ID: 4737767,
			site_URL: 'http://stantonssheetmusic.wordpress.com',
			site_name: "Stanton's Sheet Music",
			feed_URL: 'http://stantonssheetmusic.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 54714900,
			site_ID: 99349859,
			site_URL: 'indiepulsemusic.com',
			site_name: 'IndiePulse Music Magazine',
			feed_URL: 'http://indiepulsemusic.com',
			has_icon: true,
		},
		{
			feed_ID: 19238823,
			site_ID: 65314297,
			site_URL: 'http://darrensmusicblog.com',
			site_name: "Darren's music blog",
			feed_URL: 'http://darrensmusicblog.com',
			has_icon: true,
		},
		{
			feed_ID: 134962190,
			site_ID: 5186906,
			site_URL: 'http://jazzimproviser.com',
			site_name: 'Modern Music Theory Improvisation and Application',
			feed_URL: 'http://jazzimproviser.com',
			has_icon: true,
		},
		{
			feed_ID: 50314996,
			site_ID: 53246333,
			site_URL: 'http://newleasemusic.com',
			site_name: 'New Lease Music',
			feed_URL: 'http://newleasemusic.com',
			has_icon: true,
		},
		{
			feed_ID: 177216085,
			site_ID: 21987375,
			site_URL: 'http://music-defined.com',
			site_name: 'Music. Defined.',
			feed_URL: 'http://music-defined.com',
			has_icon: true,
		},
	],
	movies: [
		{
			feed_ID: 402803,
			site_ID: 23972029,
			site_URL: 'http://dejareviewer.com',
			site_name: 'Deja Reviewer',
			feed_URL: 'http://dejareviewer.com',
			has_icon: true,
		},
		{
			feed_ID: 276621,
			site_ID: 16188534,
			site_URL: 'moviesfilmsandflix.com',
			site_name: 'Movies, Films & Flix',
			feed_URL: 'http://moviesfilmsandflix.com',
			has_icon: true,
		},
		{
			feed_ID: 6897300,
			site_ID: 31913547,
			site_URL: 'http://keithandthemovies.com',
			site_name: 'Keith & the Movies',
			feed_URL: 'http://keithandthemovies.com',
			has_icon: true,
		},
		{
			feed_ID: 164758111,
			site_ID: 6358508,
			site_URL: 'http://letsgotothemovies.com',
			site_name: "Let's Go To The Movies",
			feed_URL: 'http://letsgotothemovies.com',
			has_icon: true,
		},
		{
			feed_ID: 35855382,
			site_ID: 46598344,
			site_URL: 'http://moviesofthesoul.com',
			site_name: 'Movies of the Soul',
			feed_URL: 'http://moviesofthesoul.com',
			has_icon: true,
		},
		{
			feed_ID: 26665509,
			site_ID: 80186886,
			site_URL: 'http://festivalreviews.org',
			site_name: 'Festival Reviews',
			feed_URL: 'http://festivalreviews.org',
			has_icon: true,
		},
		{
			feed_ID: 170581660,
			site_ID: 29512260,
			site_URL: 'https://moviesandmania.com',
			site_name: 'MOVIES & MANIA',
			feed_URL: 'http://moviesandmania.com',
			has_icon: true,
		},
		{
			feed_ID: 160028624,
			site_ID: 219140819,
			site_URL: 'danlovesfilm.com',
			site_name: 'Dan Loves Film',
			feed_URL: 'http://danlovesfilm.com',
			has_icon: true,
		},
		{
			feed_ID: 68041947,
			site_ID: 131240215,
			site_URL: 'bandsaboutmovies.com',
			site_name: 'B&S About Movies',
			feed_URL: 'http://bandsaboutmovies.com',
			has_icon: true,
		},
		{
			feed_ID: 125357875,
			site_ID: 11325571,
			site_URL: 'thejoyofmovies.ca',
			site_name: 'The Joy of Movies',
			feed_URL: 'http://thejoyofmovies.ca',
			has_icon: true,
		},
	],
	books: [
		{
			feed_ID: 19068123,
			site_ID: 64463434,
			site_URL: 'jenniefitzkee.com',
			site_name: "A Teacher's Reflections",
			feed_URL: 'http://jenniefitzkee.com',
			has_icon: true,
		},
		{
			feed_ID: 249346,
			site_ID: 23261080,
			site_URL: 'pagesunbound.wordpress.com',
			site_name: 'Pages Unbound',
			feed_URL: 'http://pagesunbound.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 46642910,
			site_ID: 87595067,
			site_URL: 'bookreviewdirectory.com',
			site_name: 'The Book Review Directory',
			feed_URL: 'http://bookreviewdirectory.com',
			has_icon: true,
		},
		{
			feed_ID: 8353950,
			site_ID: 47520297,
			site_URL: 'fictionfanblog.wordpress.com',
			site_name: "FictionFan's Book Reviews",
			feed_URL: 'http://fictionfanblog.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 45949836,
			site_ID: 44541989,
			site_URL: 'http://teagansbooks.com',
			site_name: "Teagan's Books",
			feed_URL: 'http://teagansbooks.com',
			has_icon: true,
		},
		{
			feed_ID: 78068663,
			site_ID: 138878027,
			site_URL: 'https://bookjotter.com',
			site_name: 'Book Jotter',
			feed_URL: 'http://bookjotter.com',
			has_icon: true,
		},
		{
			feed_ID: 97359395,
			site_ID: 100806797,
			site_URL: 'chataboutbooks.blog',
			site_name: 'Chat About Books',
			feed_URL: 'http://chataboutbooks.blog',
			has_icon: true,
		},
		{
			feed_ID: 74055258,
			site_ID: 136324088,
			site_URL: 'https://breakevenbooks.com',
			site_name: 'Breakeven Books',
			feed_URL: 'http://breakevenbooks.com',
			has_icon: true,
		},
		{
			feed_ID: 107944862,
			site_ID: 181054600,
			site_URL: 'leahs-books.com',
			site_name: "Leah's Books",
			feed_URL: 'http://leahs-books.com',
			has_icon: true,
		},
		{
			feed_ID: 92472325,
			site_ID: 120979127,
			site_URL: 'http://booksonthe747.com',
			site_name: 'Books on the 7:47',
			feed_URL: 'http://booksonthe747.com',
			has_icon: true,
		},
	],
	art: [
		{
			feed_ID: 4716433,
			site_ID: 40605288,
			site_URL: 'http://photographyartplus.wordpress.com',
			site_name: 'Photography Art Plus',
			feed_URL: 'http://photographyartplus.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 46631862,
			site_ID: 45167732,
			site_URL: 'graffitiluxandmurals.com',
			site_name: 'Graffiti Lux Art & More',
			feed_URL: 'http://graffitiluxandmurals.com',
			has_icon: true,
		},
		{
			feed_ID: 102171,
			site_ID: 23856961,
			site_URL: 'kimberlyharding.wordpress.com',
			site_name: 'Soul Healing Art',
			feed_URL: 'http://kimberlyharding.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 33222275,
			site_ID: 83175719,
			site_URL: 'http://theartteacher.net',
			site_name: 'The Art Teacher',
			feed_URL: 'http://theartteacher.net',
			has_icon: true,
		},
		{
			feed_ID: 18723169,
			site_ID: 54682377,
			site_URL: 'http://medievalartresearch.com',
			site_name: 'Medieval Art Research',
			feed_URL: 'http://medievalartresearch.com',
			has_icon: true,
		},
		{
			feed_ID: 107868904,
			site_ID: 17485148,
			site_URL: 'https://streetartutopia.com',
			site_name: 'STREET ART UTOPIA',
			feed_URL: 'http://streetartutopia.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 121498286,
			site_ID: 109435321,
			site_URL: 'artchapenjoin.com',
			site_name: 'Art-Chap-Enjoin',
			feed_URL: 'http://artchapenjoin.com',
			has_icon: false,
		},
		{
			feed_ID: 71551766,
			site_ID: 134697274,
			site_URL: 'philmcaloon.wordpress.com',
			site_name: "Phil McAloon's paintings",
			feed_URL: 'http://philmcaloon.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 133354645,
			site_ID: 46587062,
			site_URL: 'claudiamcgillart.com',
			site_name: 'Claudia McGill and Her Art World',
			feed_URL: 'http://claudiamcgillart.com',
			has_icon: true,
		},
	],
	theatre: [
		{
			feed_ID: 95336,
			site_ID: 4777860,
			site_URL: 'wondersinthedark.wordpress.com',
			site_name: 'Wonders in the Dark',
			feed_URL: 'http://wondersinthedark.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 2675712,
			site_ID: 10709450,
			site_URL: 'giaonthemove.com',
			site_name: 'Gia On The Move',
			feed_URL: 'http://giaonthemove.com',
			has_icon: true,
		},
		{
			feed_ID: 20414924,
			site_ID: 59301117,
			site_URL: 'https://musicaltheatreresources.com',
			site_name: 'Musical Theatre Resources',
			feed_URL: 'http://musicaltheatreresources.com',
			has_icon: true,
		},
		{
			feed_ID: 2475717,
			site_ID: 36398526,
			site_URL: 'newyorktheater.me',
			site_name: 'New York Theater',
			feed_URL: 'http://newyorktheater.me',
			has_icon: true,
		},
		{
			feed_ID: 139429677,
			site_ID: 137850612,
			site_URL: 'munroreview.com',
			site_name: 'The Munro Review',
			feed_URL: 'http://munroreview.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 160794634,
			site_ID: 235399975,
			site_URL: 'http://themusicaltheatrereport.com',
			site_name: 'The Musical Theatre Report',
			feed_URL: 'http://themusicaltheatrereport.com',
			has_icon: true,
		},
		{
			feed_ID: 103340234,
			site_ID: 170259447,
			site_URL: 'burdreviews.com',
			site_name: 'Philadelphia Theater Reviews by Frank Burd',
			feed_URL: 'http://burdreviews.com',
			has_icon: true,
		},
	],
	writing: [
		{
			feed_ID: 38560661,
			site_ID: 27803114,
			site_URL: 'http://writingtofreedom.com',
			site_name: 'writing to freedom',
			feed_URL: 'http://writingtofreedom.com',
			has_icon: true,
		},
		{
			feed_ID: 125990,
			site_ID: 6780998,
			site_URL: 'kathytemean.wordpress.com',
			site_name: 'Writing and Illustrating',
			feed_URL: 'http://kathytemean.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 42330640,
			site_ID: 35494457,
			site_URL: 'brudberg.me',
			site_name: 'Björn Rudbergs writings',
			feed_URL: 'http://brudberg.me',
			has_icon: true,
		},
		{
			feed_ID: 70900106,
			site_ID: 68441371,
			site_URL: 'herwritinghaven.com',
			site_name: 'Her Writing Haven',
			feed_URL: 'http://herwritinghaven.com',
			has_icon: true,
		},
		{
			feed_ID: 100129212,
			site_ID: 166652922,
			site_URL: 'http://christinebialczak.com',
			site_name: 'Stine Writing',
			feed_URL: 'http://christinebialczak.com',
			has_icon: true,
		},
		{
			feed_ID: 54334346,
			site_ID: 118001721,
			site_URL: 'https://www.creativewritingnews.com',
			site_name: 'Creative Writing News',
			feed_URL: 'http://creativewritingnews.net/feed',
			has_icon: true,
		},
		{
			feed_ID: 41931423,
			site_ID: 59668460,
			site_URL: 'experiencewriting.com',
			site_name: 'Experience Writing',
			feed_URL: 'http://experiencewriting.com',
			has_icon: true,
		},
		{
			feed_ID: 106085778,
			site_ID: 95409711,
			site_URL: 'http://writingatlarge.com',
			site_name: 'Writing at Large',
			feed_URL: 'http://writingatlarge.com',
			has_icon: true,
		},
		{
			feed_ID: 50672115,
			site_ID: 68169120,
			site_URL: 'http://tiffanyswritingdesk.wordpress.com',
			site_name: 'Tiffany’s Writing Desk',
			feed_URL: 'http://tiffanyswritingdesk.wordpress.com',
			has_icon: true,
		},
	],
	architecture: [
		{
			feed_ID: 175311,
			site_ID: 25404146,
			site_URL: 'anordinarywoman.net',
			site_name: 'An Ordinary Woman',
			feed_URL: 'http://anordinarywoman.net',
			has_icon: true,
		},
		{
			feed_ID: 59220672,
			site_ID: 122319796,
			site_URL: 'misfitsarchitecture.com',
			site_name: "misfits' architecture",
			feed_URL: 'http://misfitsarchitecture.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 68357793,
			site_ID: 101125988,
			site_URL: 'futuristarchitecture.com',
			site_name: 'Futurist Architecture',
			feed_URL: 'http://www.futuristarchitecture.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 118941589,
			site_ID: 44953622,
			site_URL: 'transnationalarchitecture.group',
			site_name: 'Transnational Architecture Group',
			feed_URL: 'http://transnationalarchitecture.group',
			has_icon: true,
		},
	],
	photography: [
		{
			feed_ID: 61584541,
			site_ID: 42704984,
			site_URL: 'tom8pie.com',
			site_name: "Tom's Nature-up-close Photography",
			feed_URL: 'http://tom8pie.com',
			has_icon: true,
		},
		{
			feed_ID: 2072095,
			site_ID: 34742092,
			site_URL: 'thepoetryofphotography.wordpress.com',
			site_name: 'The Poetry of Photography',
			feed_URL: 'http://thepoetryofphotography.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 57012229,
			site_ID: 27841459,
			site_URL: 'sillarit.com',
			site_name: 'Ritva Sillanmäki Photography',
			feed_URL: 'http://sillarit.com',
			has_icon: true,
		},
		{
			feed_ID: 19320447,
			site_ID: 29027846,
			site_URL: 'dawn2dawnphotography.me',
			site_name: 'Dawn2Dawn Photography',
			feed_URL: 'http://dawn2dawnphotography.me',
			has_icon: true,
		},
		{
			feed_ID: 77479179,
			site_ID: 14921702,
			site_URL: 'https://etbtravelphotography.com',
			site_name: 'ETB Travel Photography',
			feed_URL: 'http://etbtravelphotography.com',
			has_icon: true,
		},
		{
			feed_ID: 4739493,
			site_ID: 40600836,
			site_URL: 'http://lisabonowiczphotography.wordpress.com',
			site_name: 'Lisa Bonowicz Photography',
			feed_URL: 'http://lisabonowiczphotography.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 15226313,
			site_ID: 59791453,
			site_URL: 'zeeyolqphotography.wordpress.com',
			site_name: 'Zeeyolq Photography',
			feed_URL: 'http://zeeyolqphotography.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 56449004,
			site_ID: 119179555,
			site_URL: 'http://michaelstephenwills.com',
			site_name: 'Michael Stephen Wills Photography',
			feed_URL: 'http://michaelstephenwills.com',
			has_icon: true,
		},
		{
			feed_ID: 145524953,
			site_ID: 4325317,
			site_URL: 'https://keithtomlinsonphoto.com',
			site_name: 'Keith Tomlinson Photography',
			feed_URL: 'http://keithtomlinsonphoto.com',
			has_icon: true,
		},
		{
			feed_ID: 162341130,
			site_ID: 55314545,
			site_URL: 'http://photographyandvision.wordpress.com',
			site_name: 'Photography & Vision',
			feed_URL: 'http://photographyandvision.wordpress.com',
			has_icon: true,
		},
	],
	diy: [
		{
			feed_ID: 145535335,
			site_ID: 222336513,
			site_URL: 'https://sparrowrefashion.com',
			site_name: 'Sparrow Refashion: A Blog for Sewing Lovers and DIY Enthusiasts',
			feed_URL: 'http://sparrowrefashion.com',
			has_icon: false,
		},
		{
			feed_ID: 35402900,
			site_ID: 91411060,
			site_URL: 're-fabbed.com',
			site_name: 'Re-Fabbed',
			feed_URL: 'http://www.re-fabbed.com',
			has_icon: true,
		},
		{
			feed_ID: 56931961,
			site_ID: 111220701,
			site_URL: 'the-diy-life.com',
			site_name: 'The DIY Life',
			feed_URL: 'http://www.the-diy-life.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 38869890,
			site_ID: 66296708,
			site_URL: 'https://www.grandmashousediy.com',
			site_name: 'Grandmas House DIY',
			feed_URL: 'http://www.grandmashousediy.com',
			has_icon: true,
		},
		{
			feed_ID: 107866846,
			site_ID: 178772258,
			site_URL: 'https://countrylilydecor.com',
			site_name: 'Country Lily Decor',
			feed_URL: 'http://countrylilydecor.com',
			has_icon: true,
		},
		{
			feed_ID: 46560483,
			site_ID: 53768874,
			site_URL: 'dreamgreendiy.com',
			site_name: 'Dream Green DIY',
			feed_URL: 'http://www.dreamgreendiy.com/feed',
			has_icon: true,
		},
	],
};
