import { CuratedBlogsList } from './index';

export const creativeArtsBlogs: CuratedBlogsList = {
	music: [
		{
			feed_ID: 47613982,
			site_ID: 74469258,
			site_URL: 'https://musicinjection.com.au',
			site_name: 'Music Injection',
			feed_URL: 'http://musicinjection.com.au',
			has_icon: false,
		},
		{
			feed_ID: 20857594,
			site_ID: 68410802,
			site_URL: 'https://lovemusiclovelife.com',
			site_name: 'Love Music; Love Life',
			feed_URL: 'http://lovemusiclovelife.com',
			has_icon: false,
		},
		{
			feed_ID: 45150669,
			site_ID: 107934412,
			site_URL: 'artmusiclounge.wordpress.com',
			site_name: 'The Art Music Lounge',
			feed_URL: 'http://artmusiclounge.wordpress.com',
			has_icon: false,
		},
		{
			feed_ID: 74978,
			site_ID: 2865384,
			site_URL: 'higherplainmusic.com',
			site_name: 'Higher Plain Music',
			feed_URL: 'http://higherplainmusic.com',
			has_icon: true,
		},
		{
			feed_ID: 54714900,
			site_ID: 99349859,
			site_URL: 'indiepulsemusic.com',
			site_name: 'IndiePulse Music Magazine',
			feed_URL: 'http://indiepulsemusic.com',
			has_icon: false,
		},
		{
			feed_ID: 45553450,
			site_ID: 108354920,
			site_URL: '2loud2oldmusic.com',
			site_name: '2 Loud 2 Old Music',
			feed_URL: 'http://2loud2oldmusic.com',
			has_icon: true,
		},
	],
	movies: [
		{
			feed_ID: 23924186,
			site_ID: 73640258,
			site_URL: 'reallyawfulmovies.com',
			site_name: 'Really Awful Movies',
			feed_URL: 'http://reallyawfulmovies.com',
			has_icon: true,
		},
		{
			feed_ID: 276621,
			site_ID: 16188534,
			site_URL: 'moviesfilmsandflix.com',
			site_name: 'Movies, Films & Flix',
			feed_URL: 'http://moviesfilmsandflix.com',
			has_icon: true,
		},
		{
			feed_ID: 68041947,
			site_ID: 131240215,
			site_URL: 'bandsaboutmovies.com',
			site_name: 'B&S About Movies',
			feed_URL: 'http://bandsaboutmovies.com',
			has_icon: true,
		},
		{
			feed_ID: 125357875,
			site_ID: 11325571,
			site_URL: 'thejoyofmovies.ca',
			site_name: 'The Joy of Movies',
			feed_URL: 'http://thejoyofmovies.ca',
			has_icon: true,
		},
		{
			feed_ID: 160028624,
			site_ID: 219140819,
			site_URL: 'danlovesfilm.com',
			site_name: 'Dan Loves Film',
			feed_URL: 'http://danlovesfilm.com',
			has_icon: true,
		},
	],
	books: [
		{
			feed_ID: 107944862,
			site_ID: 181054600,
			site_URL: 'leahs-books.com',
			site_name: "Leah's Books",
			feed_URL: 'http://leahs-books.com',
			has_icon: true,
		},
		{
			feed_ID: 19068123,
			site_ID: 64463434,
			site_URL: 'jenniefitzkee.com',
			site_name: "A Teacher's Reflections",
			feed_URL: 'http://jenniefitzkee.com',
			has_icon: true,
		},
		{
			feed_ID: 249346,
			site_ID: 23261080,
			site_URL: 'pagesunbound.wordpress.com',
			site_name: 'Pages Unbound',
			feed_URL: 'http://pagesunbound.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 97359395,
			site_ID: 100806797,
			site_URL: 'chataboutbooks.blog',
			site_name: 'Chat About Books',
			feed_URL: 'http://chataboutbooks.blog',
			has_icon: true,
		},
		{
			feed_ID: 8353950,
			site_ID: 47520297,
			site_URL: 'fictionfanblog.wordpress.com',
			site_name: "FictionFan's Book Reviews",
			feed_URL: 'http://fictionfanblog.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 46642910,
			site_ID: 87595067,
			site_URL: 'bookreviewdirectory.com',
			site_name: 'The Book Review Directory',
			feed_URL: 'http://bookreviewdirectory.com',
			has_icon: true,
		},
	],
	art: [
		{
			feed_ID: 46631862,
			site_ID: 45167732,
			site_URL: 'graffitiluxandmurals.com',
			site_name: 'Graffiti Lux Art & More',
			feed_URL: 'http://graffitiluxandmurals.com',
			has_icon: true,
		},
		{
			feed_ID: 71551766,
			site_ID: 134697274,
			site_URL: 'philmcaloon.wordpress.com',
			site_name: "Phil McAloon's paintings",
			feed_URL: 'http://philmcaloon.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 102171,
			site_ID: 23856961,
			site_URL: 'kimberlyharding.wordpress.com',
			site_name: 'Soul Healing Art',
			feed_URL: 'http://kimberlyharding.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 121498286,
			site_ID: 109435321,
			site_URL: 'artchapenjoin.com',
			site_name: 'Art-Chap-Enjoin',
			feed_URL: 'http://artchapenjoin.com',
			has_icon: false,
		},
		{
			feed_ID: 133354645,
			site_ID: 46587062,
			site_URL: 'claudiamcgillart.com',
			site_name: 'Claudia McGill and Her Art World',
			feed_URL: 'http://claudiamcgillart.com',
			has_icon: true,
		},
	],
	theatre: [
		{
			feed_ID: 103340234,
			site_ID: 170259447,
			site_URL: 'burdreviews.com',
			site_name: 'Philadelphia Theater Reviews by Frank Burd',
			feed_URL: 'http://burdreviews.com',
			has_icon: true,
		},
		{
			feed_ID: 2675712,
			site_ID: 10709450,
			site_URL: 'giaonthemove.com',
			site_name: 'Gia On The Move',
			feed_URL: 'http://giaonthemove.com',
			has_icon: true,
		},
		{
			feed_ID: 95336,
			site_ID: 4777860,
			site_URL: 'wondersinthedark.wordpress.com',
			site_name: 'Wonders in the Dark',
			feed_URL: 'http://wondersinthedark.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 2475717,
			site_ID: 36398526,
			site_URL: 'newyorktheater.me',
			site_name: 'New York Theater',
			feed_URL: 'http://newyorktheater.me',
			has_icon: true,
		},
		{
			feed_ID: 139429677,
			site_ID: 137850612,
			site_URL: 'munroreview.com',
			site_name: 'The Munro Review',
			feed_URL: 'http://munroreview.com/feed',
			has_icon: true,
		},
	],
	writing: [
		{
			feed_ID: 70900106,
			site_ID: 68441371,
			site_URL: 'herwritinghaven.com',
			site_name: 'Her Writing Haven',
			feed_URL: 'http://herwritinghaven.com',
			has_icon: true,
		},
		{
			feed_ID: 41931423,
			site_ID: 59668460,
			site_URL: 'experiencewriting.com',
			site_name: 'Experience Writing',
			feed_URL: 'http://experiencewriting.com',
			has_icon: true,
		},
		{
			feed_ID: 125990,
			site_ID: 6780998,
			site_URL: 'kathytemean.wordpress.com',
			site_name: 'Writing and Illustrating',
			feed_URL: 'http://kathytemean.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 42330640,
			site_ID: 35494457,
			site_URL: 'brudberg.me',
			site_name: 'Björn Rudbergs writings',
			feed_URL: 'http://brudberg.me',
			has_icon: true,
		},
		{
			feed_ID: 35130000,
			site_ID: 78968939,
			site_URL: 'whatinspiresyourwriting.wordpress.com',
			site_name: 'What Inspires Your Writing?',
			feed_URL: 'http://whatinspiresyourwriting.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 43661028,
			site_ID: 30676399,
			site_URL: 'poetrybreakfast.com',
			site_name: 'Poetry Breakfast',
			feed_URL: 'http://poetrybreakfast.com',
			has_icon: true,
		},
	],
	architecture: [
		{
			feed_ID: 100213967,
			site_ID: 22166610,
			site_URL: 'landscapearchitecturemagazine.org',
			site_name: 'Landscape Architecture Magazine',
			feed_URL: 'http://landscapearchitecturemagazine.org',
			has_icon: false,
		},
		{
			feed_ID: 16419473,
			site_ID: 61648479,
			site_URL: 'architecturehereandthere.com',
			site_name: 'Architecture Here and There',
			feed_URL: 'http://architecturehereandthere.com',
			has_icon: false,
		},
		{
			feed_ID: 175311,
			site_ID: 25404146,
			site_URL: 'anordinarywoman.net',
			site_name: 'An Ordinary Woman',
			feed_URL: 'http://anordinarywoman.net',
			has_icon: true,
		},
		{
			feed_ID: 118941589,
			site_ID: 44953622,
			site_URL: 'transnationalarchitecture.group',
			site_name: 'Transnational Architecture Group',
			feed_URL: 'http://transnationalarchitecture.group',
			has_icon: true,
		},
		{
			feed_ID: 68357793,
			site_ID: 101125988,
			site_URL: 'futuristarchitecture.com',
			site_name: 'Futurist Architecture',
			feed_URL: 'http://www.futuristarchitecture.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 59220672,
			site_ID: 122319796,
			site_URL: 'misfitsarchitecture.com',
			site_name: "misfits' architecture",
			feed_URL: 'http://misfitsarchitecture.com/feed',
			has_icon: true,
		},
	],
	photography: [
		{
			feed_ID: 2072095,
			site_ID: 34742092,
			site_URL: 'thepoetryofphotography.wordpress.com',
			site_name: 'The Poetry of Photography',
			feed_URL: 'http://thepoetryofphotography.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 15226313,
			site_ID: 59791453,
			site_URL: 'zeeyolqphotography.wordpress.com',
			site_name: 'Zeeyolq Photography',
			feed_URL: 'http://zeeyolqphotography.wordpress.com',
			has_icon: false,
		},
		{
			feed_ID: 61584541,
			site_ID: 42704984,
			site_URL: 'tom8pie.com',
			site_name: "Tom's Nature-up-close Photography",
			feed_URL: 'http://tom8pie.com',
			has_icon: true,
		},
		{
			feed_ID: 19320447,
			site_ID: 29027846,
			site_URL: 'dawn2dawnphotography.me',
			site_name: 'Dawn2Dawn Photography',
			feed_URL: 'http://dawn2dawnphotography.me',
			has_icon: true,
		},
		{
			feed_ID: 57012229,
			site_ID: 27841459,
			site_URL: 'sillarit.com',
			site_name: 'Ritva Sillanmäki Photography',
			feed_URL: 'http://sillarit.com',
			has_icon: true,
		},
	],
	diy: [
		{
			feed_ID: 123937135,
			site_ID: 199819352,
			site_URL: 'diyprojectslab.com',
			site_name: 'DIY Projects Lab',
			feed_URL: 'http://www.diyprojectslab.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 46560483,
			site_ID: 53768874,
			site_URL: 'dreamgreendiy.com',
			site_name: 'Dream Green DIY',
			feed_URL: 'http://www.dreamgreendiy.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 35402900,
			site_ID: 91411060,
			site_URL: 're-fabbed.com',
			site_name: 'Re-Fabbed',
			feed_URL: 'http://www.re-fabbed.com',
			has_icon: true,
		},
		{
			feed_ID: 56931961,
			site_ID: 111220701,
			site_URL: 'the-diy-life.com',
			site_name: 'The DIY Life',
			feed_URL: 'http://www.the-diy-life.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 33360370,
			site_ID: 50125255,
			site_URL: 'diyncrafts.com',
			site_name: 'DIY & Crafts',
			feed_URL: 'http://www.diyncrafts.com/feed',
			has_icon: true,
		},
	],
};
