import { CuratedBlogsList } from './index';

export const industryBlogs: CuratedBlogsList = {
	business: [
		{
			feed_ID: 83448543,
			site_ID: 147199084,
			site_URL: 'https://seths.blog/',
			site_name: "Seth's Blog",
			feed_URL: 'http://seths.blog/feed',
			has_icon: false,
		},
		{
			feed_ID: 102181945,
			site_ID: 164745976,
			site_URL: 'https://tim.blog/',
			site_name: 'The Blog of Author Tim Ferriss',
			feed_URL: 'http://tim.blog/feed',
			has_icon: true,
		},
		{
			feed_ID: 63349823,
			site_ID: 126020344,
			site_URL: 'https://venturebeat.com/',
			site_name: 'VentureBeat',
			feed_URL: 'http://venturebeat.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 34131275,
			site_ID: 41106627,
			site_URL: 'https://www.ducttapemarketing.com/',
			site_name: 'Duct Tape Marketing',
			feed_URL: 'http://www.ducttapemarketing.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 69594518,
			site_ID: 133617928,
			site_URL: 'http://trendingbusinessinsights.com',
			site_name: 'Business Insights',
			feed_URL: 'http://trendingbusinessinsights.com',
			has_icon: true,
		},
		{
			feed_ID: 42227761,
			site_ID: 104842126,
			site_URL: 'https://www.thesmallbusinesssite.co.za/',
			site_name: 'The Small Business Site',
			feed_URL: 'http://www.thesmallbusinesssite.co.za',
			has_icon: true,
		},
		{
			feed_ID: 112355958,
			site_ID: 180059651,
			site_URL: 'http://technologyandbusinessnews.wordpress.com',
			site_name: 'Technology & Business News',
			feed_URL: 'http://technologyandbusinessnews.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 8892459,
			site_ID: 0,
			site_URL: 'https://www.businesspundit.com/',
			site_name: 'Business Pundit',
			feed_URL: 'http://www.businesspundit.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 55005345,
			site_ID: 116448446,
			site_URL: 'https://www.entrepreneurbusinessblog.com',
			site_name: 'Entrepreneur Business Blog',
			feed_URL: 'http://www.entrepreneurbusinessblog.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 107897208,
			site_ID: 180997989,
			site_URL: 'https://businessmanagementblog.com',
			site_name: 'Business Management Blog',
			feed_URL: 'http://businessmanagementblog41087550.wordpress.com',
			has_icon: true,
		},
	],
	startups: [
		{
			feed_ID: 116494,
			site_ID: 6599589,
			site_URL: 'https://steveblank.com/',
			site_name: 'Steve Blank',
			feed_URL: 'http://steveblank.com',
			has_icon: true,
		},
		{
			feed_ID: 111100674,
			site_ID: 136296444,
			site_URL: 'https://techcrunch.com/',
			site_name: 'TechCrunch',
			feed_URL: 'http://techcrunch.com',
			has_icon: true,
		},
		{
			feed_ID: 359631,
			site_ID: 6003453,
			site_URL: 'http://davidcummings.org/',
			site_name: 'David Cummings on Startups',
			feed_URL: 'http://davidcummings.org',
			has_icon: true,
		},
		{
			feed_ID: 458090,
			site_ID: 11070789,
			site_URL: 'http://kellblog.com',
			site_name: 'Kellblog',
			feed_URL: 'http://kellblog.com',
			has_icon: true,
		},
		{
			feed_ID: 57294374,
			site_ID: 44421129,
			site_URL: 'https://inspire99.com',
			site_name: 'Inspire99',
			feed_URL: 'http://inspire99.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 63349823,
			site_ID: 126020344,
			site_URL: 'https://venturebeat.com/',
			site_name: 'VentureBeat',
			feed_URL: 'http://venturebeat.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 69531647,
			site_ID: 133193919,
			site_URL: 'https://sangkrit.net',
			site_name: 'Internet Growth Engine: the startup interface',
			feed_URL: 'http://sangkrit.net/feed',
			has_icon: true,
		},
		{
			feed_ID: 116044414,
			site_ID: 186248957,
			site_URL: 'http://tremendous.blog',
			site_name: 'Tremendous',
			feed_URL: 'http://tremendous.blog',
			has_icon: true,
		},
		{
			feed_ID: 23707152,
			site_ID: 33216796,
			site_URL: 'https://startupiceland.com',
			site_name: 'Startup Iceland',
			feed_URL: 'http://startupiceland.com',
			has_icon: true,
		},
		{
			feed_ID: 25353898,
			site_ID: 0,
			site_URL: 'https://www.tomtunguz.com/',
			site_name: 'Tomasz Tunguz',
			feed_URL: 'http://tomtunguz.com/index.xml',
			has_icon: false,
		},
	],
	finance: [
		{
			feed_ID: 161425747,
			site_ID: 234156106,
			site_URL: 'https://themoneymindedmom.com',
			site_name: 'The Money Minded Mom | Personal Finance Blog',
			feed_URL: 'http://themoneymindedmom.com',
			has_icon: true,
		},
		{
			feed_ID: 23676236,
			site_ID: 73350021,
			site_URL: 'https://blog.bankbazaar.com',
			site_name: 'BankBazaar - The Definitive Word on Personal Finance',
			feed_URL: 'http://blog.bankbazaar.com',
			has_icon: true,
		},
		{
			feed_ID: 162169651,
			site_ID: 143180195,
			site_URL: 'http://mmufande.blog',
			site_name: 'Finance & Economics Hub',
			feed_URL: 'http://mmufande.blog',
			has_icon: true,
		},
		{
			feed_ID: 9046327,
			site_ID: 0,
			site_URL: 'https://abnormalreturns.com/',
			site_name: 'Abnormal Returns',
			feed_URL: 'http://abnormalreturns.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 8873211,
			site_ID: 0,
			site_URL: 'http://www.calculatedriskblog.com/',
			site_name: 'Calculated Risk',
			feed_URL: 'http://feeds.feedburner.com/CalculatedRisk',
			has_icon: false,
		},
		{
			feed_ID: 46459237,
			site_ID: 0,
			site_URL: 'https://ritholtz.com/',
			site_name: 'The Big Picture',
			feed_URL: 'http://ritholtz.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 32743323,
			site_ID: 0,
			site_URL: 'https://awealthofcommonsense.com/',
			site_name: 'A Wealth of Common Sense',
			feed_URL: 'http://awealthofcommonsense.com/feed',
			has_icon: false,
		},
	],
	space: [
		{
			feed_ID: 99248196,
			site_ID: 66864929,
			site_URL: 'https://explainingscience.org/',
			site_name: 'Explaining Science',
			feed_URL: 'http://explainingscience.org',
			has_icon: true,
		},
		{
			feed_ID: 45847571,
			site_ID: 24000880,
			site_URL: 'https://www.universetoday.com/',
			site_name: 'Universe Today',
			feed_URL: 'http://www.universetoday.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 88386315,
			site_ID: 122153163,
			site_URL: 'https://spaceq.ca/',
			site_name: 'SpaceQ',
			feed_URL: 'http://spaceq.ca/feed',
			has_icon: true,
		},
		{
			feed_ID: 127625644,
			site_ID: 6330659,
			site_URL: 'https://newspaceeconomy.ca/',
			site_name: 'New Space Economy',
			feed_URL: 'http://newspaceeconomy.ca',
			has_icon: true,
		},
		{
			feed_ID: 109455857,
			site_ID: 0,
			site_URL: 'https://www.planetary.org/',
			site_name: 'The Planetary Society Articles',
			feed_URL: 'http://www.planetary.org/rss/articles',
			has_icon: false,
		},
		{
			feed_ID: 46452720,
			site_ID: 80681979,
			site_URL: 'https://spacenews.com/',
			site_name: 'SpaceNews',
			feed_URL: 'http://spacenews.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 136382237,
			site_ID: 212796078,
			site_URL: 'https://nasaspacenews.com',
			site_name: 'NASA Space News',
			feed_URL: 'http://nasaspacenews.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 55764368,
			site_ID: 0,
			site_URL: 'https://spaceflightnow.com/',
			site_name: 'Spaceflight Now',
			feed_URL: 'http://spaceflightnow.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 157803248,
			site_ID: 0,
			site_URL: 'https://www.nasa.gov/',
			site_name: 'NASA',
			feed_URL: 'http://www.nasa.gov/feed',
			has_icon: false,
		},
	],
	leadership: [
		{
			feed_ID: 36408839,
			site_ID: 23168767,
			site_URL: 'http://paulitaylor.com/',
			site_name: 'Paul Taylor',
			feed_URL: 'http://paulitaylor.com',
			has_icon: true,
		},
		{
			feed_ID: 161514445,
			site_ID: 11817513,
			site_URL: 'http://drsaraheaton.com',
			site_name: 'Learning, Teaching and Leadership',
			feed_URL: 'http://drsaraheaton.com',
			has_icon: true,
		},
		{
			feed_ID: 449369,
			site_ID: 2846523,
			site_URL: 'http://leadership101.wordpress.com',
			site_name: 'Leadership 101',
			feed_URL: 'http://leadership101.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 57820657,
			site_ID: 117810150,
			site_URL: 'https://leadershipdots.com',
			site_name: 'leadership dots',
			feed_URL: 'http://leadershipdots.com',
			has_icon: true,
		},
		{
			feed_ID: 99145439,
			site_ID: 135824014,
			site_URL: 'https://bulluckg.com',
			site_name: 'Servant Leadership NOW: "Stepping Up Your Leadership Call"',
			feed_URL: 'http://bulluckg.com',
			has_icon: true,
		},
		{
			feed_ID: 2608322,
			site_ID: 36441788,
			site_URL: 'http://pragmaticleadership.wordpress.com',
			site_name: 'pragmatic  leadership',
			feed_URL: 'http://pragmaticleadership.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 25599614,
			site_ID: 124014575,
			site_URL: 'https://randsinrepose.com/',
			site_name: 'Rands in Repose',
			feed_URL: 'http://randsinrepose.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 130459494,
			site_ID: 26787474,
			site_URL: 'https://cassieroma.com',
			site_name: 'Reshaping Modern Leadership',
			feed_URL: 'http://cassieroma.com',
			has_icon: true,
		},
		{
			feed_ID: 57034834,
			site_ID: 0,
			site_URL: 'https://hbr.org/',
			site_name: 'HBR.org',
			feed_URL: 'http://feeds.hbr.org/harvardbusiness',
			has_icon: false,
		},
		{
			feed_ID: 41466875,
			site_ID: 0,
			site_URL: 'https://thinkers50.com/',
			site_name: 'Thinkers50',
			feed_URL: 'http://thinkers50.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 4192830,
			site_ID: 0,
			site_URL: 'https://www.askamanager.org/',
			site_name: 'Ask a Manager',
			feed_URL: 'http://askamanager.com',
			has_icon: false,
		},
	],
	marketing: [
		{
			feed_ID: 83448543,
			site_ID: 147199084,
			site_URL: 'https://seths.blog/',
			site_name: "Seth's Blog",
			feed_URL: 'http://seths.blog/feed',
			has_icon: false,
		},
		{
			feed_ID: 66184789,
			site_ID: 85568242,
			site_URL: 'https://guykawasaki.com/',
			site_name: 'Guy Kawasaki',
			feed_URL: 'http://guykawasaki.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 34131275,
			site_ID: 41106627,
			site_URL: 'https://www.ducttapemarketing.com/',
			site_name: 'Duct Tape Marketing',
			feed_URL: 'http://www.ducttapemarketing.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 102811293,
			site_ID: 171550906,
			site_URL: 'http://iconmarketingagency.wordpress.com',
			site_name: 'Icon Marketing Agency',
			feed_URL: 'http://iconmarketingagency.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 174529008,
			site_ID: 244874088,
			site_URL: 'https://discreetmarketingboss.com',
			site_name: 'Discreet Marketing Boss',
			feed_URL: 'http://discreetmarketingboss2.wpcomstaging.com',
			has_icon: true,
		},
		{
			feed_ID: 122304840,
			site_ID: 92541217,
			site_URL: 'https://shannonmcc.com',
			site_name: 'Soulful Marketing Blog',
			feed_URL: 'http://shannonmcc.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 55218042,
			site_ID: 0,
			site_URL: 'https://neilpatel.com/',
			site_name: 'Neil Patel',
			feed_URL: 'http://neilpatel.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 167115685,
			site_ID: 242029717,
			site_URL: 'http://kaeraemarketingg.wordpress.com',
			site_name: 'Kelsey Flannery (KaeRae Marketing)',
			feed_URL: 'http://kaeraemarketingg.wordpress.com',
			has_icon: true,
		},
	],
	'remote-work': [
		{
			feed_ID: 161740858,
			site_ID: 236373731,
			site_URL: 'http://beremoteconsulting.com/',
			site_name: 'Be Remote Consulting',
			feed_URL: 'http://beremoteconsulting.com',
			has_icon: true,
		},
		{
			feed_ID: 188407,
			site_ID: 1047865,
			site_URL: 'https://ma.tt/',
			site_name: 'Matt Mullenweg',
			feed_URL: 'http://ma.tt/feed',
			has_icon: true,
		},
		{
			feed_ID: 51146843,
			site_ID: 92143548,
			site_URL: 'https://piszek.com',
			site_name: 'Artur Piszek',
			feed_URL: 'http://piszek.com',
			has_icon: true,
		},
	],
	saas: [
		{
			feed_ID: 111100674,
			site_ID: 136296444,
			site_URL: 'https://techcrunch.com/',
			site_name: 'TechCrunch',
			feed_URL: 'http://techcrunch.com',
			has_icon: true,
		},
		{
			feed_ID: 359631,
			site_ID: 6003453,
			site_URL: 'http://davidcummings.org/',
			site_name: 'David Cummings on Startups',
			feed_URL: 'http://davidcummings.org',
			has_icon: true,
		},
		{
			feed_ID: 458090,
			site_ID: 11070789,
			site_URL: 'https://kellblog.com/',
			site_name: 'Kellblog',
			feed_URL: 'http://kellblog.com',
			has_icon: true,
		},
		{
			feed_ID: 25353898,
			site_ID: 0,
			site_URL: 'https://www.tomtunguz.com/',
			site_name: 'Tomasz Tunguz',
			feed_URL: 'http://tomtunguz.com/index.xml',
			has_icon: false,
		},
	],
	'creator-economy': [
		{
			feed_ID: 91274429,
			site_ID: 140678957,
			site_URL: 'http://tipsfromsharvi.com/',
			site_name: 'Tips from Sharvi',
			feed_URL: 'http://tipsfromsharvi.com',
			has_icon: true,
		},
		{
			feed_ID: 141870632,
			site_ID: 218647781,
			site_URL: 'https://bernoff.com/',
			site_name: 'Josh Bernoff',
			feed_URL: 'http://bernoff.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 108106978,
			site_ID: 181411913,
			site_URL: 'https://www.tubefilter.com/',
			site_name: 'Tubefilter',
			feed_URL: 'http://dev.tubefilter.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 150905227,
			site_ID: 225278048,
			site_URL: 'http://louderback.com/',
			site_name: 'Jim Louderback',
			feed_URL: 'http://louderback.com/feed',
			has_icon: true,
		},
	],
};
