import { CuratedBlogsList } from './index';

export const lifestyleBlogs: CuratedBlogsList = {
	health: [
		{
			feed_ID: 27232798,
			site_ID: 62003347,
			site_URL: 'https://phoebemd.com/',
			site_name: 'HEALTH + INSPIRATION',
			feed_URL: 'http://phoebemd.com',
			has_icon: true,
		},
		{
			feed_ID: 1150618,
			site_ID: 30537913,
			site_URL: 'https://fitrecovery.wordpress.com/',
			site_name: 'Fit Recovery',
			feed_URL: 'http://fitrecovery.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 5470009,
			site_ID: 41715823,
			site_URL: 'http://ourbetterhealth.org',
			site_name: 'Our Better Health',
			feed_URL: 'http://ourbetterhealth.org',
			has_icon: true,
		},
		{
			feed_ID: 99853252,
			site_ID: 166484180,
			site_URL: 'https://healthtipsnow.net/',
			site_name: 'Health Tips Now',
			feed_URL: 'http://healthtipsnow.net/feed',
			has_icon: true,
		},
		{
			feed_ID: 34190335,
			site_ID: 83829697,
			site_URL: 'https://lifediethealth.com',
			site_name: 'Life Diet Health',
			feed_URL: 'http://www.lifediethealth.com',
			has_icon: true,
		},
		{
			feed_ID: 37662890,
			site_ID: 37547896,
			site_URL: 'https://healthyhelperkaila.com/',
			site_name: 'Healthy Helper',
			feed_URL: 'http://healthyhelperblog.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 112106194,
			site_ID: 53685563,
			site_URL: 'https://resiliencymentalhealth.com',
			site_name: 'Resiliency Mental Health',
			feed_URL: 'http://resiliencymentalhealth.com',
			has_icon: true,
		},
		{
			feed_ID: 60719065,
			site_ID: 115141267,
			site_URL: 'http://generalhealthmagazine.com',
			site_name: 'General Health Magazine',
			feed_URL: 'http://generalhealthmagazine.com',
			has_icon: true,
		},
	],
	'personal-finance': [
		{
			feed_ID: 118631270,
			site_ID: 190981201,
			site_URL: 'https://sakkemoto.com/',
			site_name: 'Financial Freedom',
			feed_URL: 'http://sakkemoto.com',
			has_icon: true,
		},
		{
			feed_ID: 2658025,
			site_ID: 3871088,
			site_URL: 'https://www.canajunfinances.com',
			site_name: 'Canadian Personal Finance Blog',
			feed_URL: 'http://www.canajunfinances.com',
			has_icon: true,
		},
		{
			feed_ID: 161425747,
			site_ID: 234156106,
			site_URL: 'https://themoneymindedmom.com/',
			site_name: 'The Money Minded Mom | personal finance blog',
			feed_URL: 'http://themoneymindedmom.com',
			has_icon: true,
		},
		{
			feed_ID: 23676236,
			site_ID: 73350021,
			site_URL: 'https://blog.bankbazaar.com',
			site_name: 'BankBazaar - The Definitive Word on Personal Finance',
			feed_URL: 'http://blog.bankbazaar.com',
			has_icon: true,
		},
	],
	food: [
		{
			feed_ID: 7739903,
			site_ID: 46464658,
			site_URL: 'https://thefoodgallery.wordpress.com/',
			site_name: 'The Food Gallery',
			feed_URL: 'http://thefoodgallery.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 37010753,
			site_ID: 32992360,
			site_URL: 'https://lucysfriendlyfoods.com/',
			site_name: "Lucy's Friendly Foods",
			feed_URL: 'http://lucysfriendlyfoods.com',
			has_icon: true,
		},
		{
			feed_ID: 1270452,
			site_ID: 30938996,
			site_URL: 'https://foodobs.wordpress.com/',
			site_name: 'Food Observations',
			feed_URL: 'http://foodobs.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 68681599,
			site_ID: 132578640,
			site_URL: 'http://aroundthefamilytableblog.com',
			site_name: 'Around the Family Table - Food. Fun. Fellowship',
			feed_URL: 'http://aroundthefamilytableblog.com',
			has_icon: true,
		},
		{
			feed_ID: 125849892,
			site_ID: 134042189,
			site_URL: 'http://jensfoodblog.com/',
			site_name: "Jen's Food Blog",
			feed_URL: 'http://jensfoodblog.com',
			has_icon: true,
		},
		{
			feed_ID: 89316309,
			site_ID: 153557609,
			site_URL: 'https://bestindianfoodblog.wordpress.com/',
			site_name: 'Best Indian Food Blog',
			feed_URL: 'http://bestindianfoodblog.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 72281380,
			site_ID: 25276452,
			site_URL: 'http://britishfoodhistory.com',
			site_name: 'British Food: A History',
			feed_URL: 'http://britishfoodhistory.com',
			has_icon: true,
		},
		{
			feed_ID: 85917557,
			site_ID: 149958419,
			site_URL: 'http://dansfooddiary.com',
			site_name: "Dan's Food Blog",
			feed_URL: 'http://dansfooddiary.com',
			has_icon: true,
		},
		{
			feed_ID: 1953951,
			site_ID: 27981580,
			site_URL: 'http://foodandwineaesthetics.com',
			site_name: 'Exploring the Philosophy of Food and Wine',
			feed_URL: 'http://foodandwineaesthetics.com',
			has_icon: true,
		},
		{
			feed_ID: 82004355,
			site_ID: 135222101,
			site_URL: 'https://fettysfoodblog.com',
			site_name: "Fetty's Food Blog",
			feed_URL: 'http://fettysfoodblog.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 157959229,
			site_ID: 87575547,
			site_URL: 'http://thepursuitoffoodperfection.wordpress.com',
			site_name: 'The Pursuit of Food Perfection',
			feed_URL: 'http://thepursuitoffoodperfection.wordpress.com',
			has_icon: true,
		},
	],
	'life-hacks': [
		{
			feed_ID: 90611393,
			site_ID: 143762023,
			site_URL: 'https://wiseandshinezine.com/',
			site_name: 'Wise & Shine',
			feed_URL: 'http://pointlessoverthinking.com',
			has_icon: true,
		},
		{
			feed_ID: 162167509,
			site_ID: 236808004,
			site_URL: 'http://arksale.in/',
			site_name: 'Next-Level Insights',
			feed_URL: 'http://arksale.in',
			has_icon: true,
		},
		{
			feed_ID: 91274429,
			site_ID: 140678957,
			site_URL: 'http://tipsfromsharvi.com/',
			site_name: 'Tips from Sharvi',
			feed_URL: 'http://tipsfromsharvi.com',
			has_icon: true,
		},
		{
			feed_ID: 67075716,
			site_ID: 130306686,
			site_URL: 'https://optimisticlifeat30.wordpress.com/',
			site_name: 'Optimistic Life',
			feed_URL: 'http://optimisticlifeat30.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 107132735,
			site_ID: 179513101,
			site_URL: 'https://goodlifetoo.wordpress.com/',
			site_name: 'Life hack',
			feed_URL: 'http://goodlifetoo.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 108524765,
			site_ID: 47352818,
			site_URL: 'http://fullandrobustlife.com',
			site_name: 'Full and Robust Life Hacks',
			feed_URL: 'http://fullandrobustlife.com',
			has_icon: true,
		},
	],
	'mental-health': [
		{
			feed_ID: 141405234,
			site_ID: 218181139,
			site_URL: 'http://mind4youth.com',
			site_name: 'Mind4Youth',
			feed_URL: 'http://mind4youth.com',
			has_icon: true,
		},
		{
			feed_ID: 44793102,
			site_ID: 101000435,
			site_URL: 'http://therapybits.com/',
			site_name: 'Therapy Bits',
			feed_URL: 'http://therapybits.com',
			has_icon: true,
		},
		{
			feed_ID: 100704960,
			site_ID: 141517174,
			site_URL: 'http://letstalkaboutmentalhealth.com.au/',
			site_name: 'Let’s Talk About Mental Health',
			feed_URL: 'http://letstalkaboutmentalhealth.com.au',
			has_icon: true,
		},
		{
			feed_ID: 112106194,
			site_ID: 53685563,
			site_URL: 'https://resiliencymentalhealth.com/',
			site_name: 'Resiliency Mental Health',
			feed_URL: 'http://resiliencymentalhealth.com',
			has_icon: true,
		},
		{
			feed_ID: 80642835,
			site_ID: 46544096,
			site_URL: 'https://lancek4.com',
			site_name: 'Mental Health, Philosophy, Psychology you are mattering',
			feed_URL: 'http://lancek4.com',
			has_icon: true,
		},
		{
			feed_ID: 132870273,
			site_ID: 209099465,
			site_URL: 'http://simplymentalhealth.ca/',
			site_name: 'Simply mental health',
			feed_URL: 'http://simplymentalhealth.ca',
			has_icon: true,
		},
		{
			feed_ID: 162408135,
			site_ID: 61724223,
			site_URL: 'http://seneeseale.wordpress.com',
			site_name: 'The Princess Guide to Relationships & Mental Health',
			feed_URL: 'http://seneeseale.wordpress.com',
			has_icon: true,
		},
	],
	sleep: [
		{
			feed_ID: 13096676,
			site_ID: 66008408,
			site_URL: 'https://neurosciencenews.com/',
			site_name: 'Neuroscience News',
			feed_URL: 'http://neurosciencenews.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 144414492,
			site_ID: 35212544,
			site_URL: 'http://naturalremediesgoodhealth.com/',
			site_name: 'News on Natural Remedies, Good Sleep and Good Health',
			feed_URL: 'http://naturalremediesgoodhealth.com',
			has_icon: true,
		},
		{
			feed_ID: 176185437,
			site_ID: 231287213,
			site_URL: 'https://somaticsleepcoach.com',
			site_name: 'Somatic Sleep Coach',
			feed_URL: 'http://somaticsleepcoach.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 47798491,
			site_ID: 103187149,
			site_URL: 'https://sleepwithsilk.com/',
			site_name: 'Sleep With Silk',
			feed_URL: 'http://sleepwithsilk.com',
			has_icon: true,
		},
	],
	relationships: [
		{
			feed_ID: 1901833,
			site_ID: 19760099,
			site_URL: 'https://sybersue.com/',
			site_name: 'Dating Relationship Coaching & Advice',
			feed_URL: 'http://sybersue.com',
			has_icon: true,
		},
		{
			feed_ID: 78752950,
			site_ID: 41173337,
			site_URL: 'http://clarkkent07.wordpress.com',
			site_name: 'Relationship Reinvented LLC',
			feed_URL: 'http://clarkkent07.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 106580142,
			site_ID: 178446124,
			site_URL: 'https://relationshipseeds.com',
			site_name: 'Relationship seeds',
			feed_URL: 'http://relationshipseeds.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 156082911,
			site_ID: 215835640,
			site_URL: 'https://sweetjtherapy.com/',
			site_name: 'Therapy for Relationships',
			feed_URL: 'http://sweetjtherapy.com',
			has_icon: true,
		},
	],
	parenting: [
		{
			feed_ID: 116033921,
			site_ID: 191316489,
			site_URL: 'https://thechampatree.in/',
			site_name: 'Motherhood Parenting Blog & Marketplace – THE CHAMPA TREE',
			feed_URL: 'http://thechampatree.in/feed',
			has_icon: true,
		},
		{
			feed_ID: 8070109,
			site_ID: 41049453,
			site_URL: 'http://picturebookparenting.com/',
			site_name: 'Picture Book Parenting',
			feed_URL: 'http://picturebookparenting.com',
			has_icon: true,
		},
		{
			feed_ID: 53974728,
			site_ID: 61752497,
			site_URL: 'https://theparentingadventurestipsandtricks.wordpress.com/',
			site_name: 'The Parenting Adventures',
			feed_URL: 'http://theparentingadventurestipsandtricks.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 175266425,
			site_ID: 171882735,
			site_URL: 'https://gregthebrave.com',
			site_name: 'Funny Parenting Stories for Fathers (and Mothers)',
			feed_URL: 'http://gregthebrave.com',
			has_icon: true,
		},
		{
			feed_ID: 125543499,
			site_ID: 143921227,
			site_URL: 'https://parentingbyanshu.com/',
			site_name: 'Parenting By Anshu',
			feed_URL: 'http://anshushrivastavadotcom.wpcomstaging.com',
			has_icon: true,
		},
	],
	travel: [
		{
			feed_ID: 18228049,
			site_ID: 62211166,
			site_URL: 'https://theluxurytravelexpert.com/',
			site_name: 'the Luxury Travel Expert',
			feed_URL: 'http://theluxurytravelexpert.com',
			has_icon: true,
		},
		{
			feed_ID: 7279497,
			site_ID: 45569860,
			site_URL: 'http://travelwithintent.com/',
			site_name: 'Travel with Intent',
			feed_URL: 'http://travelwithintent.com',
			has_icon: true,
		},
		{
			feed_ID: 112669284,
			site_ID: 188022353,
			site_URL: 'https://www.traveloffpath.com/',
			site_name: 'Travel Off Path',
			feed_URL: 'http://www.traveloffpath.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 125544558,
			site_ID: 13744910,
			site_URL: 'http://sherrylachelletravels.com/',
			site_name: 'Sherry Lachelle Travels',
			feed_URL: 'http://sherrylachelletravels.com',
			has_icon: true,
		},
		{
			feed_ID: 45383025,
			site_ID: 79986544,
			site_URL: 'https://imageearthtravel.com',
			site_name: 'Image Earth Travel',
			feed_URL: 'http://imageearthtravel.com',
			has_icon: true,
		},
		{
			feed_ID: 88998444,
			site_ID: 125430959,
			site_URL: 'https://thetravelarchitect.wordpress.com/',
			site_name: 'The Travel Architect',
			feed_URL: 'http://thetravelarchitect.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 81363240,
			site_ID: 145012586,
			site_URL: 'https://eatsleeplovetravel.com/',
			site_name: 'Eat Sleep Love Travel',
			feed_URL: 'http://eatsleeplovetravel.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 20190109,
			site_ID: 18883718,
			site_URL: 'http://elizabatz.com',
			site_name: 'Albatz Travel Adventures',
			feed_URL: 'http://elizabatz.com',
			has_icon: true,
		},
		{
			feed_ID: 35349681,
			site_ID: 52798793,
			site_URL: 'http://travelcocktail.me',
			site_name: 'The Travel Cocktail',
			feed_URL: 'http://travelcocktail.me',
			has_icon: true,
		},
		{
			feed_ID: 78480219,
			site_ID: 141614091,
			site_URL: 'https://fearlessfemaletravels.com',
			site_name: 'Fearless Female Travels',
			feed_URL: 'http://fearlessfemaletravels.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 108559130,
			site_ID: 182243835,
			site_URL: 'https://www.toonsarah-travels.blog',
			site_name: 'Travel with me',
			feed_URL: 'http://www.toonsarah-travels.blog',
			has_icon: true,
		},
		{
			feed_ID: 111840434,
			site_ID: 178704403,
			site_URL: 'http://travelworldsuitcase.com',
			site_name: 'Suitcase Travel Blog',
			feed_URL: 'http://travelworldsuitcase.com',
			has_icon: true,
		},
		{
			feed_ID: 63030302,
			site_ID: 125432271,
			site_URL: 'https://travelwithapen.com',
			site_name: 'Travel with a Pen',
			feed_URL: 'http://www.travelwithapen.com/feed',
			has_icon: true,
		},
	],
};
