import { CuratedBlogsList } from './index';

export const societyBlogs: CuratedBlogsList = {
	education: [
		{
			feed_ID: 155447430,
			site_ID: 202092965,
			site_URL: 'https://world-education-blog.org',
			site_name: 'World Education Blog',
			feed_URL: 'http://world-education-blog.org',
			has_icon: false,
		},
		{
			feed_ID: 19068123,
			site_ID: 64463434,
			site_URL: 'https://jenniefitzkee.com/',
			site_name: "A Teacher's Reflections",
			feed_URL: 'http://jenniefitzkee.com',
			has_icon: true,
		},
		{
			feed_ID: 69814417,
			site_ID: 39960713,
			site_URL: 'https://www.teachertoolkit.co.uk/',
			site_name: 'TeacherToolkit',
			feed_URL: 'http://www.teachertoolkit.co.uk/feed',
			has_icon: true,
		},
		{
			feed_ID: 65895799,
			site_ID: 127617468,
			site_URL: 'https://www.adelectableeducation.com',
			site_name: 'A Delectable Education Podcast',
			feed_URL: 'http://www.adelectableeducation.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 92214155,
			site_ID: 144578924,
			site_URL: 'https://oecdedutoday.com',
			site_name: 'OECD Education and Skills Today',
			feed_URL: 'http://oecdedutoday.com',
			has_icon: true,
		},
		{
			feed_ID: 54210872,
			site_ID: 87216431,
			site_URL: 'https://inclusiveteach.com',
			site_name: 'Special Education and Inclusive Learning',
			feed_URL: 'http://inclusiveteach.com',
			has_icon: true,
		},
		{
			feed_ID: 2477194,
			site_ID: 32729256,
			site_URL: 'http://internationalednews.com',
			site_name: 'International Education News',
			feed_URL: 'http://internationalednews.com',
			has_icon: true,
		},
		{
			feed_ID: 91598966,
			site_ID: 80417626,
			site_URL: 'http://homemadeeducation.com',
			site_name: 'HomeMade Education',
			feed_URL: 'http://homemadeeducation.com',
			has_icon: true,
		},
		{
			feed_ID: 2697468,
			site_ID: 11866712,
			site_URL: 'http://zigzageducation.wordpress.com',
			site_name: 'ZigZag Education',
			feed_URL: 'http://zigzageducation.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 22002764,
			site_ID: 60068710,
			site_URL: 'https://www.coolcatteacher.com/',
			site_name: 'Cool Cat Teacher Blog',
			feed_URL: 'http://www.coolcatteacher.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 78449659,
			site_ID: 102727187,
			site_URL: 'http://www.shakeuplearning.com/',
			site_name: 'Shake Up Learning',
			feed_URL: 'http://shakeuplearning.com/feed',
			has_icon: true,
		},
	],
	nature: [
		{
			feed_ID: 63062,
			site_ID: 877271,
			site_URL: 'http://tomwhelan.wordpress.com',
			site_name: 'Nature Diary',
			feed_URL: 'http://tomwhelan.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 17239565,
			site_ID: 62426488,
			site_URL: 'https://backyardbirdnerd.com/',
			site_name: 'Backyard Bird Nerd',
			feed_URL: 'http://backyardbirdnerd.com',
			has_icon: true,
		},
		{
			feed_ID: 79041338,
			site_ID: 142325617,
			site_URL: 'https://nationalparkswitht.com/',
			site_name: 'National Parks With T',
			feed_URL: 'http://nationalparkswitht.com',
			has_icon: true,
		},
		{
			feed_ID: 155668618,
			site_ID: 48819432,
			site_URL: 'https://scotlandsnature.wordpress.com/',
			site_name: "Scotland's Nature",
			feed_URL: 'http://scotlandsnature.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 103150710,
			site_ID: 34408245,
			site_URL: 'http://brichetto.wordpress.com',
			site_name: 'SIDEWALK NATURE',
			feed_URL: 'http://sidewalknature.com',
			has_icon: true,
		},
		{
			feed_ID: 16208159,
			site_ID: 61075908,
			site_URL: 'http://isleofmaynnr.wordpress.com',
			site_name: 'Isle of May National Nature Reserve',
			feed_URL: 'http://isleofmaynnr.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 81088128,
			site_ID: 144784298,
			site_URL: 'http://tranature.com',
			site_name: 'Tranature',
			feed_URL: 'http://tranature.com',
			has_icon: true,
		},
		{
			feed_ID: 106880699,
			site_ID: 179031061,
			site_URL: 'http://earthmothernaturelover.wordpress.com',
			site_name: 'Earth Mother Nature Lover',
			feed_URL: 'http://earthmothernaturelover.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 93708735,
			site_ID: 158320507,
			site_URL: 'https://scubahanknyc.com/',
			site_name: 'Scuba Hank NYC',
			feed_URL: 'http://scubahanknyc.com',
			has_icon: true,
		},
		{
			feed_ID: 165130456,
			site_ID: 237934129,
			site_URL: 'https://naturecentergb.org',
			site_name: 'Nature Center at Greenburgh',
			feed_URL: 'http://workable-support.flywheelsites.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 47864083,
			site_ID: 43646855,
			site_URL: 'https://stevecreek.com/',
			site_name: 'Steve Creek Wildlife Photography',
			feed_URL: 'http://stevecreek.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 159290362,
			site_ID: 190565878,
			site_URL: 'http://northwestnatureandhistory.wordpress.com',
			site_name: 'Northwest Nature and History',
			feed_URL: 'http://northwestnatureandhistory.co.uk',
			has_icon: true,
		},
	],
	future: [
		{
			feed_ID: 77936565,
			site_ID: 141327587,
			site_URL: 'https://bryanalexander.org/',
			site_name: 'Bryan Alexander',
			feed_URL: 'http://bryanalexander.org/feed',
			has_icon: false,
		},
		{
			feed_ID: 46138681,
			site_ID: 16638040,
			site_URL: 'https://frankdiana.net/',
			site_name: 'Reimagining the Future',
			feed_URL: 'http://frankdiana.net',
			has_icon: true,
		},
		{
			feed_ID: 388033,
			site_ID: 1011537,
			site_URL: 'https://thenextwavefutures.wordpress.com/',
			site_name: 'the next wave',
			feed_URL: 'http://thenextwavefutures.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 1430889,
			site_ID: 8522080,
			site_URL: 'https://lucept.com/',
			site_name: 'Lucept',
			feed_URL: 'http://lucept.com',
			has_icon: true,
		},
		{
			feed_ID: 66308872,
			site_ID: 101450901,
			site_URL: 'https://futurism.com/',
			site_name: 'Futurism',
			feed_URL: 'http://futurism.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 16857803,
			site_ID: 4183809,
			site_URL: 'https://singularityhub.com/',
			site_name: 'Singularity Hub',
			feed_URL: 'http://singularityhub.com/feed',
			has_icon: true,
		},
	],
	politics: [
		{
			feed_ID: 176595706,
			site_ID: 60064272,
			site_URL: 'http://policyandpoliticsjournal.wordpress.com',
			site_name: 'Policy & Politics Journal Blog',
			feed_URL: 'http://policyandpoliticsblog.com',
			has_icon: true,
		},
		{
			feed_ID: 34082885,
			site_ID: 85759654,
			site_URL: 'http://politicsandstuff.com',
			site_name: 'Politics and Other Stuff',
			feed_URL: 'http://politicsandstuff.com',
			has_icon: true,
		},
		{
			feed_ID: 144806355,
			site_ID: 205851186,
			site_URL: 'https://www.worldpoliticsreview.com/',
			site_name: 'World Politics Review',
			feed_URL: 'http://www.worldpoliticsreview.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 4860866,
			site_ID: 0,
			site_URL: 'https://politicalwire.com/',
			site_name: 'Political Wire',
			feed_URL: 'http://politicalwire.com',
			has_icon: true,
		},
		{
			feed_ID: 119663676,
			site_ID: 0,
			site_URL: 'https://www.politics.co.uk/',
			site_name: 'Politics.co.uk',
			feed_URL: 'http://www.politics.co.uk/feed',
			has_icon: false,
		},
		{
			feed_ID: 17459859,
			site_ID: 0,
			site_URL: 'https://www.factcheck.org/',
			site_name: 'FactCheck.org',
			feed_URL: 'http://FactCheck.org',
			has_icon: false,
		},
	],
	'climate-change': [
		{
			feed_ID: 173242201,
			site_ID: 247799493,
			site_URL: 'https://wattsupwiththat.com',
			site_name: 'Watts Up With That?',
			feed_URL: 'http://wattsupwiththat.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 1685478,
			site_ID: 21711903,
			site_URL: 'https://climateandsecurity.org',
			site_name: 'The Center for Climate & Security',
			feed_URL: 'http://climateandsecurity.org',
			has_icon: true,
		},
		{
			feed_ID: 50485365,
			site_ID: 113404966,
			site_URL: 'https://climatechangedispatch.com',
			site_name: 'Climate Change Dispatch',
			feed_URL: 'http://climatechangedispatch.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 42326459,
			site_ID: 0,
			site_URL: 'http://skepticalscience.com/feed.xml',
			site_name: 'Skeptical Science',
			feed_URL: 'http://skepticalscience.com/feed.xml',
			has_icon: false,
		},
		{
			feed_ID: 107813600,
			site_ID: 185804187,
			site_URL: 'https://yaleclimateconnections.org/',
			site_name: 'Yale Climate Connections',
			feed_URL: 'http://yaleclimateconnections.org/feed',
			has_icon: true,
		},
		{
			feed_ID: 40967167,
			site_ID: 0,
			site_URL: 'http://www.carbonbrief.org/feed',
			site_name: 'Carbon Brief',
			feed_URL: 'http://www.carbonbrief.org/feed',
			has_icon: false,
		},
		{
			feed_ID: 154160739,
			site_ID: 228474941,
			site_URL: 'https://insideclimatenews.org/',
			site_name: 'Inside Climate News',
			feed_URL: 'http://insideclimatenews.org/feed',
			has_icon: true,
		},
	],
	history: [
		{
			feed_ID: 95253203,
			site_ID: 161773962,
			site_URL: 'https://acoup.blog/',
			site_name: 'A Collection of Unmitigated Pedantry',
			feed_URL: 'http://acoup.blog',
			has_icon: true,
		},
		{
			feed_ID: 174361680,
			site_ID: 249134001,
			site_URL: 'https://how-to-history.com',
			site_name: 'How-to History',
			feed_URL: 'http://how-to-history.com',
			has_icon: true,
		},
		{
			feed_ID: 129254468,
			site_ID: 205334752,
			site_URL: 'https://awriterofhistory.com',
			site_name: 'A Writer of History',
			feed_URL: 'http://awriterofhistory.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 117803915,
			site_ID: 191886633,
			site_URL: 'https://historyofthegermans.com',
			site_name: 'History of the Germans Podcast',
			feed_URL: 'http://historyofthegermans.wpcomstaging.com',
			has_icon: true,
		},
		{
			feed_ID: 162175208,
			site_ID: 42179464,
			site_URL: 'https://historyofparliament.com',
			site_name: 'The History of Parliament',
			feed_URL: 'http://thehistoryofparliament.wpcomstaging.com',
			has_icon: true,
		},
		{
			feed_ID: 9002220,
			site_ID: 9563068,
			site_URL: 'http://www.thehistoryblog.com/',
			site_name: 'The History Blog',
			feed_URL: 'http://www.thehistoryblog.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 169767392,
			site_ID: 146466665,
			site_URL: 'http://davedoeshistory.org',
			site_name: 'DAVE DOES HISTORY',
			feed_URL: 'http://davedoeshistory.org',
			has_icon: true,
		},
		{
			feed_ID: 111739841,
			site_ID: 181957101,
			site_URL: 'https://livinglondonhistory.com/',
			site_name: 'Living London History',
			feed_URL: 'http://livinglondonhistory.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 144373922,
			site_ID: 218674381,
			site_URL: 'https://historyfacts.com/',
			site_name: 'History Facts',
			feed_URL: 'http://historyfacts.com/feed',
			has_icon: true,
		},
	],
	society: [
		{
			feed_ID: 110082608,
			site_ID: 177241961,
			site_URL: 'https://blog.ted.com/',
			site_name: 'TED Blog',
			feed_URL: 'http://blog.ted.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 48416491,
			site_ID: 0,
			site_URL: 'http://www.theatlantic.com/feed/all',
			site_name: 'The Atlantic',
			feed_URL: 'http://www.theatlantic.com/feed/all',
			has_icon: false,
		},
		{
			feed_ID: 38049686,
			site_ID: 0,
			site_URL: 'http://www.theguardian.com/us/rss',
			site_name: 'The Guardian',
			feed_URL: 'http://www.theguardian.com/us/rss',
			has_icon: true,
		},
		{
			feed_ID: 66598595,
			site_ID: 0,
			site_URL: 'http://www.theroot.com/rss',
			site_name: 'The Root',
			feed_URL: 'http://www.theroot.com/rss',
			has_icon: false,
		},
		{
			feed_ID: 14625,
			site_ID: 0,
			site_URL: 'http://www.newyorker.com/feed/rss',
			site_name: 'The New Yorker',
			feed_URL: 'http://www.newyorker.com',
			has_icon: false,
		},
	],
	culture: [
		{
			feed_ID: 107535240,
			site_ID: 179338616,
			site_URL: 'https://variety.com/',
			site_name: 'Variety',
			feed_URL: 'http://pmc-variety.go-vip.net/feed',
			has_icon: true,
		},
		{
			feed_ID: 161137721,
			site_ID: 235752437,
			site_URL: 'https://popculturemondays.com',
			site_name: 'Pop Culture Mondays',
			feed_URL: 'http://popculturemondays.wpcomstaging.com',
			has_icon: false,
		},
		{
			feed_ID: 55747131,
			site_ID: 118955609,
			site_URL: 'https://hyperallergic.com/',
			site_name: 'Hyperallergic',
			feed_URL: 'http://hyperallergic.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 5767946,
			site_ID: 3521287,
			site_URL: 'https://www.themarginalian.org/',
			site_name: 'The Marginalian',
			feed_URL: 'http://feeds.feedburner.com/brainpickings/rss',
			has_icon: true,
		},
		{
			feed_ID: 126767379,
			site_ID: 116583946,
			site_URL: 'http://popculturecosmos.wordpress.com',
			site_name: 'Pop Culture Cosmos',
			feed_URL: 'http://popculturecosmos.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 72583141,
			site_ID: 1769628,
			site_URL: 'http://adamnfinecup.com',
			site_name: 'A Damn Fine Cup of Culture',
			feed_URL: 'http://adamnfinecup.com',
			has_icon: true,
		},
		{
			feed_ID: 8949493,
			site_ID: 0,
			site_URL: 'https://www.dazeddigital.com/rss',
			site_name: 'Dazed',
			feed_URL: 'http://www.dazeddigital.com/rss',
			has_icon: false,
		},
		{
			feed_ID: 56317607,
			site_ID: 0,
			site_URL: 'http://www.juxtapoz.com/news/?format=feed&type=rss',
			site_name: 'Juxtapoz Magazine',
			feed_URL: 'http://www.juxtapoz.com/news/?format=feed&type=rss',
			has_icon: false,
		},
		{
			feed_ID: 10359,
			site_ID: 0,
			site_URL: 'http://pitchfork.com/feed/rss',
			site_name: 'Pitchfork',
			feed_URL: 'http://pitchfork.com',
			has_icon: false,
		},
		{
			feed_ID: 6645964,
			site_ID: 0,
			site_URL: 'https://www.openculture.com/',
			site_name: 'Open Culture',
			feed_URL: 'http://openculture.com',
			has_icon: true,
		},
	],
	philosophy: [
		{
			feed_ID: 75755245,
			site_ID: 62276702,
			site_URL: 'https://1000wordphilosophy.com/',
			site_name: '1000-Word Philosophy: An Introductory Anthology ',
			feed_URL: 'http://1000wordphilosophy.com',
			has_icon: true,
		},
		{
			feed_ID: 45806376,
			site_ID: 75932265,
			site_URL: 'https://dailynous.com/',
			site_name: 'Daily Nous',
			feed_URL: 'http://dailynous.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 56659902,
			site_ID: 31342497,
			site_URL: 'https://jewishphilosophyplace.com',
			site_name: 'jewish philosophy place',
			feed_URL: 'http://jewishphilosophyplace.com',
			has_icon: true,
		},
		{
			feed_ID: 16795041,
			site_ID: 61038653,
			site_URL: 'https://indianphilosophyblog.org',
			site_name: 'The Indian Philosophy Blog',
			feed_URL: 'http://indianphilosophyblog.org',
			has_icon: false,
		},
		{
			feed_ID: 91596664,
			site_ID: 155818645,
			site_URL: 'http://biopoliticalphilosophy.wordpress.com',
			site_name: 'BIOPOLITICAL PHILOSOPHY',
			feed_URL: 'http://biopoliticalphilosophy.com',
			has_icon: true,
		},
		{
			feed_ID: 9435358,
			site_ID: 46876232,
			site_URL: 'http://pittsburghphilosophy.wordpress.com',
			site_name: 'Pittsburgh Continental Philosophy Network',
			feed_URL: 'http://pittsburghphilosophy.com',
			has_icon: true,
		},
		{
			feed_ID: 25217327,
			site_ID: 0,
			site_URL: 'http://philosophynow.org/rss',
			site_name: 'Philosophy Now',
			feed_URL: 'http://philosophynow.org/rss',
			has_icon: true,
		},
		{
			feed_ID: 76453290,
			site_ID: 0,
			site_URL: 'https://partiallyexaminedlife.com/',
			site_name: 'The Partially Examined Life Philosophy Podcast',
			feed_URL: 'http://partiallyexaminedlife.com/feed',
			has_icon: true,
		},
	],
};
