import { CuratedBlogsList } from './index';

export const technologyBlogs: CuratedBlogsList = {
	gadgets: [
		{
			feed_ID: 100118377,
			site_ID: 166784358,
			site_URL: 'gadget.co.za',
			site_name: 'Gadget',
			feed_URL: 'http://gadget.co.za/feed',
			has_icon: false,
		},
		{
			feed_ID: 94842904,
			site_ID: 156670177,
			site_URL: 'hackaday.com',
			site_name: 'Hackaday',
			feed_URL: 'http://hackaday.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 94236820,
			site_ID: 155444975,
			site_URL: 'jabbareviews.com',
			site_name: 'Jabba Reviews',
			feed_URL: 'http://jabbareviews.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 143830506,
			site_ID: 220244849,
			site_URL: 'gadgetshubs.blog',
			site_name: 'Gadgets Hub',
			feed_URL: 'http://gadgetshubs.blog/feed',
			has_icon: true,
		},
		{
			feed_ID: 155451786,
			site_ID: 229720526,
			site_URL: 'cutetechgadgets.com',
			site_name: 'Cute Tech Gadgets',
			feed_URL: 'http://cutetechgadgets.com',
			has_icon: true,
		},
		{
			feed_ID: 153964960,
			site_ID: 228278685,
			site_URL: 'tech-guy-gadgets.com',
			site_name: 'Tech Guy Gadgets',
			feed_URL: 'http://tech-guy-gadgets.com',
			has_icon: true,
		},
	],
	software: [
		{
			feed_ID: 85143697,
			site_ID: 147945108,
			site_URL: 'engineering.fb.com',
			site_name: 'Engineering at Meta',
			feed_URL: 'http://code.fb.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 38485838,
			site_ID: 46336996,
			site_URL: 'damienbod.com',
			site_name: 'Software Engineering',
			feed_URL: 'http://damienbod.com',
			has_icon: true,
		},
		{
			feed_ID: 109786548,
			site_ID: 121784873,
			site_URL: 'ilapitan.com',
			site_name: 'Software Engineering Blog',
			feed_URL: 'http://ilapitan.com',
			has_icon: true,
		},
		{
			feed_ID: 80004389,
			site_ID: 80991526,
			site_URL: 'spyboy.blog',
			site_name: 'Spyboy blog',
			feed_URL: 'http://spyboy.blog',
			has_icon: true,
		},
		{
			feed_ID: 57622406,
			site_ID: 120870102,
			site_URL: 'polimetlase.wordpress.com',
			site_name: 'Software Engineering',
			feed_URL: 'http://polimetlase.wordpress.com',
			has_icon: true,
		},
	],
	technology: [
		{
			feed_ID: 111100674,
			site_ID: 136296444,
			site_URL: 'techcrunch.com',
			site_name: 'TechCrunch',
			feed_URL: 'http://techcrunch.com',
			has_icon: true,
		},
		{
			feed_ID: 43054659,
			site_ID: 105764647,
			site_URL: 'techandlearning.wordpress.com',
			site_name: 'Technology and Learning',
			feed_URL: 'http://techandlearning.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 107270245,
			site_ID: 172986898,
			site_URL: 'technologyreview.com',
			site_name: 'MIT Technology Review',
			feed_URL: 'http://wp.technologyreview.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 117374,
			site_ID: 15451510,
			site_URL: 'richardcoyne.com',
			site_name: 'Reflections on Technology, Media & Culture',
			feed_URL: 'http://richardcoyne.com',
			has_icon: false,
		},
		{
			feed_ID: 68503995,
			site_ID: 130369440,
			site_URL: 'techexplorist.com',
			site_name: 'Tech Explorist',
			feed_URL: 'http://www.techexplorist.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 47978431,
			site_ID: 13261070,
			site_URL: 'wjlta.com',
			site_name: 'Washington Journal of Law, Technology & Arts',
			feed_URL: 'http://wjlta.com',
			has_icon: true,
		},
	],
	design: [
		{
			feed_ID: 47166615,
			site_ID: 0,
			site_URL: 'design-milk.com',
			site_name: 'Design Milk',
			feed_URL: 'http://design-milk.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 143967848,
			site_ID: 182890486,
			site_URL: 'automattic.design',
			site_name: 'Automattic Design',
			feed_URL: 'http://automattic.design',
			has_icon: true,
		},
		{
			feed_ID: 35899213,
			site_ID: 31759332,
			site_URL: 'make.wordpress.org/design',
			site_name: 'Make WordPress Design',
			feed_URL: 'https://make.wordpress.org/design/feed',
			has_icon: false,
		},
		{
			feed_ID: 152724172,
			site_ID: 227043043,
			site_URL: 'zeldman.com',
			site_name: 'Zeldman on Web and Interaction Design',
			feed_URL: 'http://zeldmanproduction.wpcomstaging.com',
			has_icon: false,
		},
		{
			feed_ID: 542097,
			site_ID: 10273182,
			site_URL: 'researchdesignreview.com',
			site_name: 'Research Design Review',
			feed_URL: 'http://researchdesignreview.com',
			has_icon: true,
		},
		{
			feed_ID: 77846615,
			site_ID: 6604224,
			site_URL: 'kittnoir.wordpress.com',
			site_name: 'Kitt Noir',
			feed_URL: 'http://kittnoir.wordpress.com',
			has_icon: true,
		},
	],
	'artificial-intelligence': [
		{
			feed_ID: 33377745,
			site_ID: 0,
			site_URL: 'kdnuggets.com',
			site_name: 'KDnuggets',
			feed_URL: 'http://www.kdnuggets.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 71548402,
			site_ID: 0,
			site_URL: 'bair.berkeley.edu/blog',
			site_name: 'The Berkeley Artificial Intelligence Research Blog',
			feed_URL: 'http://bair.berkeley.edu/blog/feed.xml',
			has_icon: false,
		},
		{
			feed_ID: 77658316,
			site_ID: 0,
			site_URL: 'towardsdatascience.com',
			site_name: 'Towards Data Science',
			feed_URL: 'http://towardsdatascience.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 144168485,
			site_ID: 219373168,
			site_URL: 'talktweets.com',
			site_name: 'TalkTweets',
			feed_URL: 'http://talktweets.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 159917035,
			site_ID: 234484554,
			site_URL: 'pivot-to-ai.com',
			site_name: 'Pivot to AI',
			feed_URL: 'http://pivot-to-ai.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 77153121,
			site_ID: 136078298,
			site_URL: 'franksworld.com',
			site_name: "Frank's World of Data Science & AI",
			feed_URL: 'http://www.franksworld.com/feed',
			has_icon: false,
		},
	],
	cybersecurity: [
		{
			feed_ID: 107953449,
			site_ID: 0,
			site_URL: 'grahamcluley.com/writing',
			site_name: 'Graham Cluley',
			feed_URL: 'http://grahamcluley.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 5370133,
			site_ID: 0,
			site_URL: 'krebsonsecurity.com',
			site_name: 'Krebs on Security',
			feed_URL: 'http://krebsonsecurity.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 145035878,
			site_ID: 0,
			site_URL: 'darkreading.com',
			site_name: 'darkreading',
			feed_URL: 'http://www.darkreading.com/rss.xml',
			has_icon: false,
		},
		{
			feed_ID: 46075821,
			site_ID: 70550726,
			site_URL: 'latesthackingnews.com',
			site_name: 'Latest Hacking News',
			feed_URL: 'http://www.latesthackingnews.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 124628317,
			site_ID: 0,
			site_URL: 'kitploit.com',
			site_name: 'KitPloit',
			feed_URL: 'http://www.kitploit.com/feeds/posts/default',
			has_icon: false,
		},
		{
			feed_ID: 2427031,
			site_ID: 33903376,
			site_URL: 'cybersecurityupdate.wordpress.com',
			site_name: 'cybersecurity update',
			feed_URL: 'http://cybersecurityupdate.wordpress.com',
			has_icon: false,
		},
	],
	gaming: [
		{
			feed_ID: 1268641,
			site_ID: 0,
			site_URL: 'kotaku.com',
			site_name: 'Kotaku',
			feed_URL: 'http://kotaku.com',
			has_icon: false,
		},
		{
			feed_ID: 5504178,
			site_ID: 0,
			site_URL: 'vg247.com',
			site_name: 'VG247',
			feed_URL: 'http://www.vg247.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 102691389,
			site_ID: 62358124,
			site_URL: 'realwomenofgaming.com',
			site_name: 'Real Women of Gaming',
			feed_URL: 'http://realwomenofgaming.com',
			has_icon: true,
		},
		{
			feed_ID: 57567198,
			site_ID: 120817338,
			site_URL: 'cannibalhalflinggaming.com',
			site_name: 'Cannibal Halfling Gaming',
			feed_URL: 'http://cannibalhalflinggaming.com',
			has_icon: true,
		},
		{
			feed_ID: 155782255,
			site_ID: 130248864,
			site_URL: 'saviorgaming.blog',
			site_name: 'Savior Gaming',
			feed_URL: 'http://saviorgaming.blog',
			has_icon: true,
		},
		{
			feed_ID: 32769,
			site_ID: 411212,
			site_URL: 'tagn.wordpress.com',
			site_name: 'The Ancient Gaming Noob',
			feed_URL: 'http://tagn.wordpress.com',
			has_icon: true,
		},
	],
	cryptocurrency: [
		{
			feed_ID: 107681387,
			site_ID: 0,
			site_URL: 'cryptopotato.com',
			site_name: 'CryptoPotato',
			feed_URL: 'http://cryptopotato.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 96239936,
			site_ID: 0,
			site_URL: 'ambcrypto.com',
			site_name: 'AMBCrypto',
			feed_URL: 'http://ambcrypto.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 36224119,
			site_ID: 0,
			site_URL: 'cointelegraph.com',
			site_name: 'Cointelegraph News',
			feed_URL: 'http://cointelegraph.com/rss',
			has_icon: true,
		},
		{
			feed_ID: 146281302,
			site_ID: 197127043,
			site_URL: 'sapphirecrypto.org',
			site_name: 'Sapphire Crypto',
			feed_URL: 'http://sapphirecrypto.org',
			has_icon: true,
		},
		{
			feed_ID: 126992749,
			site_ID: 202999325,
			site_URL: 'cryptonewsland.com',
			site_name: 'Crypto News Land',
			feed_URL: 'http://cryptonewsland.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 30735316,
			site_ID: 69979306,
			site_URL: '247cryptonews.com',
			site_name: '24/7 Crypto News',
			feed_URL: 'http://247cryptonews.com',
			has_icon: false,
		},
	],
	science: [
		{
			feed_ID: 2863606,
			site_ID: 0,
			site_URL: 'newscientist.com',
			site_name: 'New Scientist',
			feed_URL: 'http://www.newscientist.com',
			has_icon: true,
		},
		{
			feed_ID: 2018830,
			site_ID: 0,
			site_URL: 'scientificamerican.com',
			site_name: 'Scientific American',
			feed_URL: 'http://www.scientificamerican.com',
			has_icon: false,
		},
		{
			feed_ID: 99248196,
			site_ID: 66864929,
			site_URL: 'explainingscience.org',
			site_name: 'Explaining Science',
			feed_URL: 'http://explainingscience.org',
			has_icon: true,
		},
		{
			feed_ID: 102059118,
			site_ID: 72889146,
			site_URL: 'connectingwithscience.org',
			site_name: 'Connecting with Science',
			feed_URL: 'http://connectingwithscience.org',
			has_icon: true,
		},
		{
			feed_ID: 13096676,
			site_ID: 66008408,
			site_URL: 'neurosciencenews.com',
			site_name: 'Neuroscience News',
			feed_URL: 'http://neurosciencenews.com/feed',
			has_icon: true,
		},
	],
};
