import { CuratedBlogsList } from './index';

export const technologyBlogs: CuratedBlogsList = {
	gadgets: [
		{
			feed_ID: 94842904,
			site_ID: 156670177,
			site_URL: 'hackaday.com',
			site_name: 'Hackaday',
			feed_URL: 'http://hackaday.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 100118377,
			site_ID: 166784358,
			site_URL: 'gadget.co.za',
			site_name: 'Gadget',
			feed_URL: 'http://gadget.co.za/feed',
			has_icon: false,
		},
		{
			feed_ID: 155451786,
			site_ID: 229720526,
			site_URL: 'cutetechgadgets.com',
			site_name: 'Cute Tech Gadgets',
			feed_URL: 'http://cutetechgadgets.com',
			has_icon: true,
		},
		{
			feed_ID: 53749793,
			site_ID: 116900052,
			site_URL: 'https://gauginggadgets.com',
			site_name: 'Gauging Gadgets',
			feed_URL: 'http://gauginggadgets.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 153964960,
			site_ID: 228278685,
			site_URL: 'tech-guy-gadgets.com',
			site_name: 'Tech Guy Gadgets',
			feed_URL: 'http://tech-guy-gadgets.com',
			has_icon: true,
		},
	],
	software: [
		{
			feed_ID: 80004389,
			site_ID: 80991526,
			site_URL: 'spyboy.blog',
			site_name: 'Spyboy blog',
			feed_URL: 'http://spyboy.blog',
			has_icon: true,
		},
		{
			feed_ID: 38485838,
			site_ID: 46336996,
			site_URL: 'damienbod.com',
			site_name: 'Software Engineering',
			feed_URL: 'http://damienbod.com',
			has_icon: true,
		},
		{
			feed_ID: 164741608,
			site_ID: 239592469,
			site_URL: 'https://terriblesoftware.org',
			site_name: 'Terrible Software',
			feed_URL: 'http://terriblesoftware.org',
			has_icon: true,
		},
		{
			feed_ID: 109786548,
			site_ID: 121784873,
			site_URL: 'ilapitan.com',
			site_name: 'Software Engineering Blog',
			feed_URL: 'http://ilapitan.com',
			has_icon: true,
		},
		{
			feed_ID: 9891486,
			site_ID: 9510434,
			site_URL: 'https://oss.cs.fau.de',
			site_name: 'Professorship for Open-Source Software',
			feed_URL: 'http://osr.cs.fau.de',
			has_icon: true,
		},
		{
			feed_ID: 85143697,
			site_ID: 147945108,
			site_URL: 'engineering.fb.com',
			site_name: 'Engineering at Meta',
			feed_URL: 'http://code.fb.com/feed',
			has_icon: false,
		},
	],
	technology: [
		{
			feed_ID: 111100674,
			site_ID: 136296444,
			site_URL: 'techcrunch.com',
			site_name: 'TechCrunch',
			feed_URL: 'http://techcrunch.com',
			has_icon: true,
		},
		{
			feed_ID: 117374,
			site_ID: 15451510,
			site_URL: 'richardcoyne.com',
			site_name: 'Reflections on Technology, Media & Culture',
			feed_URL: 'http://richardcoyne.com',
			has_icon: true,
		},
		{
			feed_ID: 112355958,
			site_ID: 180059651,
			site_URL: 'http://technologyandbusinessnews.wordpress.com',
			site_name: 'Technology & Business News',
			feed_URL: 'http://technologyandbusinessnews.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 68503995,
			site_ID: 130369440,
			site_URL: 'techexplorist.com',
			site_name: 'Tech Explorist',
			feed_URL: 'http://www.techexplorist.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 43054659,
			site_ID: 105764647,
			site_URL: 'techandlearning.wordpress.com',
			site_name: 'Technology and Learning',
			feed_URL: 'http://techandlearning.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 47978431,
			site_ID: 13261070,
			site_URL: 'wjlta.com',
			site_name: 'Washington Journal of Law, Technology & Arts',
			feed_URL: 'http://wjlta.com',
			has_icon: true,
		},
		{
			feed_ID: 107270245,
			site_ID: 172986898,
			site_URL: 'technologyreview.com',
			site_name: 'MIT Technology Review',
			feed_URL: 'http://wp.technologyreview.com/feed',
			has_icon: true,
		},
	],
	design: [
		{
			feed_ID: 143967848,
			site_ID: 182890486,
			site_URL: 'automattic.design',
			site_name: 'Automattic Design',
			feed_URL: 'http://automattic.design',
			has_icon: true,
		},
		{
			feed_ID: 77846615,
			site_ID: 6604224,
			site_URL: 'kittnoir.wordpress.com',
			site_name: 'Kitt Noir',
			feed_URL: 'http://kittnoir.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 152724172,
			site_ID: 227043043,
			site_URL: 'zeldman.com',
			site_name: 'Zeldman on Web and Interaction Design',
			feed_URL: 'http://zeldmanproduction.wpcomstaging.com',
			has_icon: true,
		},
		{
			feed_ID: 35899213,
			site_ID: 31759332,
			site_URL: 'make.wordpress.org/design',
			site_name: 'Make WordPress Design',
			feed_URL: 'https://make.wordpress.org/design/feed',
			has_icon: true,
		},
		{
			feed_ID: 35565593,
			site_ID: 92431059,
			site_URL: 'https://stamptasticdesigns.com',
			site_name: 'Lynn Dunn - Stamptastic Designs LLC',
			feed_URL: 'http://stamptasticdesigns.com',
			has_icon: true,
		},
		{
			feed_ID: 29821017,
			site_ID: 71044980,
			site_URL: 'https://www.cathyzielske.com',
			site_name: 'CZ Design',
			feed_URL: 'http://www.cathyzielske.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 542097,
			site_ID: 10273182,
			site_URL: 'researchdesignreview.com',
			site_name: 'Research Design Review',
			feed_URL: 'http://researchdesignreview.com',
			has_icon: true,
		},
		{
			feed_ID: 23672109,
			site_ID: 47522427,
			site_URL: 'http://cocolapinedesign.com',
			site_name: 'COCO LAPINE DESIGN',
			feed_URL: 'http://cocolapinedesign.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 55878563,
			site_ID: 92870702,
			site_URL: 'https://encyclopedia.design',
			site_name: 'Encyclopedia of Design',
			feed_URL: 'http://baileystreetdesign.com',
			has_icon: false,
		},
	],
	'artificial-intelligence': [
		{
			feed_ID: 159917035,
			site_ID: 234484554,
			site_URL: 'pivot-to-ai.com',
			site_name: 'Pivot to AI',
			feed_URL: 'http://pivot-to-ai.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 33377745,
			site_ID: 0,
			site_URL: 'kdnuggets.com',
			site_name: 'KDnuggets',
			feed_URL: 'http://www.kdnuggets.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 77153121,
			site_ID: 136078298,
			site_URL: 'franksworld.com',
			site_name: "Frank's World of Data Science & AI",
			feed_URL: 'http://www.franksworld.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 176794937,
			site_ID: 51022764,
			site_URL: 'http://pithycyborg.wordpress.com',
			site_name: 'Pithy Cyborg | AI News Made Simple | On WordPress!',
			feed_URL: 'http://pithycyborg.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 71548402,
			site_ID: 0,
			site_URL: 'bair.berkeley.edu/blog',
			site_name: 'The Berkeley Artificial Intelligence Research Blog',
			feed_URL: 'http://bair.berkeley.edu/blog/feed.xml',
			has_icon: false,
		},
		{
			feed_ID: 77658316,
			site_ID: 0,
			site_URL: 'towardsdatascience.com',
			site_name: 'Towards Data Science',
			feed_URL: 'http://towardsdatascience.com/feed',
			has_icon: true,
		},
	],
	cybersecurity: [
		{
			feed_ID: 156197069,
			site_ID: 221720208,
			site_URL: 'http://wpscan.com',
			site_name: 'WPScan',
			feed_URL: 'http://wpscan.com',
			has_icon: true,
		},
		{
			feed_ID: 170243923,
			site_ID: 245276265,
			site_URL: 'http://fintech-cyber.news',
			site_name: 'Fintech Cyber Weekly',
			feed_URL: 'http://fintech-cyber.news',
			has_icon: true,
		},
		{
			feed_ID: 46075821,
			site_ID: 70550726,
			site_URL: 'latesthackingnews.com',
			site_name: 'Latest Hacking News',
			feed_URL: 'http://www.latesthackingnews.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 80004389,
			site_ID: 80991526,
			site_URL: 'http://spyboy.blog',
			site_name: 'Spyboy blog',
			feed_URL: 'http://spyboy.blog',
			has_icon: true,
		},
		{
			feed_ID: 86836089,
			site_ID: 150943940,
			site_URL: 'https://thecyberbeat.com',
			site_name: 'The Cyber Beat',
			feed_URL: 'http://thecyberbeat.com',
			has_icon: true,
		},
		{
			feed_ID: 5370133,
			site_ID: 0,
			site_URL: 'krebsonsecurity.com',
			site_name: 'Krebs on Security',
			feed_URL: 'http://krebsonsecurity.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 145035878,
			site_ID: 0,
			site_URL: 'darkreading.com',
			site_name: 'darkreading',
			feed_URL: 'http://www.darkreading.com/rss.xml',
			has_icon: false,
		},
		{
			feed_ID: 107953449,
			site_ID: 0,
			site_URL: 'grahamcluley.com/writing',
			site_name: 'Graham Cluley',
			feed_URL: 'http://grahamcluley.com/feed',
			has_icon: true,
		},
	],
	gaming: [
		{
			feed_ID: 32769,
			site_ID: 411212,
			site_URL: 'tagn.wordpress.com',
			site_name: 'The Ancient Gaming Noob',
			feed_URL: 'http://tagn.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 155782255,
			site_ID: 130248864,
			site_URL: 'saviorgaming.blog',
			site_name: 'Savior Gaming',
			feed_URL: 'http://saviorgaming.blog',
			has_icon: true,
		},
		{
			feed_ID: 102691389,
			site_ID: 62358124,
			site_URL: 'realwomenofgaming.com',
			site_name: 'Real Women of Gaming',
			feed_URL: 'http://realwomenofgaming.com',
			has_icon: true,
		},
		{
			feed_ID: 57567198,
			site_ID: 120817338,
			site_URL: 'cannibalhalflinggaming.com',
			site_name: 'Cannibal Halfling Gaming',
			feed_URL: 'http://cannibalhalflinggaming.com',
			has_icon: true,
		},
		{
			feed_ID: 98146593,
			site_ID: 98888289,
			site_URL: 'http://gamingheartscollection.net',
			site_name: 'Gaming Hearts Collection',
			feed_URL: 'http://gamingheartscollection.net',
			has_icon: true,
		},
		{
			feed_ID: 44673496,
			site_ID: 106613825,
			site_URL: 'https://seafoamgaming.com',
			site_name: 'Seafoam Gaming',
			feed_URL: 'http://seafoamgaming.com',
			has_icon: true,
		},
		{
			feed_ID: 5504178,
			site_ID: 0,
			site_URL: 'vg247.com',
			site_name: 'VG247',
			feed_URL: 'http://www.vg247.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 39651147,
			site_ID: 102112870,
			site_URL: 'http://cynicalgamingblog.wordpress.com',
			site_name: 'Cynical Gaming Blog',
			feed_URL: 'http://cynicalgamingblog.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 169785451,
			site_ID: 177197671,
			site_URL: 'https://xynodegaming.com',
			site_name: 'Xynode Gaming',
			feed_URL: 'http://xynodegaming.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 1268641,
			site_ID: 0,
			site_URL: 'kotaku.com',
			site_name: 'Kotaku',
			feed_URL: 'http://kotaku.com',
			has_icon: false,
		},
	],
	cryptocurrency: [
		{
			feed_ID: 96484837,
			site_ID: 106238743,
			site_URL: 'http://succeedonlinetips.wordpress.com',
			site_name: 'Crypto-Corner',
			feed_URL: 'http://crypto-corner.com',
			has_icon: true,
		},
		{
			feed_ID: 104087610,
			site_ID: 173916256,
			site_URL: 'https://internetwealthresource.com',
			site_name: 'Internet Wealth Resource',
			feed_URL: 'http://internetwealthresource.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 146281302,
			site_ID: 197127043,
			site_URL: 'sapphirecrypto.org',
			site_name: 'Sapphire Crypto',
			feed_URL: 'http://sapphirecrypto.org',
			has_icon: true,
		},
		{
			feed_ID: 126992749,
			site_ID: 202999325,
			site_URL: 'cryptonewsland.com',
			site_name: 'Crypto News Land',
			feed_URL: 'http://cryptonewsland.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 36224119,
			site_ID: 0,
			site_URL: 'cointelegraph.com',
			site_name: 'Cointelegraph News',
			feed_URL: 'http://cointelegraph.com/rss',
			has_icon: true,
		},
	],
	science: [
		{
			feed_ID: 13096676,
			site_ID: 66008408,
			site_URL: 'neurosciencenews.com',
			site_name: 'Neuroscience News',
			feed_URL: 'http://neurosciencenews.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 99248196,
			site_ID: 66864929,
			site_URL: 'explainingscience.org',
			site_name: 'Explaining Science',
			feed_URL: 'http://explainingscience.org',
			has_icon: true,
		},
		{
			feed_ID: 50764,
			site_ID: 6936594,
			site_URL: 'http://scottlocklin.wordpress.com',
			site_name: 'Locklin on science',
			feed_URL: 'http://scottlocklin.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 91104997,
			site_ID: 123172266,
			site_URL: 'http://myfusimotors.wordpress.com',
			site_name: 'Scents of Science',
			feed_URL: 'http://myfusimotors.com',
			has_icon: true,
		},
		{
			feed_ID: 266650,
			site_ID: 4146307,
			site_URL: 'http://grokscience.wordpress.com',
			site_name: 'Groks Science Radio Show and Podcast',
			feed_URL: 'http://grokscience.wordpress.com',
			has_icon: true,
		},
		{
			feed_ID: 102059118,
			site_ID: 72889146,
			site_URL: 'connectingwithscience.org',
			site_name: 'Connecting with Science',
			feed_URL: 'http://connectingwithscience.org',
			has_icon: true,
		},
		{
			feed_ID: 162932267,
			site_ID: 233338632,
			site_URL: 'https://www.popsci.com',
			site_name: 'Popular Science',
			feed_URL: 'http://www.popsci.com/feed',
			has_icon: false,
		},
		{
			feed_ID: 95069826,
			site_ID: 161469808,
			site_URL: 'https://www.sciencefix.co.uk',
			site_name: 'Danny Nics Science Fix',
			feed_URL: 'http://sciencefix.co.uk/feed',
			has_icon: true,
		},
		{
			feed_ID: 149099498,
			site_ID: 145599608,
			site_URL: 'https://geologyscience.com',
			site_name: 'Geology Science',
			feed_URL: 'http://geologyscience.com/feed',
			has_icon: true,
		},
		{
			feed_ID: 2018830,
			site_ID: 0,
			site_URL: 'scientificamerican.com',
			site_name: 'Scientific American',
			feed_URL: 'http://www.scientificamerican.com',
			has_icon: false,
		},
		{
			feed_ID: 2863606,
			site_ID: 0,
			site_URL: 'newscientist.com',
			site_name: 'New Scientist',
			feed_URL: 'http://www.newscientist.com',
			has_icon: true,
		},
	],
};
