/**
 * Module variables
 */
export const action = {
	INVITE_ACCEPTED: 'INVITE_ACCEPTED',
	RECEIVE_INVITE_ACCEPTED_SUCCESS: 'RECEIVE_INVITE_ACCEPTED_SUCCESS',
	RECEIVE_INVITE_ACCEPTED_ERROR: 'RECEIVE_INVITE_ACCEPTED_ERROR',
	SENDING_INVITES: 'SENDING_INVITES',
	RECEIVE_SENDING_INVITES_ERROR: 'RECEIVE_SENDING_INVITES_ERROR',
	RECEIVE_SENDING_INVITES_SUCCESS: 'RECEIVE_SENDING_INVITES_SUCCESS',
	CREATE_INVITE_VALIDATION: 'CREATE_INVITE_VALIDATION',
	RECEIVE_CREATE_INVITE_VALIDATION_ERROR: 'RECEIVE_CREATE_INVITE_VALIDATION_ERROR',
	RECEIVE_CREATE_INVITE_VALIDATION_SUCCESS: 'RECEIVE_CREATE_INVITE_VALIDATION_SUCCESS',
};
