/**
 * Module variables
 */
export const action = {
	INVITE_ACCEPTED: 'INVITE_ACCEPTED',
	RECEIVE_INVITE_ACCEPTED_SUCCESS: 'RECEIVE_INVITE_ACCEPTED_SUCCESS',
	RECEIVE_INVITE_ACCEPTED_ERROR: 'RECEIVE_INVITE_ACCEPTED_ERROR',
};
