/**
 * External dependencies
 */
import React, { Component, PropTypes } from 'react';
import { pick } from 'lodash';
import moment from 'moment';

/**
 * Internal dependencies
 */
import Card from 'components/card';
import FormFieldset from 'components/forms/form-fieldset';
import FormLabel from 'components/forms/form-label';
import FormSettingExplanation from 'components/forms/form-setting-explanation';
import FormTextInput from 'components/forms/form-text-input';
import FormToggle from 'components/forms/form-toggle/compact';
import SectionHeader from 'components/section-header';
import WrapSettingsForm from '../wrap-settings-form';

class DebugTab extends Component {
	static propTypes = {
		fields: PropTypes.object,
		translate: PropTypes.func.isRequired,
	};

	static defaultProps = {
		fields: {},
	};

	render() {
		const {
			fields: {
				wp_super_cache_debug,
				wp_cache_debug_ip,
				wp_super_cache_comments,
				wp_super_cache_front_page_check,
				wp_super_cache_front_page_clear,
				wp_super_cache_front_page_text,
				wp_super_cache_front_page_notification,
			},
			handleAutosavingToggle,
			handleChange,
			isRequesting,
			isSaving,
			translate,
		} = this.props;

		return (
			<div>
				<SectionHeader
					label={ translate( 'Debug' ) }>
				</SectionHeader>
				<Card>
					<form>
						<FormFieldset>
							<FormToggle
								checked={ !! wp_super_cache_debug }
								disabled={ isRequesting || isSaving }
								onChange={ handleAutosavingToggle( 'wp_super_cache_debug' ) }>
								<span>
									{ translate( 'Enable Debugging' ) }
								</span>
							</FormToggle>
						</FormFieldset>
						<div className="wp-super-cache__debug-fieldsets">
							<FormFieldset>
								<FormLabel htmlFor="ipAddress">
									{ translate( 'IP Address' ) }
								</FormLabel>
								<FormTextInput
									disabled={ isRequesting || isSaving || ! wp_super_cache_debug }
									id="ipAddress"
									onChange={ handleChange( 'wp_cache_debug_ip' ) }
									value={ wp_cache_debug_ip || '' } />
								<FormSettingExplanation>
									{ translate(
										'(only log requests from this IP address. Your IP is %(ipAddress)s)',
										{
											args: { ipAddress: '1.2.3.4' }
										}
									) }
								</FormSettingExplanation>
							</FormFieldset>
							<FormFieldset>
								<FormToggle
									checked={ !! wp_super_cache_comments }
									disabled={ isRequesting || isSaving || ! wp_super_cache_debug }
									onChange={ handleAutosavingToggle( 'wp_super_cache_comments' ) }>
									<span>
										{ translate( 'Cache Status Messages' ) }
									</span>
								</FormToggle>
								<FormSettingExplanation>
									{
										translate(
											'Display comments at the end of every page like this:' +
											'{{pre}}' +
											'<!-- Dynamic page generated in 0.450 seconds. -->\n' +
											'<!-- Cached page generated by WP-Super-Cache on %(date)s -->\n' +
											'<!-- super cache -->' +
											'{{/pre}}',
											{
												args: { date: moment().utc().format( 'YYYY-MM-DD HH:mm:ss' ) },
												components: { pre: <pre /> },
											}
										)
									}
								</FormSettingExplanation>
							</FormFieldset>
						</div>
					</form>
				</Card>
				<SectionHeader
					label={ translate( 'Advanced' ) }>
				</SectionHeader>
				<Card>
					<p>{ translate( 'In very rare cases two problems may arise on some blogs:' ) }</p>
					<ol>
						<li>{ translate( 'The front page may start downloading as a zip file.' ) }</li>
						<li>{ translate(
							'The wrong page is occasionally cached as the front page ' +
							'if your blog uses a static front page and the permalink structure ' +
							'is {{em}}%(permalinkStructure)s{{/em}}.',
							{
								args: { permalinkStructure: '/%category%/%postname%/' },
								components: { em: <em /> }
							}
						 ) }</li>
					</ol>
					<p>
						{ translate(
							'I\'m 99% certain that they aren\'t bugs in WP Super Cache and they only ' +
							'happen in very rare cases but you can run a simple check once every 5 minutes ' +
							'to verify that your site is ok if you\'re worried. You will be emailed if ' +
							'there is a problem.'
						) }
					</p>
					<form>
						<FormFieldset>
							<FormToggle
								checked={ !! wp_super_cache_front_page_check }
								disabled={ isRequesting || isSaving || ! wp_super_cache_debug }
								onChange={ handleAutosavingToggle( 'wp_super_cache_front_page_check' ) }>
								<span>
									{ translate( 'Check front page every 5 minutes.' ) }
								</span>
							</FormToggle>
						</FormFieldset>
						<FormFieldset>
							<FormLabel htmlFor="frontPageText">
								{ translate( 'Front page text' ) }
							</FormLabel>
							<FormTextInput
								disabled={ isRequesting || isSaving || ! wp_super_cache_debug }
								id="frontPageText"
								onChange={ handleChange( 'wp_super_cache_front_page_text' ) }
								value={ wp_super_cache_front_page_text || '' } />
							<FormSettingExplanation>
								{ translate(
									'Text to search for on your front page. If this text is missing, ' +
									'the cache will be cleared. Leave blank to disable.'
								) }
							</FormSettingExplanation>
						</FormFieldset>
						<FormFieldset>
							<FormToggle
								checked={ !! wp_super_cache_front_page_clear }
								disabled={ isRequesting || isSaving || ! wp_super_cache_debug }
								onChange={ handleAutosavingToggle( 'wp_super_cache_front_page_clear' ) }>
								<span>
									{ translate( 'Clear cache on error.' ) }
								</span>
							</FormToggle>
						</FormFieldset>
						<FormFieldset>
							<FormToggle
								checked={ !! wp_super_cache_front_page_notification }
								disabled={ isRequesting || isSaving || ! wp_super_cache_debug }
								onChange={ handleAutosavingToggle( 'wp_super_cache_front_page_notification' ) }>
								<span>
									{ translate( 'Email the blog admin when checks are made. (useful for testing)' ) }
								</span>
							</FormToggle>
						</FormFieldset>
					</form>
				</Card>
			</div>
		);
	}
}

const getFormSettings = settings => {
	return pick( settings, [
		'wp_super_cache_debug',
		'wp_cache_debug_ip',
		'wp_super_cache_comments',
		'wp_super_cache_front_page_check',
		'wp_super_cache_front_page_clear',
		'wp_super_cache_front_page_text',
		'wp_super_cache_front_page_notification',
	] );
};

export default WrapSettingsForm( getFormSettings )( DebugTab );
