export const DEFAULT_THEME_QUERY = {
	search: '',
	tier: '',
	filter: '',
	number: 20,
	offset: 0,
	page: 1
};

export const PREMIUM_SQUARED_THEMES = [
	'premium/headlines',
	'premium/crisp',
	'premium/fresh-news',
	'premium/delicious-magazine',
	'premium/chapters',
	'premium/bold-news',
	'premium/currents',
	'premium/hustle-express',
	'premium/scrollider-express',
	'premium/magnate-express',
	'premium/standard',
	'premium/basic-maths',
	'premium/pretty-young-thing',
	'premium/tapestry',
	'premium/lifestyle',
	'premium/minimum',
	'premium/eight',
	'premium/magazine',
	'premium/elemin',
	'premium/funki',
	'premium/modern-news',
	'premium/newsy',
	'premium/thememin',
	'premium/just-desserts',
	'premium/vintage-kitchen',
	'premium/everyday',
	'premium/a-simpler-time',
	'premium/blog-simple',
	'premium/petite-melodies',
	'premium/the-great-adventure',
	'premium/pinboard',
	'premium/simfo',
	'premium/further',
	'premium/little-story',
	'premium/bon-vivant',
	'premium/vagabond',
	'premium/flora-and-fauna',
	'premium/wire',
	'premium/forefront',
	'premium/inspiration-laboratory',
	'premium/nurture',
	'premium/the-parisian',
	'premium/poly',
	'premium/sixteen-nine',
	'premium/espresso',
	'premium/veeva',
	'premium/pressly',
	'premium/mood',
	'premium/on-a-whim',
	'premium/luscious'
];
