module.exports.action = {
	ACTION_RECEIVE_READER_LIST_TAGS: 'ACTION_RECEIVE_READER_LIST_TAGS',
	ACTION_RECEIVE_READER_LIST_TAGS_ERROR: 'ACTION_RECEIVE_READER_LIST_TAGS_ERROR',
	ACTION_FETCH_READER_LIST_TAGS: 'ACTION_FETCH_READER_LIST_TAGS',
	ACTION_FETCH_READER_LIST_TAGS_COMPLETE: 'ACTION_FETCH_READER_LIST_TAGS_COMPLETE'
};
