export const CHECK_YOUR_EMAIL_PAGE = 'CHECK_YOUR_EMAIL_PAGE';
export const INTERSTITIAL_PAGE = 'INTERSTITIAL_PAGE';
export const LINK_EXPIRED_PAGE = 'LINK_EXPIRED_PAGE';
export const REQUEST_FORM = 'REQUEST_FORM';
