export default {
	ID: 91234567890,
	URL: 'http://example.com/',
	canUpdateFiles: true,
	capabilities: {},
	description: 'Just another WordPress site',
	domain: 'example.com',
	hasJetpackProtect: true,
	icon: {},
	is_following: false,
	is_private: false,
	jetpack: false,
	lang: 'en',
	logo: {},
	meta: {},
	name: 'Example Site',
	options: {},
	plan: 1,
	plugins: [],
	post_count: 13,
	single_user_site: true,
	slug: 'example.com',
	subscribers_count: 0,
	title: 'Example Site',
	update: {},
	jp_version: '3.8',
	user_can_manage: true,
	visible: true,
	wpcom_url: 'example.wordpress.com',
};
