export const NOT_SUBMITTED = 'NOT_SUBMITTED';
export const SUBMITTING = 'SUBMITTING';
export const SUBMIT_FAILURE = 'SUBMIT_FAILURE';
export const SUBMITTED = 'SUBMITTED';

export const NPS_SURVEY_RAND_MAX = 5000;
