/**
 * Provides an auto-completer to aid in cross-company communication
 * Autocompletes Automattic-specific slang and abbreviations
 * 
 * @TODO:
 *  - build an API to provide this data
 *  - add optional links for further context on these terms
 *  - add a sidebar plugin to enable easy editing of these terms
 *  - track which terms are selected and sort by frequency
 */

wp.hooks.addFilter(
    'blocks.Autocomplete.completers',
    'extendaberg/autocompleters/idioticon',
    completers => [ ...completers, {
        name: 'idioticon',
        triggerPrefix: '_',
        options: [
            [ '_', 'a plain old underscore' ],
            [ '+t+d', '"totes def" or "totally, definitely"' ],
            [ '2FA', 'Two-factor authorization' ],
            [ '2SA', 'Two-step authorization' ],
            [ '3PD', 'Third-party devs, mainly WooCommerce' ],
            [ 'a11n', 'Automattician, one who works at Automattic' ],
            [ 'a11y', 'Accessibility' ],
            [ 'a12s', 'Automatticians, all who work at Automattic' ],
            [ 'a8c', 'Automattic' ],
            [ 'AA', 'Atomic ambassador, person from the Atomic guild who supports Atomic sites' ],
            [ 'ACK', 'Acknowledged, reminiscient of a TCP handshake' ],
            [ 'ACME', 'Automated Certificate Management Environment' ],
            [ 'Adyen', 'Payment processor we use to accept payment by bank transfer in Germany' ],
            [ 'AFK', 'Away from keyboard, on vacation or out of office, not available' ],
            [ 'AL/R', 'Activity Log & Rewind, new feature set replacing VaultPress for backups' ],
            [ 'AMA', 'Ask Matt Anything, or "Ask me anything"' ],
            [ 'AR', 'Account Recovery' ],
            [ 'ARGP', 'Auto Renewal Grace Period' ],
            [ 'AT', 'Atomic Site, sites with WordPress.com business plans and a custom plugin or theme' ],
            [ 'Atomic sit', 'Atomic Site, sites with WordPress.com business plans and a custom plugin or theme' ],
            [ 'Attribution', 'the process of identifying a set of user actions (“events” or “touchpoints”) that contribute in some manner to a desired outcome, and then assigning a value to each of these events. Marketing attribution provides a level of understanding of what combination of events in what particular order influence individuals to engage in a desired behavior, typically referred to as a conversion' ],
            [ 'Audience', 'particular group of consumers within a predetermined target market, identified as the targets or recipients for a particular advertisement or message. Some audiences are also known as “segments,” groups of people that share the same characteristics or took the same online actions.' ],
            [ 'AUX', 'Auxiliary or Automattician & User Experience (as in Store Aux Squad)' ],
            [ 'AYS', 'Are you sure?' ],
            [ 'BFM', 'Big F*ing Merge. What happens when the development branch of trunk (beta or RCs) is merged into .com.' ],
            [ 'Calypso', 'The next generation interface for WordPress.com, a replacement for wp-admin. Powered by our REST API' ],
            [ 'Cancel/refund', 'When a user cancels all services and drops down to “free”. Not to be confused with a downgrade.' ],
            [ 'Caturday', 'Formerly known as “Saturday,” Caturday is a day when the posting of cats and lolcats is acceptable, and encouraged.' ],
            [ 'churn', 'A paid user/subscriber who doesn’t renew.' ],
            [ 'CLI', 'Command Line Interface' ],
            [ 'COI', 'Conflict of interest' ],
            [ 'CP', 'Can mean either Code Poet or Child Pornography, depending on which team’s P2 you are reading.' ],
            [ 'CPA', '(Cost per acquisition), also known as pay per acquisition (PPA) and cost per conversion, is an online advertising pricing model where the advertiser pays for each specified acquisition – for example, an impression, click, form submit (e.g., contact request, newsletter sign up, registration etc.), double opt-in or sale.' ],
            [ 'CPT', '(Custom Post Types): Custom post types are new post types you can create.' ],
            [ 'CTR', '(Click-through rate): is the ratio of users who click on a specific link to the number of total users who view a page, email, or advertisement. It is commonly used to measure the success of an online advertising campaign for a particular website as well as the effectiveness of email campaigns.' ],
            [ 'Cute!', 'Versatile interjection: (1) I love that; (2) I agree; (3) What’s for lunch?; (4) That’s awesome; (5) I’m sleepy; (6) Nope. You’re doing it wrong; (7) CHOCOLATE CAKE!' ],
            [ 'DARC', 'Domain Admin Report Card' ],
            [ 'Deterministic', 'Data that can accurately identify a consumer for targeting ads, such as a visitor’s login information for a website. Other deterministic data points are credit cards, phone numbers, and addresses. (See “Probabilistic“)' ],
            [ 'DIO', 'Deal Is Official: Used in VIP when a sale / agreement happens' ],
            [ 'DMCA', 'Digital Millenium Copyright Act' ],
            [ 'DMP', '(Data-management platform): The systems that brands use to make sense of any information they can find about consumers and the marketplace. Brands upload first-party data (consumer emails, sales figures, etc.) to a DMP and combine it with other data sets to make better decisions for their marketing' ],
            [ 'Downgrade', 'When a user drops down to a lower plan or to a service at a lower price point. Unlike cancel/refund, the user is still paying us' ],
            [ 'D’OH', 'Developing Our Happiness' ],
            [ 'DOH', 'Developing Our Happiness' ],
            [ 'DOPS', 'Dot Org Premium Services' ],
            [ 'DSS', 'Dynamic Screen Shots' ],
            [ 'DSP', 'Demand-side platform' ],
            [ 'DRI', 'Direct Responsible Individual' ],
            [ 'DWPO', 'Domains With Plans Only' ],
            [ 'ELIF', 'Explain [it] like I’m five' ],
            [ 'ELI5', 'Explain [it] like I’m five' ],
            [ 'ELL', 'English Language Learners' ],
            [ 'en.blog', 'Shorthand for the WordPress.com news blog, at http://en.blog.wordpress.com/' ],
            [ 'Engineer', 'Anyone in the company, basically.' ],
            [ 'EOS', 'End of shift (referring to live chat).' ],
            [ 'ERGP', 'Explicit Renewal Grace Period. This is when we have informed the user of their impending renewal.' ],
            [ 'FC', 'Full Color' ],
            [ 'Feedbag', 'Software that packages up reader content and puts it in a “bag” to be sent to the API.' ],
            [ 'FG', 'The Field Guide' ],
            [ 'FOA', 'Friends of Automattic; mostly used in a VIP or Team 51 context' ],
            [ 'VVIP', 'Very important VIP; mostly used in a VIP or Team 51 context' ],
            [ 'FPP', 'VIP’s Featured Partner Program' ],
            [ 'FP', 'False positive, related to Risk & Safety and bkismet' ],
            [ 'FR', 'Feedback Received. An FR is any ticket which we’ve answered, and the user has since replied to. It’s an open ticket that has an ongoing dialogue with the user.' ],
            [ 'FT', 'Full Timer. Frequently used in #tickets and #happiness' ],
            [ 'FU', 'Follow Up' ],
            [ 'FUE', 'Follow up email' ],
            [ 'FUE', 'Follow ups' ],
            [ 'Fusion', 'The system that keeps Jetpack and WordPress.com codebases in sync' ],
            [ 'FWIW', 'For what it’s worth' ],
            [ 'GA', 'Google Analytics' ],
            [ 'GA', 'General Availability' ],
            [ 'GDPR', 'General Data Protection Regulation' ],
            [ 'GM', 'Grand Meetup' ],
            [ 'GT', 'Guided Transfer' ],
            [ 'GTK', 'Good to know' ],
            [ 'GUT', 'Grand Unified Theory' ],
            [ 'HC', 'Happychat: our custom chat software used by HEs inside of Calypso' ],
            [ 'HE', 'Happiness Engineer' ],
            [ 'HG', 'Happiness Gardener' ],
            [ 'Highlander', 'There can be only one. Codename for the WordPress.com Comments project' ],
            [ 'HRS', 'OpenHRS: Tucows’ hosted registrar services platform and is currently the API/platform we use to register, renew, and transfer in domains where a8c is the registrar of record' ],
            [ 'HRV', 'Human Resources Violation' ],
            [ 'HTH', 'Hope this helps' ],
            [ 'HUD', 'Happiness Ungineering Device: operator-facing tool for HEs for chatting with customers' ],
            [ 'i18n', 'Internationalization' ],
            [ 'IC', 'Individual Contributor' ],
            [ 'IDC', 'Jetpack Identity Crysis' ],
            [ 'IANAL', 'I am not a lawyer' ],
            [ 'In-westi-gate', 'To investigate some code or functionality, secretly hoping that Westi will hop in the thread saying “just use [blah]“' ],
            [ 'IS', 'Infinite Scroll' ],
            [ 'Jabberlanche', 'When you open your Jabber client after a long break and get a bazillion new posts.' ],
            [ 'JIC', 'Just in case (via Dean Royal)' ],
            [ 'JPC', 'Jetpack Connect' ],
            [ 'JPM', 'Jetpack Manage' ],
            [ 'JPO', 'Jetpack Onboarding' ],
            [ 'JPOP', 'Jetpack & .Org Premium' ],
            [ 'JPPHP', 'Jetpack Premium Host Partnership' ],
            [ 'JSYK', 'Just so you know' ],
            [ 'l10n', 'localization' ],
            [ 'LB', 'load balancer' ],
            [ 'LCA', 'Live Chat Academy, an open company-wide support project.' ],
            [ 'Le', 'Let’s Encrypt SSL certificates' ],
            [ 'LFM', 'Little Fuc*ing Merge (brother of the Big Fuc*ing Merge)' ],
            [ 'LGTM', 'Looks good to me' ],
            [ 'LoL', 'Lead of leads' ],
            [ 'LP', 'Landing page. Usually referencing a logged-out page used for converting users' ],
            [ 'Lrec', 'Large Rectangle (Display Ads)' ],
            [ 'Matt Bombing', 'When a long and often rat-hole-y discussion is shut down with a short comment by Matt deep in the thread' ],
            [ 'MBP', 'MacBook Pro' ],
            [ 'Modlook', 'Threads that require staff intervention are tagged with modlook in forums' ],
            [ 'morechat', 'Call for more HEs to chat, as demand grows on HUD' ],
            [ 'MC', 'Mission Control: https://mc.a8c.com/' ],
            [ 'MGS', 'Matt’s Global Search. Available in MC. Searches multiple sources at once, including P2s, IRC logs, and more. “Like Dogpile”' ],
            [ 'MVLP', 'Minimally Viable Lovable Product' ],
            [ 'NA', 'Network-Admin' ],
            [ 'NASCAR', 'Loose codename for the Sharedaddy redesign by Team Social' ],
            [ 'Newdash', 'an ongoing project to simplify the WordPress.com user experience. Team Triton was leading this and Janitorial kicked the project off in 2011. Triton’s working on newdash’s foundation, two-dash issues, and NUX. It was replaced by Calypso starting 2014' ],
            [ 'NDA', 'Non-disclosure agreement' ],
            [ 'NDO', 'Non-disclosure order' ],
            [ 'Newstore', 'the store site at store.wordpress.com, that includes information about all our plans and upgrades and is available to logged-out users' ],
            [ 'np', 'no problem' ],
            [ 'NUX', 'New User Experience; the opposite of SUX' ],
            [ 'OBW', 'On-boarding Wizard. The flow used to sign up a new user/account' ],
            [ 'OKR', 'Objectives and Key Results' ],
            [ 'OpenHRS', 'Tucows’ hosted registrar services platform and is currently the API/platform we use to register, renew, and transfer in domains where a8c is the registrar of record' ],
            [ 'OpenSRS', 'Tucows’ shared registration system, which is a reseller platform for domain registrations We currently use OpenSRS to register, renew, and transfer in domains where a8c is a reseller not the registrar. in this case, Tucows is the registrar of record' ],
            [ 'OTP', 'On the phone' ],
            [ 'OTP', 'One-time password' ],
            [ 'Paytm', 'Digital wallet provider in India, payment method for India users' ],
            [ 'Plan', 'A level of service, or tier, or upgrade plan, on your WordPress.com blog. We used to call these “Bundles”. We started with the Premium Bundle and then added the Business Bundle. Now we call them WordPress.com Premium and WordPress.com Business. Adding “plan” is optional.' ],
            [ 'PIC', 'Pre-interview challenge' ],
            [ 'Ping', 'A “you there?” equivalent derived from technical terminology; used frequently within real-time a8c chat mediums to determine if someone is actually present and available for conversation.' ],
            [ 'PR', 'Pull Request on Github' ],
            [ 'PR', 'Public Relations' ],
            [ 'Probabilistic', 'Using data points to guess who the consumer is on the other side of the screen. Knowing where a person is, what time it is and the device in use help, but not with nearly 100% confidence. This type of data is considered less accurate than deterministic (see “Deterministic“), though many say a blend of the two yields the most accurate results.' ],
            [ 'PUG', 'Paid, Unpaid, Gravatar (a sub-team of Core Happy)' ],
            [ 'QvQ', '(Project) Quantity vs. Quality, by two Happiness teams, Athens and Sparta' ],
            [ 'RC', 'Report Card. A user or blog summary including contact details, audit trails and support history.' ],
            [ 'Recombinant blog', 'A blog that only publishes posts from other blogs (e.g. freshlypressed, news, botd) and requires special code to correctly generate post permalinks' ],
            [ 'Refund/cancel', 'When a user cancels all services and drops down to “free”. Not to be confused with a downgrade' ],
            [ 'RGP', 'Redemption Grace Period AKA (pending_delete)' ],
            [ 'ROAS', '(Return On Ad Spend) = revenue from ad campaign/cost of ad campaign' ],
            [ 'RQ', 'Review Queue' ],
            [ 's12y', 'Sustainability' ],
            [ 'Sabbattician', 'An Automattician currently on a sabbatical' ],
            [ 'Sadday', 'When a customer does not renew with VIP; business churn and loss of revenue' ],
            [ 'Sequential messaging', 'Hitting a consumer with one message, then a different one and then another to guide them toward buying or taking some other action. Sequential messaging, also known as sequential targeting, often requires cross-device capabilities to accurately reach the same consumer across screens when they visit different digital properties.' ],
            [ 'Smooshing', '(Not Jersey Shore style): Rose knows 😉' ],
            [ 'SA', 'Super Admin.  Admin access to wpcom sites with bonus privileges (like refunding payments), or a person with these super powers.  “With great power…” (or if an HE asks for a link to the SA, this can also mean Store Admin. Which is a page that lists all of the upgrades owned by a given user account)' ],
            [ 'SEM', 'Search Engine Marketing (A type of Internet marketing associated with the researching, submitting and positioning of a website within search engines to achieve maximum visibility and increase your share of paid and/or organic traffic referrals from search engines)' ],
            [ 'SIRT', 'Security incident responce team. Two members of each a8c team compromise this group and coordinate sirtp2.' ],
            [ 'SLA', 'Service-level agreement' ],
            [ 'SR', 'Support Rotation.' ],
            [ 'SSP', 'Super Secret Password' ],
            [ 'SSP', 'Sell-Side Platform: While marketers use DSPs to buy digital ads, publishers use SSPs to sell them. Publishers use SSPs to offer inventory to ad exchanges, networks, trading desks—anywhere that has a pool of demand. They also use SSPs to set the terms of the auctions and manage private auctions, known as private marketplaces, where select advertisers are invited to participate. An SSP gives them control over who can advertise and the types of ads that run. Like DSPs, SSPs also plug into data-management platforms.' ],
            [ 'SSR', '(mostly used in the context of Calypso): Server Side Rendering' ],
            [ 'SRS', 'OpenSRS: Tucows’ shared registration system, which is a reseller platform for domain registrations We currently use OpenSRS to register, renew, and transfer in domains where a8c is a reseller not the registrar. in this case, Tucows is the registrar of record' ],
            [ 'SU', 'Super User. While using Calypso as an Automattician, you can ‘become’ another user, and navigate Calypso as them with the super user admin command' ],
            [ 'TAE', 'Technical Account Engineer' ],
            [ 'TAM', 'Total Available Market' ],
            [ 'TC', 'Takedown Czar (via @starxedsteph)' ],
            [ 't12n', 'Trialmattician (Automattician on trial)' ],
            [ 'TIL', 'Today I learned' ],
            [ 'TLD', 'Top Level Domain' ],
            [ 'TOSRR', 'Terms Of Service Report Reviewer. One of the tools used by Happiness team to monitor terms of service reports' ],
            [ 'TOSSER', 'Member of the TOS team' ],
            [ 'TQR', 'Ticket Queue Reviewer. One of the tools used by the Happiness team to monitor the forums and answer Private support requests #' ],
            [ 'TWIL', 'This Week I Learned. Used in posts by many happiness teams to summarize things learned while supporting our products.' ],
            [ 'UI Suckle', 'A professional technical term that measures how simple a UI is to use, by how long it takes you to figure out and become comfortable with it. “The UI suckle of an elevator is about two seconds for me”' ],
            [ 'UUID', 'Universally unique identifier' ],
            [ 'UPI', 'Payment method for India users facilitating direct account debit' ],
            [ 'VP', 'VaultPress or VideoPress depending on the context' ],
            [ 'WAPI', 'Wild West Domains API.  It can refer either to the WWD API itself or our code that uses it. This is deprecated and has been replaced with WWD’s REST API' ],
            [ 'WC', 'WooCommerce' ],
            [ 'WFM', 'Works for me' ],
            [ 'WHTA', 'We Have The Answers. The Happiness team’s P2' ],
            [ 'WIP', 'Work in progress.' ],
            [ 'WPJM', 'WP Job Manager.' ],
            [ 'WordPress.com Business', 'One of the several levels of service, or tiers, available on WordPress.com. Known officially as a “plan” (and not a bundle). WordPress.com Business is the third tier: better than a free blog and WordPress.com Premium, not as good as WordPress.com Enterprise.' ],
            [ 'WordPress.com Premium', 'One of the several levels of service, or tiers, available on WordPress.com. Known officially as a “plan” (and not a bundle). WordPress.com Premium is the second tier: better than a free blog, not as good as WordPress.com Business. The WordPress.com Premium plan is one of the most successful products on WordPress.com.' ],
            [ 'WPiOS', 'Shorthand for the WordPress for iOS project (app for iPhone, iPod, and iPad devices)' ],
            [ 'WPAndroid', 'Shorthand for the WordPress for Android project (app for Android phones and tablets).' ],
            [ 'WPBlackBerry', 'Shorthand for the WordPress for BlackBerry project (app for BlackBerry phones).' ],
            [ 'WPCC', 'WordPress.com Connect' ],
            [ 'WPSC', 'WordPress Super Cache' ],
            [ 'WPWindowsPhone', 'Shorthand for the WordPress for Windows Phone 7 project (app for Windows Phone 7+ devices)' ],
            [ 'WPW', 'Shorthand for the WordPress for Windows Phone 7 project (app for Windows Phone 7+ devices)' ],
            [ 'WPNokia', 'Shorthand for the WordPress for Nokia project (app for older Nokia phones, built on the QT platform)' ],
            [ 'WPwebOS', 'Shorthand for the WordPress for webOS project (an app created solely for the now discontinued HP TouchPad tablet)' ],
            [ 'WRT', 'with regards to' ],
            [ 'WTB', 'World Time Buddy, “a cross between a time zone converter, a world clock converter, and an online meeting scheduler”' ],
            [ 'WWD', 'Wild West Domains (a subsidiary of Godaddy). This is one of our registrar/reseller partners that handles domain registrations (see also OpenHRS. OpenSRS).  Automattic is a reseller for domains that use WWD and WWD is the registrar of record. We are no longer registering any new domains using WWD' ],
            [ 'X-post', 'A “cross-post”, where a P2 is pinged from another P2 post: triggered by +p2name' ],
            [ 'X-comment', 'A “cross-post”, where a P2 is pinged from another P2 comment: triggered by +p2name' ],
            [ 'YRM', 'Your recent message in live chat' ],
            [ 'ZNC', 'IRC pass-through server that keeps you online when you’re offline, so you can see any pings or PMs that you would otherwise have missed. Ask System’s Ashish about it.' ],
        ],
        getOptionKeywords: ( [ abbr, title ] ) => abbr,
        getOptionLabel: ( [ abbr, title ] ) => `${ abbr } - ${ title }`,
        getOptionCompletion: ( [ abbr, title ] ) => '_' === abbr ? '_' : <React.Fragment><abbr title={ title }>{ abbr }</abbr>{ '‌\u0020' }</React.Fragment>
    } ]
);
