export default [ {
	ID: 'twitter',
	name: 'Twitter',
	shortname: 'twitter',
	custom: false,
	enabled: false,
	visibility: 'visible'
}, {
	ID: 'facebook',
	name: 'Facebook',
	shortname: 'facebook',
	custom: false,
	enabled: false,
	visibility: 'visible'
}, {
	ID: 'google-plus-1',
	name: 'Google',
	shortname: 'googleplus1',
	custom: false,
	enabled: false,
	visibility: 'visible'
}, {
	ID: 'email',
	name: 'Email',
	shortname: 'email',
	custom: false,
	enabled: false
}, {
	ID: 'print',
	name: 'Print',
	shortname: 'print',
	custom: false,
	enabled: false
}, {
	ID: 'linkedin',
	name: 'LinkedIn',
	shortname: 'linkedin',
	custom: false,
	enabled: false
}, {
	ID: 'reddit',
	name: 'Reddit',
	shortname: 'reddit',
	custom: false,
	enabled: false
}, {
	ID: 'tumblr',
	name: 'Tumblr',
	shortname: 'tumblr',
	custom: false,
	enabled: false
}, {
	ID: 'pinterest',
	name: 'Pinterest',
	shortname: 'pinterest',
	custom: false,
	enabled: false
}, {
	ID: 'pocket',
	name: 'Pocket',
	shortname: 'pocket',
	custom: false,
	enabled: false
}, {
	ID: 'telegram',
	name: 'Telegram',
	shortname: 'telegram',
	custom: false,
	enabled: false
}, {
	ID: 'jetpack-whatsapp',
	name: 'WhatsApp',
	shortname: 'jetpack-whatsapp',
	custom: false,
	enabled: false
}, {
	ID: 'skype',
	name: 'Skype',
	shortname: 'skype',
	custom: false,
	enabled: false
} ];
