export const WOOCOMMERCE_EDIT_PRODUCT = 'WOOCOMMERCE_EDIT_PRODUCT';
export const WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE = 'WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE';
export const WOOCOMMERCE_EDIT_PRODUCT_VARIATION = 'WOOCOMMERCE_EDIT_PRODUCT_VARIATION';
export const WOOCOMMERCE_UPDATE_PRODUCT_VARIATIONS = 'WOOCOMMERCE_UPDATE_PRODUCT_VARIATIONS';
