export const WOOCOMMERCE_API_SET_ERROR = 'WOOCOMMERCE_API_SET_ERROR';
export const WOOCOMMERCE_API_CLEAR_ERROR = 'WOOCOMMERCE_API_CLEAR_ERROR';
export const WOOCOMMERCE_EDIT_PRODUCT = 'WOOCOMMERCE_EDIT_PRODUCT';
export const WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE = 'WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE';
export const WOOCOMMERCE_EDIT_PRODUCT_VARIATION = 'WOOCOMMERCE_EDIT_PRODUCT_VARIATION';
