export const WOOCOMMERCE_EDIT_PRODUCT = 'WOOCOMMERCE_EDIT_PRODUCT';
export const WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE = 'WOOCOMMERCE_EDIT_PRODUCT_ATTRIBUTE';
export const WOOCOMMERCE_EDIT_PRODUCT_VARIATION = 'WOOCOMMERCE_EDIT_PRODUCT_VARIATION';
