import { supported } from '@github/webauthn-json';
import {
	Button,
	Card,
	CardBody,
	CardHeader,
	CheckboxControl,
	Modal,
	Notice,
} from '@wordpress/components';
import { createInterpolateElement } from '@wordpress/element';
import { __, sprintf } from '@wordpress/i18n';
import debugFactory from 'debug';
import { useEffect, useState } from 'react';
import twoStepAuthorization from 'calypso/lib/two-step-authorization';
import SecurityKeyForm from './security-key-form';
import TwoFactorActions from './two-factor-actions';
import VerificationCodeInput from './verification-code-input';

const debug = debugFactory( 'dashboard:auth:reauth-required' );

// Cast the two-step authorization module to include event emitter methods
type TwoStepAuthorizationWithEmitter = typeof twoStepAuthorization & {
	on: ( event: string, callback: () => void ) => void;
	off: ( event: string, callback: () => void ) => void;
	data?: {
		two_step_enhanced_security?: boolean;
		two_step_sms_last_four?: string;
	};
};

interface ReauthRequiredProps {
	/**
	 * The two-step authorization module. Allows for testing by injecting a mock.
	 */
	twoStepAuthorization?: typeof twoStepAuthorization;

	/**
	 * Function to call when user clicks "Log out".
	 */
	onLogout?: () => void;
}

/**
 * Component that handles two-factor re-authentication for sensitive operations.
 */
export default function ReauthRequired( {
	twoStepAuthorization: twoStepAuth = twoStepAuthorization as TwoStepAuthorizationWithEmitter,
	onLogout,
}: ReauthRequiredProps ) {
	const [ codeRequestTimer, setCodeRequestTimer ] = useState< ReturnType<
		typeof setTimeout
	> | null >( null );
	const [ remember2fa, setRemember2fa ] = useState( false );
	const [ code, setCode ] = useState( '' );
	const [ smsRequestsAllowed, setSmsRequestsAllowed ] = useState( true );
	const [ twoFactorAuthType, setTwoFactorAuthType ] = useState( 'authenticator' );
	const [ validatingCode, setValidatingCode ] = useState( false );

	const [ , setStateForceUpdate ] = useState( {} );

	const handleUpdate = () => {
		// Force a re-render when the two-step auth state changes
		setStateForceUpdate( {} );
	};

	useEffect( () => {
		twoStepAuth.on( 'change', handleUpdate );

		return () => {
			if ( codeRequestTimer ) {
				clearTimeout( codeRequestTimer );
			}
			twoStepAuth.off( 'change', handleUpdate );
		};
	}, [] );

	const handleSendSMSCode = () => {
		setSmsRequestsAllowed( false );
		const timer = setTimeout( () => {
			setSmsRequestsAllowed( true );
		}, 60000 );
		setCodeRequestTimer( timer );

		twoStepAuth.sendSMSCode( ( error: Error | null, data: { sent: boolean } | null ) => {
			if ( ! error && data?.sent ) {
				debug( 'SMS code successfully sent' );
			} else {
				debug( 'There was a failure sending the SMS code.' );
			}
		} );
	};

	const handleSubmitForm = ( event: React.FormEvent ) => {
		event.preventDefault();
		setValidatingCode( true );

		twoStepAuth.validateCode(
			{
				code: code.replace( /\s/g, '' ),
				remember2fa,
			},
			( error: Error | null, data: { validated: boolean } | null ) => {
				setValidatingCode( false );
				if ( error ) {
					debug( 'There was an error validating that code: ' + JSON.stringify( error ) );
				} else {
					debug( 'The code validated!' + JSON.stringify( data ) );
				}
			}
		);
	};

	const handleAuthSwitch = ( authType: string ) => {
		setTwoFactorAuthType( authType );
		if ( authType === 'sms' ) {
			handleSendSMSCode();
		}
	};

	const handleLogout = () => {
		if ( onLogout ) {
			onLogout();
		} else {
			// Default behavior - redirect to logout page
			window.location.href = '/logout';
		}
	};

	const preValidateAuthCode = () => {
		return code.length > 5;
	};

	const renderCodeMessage = () => {
		if ( twoStepAuth.isTwoStepSMSEnabled() ) {
			return createInterpolateElement(
				sprintf(
					// translators: %s is the last four digits of the phone number
					__(
						'Press the button below to request an SMS verification code. Once you receive our text message at your phone number ending with <strong>%(smsLastFour)s</strong>, enter the code below.'
					),
					{
						smsLastFour: twoStepAuth.getSMSLastFour(),
					}
				),
				{
					strong: <strong />,
				}
			);
		}

		if ( twoFactorAuthType === 'sms' ) {
			return __(
				'We just sent you a verification code to your phone number on file, please enter the code below.'
			);
		}

		return __( 'Please enter the verification code generated by your authenticator app.' );
	};

	const renderSecurityKeyUnsupported = () => {
		return (
			<Card>
				<CardHeader>{ __( 'Two Factor Authentication Required' ) }</CardHeader>
				<CardBody>
					<Notice status="warning" isDismissible={ false }>
						{ __(
							'Your WordPress.com account requires the use of security keys, but the current device does not seem to support them.'
						) }
					</Notice>
					<div style={ { marginTop: '16px' } }>
						<Button variant="primary" onClick={ handleLogout }>
							{ __( 'Log out' ) }
						</Button>
					</div>
				</CardBody>
			</Card>
		);
	};

	const renderVerificationForm = () => {
		const enhancedSecurity = twoStepAuth.data?.two_step_enhanced_security;
		if ( enhancedSecurity ) {
			return renderSecurityKeyUnsupported();
		}

		const method = twoStepAuth.isTwoStepSMSEnabled() ? 'sms' : 'app';

		return (
			<Card>
				<CardBody>
					<p>{ renderCodeMessage() }</p>

					<p>
						<Button variant="link" onClick={ handleLogout }>
							{ __( 'Not you? Log out' ) }
						</Button>
					</p>

					<form onSubmit={ handleSubmitForm }>
						<div style={ { marginBottom: '16px' } }>
							<VerificationCodeInput
								id="code"
								label={ __( 'Verification Code' ) }
								isError={ twoStepAuth.codeValidationFailed() }
								value={ code }
								onChange={ setCode }
								method={ method }
							/>

							{ twoStepAuth.codeValidationFailed() && (
								<Notice status="error" isDismissible={ false }>
									{ __( 'You entered an invalid code. Please try again.' ) }
								</Notice>
							) }
						</div>

						<div style={ { marginBottom: '16px' } }>
							<CheckboxControl
								label={ __( 'Remember for 30 days.' ) }
								checked={ remember2fa }
								onChange={ setRemember2fa }
							/>
						</div>

						{ twoStepAuth.isSMSResendThrottled() && (
							<div style={ { marginBottom: '16px' } }>
								<Notice status="warning" isDismissible={ false }>
									{ __( 'SMS codes are limited to once per minute. Please wait and try again.' ) }
								</Notice>
							</div>
						) }

						<Button
							variant="primary"
							type="submit"
							disabled={ validatingCode || ! preValidateAuthCode() }
							style={ { width: '100%' } }
						>
							{ __( 'Verify' ) }
						</Button>
					</form>
				</CardBody>
			</Card>
		);
	};

	const renderDialog = () => {
		const enhancedSecurity = twoStepAuth.data?.two_step_enhanced_security;
		const method = twoStepAuth.isTwoStepSMSEnabled() ? 'sms' : 'authenticator';
		const isSecurityKeySupported = twoStepAuth.isSecurityKeyEnabled() && supported();
		const twoFactorType = enhancedSecurity ? 'webauthn' : twoFactorAuthType;

		// This enables the SMS button on the security key form regardless if we can send SMS or not.
		// Otherwise, there's no way to go back to the verification form if smsRequestsAllowed is false.
		const shouldEnableSmsButton =
			smsRequestsAllowed || ( method === 'sms' && twoFactorType === 'webauthn' );

		const hasSmsRecoveryNumber = !! twoStepAuth?.data?.two_step_sms_last_four?.length;

		return (
			<Modal
				title={ __( 'Two Factor Authentication Required' ) }
				onRequestClose={ () => {} } // Modal can't be closed
				isFullScreen={ false }
				shouldCloseOnClickOutside={ false }
				isDismissible={ false }
			>
				{ isSecurityKeySupported && twoFactorType === 'webauthn' ? (
					<SecurityKeyForm twoStepAuthorization={ twoStepAuth } />
				) : (
					renderVerificationForm()
				) }

				<TwoFactorActions
					twoFactorAuthType={ twoFactorType }
					onChange={ handleAuthSwitch }
					isSmsSupported={
						! enhancedSecurity &&
						( method === 'sms' || ( method === 'authenticator' && hasSmsRecoveryNumber ) )
					}
					isAuthenticatorSupported={ ! enhancedSecurity && method !== 'sms' }
					isSmsAllowed={ shouldEnableSmsButton }
					isSecurityKeySupported={ isSecurityKeySupported }
				/>
			</Modal>
		);
	};

	// Only render the dialog if reauth is required
	if ( ! twoStepAuth.isReauthRequired() ) {
		return null;
	}

	return renderDialog();
}
