module.exports.action = {
	UPDATE_READER_LIST: 'UPDATE_READER_LIST',
	RECEIVE_UPDATE_READER_LIST: 'RECEIVE_UPDATE_READER_LIST',
	DISMISS_READER_LIST_NOTICE: 'DISMISS_READER_LIST_NOTICE',
	RECEIVE_READER_LIST: 'RECEIVE_READER_LIST',
	RECEIVE_READER_LISTS: 'RECEIVE_READER_LISTS',
	RECEIVE_CREATE_READER_LIST: 'RECEIVE_CREATE_READER_LIST',
	FOLLOW_LIST: 'FOLLOW_LIST',
	RECEIVE_FOLLOW_LIST: 'RECEIVE_FOLLOW_LIST'
};
