/** @format */
module.exports.action = {
	UPDATE_READER_LIST: 'UPDATE_READER_LIST',
	RECEIVE_UPDATE_READER_LIST: 'RECEIVE_UPDATE_READER_LIST',
	DISMISS_READER_LIST_NOTICE: 'DISMISS_READER_LIST_NOTICE',
	RECEIVE_READER_LIST: 'RECEIVE_READER_LIST',
	RECEIVE_READER_LISTS: 'RECEIVE_READER_LISTS',
	FOLLOW_LIST: 'FOLLOW_LIST',
	RECEIVE_FOLLOW_LIST: 'RECEIVE_FOLLOW_LIST',
	RECEIVE_FOLLOW_LIST_ERROR: 'RECEIVE_FOLLOW_LIST_ERROR',
	UNFOLLOW_LIST: 'UNFOLLOW_LIST',
	RECEIVE_UNFOLLOW_LIST: 'RECEIVE_UNFOLLOW_LIST',
	RECEIVE_UNFOLLOW_LIST_ERROR: 'RECEIVE_UNFOLLOW_LIST_ERROR',
	CREATE_READER_LIST: 'CREATE_READER_LIST',
	RECEIVE_CREATE_READER_LIST: 'RECEIVE_CREATE_READER_LIST',
};
