
// TODO: Remove WOOCOMMERCE_ prefix after api-data is split out from extension code.
export const WOOCOMMERCE_API_CLIENT_ERROR = 'WOOCOMMERCE_API_CLIENT_ERROR';
export const WOOCOMMERCE_API_CLIENT_REQUESTED = 'WOOCOMMERCE_API_CLIENT_REQUESTED';
export const WOOCOMMERCE_API_CLIENT_RECEIVED = 'WOOCOMMERCE_API_CLIENT_RECEIVED';
