openapi: 3.0.3
info:
  title: Migration API
  version: 0.0.1
  description: API for managing website migrations to WPCOM platform

paths:
  /sites/{siteSlug}/migrations:
    get:
      summary: |
        List migrations related to the WPCOM site slug. It also returns the the hosting details and the available options E.g application_password, credentials, backup_file.
      parameters:
        - in: path
          name: siteSlug
          description: The WPCOM site slug
          required: true
          schema:
            type: string
        - in: query
          name: latest
          description: 'Returns only the latest migration'
          schema:
            type: integer
            enum: [1]
      responses:
        '200': 
          description: |
            Return the list of migrations by site
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Migration'
        '400':  
          description: "Missing or invalid required params"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing or invalid parameters"
        
        '404':
          description: No migration found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No migration found for siteSlug."
    post:
      summary: |
        Create an entity "migration"
      description: |
        It automatically sets a migration as "pending" as "in-progress" if all required information were provided. For example DIY migration doesn't require  credentials or file, so there is no depedency to start without more information.
        If there are missing information, the status will be "pending"
        It also can return "cancelled" if the source site is not using wordpress or is already wpcom.
      parameters:
        - in: path
          name: siteSlug
          required: true
          description: The WPCOM site slug
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MigrationInput'
      responses:
        '201':
          description: The created migration with its status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Migration'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
    patch:
      summary: Update the lastest migration entity from a site
      description: |
        It automatically starts a migration if all required fields are provided
      parameters:
        - in: path
          name: siteSlug
          required: true
          description: The WPCOM site slug
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MigrationUpdate'
      responses:
        '201':
          description: The created migration with its status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Migration'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
    delete:
      summary: Cancels pending migration
      description: |
        Updates the migration status to cancelled. It should only be used by manually cancelletion when the status is pending
      parameters:
        - in: path
          name: siteSlug
          required: true
          description: The WPCOM site slug
          schema:
            type: string

      responses:
        '200':
          description: The created migration with its status
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
components:
  schemas:
    MigrationStatus:
      type: string
      enum: 
        - "pending"
        - "in-progress"
        - "completed"
        - "failed"
        - "cancelled"
      description: |
        * PENDING - Only when there is missing information to start a migration
        * IN_PROGRESS - Represents the migration automated or the HE started the migration progress
        * COMPLETED - All migration and post-migration tasks were finished
        * FAILED - Migration attempt failed

    MigrationType:
      type: string
      enum: 
        - "DIY"
        - "DIFM"
  
    MigrationStrategy:
      type: string
      description: |
        * credentials: Requires user and password
        * backup_file: Requires the backup_file_url
      enum: 
        - "credentials"
        - "backup_file"
    
    AvailableStrategies:
      type: array
      description: "Possible migration options for the site."
      example: ['credentials', 'backup_file', 'application_password']
      items:
        type: string
        enum: 
          - "credentials"
          - "backup_file"
          - "application_password"

    Migration:
      type: object
      properties:
        status: 
          $ref: "#/components/schemas/MigrationStatus"
        pending_details:
          type: string
          example: "missing-credentials"
          description: "Describe what is missing to start a migration"
        progress_details:
          type: object
          properties: 
            step:
              type: integer
              example: 1
            total:
              type: integer
              example: 2
        cancel_details:
          type: string
          example: "non-wordpress"
        origin:
          type: string
          example: "/setup/flow"
        type:
          $ref: "#/components/schemas/MigrationType"
        strategy:
          $ref: "#/components/schemas/MigrationStrategy"
        notes:
          type: string
          example: "My migration requires plugin X"
        source_site:
          type: string
          format: uri
        backup_file_url:
          type: string
          format: uri
        source_details:
          type: object
          properties:
            platform:
              type: string
            application_password:
              type: string
              example: "https://test-vanilla-wp.godaddy.test-wpcom-migrations.net/wp-admin/authorize-application.php" 
              nullable: true
        available_options:
          $ref: "#/components/schemas/AvailableStrategies"

    MigrationUpdate:
      type: object
      properties:
        status: 
          $ref: "#/components/schemas/MigrationStatus"
        source_site:
          $ref: "#/components/schemas/Migration/properties/status"
        origin:
          $ref: "#/components/schemas/Migration/properties/origin"
        type:
          $ref: "#/components/schemas/MigrationType"
        notes:
          $ref: "#/components/schemas/Migration/properties/notes"
        strategy:
          $ref: "#/components/schemas/MigrationStrategy"
        backup_file_url:
          $ref: "#/components/schemas/Migration/properties/backup_file_url"
        credentials:
          type: object
          properties:
            user:
              type: string
            password:
              type: string
          required: [user, password]
          nullable: true
      required: [source_site, origin, type, strategy]
      oneOf:
        - required: [credentials]
          properties:
            strategy:
              enum: ["credentials"]
        - required: [backup_file_url]
          properties:
            strategy:
              enum: ["backup_file"]
    
    MigrationInput:
      type: object
      properties:
        source_site:
          $ref: "#/components/schemas/Migration/properties/status"
        origin:
          $ref: "#/components/schemas/Migration/properties/origin"
        type:
          $ref: "#/components/schemas/MigrationType"
        notes:
          $ref: "#/components/schemas/Migration/properties/notes"
        strategy:
          $ref: "#/components/schemas/MigrationStrategy"
        backup_file_url:
           $ref: "#/components/schemas/Migration/properties/backup_file_url"
        credentials:
          type: object
          properties:
            user:
              type: string
            password:
              type: string
          required: [user, password]
          nullable: true
      required: [source_site, origin, type, strategy]
      oneOf:
        - required: [credentials]
          properties:
            strategy:
              enum: ["credentials"]
        - required: [backup_file_url]
          properties:
            strategy:
              enum: ["backup_file"]         
              
              
              
              
              
              
              
              