export default {
	0: {
		icon: 'dashicons-feedback',
		slug: 'feedback',
		title: 'Feedback',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/admin.php?page=feedback',
		children: {
			1: {
				parent: 'feedback',
				slug: 'edit-phppost_typefeedback',
				title: 'Feedback',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit.php?post_type=feedback',
			},
			2: {
				parent: 'feedback',
				slug: 'polls',
				title: 'Polls',
				type: 'submenu-item',
				url: 'http://feedback?page=polls',
			},
			3: {
				parent: 'feedback',
				slug: 'ratings',
				title: 'Ratings',
				type: 'submenu-item',
				url: 'http://feedback?page=ratings',
			},
		},
	},
	1: {
		icon: 'dashicons-dashboard',
		slug: 'index-php',
		title: 'Dashboard',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/index.php',
		children: {
			0: {
				parent: 'index.php',
				slug: 'index-php',
				title: 'Home',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/index.php',
			},
			6: {
				parent: 'index.php',
				slug: 'my-comments',
				title: 'Comments I&#8217;ve Made',
				type: 'submenu-item',
				url: 'index.php?page=my-comments',
			},
			7: {
				parent: 'index.php',
				slug: 'stats',
				title: 'Site Stats',
				type: 'submenu-item',
				url: 'index.php?page=stats',
			},
			8: {
				parent: 'index.php',
				slug: 'my-blogs',
				title: 'My Blogs',
				type: 'submenu-item',
				url: 'index.php?page=my-blogs',
			},
			9: {
				parent: 'index.php',
				slug: 'subscriptions',
				title: 'Blogs I Follow',
				type: 'submenu-item',
				url: 'index.php?page=subscriptions',
			},
		},
	},
	2: {
		icon: 'dashicons-cart',
		slug: 'paid-upgrades-php',
		title: 'Plans',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/admin.php?page=paid-upgrades.php',
		children: [
			{
				parent: 'paid-upgrades.php',
				slug: 'paid-upgrades-php',
				title: 'Plans',
				type: 'submenu-item',
				url: 'paid-upgrades.php?page=paid-upgrades.php',
			},
			{
				parent: 'paid-upgrades.php',
				slug: 'premium-themes',
				title: 'Premium Themes',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/premium-themes',
			},
			{
				parent: 'paid-upgrades.php',
				slug: 'domains',
				title: 'My Domains',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/domains',
			},
			{
				parent: 'paid-upgrades.php',
				slug: 'my-upgrades',
				title: 'Manage Purchases',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/my-upgrades',
			},
			{
				parent: 'paid-upgrades.php',
				slug: 'billing-history',
				title: 'Billing History',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/billing-history',
			},
		],
	},
	3: {
		type: 'separator',
	},
	4: {
		icon: 'dashicons-admin-post',
		slug: 'edit-php',
		title: 'Posts',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/edit.php',
		children: {
			5: {
				parent: 'edit.php',
				slug: 'edit-php',
				title: 'All Posts',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit.php',
			},
			10: {
				parent: 'edit.php',
				slug: 'post-new-php',
				title: 'Add New',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/post-new.php',
			},
			15: {
				parent: 'edit.php',
				slug: 'edit-tags-phptaxonomycategory',
				title: 'Categories',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit-tags.php?taxonomy=category',
			},
			16: {
				parent: 'edit.php',
				slug: 'edit-tags-phptaxonomypost_tag',
				title: 'Tags',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit-tags.php?taxonomy=post_tag',
			},
			17: {
				parent: 'edit.php',
				slug: 'httpssimpletestsimple1234556-wordpress-comwp-adminedit-php',
				title: 'Copy a Post',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit.php',
			},
		},
	},
	5: {
		icon: 'dashicons-admin-media',
		slug: 'upload-php',
		title: 'Media',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/upload.php',
		children: {
			5: {
				parent: 'upload.php',
				slug: 'upload-php',
				title: 'Library',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/upload.php',
			},
			10: {
				parent: 'upload.php',
				slug: 'media-new-php',
				title: 'Add New',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/media-new.php',
			},
		},
	},
	6: {
		icon: 'dashicons-admin-links',
		slug: 'link-manager-php',
		title: 'Links',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/link-manager.php',
		children: {
			5: {
				parent: 'link-manager.php',
				slug: 'link-manager-php',
				title: 'All Links',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/link-manager.php',
			},
			10: {
				parent: 'link-manager.php',
				slug: 'link-add-php',
				title: 'Add New',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/link-add.php',
			},
			15: {
				parent: 'link-manager.php',
				slug: 'edit-tags-phptaxonomylink_category',
				title: 'Link Categories',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit-tags.php?taxonomy=link_category',
			},
		},
	},
	7: {
		icon: 'dashicons-admin-page',
		slug: 'edit-phppost_typepage',
		title: 'Pages',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/edit.php?post_type=page',
		children: {
			5: {
				parent: 'edit.php?post_type=page',
				slug: 'edit-phppost_typepage',
				title: 'All Pages',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit.php?post_type=page',
			},
			10: {
				parent: 'edit.php?post_type=page',
				slug: 'post-new-phppost_typepage',
				title: 'Add New',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/post-new.php?post_type=page',
			},
			11: {
				parent: 'edit.php?post_type=page',
				slug: 'httpssimpletestsimple1234556-wordpress-comwp-adminedit-phppost_typepage',
				title: 'Copy a Page',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/edit.php?post_type=page',
			},
		},
	},
	8: {
		icon: 'dashicons-admin-comments',
		slug: 'edit-comments-php',
		title: 'Comments',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/edit-comments.php',
		count: 1,
	},
	9: {
		type: 'separator',
	},
	10: {
		icon: 'dashicons-admin-appearance',
		slug: 'themes-php',
		title: 'Appearance',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/themes.php',
		children: {
			5: {
				parent: 'themes.php',
				slug: 'themes-php',
				title: 'Themes',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/themes.php',
			},
			6: {
				parent: 'themes.php',
				slug:
					'customize-phpreturn%2fwpcom%2fv2%2fsites%2f174746428%2fadmin-menu%2f%3f_envelope%3d1%26_locale%3den-gb',
				title: 'Customise',
				type: 'submenu-item',
				url:
					'https://examplewebsite.wordpress.com/wp-admin/customize.php?return=%2Fwpcom%2Fv2%2Fsites%2F174746428%2Fadmin-menu%2F%3F_envelope%3D1%26_locale%3Den-gb',
			},
			7: {
				parent: 'themes.php',
				slug:
					'customize-phpautofocuspanelamp_panelreturnhttps%3a%2f%2fsimpletestsimple1234556-wordpress-com%2fwp-admin%2f',
				title: 'AMP',
				type: 'submenu-item',
				url:
					'https://examplewebsite.wordpress.com/wp-admin/customize.php?autofocus%5Bpanel%5D=amp_panel&#038;return=https%3A%2F%2Fsimpletestsimple1234556.wordpress.com%2Fwp-admin%2F',
			},
			9: {
				parent: 'themes.php',
				slug: 'mobile-options',
				title: 'Mobile',
				type: 'submenu-item',
				url: 'themes.php?page=mobile-options',
			},
		},
	},
	11: {
		icon: 'dashicons-admin-plugins',
		slug: 'calypso-plugins',
		title: 'Plugins',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/admin.php?page=calypso-plugins',
	},
	12: {
		icon: 'dashicons-admin-users',
		slug: 'users-php',
		title: 'Users',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/users.php',
		children: {
			5: {
				parent: 'users.php',
				slug: 'users-php',
				title: 'All Users',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/users.php',
			},
			16: {
				parent: 'users.php',
				slug: 'wpcom-invite-users',
				title: 'Invite New',
				type: 'submenu-item',
				url: 'users.php?page=wpcom-invite-users',
			},
			17: {
				parent: 'users.php',
				slug: 'grofiles-editor',
				title: 'My Profile',
				type: 'submenu-item',
				url: 'users.php?page=grofiles-editor',
			},
			18: {
				parent: 'users.php',
				slug: 'grofiles-user-settings',
				title: 'Personal Settings',
				type: 'submenu-item',
				url: 'users.php?page=grofiles-user-settings',
			},
		},
	},
	13: {
		icon: 'dashicons-admin-tools',
		slug: 'tools-php',
		title: 'Tools',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/tools.php',
		children: {
			5: {
				parent: 'tools.php',
				slug: 'tools-php',
				title: 'Available Tools',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/tools.php',
			},
			10: {
				parent: 'tools.php',
				slug: 'import-php',
				title: 'Import',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/import.php',
			},
			36: {
				parent: 'tools.php',
				slug: 'httpswordpress-comexportsimpletestsimple1234556-wordpress-com',
				title: 'Export',
				type: 'submenu-item',
				url: '/export/simpletestsimple1234556.wordpress.com',
			},
			37: {
				parent: 'tools.php',
				slug: 'delete-blog',
				title: 'Delete Site',
				type: 'submenu-item',
				url: 'tools.php?page=delete-blog',
			},
		},
	},
	14: {
		icon: 'dashicons-admin-settings',
		slug: 'options-general-php',
		title: 'Settings',
		type: 'menu-item',
		url: 'https://examplewebsite.wordpress.com/wp-admin/options-general.php',
		children: {
			10: {
				parent: 'options-general.php',
				slug: 'options-general-php',
				title: 'General',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/options-general.php',
			},
			15: {
				parent: 'options-general.php',
				slug: 'options-writing-php',
				title: 'Writing',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/options-writing.php',
			},
			20: {
				parent: 'options-general.php',
				slug: 'options-reading-php',
				title: 'Reading',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/options-reading.php',
			},
			25: {
				parent: 'options-general.php',
				slug: 'options-discussion-php',
				title: 'Discussion',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/options-discussion.php',
			},
			30: {
				parent: 'options-general.php',
				slug: 'options-media-php',
				title: 'Media',
				type: 'submenu-item',
				url: 'https://examplewebsite.wordpress.com/wp-admin/options-media.php',
			},
			46: {
				parent: 'options-general.php',
				slug: 'debug-bar-extender',
				title: 'Debug Bar Extender',
				type: 'submenu-item',
				url: 'options-general.php?page=debug-bar-extender',
			},
			47: {
				parent: 'options-general.php',
				slug: 'sharing',
				title: 'Sharing',
				type: 'submenu-item',
				url: 'options-general.php?page=sharing',
			},
			48: {
				parent: 'options-general.php',
				slug: 'pollsactionoptions',
				title: 'Polls',
				type: 'submenu-item',
				url: 'options-general.php?page=polls&#038;action=options',
			},
			49: {
				parent: 'options-general.php',
				slug: 'ratingsactionoptions',
				title: 'Ratings',
				type: 'submenu-item',
				url: 'options-general.php?page=ratings&#038;action=options',
			},
			50: {
				parent: 'options-general.php',
				slug: 'adcontrol',
				title: 'AdControl',
				type: 'submenu-item',
				url: 'options-general.php?page=adcontrol',
			},
			51: {
				parent: 'options-general.php',
				slug: 'email_post_changes',
				title: 'Email Post Changes',
				type: 'submenu-item',
				url: 'options-general.php?page=email_post_changes',
			},
			52: {
				parent: 'options-general.php',
				slug: 'openidserver',
				title: 'OpenID',
				type: 'submenu-item',
				url: 'options-general.php?page=openidserver',
			},
			53: {
				parent: 'options-general.php',
				slug: 'webhooks',
				title: 'Webhooks',
				type: 'submenu-item',
				url: 'options-general.php?page=webhooks',
			},
		},
	},
};
