import { translate } from 'i18n-calypso';

export const THEME_COLLECTIONS = {
	recommended: {
		query: {
			collection: 'recommended',
			filter: '',
			number: 10,
			page: 1,
			search: '',
			tier: '',
		},
		title: translate( 'Recommended Themes' ),
		collectionSlug: 'recommended',
		description: <p>Lorem ipsum dolor sit amet</p>,
		seeAllLink: '/themes',
	},
	premium: {
		query: {
			collection: 'recommended',
			filter: '',
			number: 10,
			page: 1,
			search: '',
			tier: 'premium',
		},
		title: translate( 'Premium Themes' ),
		collectionSlug: 'premium-themes',
		description: <p>Lorem ipsum dolor sit amet</p>,
		seeAllLink: '/themes/premium',
	},
	marketplace: {
		query: {
			collection: 'recommended',
			filter: '',
			number: 10,
			page: 1,
			search: '',
			tier: 'marketplace',
		},
		title: translate( 'Partner Themes' ),
		collectionSlug: 'partner-themes',
		description: <p>Lorem ipsum dolor sit amet</p>,
		seeAllLink: '/themes/marketplace',
	},
	blog: {
		query: {
			collection: 'recommended',
			filter: 'blog',
			number: 10,
			page: 1,
			search: '',
			tier: '',
		},
		title: translate( 'Blog Themes' ),
		collectionSlug: 'blog-themes',
		description: <p>Lorem ipsum dolor sit amet</p>,
		seeAllLink: '/themes/filter/blog',
	},
	portfolio: {
		query: {
			collection: 'recommended',
			filter: 'portfolio',
			number: 10,
			page: 1,
			search: '',
			tier: '',
		},
		title: translate( 'Portfolio Themes' ),
		collectionSlug: 'portfolio-themes',
		description: <p>Lorem ipsum dolor sit amet</p>,
		seeAllLink: '/themes/filter/portfolio',
	},
	business: {
		query: {
			collection: 'recommended',
			filter: 'business',
			number: 10,
			page: 1,
			search: '',
			tier: '',
		},
		title: translate( 'Business Themes' ),
		collectionSlug: 'business-themes',
		description: <p>Lorem ipsum dolor sit amet</p>,
		seeAllLink: '/themes/filter/business',
	},
	'art-design': {
		query: {
			collection: 'recommended',
			filter: 'art-design',
			number: 10,
			page: 1,
			search: '',
			tier: '',
		},
		title: translate( 'Art and Design Themes' ),
		collectionSlug: 'art-design-themes',
		description: <p>Lorem ipsum dolor sit amet</p>,
		seeAllLink: '/themes/filter/art-design',
	},
};
