export const action = {
	ACTION_RECEIVE_READER_LIST_ITEMS: 'ACTION_RECEIVE_READER_LIST_ITEMS',
	ACTION_RECEIVE_READER_LIST_ITEMS_ERROR: 'ACTION_RECEIVE_READER_LIST_ITEMS_ERROR',
	ACTION_FETCH_READER_LIST_ITEMS: 'ACTION_FETCH_READER_LIST_ITEMS',
	ACTION_FETCH_READER_LIST_ITEMS_COMPLETE: 'ACTION_FETCH_READER_LIST_ITEMS_COMPLETE'
};
