/**
* Functions for validating theme search filters.
*/

/**
 * External dependencies
 */
import forIn from 'lodash/forIn';

const FILTER_REGEX_STRING = '(\\w+)\\:\\s*([\\w-]+)';
export const FILTER_REGEX_GLOBAL = new RegExp( FILTER_REGEX_STRING, 'g' );
const FILTER_REGEX_SINGLE = new RegExp( '^' + FILTER_REGEX_STRING + '$' );
export const FILTER_TAXONOMY_GROUP = 1;
export const FILTER_TERM_GROUP = 2;

/* eslint-disable */
/* Autogenerated object */
const taxonomies = {
    "color": [
        "black",
        "blue",
        "brown",
        "dark",
        "gray",
        "green",
        "light",
        "orange",
        "pink",
        "purple",
        "red",
        "silver",
        "tan",
        "white",
        "yellow"
    ],
    "column": [
        "four-columns",
        "left-sidebar",
        "one-column",
        "right-sidebar",
        "three-columns",
        "two-columns"
    ],
    "feature": [
        "accessibility-ready",
        "author-bio",
        "blog-excerpts",
        "breadcrumb-navigation",
        "classic-menu",
        "custom-background",
        "custom-colors",
        "custom-header",
        "custom-menu",
        "editor-style",
        "featured-content-with-pages",
        "featured-image-header",
        "featured-images",
        "flexible-header",
        "front-page-post-form",
        "full-width-template",
        "infinite-scroll",
        "microformats",
        "multiple-menus",
        "one-page",
        "post-formats",
        "post-slider",
        "rtl-language-support",
        "site-logo",
        "sticky-post",
        "testimonials",
        "theme-options",
        "threaded-comments",
        "translation-ready",
        "video",
        "wordads"
    ],
    "layout": [
        "fixed-layout",
        "fluid-layout",
        "responsive-layout"
    ],
    "subject": [
        "announcement",
        "art",
        "artwork",
        "blog",
        "business",
        "cartoon",
        "collaboration",
        "craft",
        "design",
        "education",
        "fashion",
        "food",
        "gaming",
        "holiday",
        "hotel",
        "journal",
        "lifestream",
        "magazine",
        "major-league-baseball",
        "mlb",
        "music",
        "nature",
        "news",
        "outdoors",
        "partner",
        "photoblogging",
        "photography",
        "portfolio",
        "productivity",
        "real-estate",
        "school",
        "scrapbooking",
        "seasonal",
        "sports",
        "travel",
        "tumblelog",
        "video",
        "wedding"
    ],
    "style": [
        "abstract",
        "artistic",
        "bright",
        "clean",
        "colorful",
        "conservative",
        "contemporary",
        "curved",
        "dark",
        "earthy",
        "elegant",
        "faded",
        "flamboyant",
        "flowery",
        "formal",
        "funny",
        "futuristic",
        "geometric",
        "glamorous",
        "grungy",
        "hand-drawn",
        "handcrafted",
        "humorous",
        "industrial",
        "light",
        "metallic",
        "minimal",
        "modern",
        "natural",
        "paper-made",
        "playful",
        "professional",
        "retro",
        "simple",
        "sophisticated",
        "tech",
        "textured",
        "traditional",
        "urban",
        "vibrant",
        "whimsical"
    ]
};
/* eslint-enable */

let termTable;

/**
 * @return {Object} a table of terms to taxonomies.
 */
function getTermTable() {
	if ( ! termTable ) {
		termTable = {};
		forIn( taxonomies, ( terms, taxonomy ) => {
			terms.forEach( ( term ) => {
				termTable[ term ] = taxonomy;
			} );
		} );
	}
	return termTable;
}

function splitFilter( filter, group ) {
	const result = filter.match( FILTER_REGEX_SINGLE );
	if ( result && result[ group ] ) {
		return result[ group ];
	}
	return '';
}

export function getTerm( filter ) {
	return splitFilter( filter, FILTER_TERM_GROUP );
}

export function getTaxonomy( filter ) {
	return splitFilter( filter, FILTER_TAXONOMY_GROUP );
}

/**
 * Given the 'term' part, returns a complete filter
 * in "taxonomy:term" search-box format.
 *
 * @param {string} term - the term slug
 * @returns {string} - complete taxonomy:term filter, or empty string if term is not valid
 */
export function getFilter( term ) {
	const terms = getTermTable();
	if ( terms[ term ] ) {
		return `${ terms[ term ] }:${ term }`;
	}
	return '';
}

/**
 * Checks that a taxonomy:term filter is valid.
 *
 * @param {string} filter - filter in form taxonomy:term
 * @returns {boolean} true if filter pair is valid
 */
export function filterIsValid( filter ) {
	return getTermTable()[ getTerm( filter ) ] === getTaxonomy( filter );
}

export function sortFilterTerms( terms ) {
	return terms.map( getFilter ).sort().map( getTerm );
}

