export const ORDER_TRANSACTION_STATUS = {
	SUCCESS: 'ORDER_TRANSACTION_STATUS_SUCCESS',
	PROCESSING: 'ORDER_TRANSACTION_STATUS_PROCESSING',
	FAILURE: 'ORDER_TRANSACTION_STATUS_FAILURE',
	ERROR: 'ORDER_TRANSACTION_STATUS_ERROR',
	UNKNOWN: 'ORDER_TRANSACTION_STATUS_UNKNOWN',
	ASYNC_PENDING: 'ORDER_TRANSACTION_STATUS_ASYNC_PENDING',
};
