export const SUCCESS = 'ORDER_TRANSACTION_STATUS_SUCCESS';
export const PROCESSING = 'ORDER_TRANSACTION_STATUS_PROCESSING';
export const FAILURE = 'ORDER_TRANSACTION_STATUS_FAILURE';
export const ERROR = 'ORDER_TRANSACTION_STATUS_ERROR';
export const UNKNOWN = 'ORDER_TRANSACTION_STATUS_UNKNOWN';
export const ASYNC_PENDING = 'ORDER_TRANSACTION_STATUS_ASYNC_PENDING';
export const ORDER_TRANSACTION_STATUS = {
	SUCCESS,
	PROCESSING,
	FAILURE,
	ERROR,
	UNKNOWN,
	ASYNC_PENDING,
};
