export default [
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'russell',
		template: 'russell',
		theme: 'russell',
		title: 'Russell',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'zoologist',
		template: 'zoologist',
		theme: 'zoologist',
		title: 'Zoologist',
	},
	{
		categories: [ { name: 'Professional Services', slug: 'professional-services' } ],
		features: [],
		is_premium: false,
		slug: 'quadrat',
		template: 'quadrat',
		theme: 'quadrat',
		title: 'Quadrat',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'geologist',
		template: 'geologist',
		theme: 'geologist',
		title: 'Geologist',
	},
	{
		categories: [
			{
				name: 'Professional Services',
				slug: 'professional-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'bantry',
		template: 'bantry',
		theme: 'bantry',
		title: 'Bantry',
	},
	{
		categories: [
			{
				name: 'Professional Services',
				slug: 'professional-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'laporte',
		template: 'laporte',
		theme: 'laporte',
		title: 'Laporte',
	},
	{
		categories: [ { name: 'Professional Services', slug: 'professional-services' } ],
		features: [],
		is_premium: false,
		slug: 'sigler',
		template: 'sigler',
		theme: 'sigler',
		title: 'Sigler',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'antin',
		template: 'antin',
		theme: 'antin',
		title: 'Antin',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'bingley',
		template: 'bingley',
		theme: 'bingley',
		title: 'Bingley',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'glen',
		template: 'glen',
		theme: 'glen',
		title: 'Glen',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'miller',
		template: 'miller',
		theme: 'miller',
		title: 'Miller',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'pollard',
		template: 'pollard',
		theme: 'pollard',
		title: 'Pollard',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'paxton',
		template: 'paxton',
		theme: 'paxton',
		title: 'Paxton',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'jones',
		template: 'jones',
		theme: 'jones',
		title: 'Jones',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'bradford',
		template: 'bradford',
		theme: 'bradford',
		title: 'Bradford',
	},
	{
		categories: [ { name: 'Creative Arts', slug: 'creative-arts' } ],
		features: [],
		is_premium: false,
		slug: 'baker',
		template: 'baker',
		theme: 'baker',
		title: 'Baker',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'blockbase',
		template: 'blockbase',
		theme: 'blockbase',
		title: 'Blockbase',
	},
	{
		categories: [
			{
				name: 'Professional Services',
				slug: 'professional-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'twentytwentyone',
		template: 'twentytwentyone',
		theme: 'twentytwentyone',
		title: 'Twenty Twenty-One',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'spearhead',
		template: 'spearhead',
		theme: 'spearhead',
		title: 'Spearhead',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'seedlet',
		template: 'seedlet',
		theme: 'seedlet',
		title: 'Seedlet',
	},
	{
		categories: [
			{
				name: 'Professional Services',
				slug: 'professional-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'twentytwenty',
		template: 'twentytwenty',
		theme: 'twentytwenty',
		title: 'Twenty Twenty',
	},
	{
		categories: [
			{
				name: 'Local Services',
				slug: 'local-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'barnsbury',
		template: 'barnsbury',
		theme: 'barnsbury',
		title: 'Barnsbury',
	},
	{
		categories: [
			{
				name: 'Local Services',
				slug: 'local-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'rivington',
		template: 'rivington',
		theme: 'rivington',
		title: 'Rivington',
	},
	{
		categories: [ { name: 'Restaurant', slug: 'restaurant' } ],
		features: [],
		is_premium: false,
		slug: 'maywood',
		template: 'maywood',
		theme: 'maywood',
		title: 'Maywood',
	},
	{
		categories: [
			{
				name: 'Local Services',
				slug: 'local-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'shawburn',
		template: 'shawburn',
		theme: 'shawburn',
		title: 'Shawburn',
	},
	{
		categories: [ { name: 'Local Services', slug: 'local-services' } ],
		features: [],
		is_premium: false,
		slug: 'alves',
		template: 'alves',
		theme: 'alves',
		title: 'Alves',
	},
	{
		categories: [
			{
				name: 'Local Services',
				slug: 'local-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'exford',
		template: 'exford',
		theme: 'exford',
		title: 'Exford',
	},
	{
		categories: [ { name: 'Restaurant', slug: 'restaurant' } ],
		features: [],
		is_premium: false,
		slug: 'rockfield',
		template: 'rockfield',
		theme: 'rockfield',
		title: 'Rockfield',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'coutoire',
		template: 'coutoire',
		theme: 'coutoire',
		title: 'Coutoire',
	},
	{
		categories: [
			{
				name: 'Local Services',
				slug: 'local-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'morden',
		template: 'morden',
		theme: 'morden',
		title: 'Morden',
	},
	{
		categories: [
			{
				name: 'Local Services',
				slug: 'local-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'stow',
		template: 'stow',
		theme: 'stow',
		title: 'Stow',
	},
	{
		categories: [
			{
				name: 'Professional Services',
				slug: 'professional-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'hever',
		template: 'hever',
		theme: 'hever',
		title: 'Hever',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'independent-publisher-2',
		template: 'independent-publisher-2',
		theme: 'independent-publisher-2',
		title: 'Independent Publisher 2',
	},
	{
		categories: [
			{
				name: 'Local Services',
				slug: 'local-services',
			},
		],
		features: [],
		is_premium: false,
		slug: 'twentysixteen',
		template: 'twentysixteen',
		theme: 'twentysixteen',
		title: 'Twenty Sixteen',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'twentyfifteen',
		template: 'twentyfifteen',
		theme: 'twentyfifteen',
		title: 'Twenty Fifteen',
	},
	{
		categories: [
			{
				name: 'Creative Arts',
				slug: 'creative-arts',
			},
		],
		features: [],
		is_premium: false,
		slug: 'hemingway-rewritten',
		template: 'hemingway-rewritten',
		theme: 'hemingway-rewritten',
		title: 'Hemingway Rewritten',
	},
];
