<?php
/**
 * Coming Soon
 *
 * @package A8C\FSE
 */

namespace A8C\FSE;

/**
 * Class WPCOM_Coming_Soon
 */
class WPCOM_Coming_Soon {
	/**
	 * Class instance.
	 *
	 * @var WPCOM_Coming_Soon
	 */
	private static $instance = null;

	/**
	 * WPCOM_Coming_Soon constructor.
	 */
	private function __construct() {
		add_filter( 'pre_get_posts', array( $this, 'exclude_from_public_queries' ), 10, 2 );

		// @TODO I think the sitemap is generated by a cron job
		// so we'll need to find out how it works
		add_filter( 'jetpack_sitemap_skip_post', array( $this, 'exclude_from_sitemap' ), 10, 2 );

		// @TODO this is a filter used in an older version of a mu-plugin/sitemap
		add_filter( 'sitemap_skip_post', array( $this, 'exclude_from_sitemap' ), 10, 2 );

		// $id = (int) get_option( 'wpcom_public_coming_soon_page_id', 0 );
		// if ( ! empty( $id ) ) {
		// delete_post_meta( $id, '_sitemap_priority' );
		// update_post_meta( $id, '_sitemap_exclude', '1' );
		// l( '<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<' );
		// l( get_post_meta( ) );
		// }
	}

	/**
	 * Creates instance.
	 *
	 * @return \A8C\FSE\WPCOM_Coming_Soon
	 */
	public function init() {
		if ( is_null( self::$instance ) ) {
			self::$instance = new self();
		}
		return self::$instance;
	}


	/**
	 * Check whether we should show a coming soon page.
	 *
	 * @TODO how are we to override any default behaviour for free simple sites?
	 * On free simple sites we want to show a default coming soon page.
	 */
	public static function should_show_coming_soon_page() {
		global $post;

		if ( is_user_logged_in() && current_user_can( 'read' ) ) {
			return false;
		}

		// Handle the case where we are not rendering a post.
		// if ( ! isset( $post ) ) {
		// return false;
		// }

		// Allow anonymous previews.
		//phpcs:ignore -- non-nonced check is intended
		if ( isset( $_GET['preview'] ) ) {
			return false;
		}

		return ( (int) get_option( 'wpcom_public_coming_soon' ) === 1 );
	}

	/**
	 * Excludes sitemap items by post ID.
	 *
	 * @since 2018-05-04
	 *
	 * @param  bool               $exclude True if excluding.
	 * @param  \WP_Post|\StdClass $post    Post object associated with the item.
	 *
	 * @return bool                        Filtered exclusion. True if excluding.
	 *
	 * @internal Site owners can add a custom field '_sitemap_exclude` to adjust this.
	 */
	public function exclude_from_sitemap( $exclude, $post ) {
		$exclude = (bool) $exclude;
		l( '$post<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<' );
		l( $post );
		$id = (int) get_option( 'wpcom_public_coming_soon_page_id', 0 );

		if ( ! empty( $id ) && $post->ID === $id ) {
			$exclude = (bool) apply_filters( 'wpcom_sitemaps_exclude_post', true, get_post( $id ) );

		}

		return $exclude;
	}

	/**
	 * Exclude from public queries
	 *
	 * @param \WP_Query $query The main query.
	 */
	public function exclude_from_public_queries( $query ) {
		$id = (int) get_option( 'wpcom_public_coming_soon_page_id', 0 );
		if ( ! empty( $id ) && ! is_admin() && $query->is_main_query() ) {
			$query->set( 'post__not_in', array( $id ) );
		}
	}

	/**
	 * Display Coming Soon Page
	 */
	public static function display_coming_soon_page() {
		global $post;

		$should_show_display_fallback_coming_soon_page = false;

		if ( ! self::should_show_coming_soon_page() ) {
			return;
		}

		$id = (int) get_option( 'wpcom_public_coming_soon_page_id', 0 );

		if ( empty( $id ) ) {
			$should_show_display_fallback_coming_soon_page = true;
		}

		$page = get_post( $id );

		if ( ! $page || ! isset( $post ) ) {
			$should_show_display_fallback_coming_soon_page = true;
		}

		// Disable a few floating UI things.
		add_filter( 'wpcom_disable_logged_out_follow', '__return_true', 1, 999 );
		add_filter( 'wpl_is_enabled_sitewide', '__return_false', 1, 999 );
		// add_filter( 'jetpack_disable_eu_cookie_law_widget', '__return_true', 1, 999 );

		if ( $should_show_display_fallback_coming_soon_page ) {
			self::render_fallback_coming_soon_page();
		} else {
			?><!doctype html>
			<html <?php language_attributes(); ?>>
				<head>
					<meta charset="<?php bloginfo( 'charset' ); ?>" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<?php wp_head(); ?>
				</head>
				<body>
					<?php
						//phpcs:ignore
						echo apply_filters( 'the_content', $page->post_content );
					?>
					<?php wp_footer(); ?>
				</body>
			</html>
			<?php
		}

		die();
	}

	/**
	 * Render Fallback Coming Soon Page
	 */
	public static function render_fallback_coming_soon_page() {
		remove_action( 'wp_enqueue_scripts', 'wpcom_actionbar_enqueue_scripts', 101 );
		remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
		remove_action( 'wp_print_styles', 'print_emoji_styles' );
		remove_action( 'wp_head', 'header_js', 5 );
		remove_action( 'wp_head', 'global_css', 5 );
		remove_action( 'wp_footer', 'wpcom_subs_js' );
		remove_action( 'wp_footer', 'stats_footer', 101 );
		//phpcs:ignore
		wp_enqueue_style( 'recoleta-font', '//s1.wp.com/i/fonts/recoleta/css/400.min.css' );

		if ( ! is_user_logged_in() ) {
			//phpcs:ignore
			wp_enqueue_style( 'buttons', '/wp-includes/css/buttons.css' );
		}

		include __DIR__ . '/fallback-coming-soon-page.php';
	}

}

add_action( 'init', __NAMESPACE__ . '\WPCOM_Coming_Soon::init' );
add_action( 'wp', __NAMESPACE__ . '\WPCOM_Coming_Soon::display_coming_soon_page' );
