export const SITE_IMPORTER_IMPORT_START = 'SITE_IMPORTER_IMPORT_START';
export const SITE_IMPORTER_IMPORT_SUCCESS = 'SITE_IMPORTER_IMPORT_SUCCESS';
export const SITE_IMPORTER_IMPORT_FAILURE = 'SITE_IMPORTER_IMPORT_FAILURE';

export const SITE_IMPORTER_IMPORT_RESET = 'SITE_IMPORTER_IMPORT_RESET';

export const SITE_IMPORTER_VALIDATION_ERROR_SET = 'SITE_IMPORTER_VALIDATION_ERROR_SET';

export const SITE_IMPORTER_VALIDATE_SITE_IMPORTABLE_START =
	'SITE_IMPORTER_VALIDATE_SITE_IMPORTABLE_START';
export const SITE_IMPORTER_VALIDATE_SITE_IMPORTABLE_SUCCESS =
	'SITE_IMPORTER_VALIDATE_SITE_IMPORTABLE_SUCCESS';
export const SITE_IMPORTER_VALIDATE_SITE_IMPORTABLE_FAILURE =
	'SITE_IMPORTER_VALIDATE_SITE_IMPORTABLE_FAILURE';
