/**
 * @jest-environment jsdom
 */
/**
 * Tests for the headless voice-assistant image generation flow.
 *
 * Focus: after the generated image is sideloaded into the media library, it is
 * applied to the target block with a caption that carries the "Generated by AI"
 * disclosure when the remembered preference is to show it.
 */
/* eslint-disable import/order */

const mockRequestJetpackAiJwt = jest.fn();
const mockWpcomRequest = jest.fn();
const mockUpdateBlockAttributes = jest.fn();
const mockGetSelectedBlockClientId = jest.fn();

jest.mock( '../request-jwt', () => ( {
	requestJetpackAiJwt: ( ...args: unknown[] ) => mockRequestJetpackAiJwt( ...args ),
} ) );

jest.mock( 'wpcom-proxy-request', () => ( {
	__esModule: true,
	default: ( ...args: unknown[] ) => mockWpcomRequest( ...args ),
} ) );

jest.mock( '@wordpress/data', () => ( {
	dispatch: () => ( {
		updateBlockAttributes: ( ...a: unknown[] ) => mockUpdateBlockAttributes( ...a ),
	} ),
	select: () => ( { getSelectedBlockClientId: () => mockGetSelectedBlockClientId() } ),
} ) );

type WpcomRequestParams = { path?: string; body?: Record< string, unknown > };

describe( 'generateAndApplyHeadless', () => {
	const STORAGE_KEY = 'big-sky-image-studio-ai-disclosure-hidden';

	function getAppliedAttrs() {
		return mockUpdateBlockAttributes.mock.calls[ 0 ]?.[ 1 ] as Record< string, unknown >;
	}

	beforeEach( () => {
		jest.clearAllMocks();
		window.localStorage.clear();

		mockRequestJetpackAiJwt.mockResolvedValue( { token: 'jwt-token', blogId: 123 } );
		mockGetSelectedBlockClientId.mockReturnValue( 'block-1' );

		// Route by request path: generation → media sideload.
		mockWpcomRequest.mockImplementation( ( params: WpcomRequestParams ) => {
			const path = params?.path ?? '';
			if ( path === '/jetpack-ai-image' ) {
				return Promise.resolve( { data: [ { url: 'https://example.com/generated.png' } ] } );
			}
			if ( path === '/sites/123/media/new' ) {
				return Promise.resolve( {
					media: [ { ID: 555, URL: 'https://files.wordpress.com/555.png', alt: 'cat' } ],
				} );
			}
			return Promise.resolve( {} );
		} );
	} );

	it( 'applies the sideloaded image to the target block', async () => {
		const { generateAndApplyHeadless } = await import( '../jetpack-ai-image' );

		const result = await generateAndApplyHeadless( { prompt: 'a cat', clientId: 'block-1' } );

		expect( result.mediaId ).toBe( 555 );
		expect( mockUpdateBlockAttributes ).toHaveBeenCalledWith(
			'block-1',
			expect.objectContaining( { id: 555, url: 'https://files.wordpress.com/555.png' } )
		);
	} );

	it( 'does not write attachment meta (no follow-up media REST call)', async () => {
		const { generateAndApplyHeadless } = await import( '../jetpack-ai-image' );
		await generateAndApplyHeadless( { prompt: 'a cat', clientId: 'block-1' } );

		const paths = mockWpcomRequest.mock.calls.map(
			( [ params ]: [ WpcomRequestParams ] ) => params?.path
		);
		expect( paths ).toEqual( [ '/jetpack-ai-image', '/sites/123/media/new' ] );
	} );

	it( 'leaves the caption empty when the disclosure preference is hidden (default)', async () => {
		const { generateAndApplyHeadless } = await import( '../jetpack-ai-image' );
		await generateAndApplyHeadless( { prompt: 'a cat', clientId: 'block-1' } );

		expect( getAppliedAttrs().caption ).toBe( '' );
	} );

	it( 'adds a "Generated by AI" caption when the remembered preference is "show"', async () => {
		window.localStorage.setItem( STORAGE_KEY, 'false' );

		const { generateAndApplyHeadless } = await import( '../jetpack-ai-image' );
		await generateAndApplyHeadless( { prompt: 'a cat', clientId: 'block-1' } );

		const caption = getAppliedAttrs().caption as string;
		expect( caption ).toContain( 'class="jetpack-ai-disclosure"' );
		expect( caption ).toContain( 'display:inline-block' );
		expect( caption ).toContain( 'border-radius:12px' );
		expect( caption ).toContain( '✦ Generated by AI' );
		expect( caption ).not.toContain( 'text-align:right' );
		expect( caption ).not.toContain( 'data:image' );
	} );
} );
