import {
	SITE_SETUP_FLOW,
	ONBOARDING_FLOW,
	SITE_MIGRATION_FLOW,
	NEW_HOSTED_SITE_FLOW,
	TRANSFERRING_HOSTED_SITE_FLOW,
	ONBOARDING_UNIFIED_FLOW,
	DOMAIN_FLOW,
	EDUCATION_FLOW,
	PLAN_UPGRADE_FLOW,
	WOO_HOSTED_PLANS_FLOW,
	LAUNCH_SITE_FLOW,
} from '@automattic/onboarding';

const FLOWS_USING_STEP_CONTAINER_V2 = [
	SITE_SETUP_FLOW,
	ONBOARDING_FLOW,
	NEW_HOSTED_SITE_FLOW,
	TRANSFERRING_HOSTED_SITE_FLOW,
	SITE_MIGRATION_FLOW,
	ONBOARDING_UNIFIED_FLOW,
	DOMAIN_FLOW,
	EDUCATION_FLOW,
	PLAN_UPGRADE_FLOW,
	WOO_HOSTED_PLANS_FLOW,
	LAUNCH_SITE_FLOW,
];

export const shouldUseStepContainerV2 = ( flow: string ) => {
	return FLOWS_USING_STEP_CONTAINER_V2.includes( flow );
};
