name: Calypso Live

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Ignore paths that trigger the design-system-docs workflow, which manages preview link comment
    paths-ignore:
      - apps/design-system-docs/**
      - .github/workflows/design-system-docs.yml
      - packages/components/**

jobs:
  calypso-live:
    name: 'Links to a calypso.live instance for your branch'
    runs-on: ubuntu-latest
    # We only offer the Calypso.live link to PRs created from the Automattic organization.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    timeout-minutes: 10
    steps:
      # 1. Try to find an existing comment with our marker
      - name: Find preview comment
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- calypso-live-watermark -->'

      # 2. Create or update a comment that shows the preview URLs
      - name: Comment (create or update)
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- calypso-live-watermark -->
            **🌐 Live Previews:**

            - [<img src="https://github.com/user-attachments/assets/b6aa37d0-b09b-402b-a06e-3ffafc438f64" height="14" valign="middle"> Calypso](https://calypso.live?image=registry.a8c.com/calypso/app:commit-${{ github.event.pull_request.head.sha }})
            - [<img src="https://github.com/user-attachments/assets/5df2cf0c-e4d6-4599-b57f-60b5857249c9" height="14" valign="middle"> Jetpack Cloud](https://calypso.live?image=registry.a8c.com/calypso/app:commit-${{ github.event.pull_request.head.sha }}&env=jetpack)
            - [<img src="https://github.com/user-attachments/assets/1eb842ba-5433-4f63-9076-700df5dcb121" height="14" valign="middle"> Automattic for Agencies](https://calypso.live?image=registry.a8c.com/calypso/app:commit-${{ github.event.pull_request.head.sha }}&env=a8c-for-agencies)
