name: Calypso Live

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  calypso-live:
    name: 'Links to a calypso.live instance for your branch'
    runs-on: ubuntu-latest
    # We only offer the Calypso.live link to PRs created from the Automattic organization.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    timeout-minutes: 10
    steps:
      # 1. Try to find an existing comment with our marker
      - name: Find preview comment
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- calypso-live-watermark -->'

      # 2. Create or update a comment that shows the preview URLs
      - name: Comment (create or update)
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- calypso-live-watermark -->
            **🌐 Live Previews:**

            - [Calypso](https://calypso.live?image=registry.a8c.com/calypso/app:commit-${{ github.event.pull_request.head.sha }})
            - [Jetpack Cloud](https://calypso.live?image=registry.a8c.com/calypso/app:commit-${{ github.event.pull_request.head.sha }}&env=jetpack)
            - [Automattic for Agencies](https://calypso.live?image=registry.a8c.com/calypso/app:commit-${{ github.event.pull_request.head.sha }}&env=a8c-for-agencies)
