name: Calculate ICFY stats

on: [push]

jobs:
  build:
    name: Build ICFY stats

    runs-on: ubuntu-latest

    steps:
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '>=12.15.0'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch origin/master
      run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - name: Install dependencies
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      run: npm ci
    - name: Build ICFY stats
      env:
        NODE_ENV: production
        BROWSERSLIST_ENV: defaults
        WORKERS: 2
      run: npm run analyze-icfy
    - run: mkdir icfy-stats && mv client/{chart,stats}.json icfy-stats
    - uses: actions/upload-artifact@v1
      with:
        name: stats.json
        path: icfy-stats
    - name: Upload build artifact
      env:
        ICFY_SECRET: ${{ secrets.ICFY_SECRET }}
      run: |
        #
        # This block should not cause a test failure and block PRs.
        # The shell should never error and exit 0 to indicate success.
        #
        set +o errexit
        ANCESTOR_SHA1=$(git merge-base HEAD origin/master)
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo 'Ancestor: ' $ANCESTOR_SHA1
        echo 'CURRENT_BRANCH: ' $CURRENT_BRANCH
        curl -X POST --globoff                                                     \
          "http://api.iscalypsofastyet.com:5000/submit-stats?secret=$ICFY_SECRET"  \
          -H 'Cache-Control: no-cache'                                             \
          -H 'Content-Type: application/json'                                      \
          -d '{
                "payload": {
                  "branch": "'"$CURRENT_BRANCH"'",
                  "build_num": '"$GITHUB_RUN_NUMBER"',
                  "sha": "'"$GITHUB_SHA"'",
                  "ancestor": "'"$ANCESTOR_SHA1"'",
                  "from": "gh-action"
                }
              }'
