name: Linear Release Sync - Creators

on:
  push:
    paths:
      # Reader
      - 'client/reader/**'
      - 'client/blocks/reader-*/**'
      # Newsletter
      - 'client/data/newsletter-categories/**'
      - 'client/data/paid-newsletter/**'
      - 'client/mailing-lists/**'
      - 'client/my-sites/email/**'
      - 'client/my-sites/subscribers/**'

jobs:
  linear-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get release date
        id: date
        run: echo "release_date=$(date +'%B %-d, %Y') (${{ github.run_number }})" >> "$GITHUB_OUTPUT"
      - uses: linear/linear-release-action@v0.5.0
        with:
          access_key: ${{ secrets.LINEAR_RELEASE_KEY_CREATORS }}
          release_version: ${{ steps.date.outputs.release_date }}
