name: Create Sentry Release
on:
  push:
    branches:
      - 'trunk'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@a74facf8a080ecbdf1cb355f16743530d712abb7 # v1.11.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: a8c
          SENTRY_PROJECT: calypso
        with:
          finalize: false
          version_prefix: calypso_
